### ISSUE TITLE
choking on big dataset

### ISSUE THREAD

**Issue by poldrack** [bids-standard/legacy-validator#10]
I have tried to run the validator on a large dataset (>100 subjects) and it seems to go forever without spitting out any output.  I'm happy to provide access to the TACC system if you want to try it out there directly.

**Comment by constellates** [comment]
That would be great if you could provide me with TACC access so I can see the issue first hand. Please send any sign in instructions directly to my email as issue communications on here are publicly viewable. Thanks.

**Comment by poldrack** [comment]
please go to portal.tacc.utexas.edu and sign up for an account.
if you would rather download some of the data and try on your machine, 
you can get them here:

https://s3.amazonaws.com/openfmri/tarballs/ds031_set01.tgz
https://s3.amazonaws.com/openfmri/tarballs/ds031_set02.tgz
https://s3.amazonaws.com/openfmri/tarballs/ds031_set03.tgz
https://s3.amazonaws.com/openfmri/tarballs/ds031_set04.tgz
https://s3.amazonaws.com/openfmri/tarballs/ds031_set05.tgz
https://s3.amazonaws.com/openfmri/tarballs/ds031_set06.tgz
https://s3.amazonaws.com/openfmri/tarballs/ds031_set07.tgz
https://s3.amazonaws.com/openfmri/tarballs/ds031_set08.tgz

each file is about 8 GB

constellates wrote:

**Comment by constellates** [comment]
Thanks. I'm current downloading a couple sets but I'd also like to try it out on TACC to gain some familiarity with that platform. I've created a user account. What are the steps to run the validator on TACC? I'm emailing you my TACC username in case you need to share data or access with me.

**Comment by constellates** [comment]
After some debugging, it looks like the issue is that JSON validation is taking quite a bit of time with those larger files. Here's a few example timings from validating JSON files in that first data set.

```
experiment_description.json:   19ms
sub00001_ses013_PDT2_001.json: 3931ms
sub00001_ses014_PDT2_001.json: 3512ms
sub00001_ses013_scan.json:     3280ms
sub00001_ses014_scan.json:     3171ms
sub00001_ses013_dwi_002.json:  64312ms
sub00001_ses013_dwi_001.json:  69650ms
sub00001_ses015_T1w_001.json:  4684ms
sub00001_ses015_PDT2_001.json: 3284ms
sub00001_ses015_scan.json:     3000ms
```

We're currently using [JSHINT](https://github.com/jshint/jshint) for JSON validation. I'll look into some other solutions and let you guys know the tradeoffs in speed, level of detail, feedback, etc.

**Comment by poldrack** [comment]
that's a bit odd that it is taking so much more time on the dwi files, 
fiven that those are relatively small compared to the functional files 
(which seem to make much less time). I wonder if something specific to 
those files is tripping it up?
cheers
rp

constellates wrote:

**Comment by constellates** [comment]
Hmm.. It looks like my timing test didn't make it to any files in a functional folder but it does look like there's a correlation between size and time to validate. Here's the same list of timings again, but I've added a size in bytes column. I would guess level of depth in JSON could affect the speed as well.

```
experiment_description.json:      19ms      829B
sub00001_ses013_PDT2_001.json:  3931ms   251000B
sub00001_ses014_PDT2_001.json:  3512ms   247000B
sub00001_ses013_scan.json:      3280ms   238000B
sub00001_ses014_scan.json:      3171ms   238000B
sub00001_ses013_dwi_002.json:  64312ms  1500000B
sub00001_ses013_dwi_001.json:  69650ms  1500000B
sub00001_ses015_T1w_001.json:   4684ms   242000B
sub00001_ses015_PDT2_001.json:  3284ms   239000B
sub00001_ses015_scan.json:      3000ms   231000B
```

**Comment by constellates** [comment]
I spent a little bit of time trying two other popular methods of JSON format validation. Below you can see the method used, the time each took on the same files and the error message given for the same error.

The native JSON.parse is by far the most performant option and will definitely work well in the browser in addition to the server/CLI tool. It leaves a lot to be desired in terms of meaningful error messaging. In practice we would be able to tell a user if a file is a valid JSON file. We would not be able to direct them to a line or character number or give an accurate message about why it is not valid. If this "good" "bad" level of validation is enough, I would highly recommend going this route. Also note, this is only for testing whether a JSON file matches the JSON spec. JSON requirements specific to BIDS will be dealt with separately.

jsonhint in somewhat of a middle ground between the other to, but appears to be relatively unmaintained.

The other option would be to continue using JSHINT but attempt to use it in a parallelized way. It could improve speed by a factor of the number a processes we would be able to start which is probably 2-8. The big complication here would be writing properly parallelized code that is agnostic to being run in the browser or in node.

Or lastly we could use some combined approach of only running JSHINT after we discover an issue with JSON.parse. So we would only incur the cost of verbose error reporting on ones that are actually invalid.

This all boils down to how verbose of error messaging we have to have. From there we can work on the best performance possible.

# JSHINT

### Timings

```
experiment_description.json:   19ms
sub00001_ses013_PDT2_001.json: 3931ms
sub00001_ses014_PDT2_001.json: 3512ms
sub00001_ses013_scan.json:     3280ms
sub00001_ses014_scan.json:     3171ms
sub00001_ses013_dwi_002.json:  64312ms
sub00001_ses013_dwi_001.json:  69650ms
sub00001_ses015_T1w_001.json:  4684ms
sub00001_ses015_PDT2_001.json: 3284ms
sub00001_ses015_scan.json:     3000ms
```

### Error Messaging

```
[ { id: '(error)',
    raw: 'Expected \'{a}\' and instead saw \'{b}\'.',
    code: 'W116',
    evidence: '    "License": "PDDL", ',
    line: 15,
    character: 5,
    scope: '(main)',
    a: '}',
    b: 'License',
    c: undefined,
    d: undefined,
    reason: 'Expected \'}\' and instead saw \'License\'.',
    severity: 'error' },
  { scope: '(main)',
    raw: 'Unrecoverable syntax error.',
    code: 'E041',
    reason: 'Unrecoverable syntax error. (75% scanned).',
    line: 15,
    character: 14,
    severity: 'error' },
  null ]
```

# JSON.parse

### Timings

```
experiment_description.json:   0ms
sub00001_ses013_PDT2_001.json: 2ms
sub00001_ses014_PDT2_001.json: 1ms
sub00001_ses013_scan.json:     1ms
sub00001_ses014_scan.json:     2ms
sub00001_ses013_dwi_002.json:  6ms
sub00001_ses013_dwi_001.json:  7ms
sub00001_ses015_T1w_001.json:  1ms
sub00001_ses015_PDT2_001.json: 1ms
sub00001_ses015_scan.json:     1ms
```

### Error Messaging

```
[SyntaxError: Unexpected string]
```

# jsonlint

### Timings

```
experiment_description.json: 4ms
sub00001_ses013_PDT2_001.json: 70ms
sub00001_ses014_PDT2_001.json: 61ms
sub00001_ses013_scan.json: 53ms
sub00001_ses014_scan.json: 47ms
sub00001_ses013_dwi_002.json: 305ms
sub00001_ses013_dwi_001.json: 292ms
sub00001_ses015_T1w_001.json: 55ms
sub00001_ses015_PDT2_001.json: 47ms
sub00001_ses015_scan.json: 45ms
```

### Error Messaging

```
[Error: Parse error on line 14:
...echnology Fund"    "License": "PDDL",
----------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'STRING']
```

**Comment by poldrack** [comment]
I think the idea of doing a first pass using the fast validator, and 
only using the expensive validator on the files that fail on the first 
pass, is the right way to go. I would try that before going down the 
road of parallelization.
cheers
rp

> constellates mailto:notifications@github.com
> July 1, 2015 at 2:28 PMvia Postbox 
> https://www.postbox-inc.com/?utm_source=email&utm_medium=sumlink&utm_campaign=reach
> 
> I spent a little bit of time trying two other popular methods of JSON 
> format validation. Below you can see the method used, the time each 
> took on the same files and the error message given for the same error.
> 
> The native JSON.parse is by far the most performant option and will 
> definitely work well in the browser in addition to the server/CLI 
> tool. It leaves a lot to be desired in terms of meaningful error 
> messaging. In practice we would be able to tell a user if a file is a 
> valid JSON file. We would not be able to direct them to a line or 
> character number or give an accurate message about why it is not 
> valid. If this "good" "bad" level of validation is enough, I would 
> highly recommend going this route. Also note, this is only for testing 
> whether a JSON file matches the JSON spec. JSON requirements specific 
> to BIDS will be dealt with separately.
> 
> jsonhint in somewhat of a middle ground between the other to, but 
> appears to be relatively unmaintained.
> 
> The other option would be to continue using JSHINT but attempt to use 
> it in a parallelized way. It could improve speed by a factor of the 
> number a processes we would be able to start which is probably 2-8. 
> The big complication here would be writing properly parallelized code 
> that is agnostic to being run in the browser or in node.
> 
> Or lastly we could use some combined approach of only running JSHINT 
> after we discover an issue with JSON.parse. So we would only incur the 
> cost of verbose error reporting on ones that are actually invalid.
> 
> This all boils down to how verbose of error messaging we have to have. 
> From there we can work on the best performance possible.
> 
>   JSHINT
> 
> ```
>   Timings
> ```
> 
> |experiment_description.json: 19ms
> sub00001_ses013_PDT2_001.json: 3931ms
> sub00001_ses014_PDT2_001.json: 3512ms
> sub00001_ses013_scan.json: 3280ms
> sub00001_ses014_scan.json: 3171ms
> sub00001_ses013_dwi_002.json: 64312ms
> sub00001_ses013_dwi_001.json: 69650ms
> sub00001_ses015_T1w_001.json: 4684ms
> sub00001_ses015_PDT2_001.json: 3284ms
> sub00001_ses015_scan.json: 3000ms
> |
> 
> ```
>   Error Messaging
> ```
> 
> |[ { id: '(error)',
> raw: 'Expected \'{a}\' and instead saw \'{b}\'.',
> code: 'W116',
> evidence: ' "License": "PDDL", ',
> line: 15,
> character: 5,
> scope: '(main)',
> a: '}',
> b: 'License',
> c: undefined,
> d: undefined,
> reason: 'Expected \'}\' and instead saw \'License\'.',
> severity: 'error' },
> { scope: '(main)',
> raw: 'Unrecoverable syntax error.',
> code: 'E041',
> reason: 'Unrecoverable syntax error. (75% scanned).',
> line: 15,
> character: 14,
> severity: 'error' },
> null ]
> |
> 
>   JSON.parse
> 
> ```
>   Timings
> ```
> 
> |experiment_description.json: 0ms
> sub00001_ses013_PDT2_001.json: 2ms
> sub00001_ses014_PDT2_001.json: 1ms
> sub00001_ses013_scan.json: 1ms
> sub00001_ses014_scan.json: 2ms
> sub00001_ses013_dwi_002.json: 6ms
> sub00001_ses013_dwi_001.json: 7ms
> sub00001_ses015_T1w_001.json: 1ms
> sub00001_ses015_PDT2_001.json: 1ms
> sub00001_ses015_scan.json: 1ms
> |
> 
> ```
>   Error Messaging
> ```
> 
> |[SyntaxError: Unexpected string]
> |
> 
>   jsonlint
> 
> ```
>   Timings
> ```
> 
> |experiment_description.json: 4ms
> sub00001_ses013_PDT2_001.json: 70ms
> sub00001_ses014_PDT2_001.json: 61ms
> sub00001_ses013_scan.json: 53ms
> sub00001_ses014_scan.json: 47ms
> sub00001_ses013_dwi_002.json: 305ms
> sub00001_ses013_dwi_001.json: 292ms
> sub00001_ses015_T1w_001.json: 55ms
> sub00001_ses015_PDT2_001.json: 47ms
> sub00001_ses015_scan.json: 45ms
> |
> 
> ```
>   Error Messaging
> ```
> 
> |[Error: Parse error on line 14:
> ...echnology Fund" "License": "PDDL",
> ----------------------^
> Expecting 'EOF', '}', ':', ',', ']', got 'STRING']
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Squishymedia/bids-validator/issues/10#issuecomment-117830338.

## 

Russell A. Poldrack
Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu mailto:poldrack@stanford.edu
http://www.poldracklab.org/
Twitter: @russpoldrack

**Comment by constellates** [comment]
Try this again when you get a chance. It should be drastically faster (assuming you don't have a ton of invalid JSON). There will likely be some false positives on the sidecar checks as we haven't implemented anything new there. In addition to this performance fix, I'm starting work of a progress bar. So if it's slow you'll at least know that something is happening.
