### ISSUE TITLE
Problem with error in scans.tsv matching for directory-based datasets (BTI, CTF, ...)

### ISSUE THREAD

**Issue by adam2392** [bids-standard/legacy-validator#1002]
**Summary**
In the recent PR #976 scans in the scans.tsv file are matched against files found in the system. However, this for some reason breaks when doing BTI and CTF data.

See mne-bids related issue: https://github.com/mne-tools/mne-bids/issues/459

BTI and CTF data are unique because they nest another folder within the normal `<kind>/<fname>`, and their scans.tsv looks like `<kind>/<dir>/<fnames`. For some reason this breaks. 

**I am not sure  how to fix it, but I presume the lines here are problematic because they are storing a relativePath  that gets recursively gotten?** 

https://github.com/bids-standard/bids-validator/blob/9df173d9cf0fe84893ad5c615337de8b79287ff0/bids-validator/validators/tsv/tsv.js#L309-L312

**Misc questions**

**As I type this out, I'm not sure based on reading the specification, if this is a problem with how `mne-bids` is writing out the scans file for BTI/CTF/etc datasets that have this nested directory, or if it's a problem with the validator?**

**Example Output / Error**
For an example, check out the latest mne-bids and run `test_ctf` and `test_bti` unit tests.

The output is:

1. For BTI:

bids-validator error:

```
	1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)

		./sub-01/ses-01/meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.bti/c,rf0.1Hz

			Evidence: c,rf0.1Hz

		./sub-01/ses-01/meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.bti/config

			Evidence: config

		./sub-01/ses-01/meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.bti/hs_file

			Evidence: hs_file
```

where the file structure looks like:

```
meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.bti	2012-09-23T11:51:38
├── sub-01
│   └── ses-01
│       ├── meg
│       │   ├── sub-01_ses-01_task-testing_acq-01_run-01_events.tsv
│       │   ├── sub-01_ses-01_task-testing_acq-01_run-01_channels.tsv
│       │   ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.json
│       │   ├── sub-01_ses-01_acq-01_coordsystem.json
│       │   └── sub-01_ses-01_task-testing_acq-01_run-01_meg.bti
│       │       ├── config
│       │       ├── c,rf0.1Hz
│       │       └── hs_file
│       └── sub-01_ses-01_scans.tsv
├── dataset_description.json
├── participants.json
└── participants.tsv
```

and the scans.tsv contents are: `OrderedDict([('filename', ['meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.bti']), ('acq_time', ['2012-09-23T11:51:38'])])`

2. For CTF:

bids-validator error:
```
	1: [ERR] The filename in scans.tsv file does not match what is present in the BIDS dataset. (code: 129 - SCANS_FILENAME_NOT_MATCH_DATASET)

		./sub-01/ses-01/sub-01_ses-01_scans.tsv

			@ line: 1

			Evidence: Filename: /sub-01/ses-01/meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.ds

```

where the file structure looks like: 

```
meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.ds	2013-04-29T09:36:00
├── sub-01
│   └── ses-01
│       ├── meg
│       │   ├── sub-01_ses-01_task-testing_acq-01_run-01_channels.tsv
│       │   ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.json
│       │   ├── sub-01_ses-01_acq-01_coordsystem.json
│       │   └── sub-01_ses-01_task-testing_acq-01_run-01_meg.ds
│       │       ├── BadChannels
│       │       ├── bad.segments
│       │       ├── params.dsc
│       │       ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.res4
│       │       ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.hc
│       │       ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.infods
│       │       ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.acq
│       │       ├── ClassFile.cls
│       │       ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.newds
│       │       ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.meg4
│       │       └── processing.cfg
│       └── sub-01_ses-01_scans.tsv
├── dataset_description.json
├── participants.json
└── participants.tsv
```

and the scans.tsv file has contents: `OrderedDict([('filename', ['meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.ds']), ('acq_time', ['2013-04-29T09:36:00'])])`

**Comment by sappelhoff** [comment]
didn't read the whole issue in detail, but a quick note that I remember:

There was always the question whether for _directory based_ file formats, BIDS:
1. requires the contents of the directory to follow BIDS naming ... or
1. ignores the contents of the directory (they can follow whatever naming they like)

I am 80% sure that it's 2. ... but somebody needs to check.

**Comment by adam2392** [comment]
> didn't read the whole issue in detail, but a quick note that I remember:
> 
> There was always the question whether for _directory based_ file formats, BIDS:
> 
> 1. requires the contents of the directory to follow BIDS naming ... or
> 2. ignores the contents of the directory (they can follow whatever naming they like)
> 
> I am 80% sure that it's 2. ... but somebody needs to check.

As in `sub-01_ses-01_task-testing_acq-01_run-01_meg.ds/` is properly named, but the directory inside can be arbitrary? 

With that case tho, then the fact that bids-validator breaks implies that it is recursively grabbing every filepath inside the bids_root. Then doing the `scans.tsv` check against that list of filepaths. If that is the case, what is the correct fix to accommodate directory based files?

**Comment by sappelhoff** [comment]
> As in sub-01_ses-01_task-testing_acq-01_run-01_meg.ds/ is properly named, but the directory inside can be arbitrary? 

yes, and that's actually the case, see these tests that document it: https://github.com/bids-standard/bids-validator/blob/d7e1d39dc91c0d06570448edc1c0b700eb4d3a2c/bids-validator/tests/type.spec.js#L183-L185

> With that case tho, then the fact that bids-validator breaks implies that it is recursively grabbing every filepath inside the bids_root. Then doing the scans.tsv check against that list of filepaths.

it sounds like a plausible explanation for this bug ... bids-validator is descending into directories that SHOULD NOT BE CHECKED (e.g. `.ds`)

> If that is the case, what is the correct fix to accommodate directory based files?

find the part in the code that does the recursion and add a logic that for directories X, Y, Z, recursion should stop at the top level

Just loose thoughts, sorry I can't invest more time right now

**Comment by sappelhoff** [comment]
btw, this is related: https://github.com/bids-standard/bids-validator/issues/692
