### ISSUE TITLE
Test consistency of scanning parameters

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#101]
Several basic scanning parameters should be read from data and checked for consistency across subjects:
- data dimensionality (x, y, z and time when applicable - _bold and _dwi)
- resolution (in mm for the first three dimensions and seconds for the last one when applicable - _bold and _dwi)

Those parameters can be read from NIFTI headers (see here for details: http://brainder.org/2012/09/23/the-nifti-file-format/)

The consistency of those parameters should be checked across subjects (not necessarily across sessions). For each parameter and scan, a value expressed by the majority of subjects should be found and subjects deviating from this value should be reported in a warning.

This check is similar to https://github.com/poldracklab/mriqc/issues/29

**Comment by rwblair** [comment]
Current commit in my fork is now testing dim, pixdim, and xyzt_units fields from headers. Is there a good dataset that I can test against that has subjects with varying dimensions and resolution for the same tasks to ensure its working how we want?

**Comment by chrisgorgo** [comment]
7t_trt has one subject with wrong resolution:
https://drive.google.com/folderview?id=0B2JWN60ZLkgkMGlUY3B4MXZIZW8&usp=sharing

**Comment by rwblair** [comment]
Ok I'll test against that one. Also @wtriplett pointed me too ds000172 which has intentionally different resolutions and dimensions. 

I'll make a PR if testing goes well with these.
