### ISSUE TITLE
Use all-contributors bot to acknowledge and document contributions

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#1020]
currently, contributions are tracked in the README (here: https://github.com/bids-standard/bids-validator#maintainers-and-contributors)

and it looks like this:

![image](https://user-images.githubusercontent.com/9084751/88312306-45a88980-cd12-11ea-8c47-2913b9f864d9.png)

---

Perhaps it'd be nicer to use the [all-contributors bot](https://github.com/all-contributors/all-contributors-bot) as for example here: https://github.com/datalad/datalad-osf#contributors-

looks like this:

![image](https://user-images.githubusercontent.com/9084751/88312693-bcde1d80-cd12-11ea-9db4-742277dd6a8d.png)

--- 

Benefits:

- acknowledges with actual names
- tracking the kinds of contributions
- more control over who shows up on the list compared to our current implementation of tracking contributors
    - works by commenting in an issue or PR with a syntax like this: `hey @all-contributors please add @username for doc userTesting <insert contribution as taken from list>`

Drawbacks:

- I don't like the ✨ it has in the heading and the sentence about wonderful people :slightly_smiling_face: 
- entering all contributors there will be some initial hassle, but can also be done step-wise

**Comment by sappelhoff** [comment]
what are your opinions @rwblair @effigies @franklin-feingold

**Comment by effigies** [comment]
I'm fine with moving to all-contributors if somebody has the activation energy to do it.

**Comment by franklin-feingold** [comment]
sounds good to me

**Comment by sappelhoff** [comment]
Let's try this out:

@all-contributors please add @rwblair for maintenance

**Comment by sappelhoff** [comment]
The "https://sourcerer.io/fame/chrisfilo/bids-standard/bids-validator/images/0" links are broken and are not getting rendered anymore, see screenshot:

![image](https://user-images.githubusercontent.com/9084751/107057437-be18f880-67d3-11eb-9e3d-894916d2a720.png)


https://github.com/bids-standard/bids-validator/blob/970921cbf2e3e85df195ca16f63ee460c588e596/bids-validator/README.md#maintainers-and-contributors


Thus I am reopening this. I still think the all-contributors bot would be an improvement over the old "sourcerer" links.

**Comment by sappelhoff** [comment]
@Remi-Gau would you be interested in helping to set this up?

**Comment by sappelhoff** [comment]
Sorry for tagging you Remi prematurely, I went ahead and did it myself in #1167
