### ISSUE TITLE
Status of channels.tsv files if provided should only be "good", or "bad"

### ISSUE THREAD

**Issue by adam2392** [bids-standard/legacy-validator#1021]
One thing I noticed while going through the bids-validator is that the unit tests for `tsv.js` doesn't enforce the `status` to be only `good`, or `bad`, whereas: https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html

for MEG, EEG, iEEG only uses those two keywords.

**Proposed Fix**
If `status` is a column in the `*_channels.tsv` file (since it's optional), it should be either `good`, or `bad` (upper-casing warns it to use lower-case(?)), else an error occurs.

**Comment by sappelhoff** [comment]
isn't that what https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/tsv/checkStatusCol.js is doing?
