### ISSUE TITLE
Upgrade packages: urix, resolve-url, requests, mkdirp-promise

### ISSUE THREAD

**Issue by VisLab** [bids-standard/legacy-validator#1025]
I am trying to run bids-validator through npm  (bids-validator 1.5.4).  This error seems to be fixed in master, but the version on npm crashes:

bids-validator --no-config AdvancedGuardDuty
C:\Users\Kay Robbins\AppData\Roaming\npm\node_modules\bids-validator\utils\type.js:1
Error: Cannot find module '../bids_validator/rules/fixed_top_level_names.json'

**Comment by rwblair** [comment]
Very strange. I just tried a fresh install from npm and didn't see that error (used --no-config, ds000005, windows 10 virtual box). You might try removing C:\Users\Kay Robbins\AppData\Roaming\npm\node_modules\bids-validator\ and reinstalling with npm to see if that gets it the files it needs.

**Comment by VisLab** [comment]
Thanks.... that fixed it.  BTW, I get the following warnings when I
install.  The last one is particularly worrisome, since promises are an
integral part of the implementation.

npm WARN deprecated urix@0.1.0: Please see
https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1:
https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see
https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no
longer maintained. 'mkdirp' itself supports promises now, please switch to
that.

**Comment by rwblair** [comment]
I'll look into upgrading those packages! What version of node are you running for reference?

**Comment by VisLab** [comment]
npm version 6.12.1
