### ISSUE TITLE
events.json does not have JSON schema

### ISSUE THREAD

**Issue by VisLab** [bids-standard/legacy-validator#1032]
A schema should probably be added to assure proper validation.

**Comment by sappelhoff** [comment]
Could you be more specific with what you want to check with the schema?

events.tsv files have two REQUIRED columns: onset and duration, so an events.json schema could look like this:

```JSON
{
  "type":"object",
  "properties":{
    "onset":{
      "type":"object"
    },
    "duration":{
      "type":"object"
    }
  },
  "required":[
    "onset",
    "duration"
  ],
  "additionalProperties":true
}
```

But I am not sure

1. whether onset and duration should be REQUIRED to be described in events.json
1. how to make the schema perform valuable checks

perhaps you have thought more about this. If so, please let us know about reasonable things to do with the schema :-)

**Comment by VisLab** [comment]
Roadmap.....

I'd like to wait until pull request #527 in the bids-specification and pull request #1015 of the bids-validator are incorporated before moving forward.  

One reason why we think it is really important to get the HED schema version information into the spec is that we have been working on a major enhancement of HED that will need the schema during analysis.  The motivation is two-fold. First, we want to make it easier for people to actually tag their events. Second, most EEG analysis is event-centric, but the data required in the BIDS spec does not, in general provide enough information to do analysis without a lot of manual coding and most likely tracking down the data-authors for more information. 

We just put the following white-paper out on OSFPreprints:   https://osf.io/5fg73/ and would greatly appreciate comments.

Our goal is to release HED-3 in September. With the incorporation of the above pull requests and the addition of a mapping function in the bids-validator, BIDS is HED-3 ready.  Our goal is to make it much easier for people to annotate, while enabling much better support for downstream automated analysis.

**Comment by sappelhoff** [comment]
crosslink to https://github.com/bids-standard/bids-specification/pull/573

more optional structured fields getting added to events.json --> a schema seems to become more and more useful
