### ISSUE TITLE
Should acq and rec be supported for behavior-only data?

### ISSUE THREAD

**Issue by tsalo** [bids-standard/legacy-validator#1036]
This stems from https://github.com/bids-standard/bids-specification/pull/556#issuecomment-667694066. As part of https://github.com/bids-standard/bids-specification/pull/556, we noticed that the validator supports `acq` and `rec` entities for the `beh` datatype, even though the specification does not.

Is it possible that this is an oversight on the validator side, or should the specification include support for `acq` and `rec`?

Here are the relevant rules, for reference:

https://github.com/bids-standard/bids-validator/blob/8317fb5638dfa6d9907116e1fcfdde7d35e96a7d/bids-validator/bids_validator/rules/file_level_rules.json#L58-L72

**Comment by effigies** [comment]
There is an existing [dataset](https://openneuro.org/datasets/ds001784) with `acq-*_beh.tsv`.

**Comment by tsalo** [comment]
That seems like a good use-case for `acq`. Since `acq` is a freeform, truly optional entity, I guess it makes sense to support it in pretty much every case. Any thoughts on `rec`?

**Comment by tsalo** [comment]
Per the maintainers call today, `rec` support should be dropped from the validator, while `acq` should be added to the specification. I will incorporate the latter into bids-standard/bids-specification#556.

**Comment by effigies** [comment]
And we do want `recording` for `physio` and `stim`. It looks like this is covered here:

https://github.com/bids-standard/bids-validator/blob/8317fb5638dfa6d9907116e1fcfdde7d35e96a7d/bids-validator/bids_validator/rules/file_level_rules.json#L74-L84

But that also has `rec-`. Not immediately clear whether that needs to be dropped from `func/` continuous recordings or `beh/` and `func/` need to be split.

**Comment by tsalo** [comment]
`rec` is labeled as OPTIONAL for `physio` and `stim` data under `func/`, so, if we assume the specification is accurate in this respect, then it should be split.

**Comment by effigies** [comment]
If we look at `anat`, we can see how to add `_recording-<>_(physio|stim).<ext>` to the otherwise matching entities.

https://github.com/bids-standard/bids-validator/blob/8317fb5638dfa6d9907116e1fcfdde7d35e96a7d/bids-validator/bids_validator/rules/file_level_rules.json#L2-L30
