### ISSUE TITLE
Code 0: internal error - too many arguments 

### ISSUE THREAD

**Issue by cdale8** [bids-standard/legacy-validator#1037]
New, post-covid-collected dataset returns Error code 0: INTERNAL ERROR.  Data appears to be the same as the prior data set acquisitions (modalities, size, tasks, etc.) that did validate (and still validate when I re-run them through BIDS conversion and validation). I'm using same validator, BIDS conversion script, acquisition protocols, etc as for the prior successful datasets.  If any of the 4 modalities' data directories are in the BIDS path (anat, meg, dwi, func), it returns this error.  No data (exception: subject's derivatives dir) and no scans.tsv present = no error.

Any ideas where to even start looking?

Error 1: [Code 0] INTERNAL ERROR

SOME VALIDATION STEPS MAY NOT HAVE OCCURRED
1 file
NaN KB |
Location:

Reason:

too many arguments provided for a function call; please help the BIDS team and community by opening an issue at (https://github.com/bids-standard/bids-validator/issues) with the evidence here.
Evidence:

Oi@https://bids-standard.github.io/bids-validator/_next/static/lcAFkzjYJB3Y9y9R5kJls/pages/index.js:1:1384136 Rs/<@https://bids-standard.github.io/bids-validator/_next/static/lcAFkzjYJB3Y9y9R5kJls/pages/index.js:1:1396153

**Comment by rwblair** [comment]
Is there any chance you can download and post the error log if its present?

What json or tsv files have you added to the dataset when the error is generated? A list of the paths and files in the dataset would be helpful, can test similar setup to try and recreate the error. Finally I have seen this error come up with a malformed dataset_description.json, if you can link to or post that I can test against it locally.

**Comment by cdale8** [comment]
Thanks for the reply @rwblair .  This is the contents of the downloaded errors.txt log (as well as the message on the screen):
[BIDS_T2_errors.txt](https://github.com/bids-standard/bids-validator/files/5026211/BIDS_T2_errors.txt)


File Path: Internal error. SOME VALIDATION STEPS MAY NOT HAVE OCCURRED

	Type:		Error
	Reason:		too many arguments provided for a function call; please help the BIDS team and community by opening an issue at (https://github.com/bids-standard/bids-validator/issues) with the evidence here.
	Evidence:	Oi@https://bids-standard.github.io/bids-validator/_next/static/lcAFkzjYJB3Y9y9R5kJls/pages/index.js:1:1384136
Rs/<@https://bids-standard.github.io/bids-validator/_next/static/lcAFkzjYJB3Y9y9R5kJls/pages/index.js:1:1396153

======================================================

I should add that I'm using the web browser-based validator, rather than command line tools, and the size of my bids directory structure is approaching a terabyte (in case that has any bearing on performance).

My conversion script utilizes a combination of dicm2nii.m and data2bids.m to create the tsv and json files for each subject x modality x run. So far, 236 subjects through this conversion will successfully validate, but the 237th throws the error above. Because this is number 237, the dataset_description.json isn't changed from the successful validation prior to 237th. The directory will validate when I remove dataset 237.   For fun, I removed 236 and re-converted that subject into the bids location, and the bids directory validated.  

I have also tried to validate with just a single modality for 237 included at a time, and as long as there's a data directory in the ses-01 path for subject 237, it errors out.  It is possible that (because this is our first subject since March), a change in the MR protocol caused differences in dicom headers, which end up populating jsons/tsv. If that were the case, however, I'd expect the data to validate with just the meg directory included, which it doesn't.

Is there any clue in the log as to what function is triggering the error?  Per subject, I have 3 runs of func resting state, 2 runs of dwi, 1 T1 anat, 1 T2 anat, and 3 CTF meg runs (with their associated json/tsv files).  I'd love to narrow down where to start comparing these guts of these files with those of previous subjects.

Attaching the path/file list for the failed subject's dataset (271) and the last subject that went through validation successfully (260) and was also successful on re-conversion, as long as 271 doesn't have any imaging data in their bids dir.

[sub260_validationpath.log](https://github.com/bids-standard/bids-validator/files/5026170/sub260_validationpath.log)

[sub271_validationpath.log](https://github.com/bids-standard/bids-validator/files/5026164/sub271_validationpath.log)

**Comment by rwblair** [comment]
So as best I can tell that error is being generated around here here:
https://github.com/bids-standard/bids-validator/blob/cb31b1130f327392292fdb2660a242cef4451b3e/bids-validator/validators/bids/fullTest.js#L196

The exact column number is on the call to the session validation function, and immediately before it is the tsv custom column validation, which is passed the contents of the json files. Any tsv columns not specified in the spec generate issue about needing a description Now well before this nifti validation, json validation, and the initial tsv validation occurs.

Reading the session validation code there are a lot of comparisons between filenames. It goes through every subjects files to issue a warning if some files appear for some subjects or in some sessions and not others. Are you validating all 271 subjects at once? Whats the total file count for the dataset? maybe the total file count is an issue here.

File organization seems good, though I have limited experience with MEG datasets. What does the contents of scans.tsv look like, typical filename, acq_time? When you tested validating other modalities by them selves was scans.tsv present?

Terabyte is large. The contents of many files are loaded into memory for validation. How large are the json and tsv files? Any outliers?

I'm sorry I don't have any clear cut answers for you, thanks for the detailed responses and helping debug this.

**Comment by cdale8** [comment]
@rwblair -  thanks for the pointers.  I am validating the whole study directory at once, each time I add a participant (or small group of participants).  The various people doing analyses then have all the current subjects in one linkable location with a single file that includes all the participants.tsv info.

The successfully-validated project directory has 22504 files, 952.18GB for 236 subjects.  Adding this next subject causes it to fail (121 files, 3.99GB). Filesizes for the newly added subject are similar/identical to that of the prior subject acquired at that site.

To test this subject in isolation, I created a separate BIDS project directory and ran a one-subject validation. I copied in the dataset_description.json, README, participants.json from the main BIDS output directory, and edited the participants.tsv to include only the line for the  subject that causes the validator to fail. I included full imaging data directories/tsv/json files associated with this subject.  Running the validator on this one-subject study directory was successful.

I suspect that this study is straining the validation tool.  It involves anat/func/dwi/meg imaging data from two different sites that are using two different MR machines, and two different MEG machines. Target enrollment across the sites is 410, with one site doing test-retest sessions on about 10% of their participant base.  I turn warnings off, as we expect differences in filetypes and filecount (ie: files generated using CTF versus Magnes/BTi), but even the various protocol-defined MR scan resolutions were triggering warnings. 

I believe it is important for at least one of the downstream pipelines used that this validator completes without error (datalad, fmriprep). Aside from setting up a second BIDS output directory and splitting the study in half, any suggestions?  Would using a different version of the validation tool or a different browser help?

**Comment by rwblair** [comment]
Fmriprep does make a call to the validator but there are flags to skip validation. I believe it doesn't rely on too many of the fine points of the specification, but rather relies on the file structure.

I would be interested to see how the node version of the validator does in comparison to the browser. We have had issues with some users running up against ulimits for open files. There have been fixes towards this issue and this dataset certainly would put it to the test. Do you have easy access to node and npm on the computer that houses the dataset? https://github.com/bids-standard/bids-validator#through-command-line

It might also give you a clearer error message since its javascript isn't minified.

I could look into adding a per subject validation, where the validator would just load files for one subject at a time and skip any tests that span across subjects. I believe that the cross subject tests only issue warnings at the moment. I can't give a timeline for how long that might take at the moment.

Let me know how the cli validation goes, or if you have any issues setting it up.

**Comment by cdale8** [comment]
It only took a month, but IT finally installed the command line version (in a singularity container) and I ran the command line version that also returned the Internal Error:


bids-validator@1.5.4

	1: [ERR] Internal error. SOME VALIDATION STEPS MAY NOT HAVE OCCURRED (code: 0 - INTERNAL ERROR)
		.undefined
			Evidence: RangeError: Maximum call stack size exceeded
    at missingSessionFiles (/src/validators/session.js:20:10)
    at /src/validators/bids/fullTest.js:190:40

	Please visit https://neurostars.org/search?q=INTERNAL ERROR for existing conversations about this issue.


        Summary:                     Available Tasks:        Available Modalities: 
        22865 Files, 965.82GB                    
        238 - Subjects                    
        2 - Sessions                                        
 <task list and modality list removed for clarity>

**Comment by effigies** [comment]
Can you try increasing the stack size? https://stackoverflow.com/questions/11332422/how-can-i-increase-the-maximum-call-stack-size-in-node-js

**Comment by cdale8** [comment]
To make it more fun, I removed the subjects added in Aug-Sept from the large directory.  The command line validator returned the same error, but the web-based validator returned a valid dataset. Using a split-directory test, I can affirm the following:

The web-based validator tops out at 236 subjects/~950GB of data
The command-line validator tops out at 400GB and 565GB, depending on the capability/resources of the machine I ssh into to run the command.
 
I put in another ticket to IT to increase stack size allocation within to node.js, which I apparently don't have normal command line access to.  Let's see how long this takes...

**Comment by cdale8** [comment]
The calls to increase stack size using the node.js option didn't work for us (myself and someone with access to root permissions). Not sure whether it's an issue with singularity or node at this point, but its definitely an issue with the size of this study.  I'm able to validate individual subject directories to affirm BIDS structure, so I think that's how I'll proceed as new data collection ramps back up.

**Comment by effigies** [comment]
I don't think adding a subject should cause us to exhaust stack frames, so there's room for a fix to be sought, but it's going to take someone with greater JS-foo than I have to find it.
