### ISSUE TITLE
Problem with top level coordsystem.json and events.json

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#1039]
Fix in top level rules and in json validator:
https://github.com/bids-standard/bids-specification/issues/528#issuecomment-669951872

**Comment by sappelhoff** [comment]
I think we can close this one for now, see my comment in https://github.com/bids-standard/bids-specification/issues/528#issuecomment-686350453

We can reopen if someone else thinks that this is problematic.
