### ISSUE TITLE
sbref.json not allowed in root folder?

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/legacy-validator#1045]
Trying to create a bids data set with some DWI for the first time and I realized that the validator was not happy with me putting a `sbref.json` in the root folder but that had to keep the json file in the `dwi` of each subject.

Is this normal? Or am I missing something from the specifications in terms of the inheritance principle not applying to some files?

Also the appendix table in the specs does not mention sbref files for DWI: should I make a pull request for that?

**Comment by tsalo** [comment]
If I'm not misunderstanding it, this seems like a pretty straightforward bug in the validator.

Two quick questions:
1. @Remi-Gau do you know if this is still a problem?
2. If so, should this be transferred to the `bids-validator` repository?

**Comment by Remi-Gau** [comment]
yes still an issue.

double checked on original data set I had a problem with.

And also on one of the example dataset from BIDS-examples:

if you run the following from within the `BIDS-examples` folder:

```bash
cp ieeg_visual_multimodal/sub-som682/ses-nyu3t01/func/sub-som682_ses-nyu3t01_task-*object*01_sbref.json \
ieeg_visual_multimodal/sbref.json

bids-validator ieeg_visual_multimodal/ --ignoreNiftiHeaders
```

You get the extra error:

```
1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
		./sbref.json
			Evidence: sbref.json
```

**Comment by tsalo** [comment]
Okay thank you. That seems like a validator bug then. I think we should either transfer the issue to `bids-validator` or open a separate issue there. Do you have a preference?

**Comment by Remi-Gau** [comment]
Let's transfer. :-)

**Comment by Remi-Gau** [comment]
you will have to do it I think: I don't have the access rights.

**Comment by tsalo** [comment]
Unfortunately, I don't have access rights on the bids-validator repo. @rwblair, would you mind transferring this issue to `bids-validator`?
