### ISSUE TITLE
Modality-specific electrophysiology json sidecar files PowerLineFrequency required to be an integer

### ISSUE THREAD

**Issue by alexrockhill** [bids-standard/legacy-validator#1046]
After testing the data used for testing (20 seconds) compared to random data, the difference between the 50 Hz and 60 Hz power was not enough not to classify random data incorrectly a significant portion of the time. This means that the powerline frequency cannot be determined reliably from the data https://github.com/mne-tools/mne-bids/pull/505, and so should be given as 'n/a'. 'n/a' is not accepted by the validator, only an integer (-1 for now). The major downside to requiring the powerline frequency be not missing, as discussed, is that if it is automatically selected and wrong there is the potential to lead to spurious results, whereas if it is not specified than it is at the discretion of the person conducting the analysis to determine where to filter to remove line noise, and if there is not an obvious peak at 50 or 60 Hz then they would need to follow up or take into account that their analysis shouldn't include these frequencies.

**Comment by sappelhoff** [comment]
thanks @alexrockhill 

> 'n/a' is not accepted by the validator, only an integer (-1 for now)

I think that's weird, the validator should accept n/a ... and not -1
