### ISSUE TITLE
The new physio.json check does not respect Inheritance

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#1049]
Thanks to @rwblair we have the new check making sure that each physio.tsv is accompanied with a physio.json ... which is REQUIRED.

However, this check should respect the inheritance principle.

For example, I am getting this error:

```
	3: [ERR] Continous recording data files are required to have an associated JSON metadata file. (code: 133 - CONTINOUS_RECORDING_MISSING_JSON)
		./sub-01/eeg/sub-01_task-ActiveFixed_recording-eyetracking_physio.tsv.gz
		./sub-01/eeg/sub-01_task-YokedFixed_recording-eyetracking_physio.tsv.gz
		./sub-01/eeg/sub-01_task-description_recording-eyetracking_physio.tsv.gz
                ...
		... and 110 more files having this issue (Use --verbose to see them all).
```

for a file tree like this (simplified example):

```
.
├── CHANGES
├── dataset_description.json
├── LICENSE
├── participants.json
├── participants.tsv
├── README
├── recording-eyetracking_physio.json
├── sub-01
│   └── eeg
│       ├── sub-01_task-ActiveFixed_recording-eyetracking_physio.tsv.gz
│       ├── sub-01_task-description_recording-eyetracking_physio.tsv.gz
│       └── sub-01_task-YokedFixed_recording-eyetracking_physio.tsv.gz

```

The `recording-eyetracking_physio.json` at the root defines all necessary details for the other physio.tsv files.

One could perhaps say that this inheritance is a bad idea, because `StartTime` in the JSON would differ for each physio.tsv file ... however, there could be cases where:

1. the `StartTime` is always the same or
1. the `StartTime` is `n/a`, like in the scenario I describe here: https://github.com/bids-standard/bids-validator/issues/1048

Thus I think that inheritance should be enabled for this check.

**Comment by rwblair** [comment]
@sappelhoff can you test this with current validator master, code that finds related files was just updated. If its still an issue can you send me the dataset you see the issue for? Haven't been able to quickly recreate with physio data I have locally.

**Comment by sappelhoff** [comment]
The most recent commit (59b750416984addbe3484ddf3658ed101e1e37ec) solved this, thanks a bunch!
