### ISSUE TITLE
`GeneticLevel` in schema expects array of str, but should ALSO accept a string

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#1065]
EDIT: see discussion below --> this issue should be solved by allowing a string AND an array of strings

evidence in code:

https://github.com/bids-standard/bids-validator/blob/f8dc8c75d0357a3964d4d82ad4ef57337e574b70/bids-validator/validators/json/schemas/genetic_info.json#L4-L17

however, the spec says: 

> REQUIRED. String. Describes the level of analysis. Values MUST be one of Genetic, Genomic, Epigenomic, Transcriptomic, Metabolomic, or Proteomic.

see: https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/08-genetic-descriptor.html#genetic-information

Is this an error in the spec or in the validator @CPernet ? Would you want people to specify something like `["Genetic", "Genomic"]` ... or should it be either `"Genetic"` **or** `"Genomic"`?

would need to be fixed here: https://github.com/bids-standard/bids-examples/tree/master/genetics_ukbb

**Comment by effigies** [comment]
This was set in a reformatting: https://github.com/bids-standard/bids-specification/commit/db8cb3747606fbe41b9ab64edab51c695ed8141f

Hopefully the semantic change was reviewed. The example only shows a string, not an array.

**Comment by CPernet** [comment]
but an array e.g. ["Genetic", "Genomic"]  would be better - several analytic levels can be performed on the same data

**Comment by CPernet** [comment]
- an array makes more sense
- ukbb example is fine nothing to fix
- I guess the previous iteration bids-standard/bids-specification@db8cb37 without the 'one of' was better allowing array

**Comment by effigies** [comment]
Thanks for the clarification, @CPernet. @sappelhoff I think for backwards compatibility, we should permit a string or array of strings.

**Comment by sappelhoff** [comment]
okay, sounds good to me - practically we'd then adjust the schema to also accept str ... and I will clarify the spec in https://github.com/bids-standard/bids-specification/pull/605

**Comment by CPernet** [comment]
we also need to add in the spec the new reference :-)

`Clara Moreau, Martineau Jean-Louis; Ross Blair; Christopher Markiewicz, Jessica Turner, Vince Calhoun, Thomas Nichols, Cyril Pernet (2020) The genetics-BIDS extension: Easing the search for genetic data associated with human brain imaging. GigaScience `

don't have the issue number or page yet
