### ISSUE TITLE
ENH ephys schemas --> all "Unit" keys should validate a restricted vocabulary

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#1069]
The meg, eeg, ieeg schemas in https://github.com/bids-standard/bids-validator/tree/master/bids-validator/validators/json/schemas

should get an update such that they only accept a restricted vocabulary as a string for all fields ending on "UNIT".

For example 

https://github.com/bids-standard/bids-validator/blob/4354d0338b6bdae40b7a038f444b5643038f6e15/bids-validator/validators/json/schemas/coordsystem_eeg.json#L7

according to the specification, the only permitted values in this field are "m", "mm", "cm"

ref: https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html#coordinate-system-json-_coordsystemjson

**Comment by rwblair** [comment]
First grep is of the spec source and second is of the validator schemas. I Have a few Units that I need to add to schemas:

```
~/projects/bids-specification $ grep -REho '[[:alpha:]]+Unit' src/04-modality-specific-files/ | sort | uniq
AnatomicalLandmarkCoordinateUnit
DigitizedHeadPointsCoordinateUnit
EEGCoordinateSystemUnit
EEGCoordinateUnit
FiducialsCoordinateUnit
HeadCoilCoordinateUnit
iEEGCoordinateSystemUnit
iEEGCoordinateUnit
MEGCoordinateUnit
```

```
~/projects/bids-specification $ grep -REho '[[:alpha:]]+Unit' src/ | sort | uniq | while read i; do grep -RFho $i ~/projects/bids-validator/bids-validator/validators/json/schemas/; done | sort | uniq
AnatomicalLandmarkCoordinateUnit
DigitizedHeadPointsCoordinateUnit
EEGCoordinateUnit
HeadCoilCoordinateUnit
iEEGCoordinateUnit
MEGCoordinateUnit
```

**Comment by sappelhoff** [comment]
:scream: your grepping revealed a :bug:

what a friday morning surprise :-)

--> `EEGCoordinateSystemUnit`, and `iEEGCoordinateSystemUnit` seem to be errors :thinking: they appear only in the spec text, and apparently we forgot to change them to `*EEGCoordinateUnits`, like how they are in the spec table (which is more important).

I'll submit a fix PR to the spec, removing those two.

Like that it seems that only `FiducialsCoordinateUnit` is missing from the EEG schema. --> actually, all of the "*Fiducial*" fields except one are missing from the EEG schema, could you add them as well, please?
