### ISSUE TITLE
After a release, bump the version number of the development version

### ISSUE THREAD

**Issue by hoechenberger** [bids-standard/legacy-validator#1080]
Hello, I'm running into an issue with `bids-validator`; specifically, we're running a CI job that once installs the latest stable release from NPM, and in another set of runs installs the code from the `master` branch. Unfortunately, both versions carry the exact same version number (1.5.4), so there is no way for our tests to find out whether they're being run in an environment with a stable or a development version of the validator. Would it be possible to bump the version number after a release? One could use NPM pre-release version identifiers, such `as 1.5.5-alpha.0`. Any thoughts?

**Comment by sappelhoff** [comment]
x-ref #803

**Comment by hoechenberger** [comment]
Now that 1.5.6 has been released, can we bump the version number to 1.5.7-dev.0, similarly to how we handled this in https://github.com/bids-standard/bids-validator/pull/1081?
