### ISSUE TITLE
Simplify some unnecessarily complicated schemas

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#1082]
The following schema specifications are more complicated than they need to be:

https://github.com/bids-standard/bids-validator/blob/25daeb53ae070b1fcfcad57220cd1a8157a8e419/bids-validator/validators/json/schemas/dataset_description.json#L23-L33

This would be sufficient:

```JSON
 "Acknowledgements": { 
   "type": "string" 
 }, 
 "HowToAcknowledge": { 
   "type": "string" 
 }
```

it's possible that more schema fields can be simplified in this way, I didn't check everywhere.

**Comment by effigies** [comment]
Is this a way of permitting a string or list of strings?

**Comment by sappelhoff** [comment]
> Is this a way of permitting a string or list of strings?

I think that'd have to be:

```

 "Acknowledgements": { 
   "items": { 
     "type": "string" 
   }, 
   "type": "array" 
 }, 
 "HowToAcknowledge": { 
   "items": { 
     "type": "string" 
   }, 
   "type": "array" 
```

Also, "Acknowledgments" and "HowToAcknowledge" MUST be strings, as per https://bids-specification.readthedocs.io/en/latest/03-modality-agnostic-files.html#dataset_descriptionjson
