### ISSUE TITLE
Warnings during build

### ISSUE THREAD

**Issue by effigies** [bids-standard/legacy-validator#1106]
```
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

npm WARN deprecated har-validator@5.1.5: this library is no longer supported

npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.

/usr/local/bin/bids-validator -> /usr/local/lib/node_modules/bids-validator/bin/bids-validator
npm WARN @octokit/plugin-request-log@1.0.2 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.
```

Can these be easily resolved?

**Comment by sappelhoff** [comment]
maybe as part of #1102, which was also intended to solve the several security issues that GitHub alerts us to.

**Comment by effigies** [comment]
Nope, still an issue in the Docker build: https://app.circleci.com/pipelines/github/bids-standard/bids-validator/404/workflows/6ab64555-bd9d-4630-be6d-964e197fcf8c/jobs/6403

**Comment by sappelhoff** [comment]
cc @nellh

**Comment by DimitriPapadopoulos** [comment]
What's the current status of this issue?

I suspect you need to update `lerna` in [`package.json`](https://github.com/bids-standard/bids-validator/blob/master/package.json), the currently suggested version is:
[`3.15.0`](https://github.com/bids-standard/bids-validator/blob/b542235/package.json#L30) (2019-06-09)
but the most recent release in the 3 series is:
[`3.22.1`](https://github.com/lerna/lerna/releases/tag/v3.22.1) (2020-06-09)

As far as I can tell, this release `3.15.0` pulls old obsolete packages.

**Comment by sappelhoff** [comment]
> What's the current status of this issue?

good timing @DimitriPapadopoulos and thanks for suggesting a solution. We'll (hopefully this week) have a meeting with a few devs/maintainers to discuss several issues about lerna, yarn vs npm7, outdated packages, and security warnings.

I'll keep you posted.

**Comment by sappelhoff** [comment]
Coming back, I think this was already raised in #1025
