### ISSUE TITLE
Can runs be alphanumeric (example of run: 5H)?

### ISSUE THREAD

**Issue by arnodelorme** [bids-standard/legacy-validator#1109]
This data file passed the validator on OpenNeuro

ds003190/sub-01/ses-01/eeg/sub-01_ses-01_task-ctos_run-5H_eeg.eeg

**Comment by effigies** [comment]
Shouldn't, no. I also don't think .eeg is a valid extension, so I'm assuming they've ignored their file.

**Comment by arnodelorme** [comment]
.eeg is a valid extension. This is the extension for Brain Vision Analyzer Exchange format. Also, many other valid files in this folder use the same 5H run number

**Comment by effigies** [comment]
Ah, thanks for the clarification.

**Comment by effigies** [comment]
I checked and it was a bidsignore file. I've left a comment on the dataset.
