### ISSUE TITLE
ReptitionTime Rounding in NifTIs

### ISSUE THREAD

**Issue by jpellman** [bids-standard/legacy-validator#111]
Another thing I've noticed when running the validator is that very often I'll get warnings like the following:

>  1: Repetition time did not match between the scan's header and the associated JSON metadata file. 
> (code: 12)
>  /_sub_/_ses_/func/_func_scan_name__bold.nii.gz
>  Repetition time defined in the JSON (2.0 sec.) did not match the one defined in the NIFT
> I header (2.01 sec.)

When I inspect the NifTI headers with 3dinfo, I do indeed get 2.01 seconds.  However, when I open up the original DICOM headers I get 2000 ms.  My guess is that there is some sort of rounding error when the NifTI headers are created (we've been using mcverter).  Would it be possible to make the validator more robust to this sort of scenario (maybe using something similar to numpy's isclose method?).

**Comment by chrisgorgo** [comment]
Why not fixing the TR in NifTI headers instead?

**Comment by jpellman** [comment]
Because that would be too straightforward.
