### ISSUE TITLE
Would like warning if no References and Links

### ISSUE THREAD

**Issue by VisLab** [bids-standard/legacy-validator#1112]
I would like to suggest that a warning be raised if there are no References and Links in the dataset_description. It is easy to forget to include in the relief of getting a dataset to validate.

**Comment by effigies** [comment]
Warnings should generally be for recommendations, so if this is something that we strongly feel adds enough value to the dataset to justify a warning, I would suggest we promote it to RECOMMENDED.

**Comment by sappelhoff** [comment]
related: https://github.com/bids-standard/bids-validator/issues/524, https://github.com/bids-standard/bids-specification/issues/670

**Comment by VisLab** [comment]
My vote is to promote references and links to Recommended.

**Comment by effigies** [comment]
If the spec is updated, the schema validator will follow.
