### ISSUE TITLE
Validator should ensure TSV files do not contain a tab character before the linebreak

### ISSUE THREAD

**Issue by gllmflndn** [bids-standard/legacy-validator#1113]
As discussed [here](https://github.com/bids-standard/bids-matlab/issues/96), the bids validator accepts this file from openneuro:
https://openneuro.org/crn/datasets/ds003195/snapshots/1.0.3/files/participants.tsv
that contains a tab at the end of each line. The question is whether this is indeed a compliant file.

**Comment by effigies** [comment]
I would say it's probably not, but we should check whether there's any external consensus on TSV.

**Comment by effigies** [comment]
Well by the [IANA "standard"](https://www.iana.org/assignments/media-types/text/tab-separated-values):

```
field    ::= [character]+           # multiple characters
name     ::= [character]+            
nameline ::= name [TAB name]+ EOL

record   ::= field [TAB field]+ EOL   # at least one field, or more

tsv      ::= nameline record+

Given that the number of tabs per line must be constant.
```

It looks like the one thing a line can't end with is TAB.

**Comment by effigies** [comment]
Looks like we accidentally introduced this in #631 because `\r\n` was breaking the assumption that EOL == `\n`. So we now over-trim tabs.

https://github.com/bids-standard/bids-validator/blob/73580bfa1a9015ec92db1d03db785cada3d09178/bids-validator/validators/tsv/tsvParser.js#L6-L19

We probably want to add:

```Javascript
const normalizeEOL = str => str.replace('\r\n', '\n').replace('\r', '\n')
```

And change

```Diff
-   content.rows = trimSplit('\n')(contents)
+   content.rows = normalizeEOL(contents)
+     .split('\n')
      .filter(isContentfulRow) 
-     .map(trimSplit('\t'))
+     .map(split('\t'))
```

**Comment by gllmflndn** [comment]
Thanks for looking into this. I would agree to consider this file not valid. Note that BIDS's TSV does not follow the IANA as it allows tabs in double quoted fields, so we are off-piste already anyway.

**Comment by effigies** [comment]
> BIDS's TSV does not follow the IANA as it allows tabs in double quoted fields

Oh...

> String values containing tabs MUST be escaped using double quotes.

Does anybody actually use that? The validator certainly doesn't try to parse it from what I can see.

**Comment by gllmflndn** [comment]
I would hope not but that's in the specs... For what it's worth (i.e. not much), I argued against at the time.

Would it be ok to apply your change above to the validator? How does it work for a dataset on openneuro that was declared as valid and is not any more?

**Comment by gllmflndn** [comment]
Given that the BIDS specs define a TSV file as a CSV file where you replace commas with tabs, I presume [this HN classic about CSV format](http://thomasburette.com/blog/2014/05/25/so-you-want-to-write-your-own-CSV-code/) applies.

**Comment by effigies** [comment]
Feel free to submit the patch, or I can if I get a minute this afternoon. I'm curious what all will break...

**Comment by sappelhoff** [comment]
> Given that the BIDS specs define a TSV file as a CSV file where you replace commas with tabs, I presume this HN classic about CSV format applies.

it would be good to clarify that in the specification - with a link to that external standard (if it's truly a fit). If any of you have time to do that PR as well.

**Comment by gllmflndn** [comment]
I just searched through old emails (~ 5 years ago) and, when I was arguing against tabs in double quotes in TSV files, I mentioned this as well: http://dataprotocols.org/linear-tsv/ (that uses `\t` for tabs within a field).
I don't think there are any 'official' TSV specifications we could link to, unfortunately. But maybe there could be some clarification in the BIDS specification (then we can do the same with [JSON](http://seriot.ch/parsing_json.php) :smile:).
