### ISSUE TITLE
"events.json" at root not properly picked up for inheritance

### ISSUE THREAD

**Issue by dvanblooijs** [bids-standard/legacy-validator#1119]
I have six subjects with several tasks, but all these different tasks result in the same columns in each subject’s events.tsv. I also made one events.json which describe the extra columns in events.tsv and located that in dataset/events.json. All subject’s events.tsv (and corresponding ecogs, channels.tsv etc.) are located in dataset/sub-001/ses-1/ieeg/sub-001_ses-1_task-X_run-XX_events.tsv. However, I got this error when running the bids validator webpage...:

events.json 1.153 KB | application/json

Location:

dataset/events.json

Reason:

Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a “.bidsignore” file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.

Evidence:

events.json

At the same time, I get this warning:
sub-RESP0521_ses-1_task-SPESclin_run-021231_events.tsv 80.253 KB |

Location:

dataset/sub-RESP0521/ses-1/ieeg/sub-RESP0521_ses-1_task-SPESclin_run-021231_events.tsv

Reason:

Tabular file contains custom columns not described in a data dictionary

Evidence:

Columns: sub_type, electrodes_involved_onset, electrodes_involved_offset, offset, sample_start, sample_end, electrical_stimulation_type, electrical_stimulation_site, electrical_stimulation_current, electrical_stimulation_frequency, electrical_stimulation_pulsewidth, notes not defined, please define in: /sub-RESP0521/ses-1/ieeg/sub-RESP0521_ses-1_events.json, /sub-RESP0521/ses-1/ieeg/sub-RESP0521_ses-1_task-SPESclin_events.json,/sub-RESP0521/ses-1/sub-RESP0521_ses-1_events.json,/sub-RESP0521/ses-1/sub-RESP0521_ses-1_task-SPESclin_events.json,/sub-RESP0521/sub-RESP0521_events.json,/sub-RESP0521/sub-RESP0521_task-SPESclin_events.json,**/events.json**,/task-SPESclin_events.json,/sub-RESP0521/ses-1/ieeg/sub-RESP0521_ses-1_task-SPESclin_run-021231_events.json

Apparently, the events.json is not recognized as a descriptor of the fields in the events.tsv files, although it is given as an option in Evidence (see bold).

**Comment by dvanblooijs** [comment]
At the same time, I get this warning:
sub-RESP0521_ses-1_task-SPESclin_run-021231_events.tsv 80.253 KB |

Location:

dataset descriptor/sub-RESP0521/ses-1/ieeg/sub-RESP0521_ses-1_task-SPESclin_run-021231_events.tsv

Reason:

Tabular file contains custom columns not described in a data dictionary

Evidence:

Columns: sub_type, electrodes_involved_onset, electrodes_involved_offset, offset, sample_start, sample_end, electrical_stimulation_type, electrical_stimulation_site, electrical_stimulation_current, electrical_stimulation_frequency, electrical_stimulation_pulsewidth, notes not defined, please define in: /sub-RESP0521/ses-1/ieeg/sub-RESP0521_ses-1_events.json, /sub-RESP0521/ses-1/ieeg/sub-RESP0521_ses-1_task-SPESclin_events.json,/sub-RESP0521/ses-1/sub-RESP0521_ses-1_events.json,/sub-RESP0521/ses-1/sub-RESP0521_ses-1_task-SPESclin_events.json,/sub-RESP0521/sub-RESP0521_events.json,/sub-RESP0521/sub-RESP0521_task-SPESclin_events.json,/events.json,/task-SPESclin_events.json,/sub-RESP0521/ses-1/ieeg/sub-RESP0521_ses-1_task-SPESclin_run-021231_events.json

**Comment by sappelhoff** [comment]
Hi @dvanblooijs - sorry to reply so late ... you probably solved the issue yourself by now. But the solution would be to make a bit less use of the inheritance principle, and create individual `events.json` files that are placed closer to the files they are supposed to describe. 

For me, it works to have `task-mytask_events.json` at the root of my repository, instead of only `events.json`. And then I just have one events.json file per task ... I don't know why the validator throws an error for just `events.json` though ...

**Comment by dvanblooijs** [comment]
Thanks for looking into this. Since I have the same events.tsv for all tasks, it does not make sense to use task-mytask_events.json. I placed the events.json now in each patient folder. This was also correct according to the bids validator.

**Comment by sappelhoff** [comment]
I am pretty sure this issue can be fixed by adding a line `events.json` to this part of the code: https://github.com/bids-standard/bids-validator/blob/5d3835b5b6f4fcbbade1b7122c57a3f48f92cb46/bids-validator/bids_validator/rules/top_level_rules.json#L1-L19

Let me ask some maintainers whether this is sensible.

**Comment by effigies** [comment]
Makes sense to me.
