### ISSUE TITLE
EMPTY_FILE rears its head

### ISSUE THREAD

**Issue by VisLab** [bids-standard/legacy-validator#1129]
This may be the resurrection of an old issue, but I am running the bids-validator 1.5.8 on some of the bids-examples such as eeg_matchingpennies.  It reports an error because all of the eeg data files are empty.  This is a known problem with all of the examples and the work around is to add a bidsconfig.json file to ignore error code 99.  The configuration file is in the bids-examples, but it doesn't seem to work.

**Comment by sappelhoff** [comment]
closed in https://github.com/bids-standard/bids-examples/issues/229
