### ISSUE TITLE
Run gulp build as a smoke test

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#113]
To improve code quality we should incorporate gulp build (generation of the web version of the validator) as a smoke test (run it even if we are not pushing to gh-pages). This would let us catch errors such as #112 before merging.

**Comment by constellates** [comment]
This is done. To test I just pushed a new branch that's a mirror of the current master that's failing during minification.
https://circleci.com/gh/INCF/bids-validator/259

**Comment by constellates** [comment]
I also tested rerunning the origin failing build on master and it will not reach the deploy stage now if it can't build. So it won't publish to npm in that case..

**Comment by constellates** [comment]
I spoke to soon. There's one more issue I need to address. The build is still pulling the latest version from npm to attempt the build with and not using the current branch being tested.

**Comment by constellates** [comment]
Ok I think this is actually finished now. After the initial npm install circle CI now re-installs the validator directly from git and then proceeds with the build.

```
npm install git+https://git@github.com/incf/bids-validator.git\#${CIRCLE_BRANCH}
```

I've retested a few builds and everything looks good.
