### ISSUE TITLE
Unhandled rejection with docker image

### ISSUE THREAD

**Issue by antotorov** [bids-standard/legacy-validator#1131]
Hello,

I am on ubuntu focal and tried to bids-validate my dataset using the docker image.

I am using the default docker image, the exact command I run is (as per documentation)

`sudo docker run -ti --rm -v /home/me/my_project/data:/data:ro bids/validator /data`

The output I have is

```
bids-validator@1.5.8

Unhandled rejection (
  reason: Error: EISDIR: illegal operation on a directory, read
).
```

My docker version is 20.10.1. My nodejs version is v10.19.0, but I think this is irrelevant when using docker.

**Comment by sappelhoff** [comment]
I could not replicate this on Ubuntu 18.04, with `docker --version`: 

> Docker version 19.03.11, build dd360c7

and `bids-validator --version`

> 1.6.1

Did you try again in the meantime @antotorov?

**Comment by sappelhoff** [comment]
PS: I tried validating this dataset: https://github.com/bids-standard/bids-examples/tree/master/eeg_matchingpennies (and it worked with the expected error 99, that some files are empty)

**Comment by sappelhoff** [comment]
Hi @antotorov - I hope your issue resolved itself in the meantime. I am closing this because I could not replicate it, and there is not enough information to continue the investigation.

Please reopen with more info if this is still a problem for you.
