### ISSUE TITLE
BUG: Invalid values in JSON should generate errors with the correct JSON file path

### ISSUE THREAD

**Issue by jbwexler** [bids-standard/legacy-validator#1139]
I got the following output from bids-validator, despite the fact that none of these jsons contain a CogAtlasID field:

 bids-validator@1.5.8

	1: [ERR] Invalid JSON file. The file is not formatted according the schema. (code: 55 - JSON_SCHEMA_VALIDATION_ERROR)
		./sub-9001/ses-1/func/sub-9001_ses-1_task-arrows_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-9001/ses-1/func/sub-9001_ses-1_task-faces_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-9001/ses-1/func/sub-9001_ses-1_task-rest_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-9001/ses-1/func/sub-9001_ses-1_task-sleepiness_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-9001/ses-2/func/sub-9001_ses-2_task-arrows_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-9001/ses-2/func/sub-9001_ses-2_task-faces_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-9001/ses-2/func/sub-9001_ses-2_task-rest_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-9001/ses-2/func/sub-9001_ses-2_task-sleepiness_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-9002/ses-1/func/sub-9002_ses-1_task-arrows_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-9002/ses-1/func/sub-9002_ses-1_task-faces_bold.json
			Evidence: .CogAtlasID should match format "uri"
		... and 649 more files having this issue (Use --verbose to see them all).

Here's an example json:

{
  "TaskName" : "arrows",
  "AcquisitionDuration" : 1215.000448,
  "Columns" : 128,
  "EchoTime" : 0.034,
  "EchoTrainLength" : 1,
  "EffectiveEchoSpacing" : 0.000532,
  "FieldOfView" : [ 240, 240, 108 ],
  "FlipAngle" : 80,
  "GEImageTypeRIMPCode" : 0,
  "ImageType" : "ORIGINAL/PRIMARY/EPI/NONE",
  "ImagingFrequency" : 127.76526,
  "InplanePhaseEncodingDirection" : "COL",
  "InversionTime" : 0,
  "MRAcquisitionType" : "2D",
  "MagneticFieldStrength" : 3,
  "Manufacturer" : "GE MEDICAL SYSTEMS",
  "ManufacturersModelName" : "DISCOVERY MR750",
  "NumberOfAverages" : 1,
  "NumberOfEPIShots" : 1,
  "NumberOfEchoes" : 1,
  "NumberOfSlices" : 45,
  "ParallelImagingReductionFactors" : [ 0.5, 1 ],
  "PercentPhaseFieldOfView" : 100,
  "PhaseEncodingDirection" : "j",
  "PixelBandwidth" : 3906.25,
  "PixelSpacing" : [ 1.875, 1.875 ],
  "ReceiveCoilName" : "8HRBRAIN",
  "RepetitionTime" : 3,
  "Rows" : 128,
  "SATFatWaterBone" : 1,
  "ScanOptions" : [ "SAT_GEMS", "EPI_GEMS", "ACC_GEMS", "FS" ],
  "ScanningSequence" : [ "EP", "GR" ],
  "SequenceVariant" : "SS",
  "SeriesDate" : "18730311",
  "SeriesDescription" : "fMRI-arrows",
  "SeriesNumber" : 10,
  "SeriesTime" : "191348",
  "SliceThickness" : 2.3,
  "SliceTiming" : [ 0, 1.53333, 0.06667, 1.6, 0.13333, 1.66667, 0.2, 1.73333, 0.26667, 1.8, 0.33333, 1.86667, 0.4, 1.93333, 0.46667, 2, 0.53333, 2.06667, 0.6, 2.13333, 0.66667, 2.2, 0.73333, 2.26667, 0.8, 2.33333, 0.86667, 2.4, 0.93333, 2.46667, 1, 2.53333, 1.06667, 2.6, 1.13333, 2.66667, 1.2, 2.73333, 1.26667, 2.8, 1.33333, 2.86667, 1.4, 2.93333, 1.46667 ],
  "SliceTimingComputationMethod" : "SliceNumber*RepetitionTime/NumberOfSlices (interleaved ascending, odd first)",
  "SpacingBetweenSlices" : 2.4,
  "StudyTime" : "182112",
  "dummyScans" : 5
}

**Comment by effigies** [comment]
Is there another JSON file higher in the hierarchy that has it? Try `grep -rI CogAtlasID /path/to/dataset`.

**Comment by jbwexler** [comment]
Ah, yes there is! Thanks!

**Comment by effigies** [comment]
This was a topic of discussion at the last BIDS maintainers meeting. We need to improve the error messages here, since the bad values are being reported at the leaf even when they're defined at the root.

**Comment by effigies** [comment]
Fixed in the schema validator.
