### ISSUE TITLE
Support Policy (browser & node)

### ISSUE THREAD

**Issue by constellates** [bids-standard/legacy-validator#115]
Now that there are more of us contributing to the validator and it's starting to be tested/used more broadly we should figure out what versions of node and browsers we want to officially support. Outside of those we can decide on a case by case basis whether it's worth it to add support.
### Node

This seems relatively straightforward. We can continue targeting the most recent LTS version of node. Right now that is v4.4.1. We can regularly update the version of node in Circle CI to match this to get day to day test coverage on this version.
##### Potential Conflicts
- Users who are unable to update their system to the latest LTS version of node due to policies or access limitations where they're working.
### Browser

This may also be straightforward. The web validator currently only supports chrome. This is because chrome is the only browser to support selecting a full directory into a file select input. If we only target support for Chrome there should only be a handful of language features node supports, but Chrome doesn't (block scoping, etc.). We can also be relatively sure users have an updated version because Chrome auto updates.
##### Potential Conflicts
- People making applications that reconstruct a dataset in the browser from a database and then run validation on it.
- People not using the the core BIDS validation function and instead using the validations that can run on single files such as testing an individual .tsv file.
### Recommendation

It seems like we can go with latest LTS version in Node and the latest Chrome. Let me know if any of the above conflicts are serious enough to consider or if I'm missing other reasons to broaden support.

**Comment by chrisgorgo** [comment]
I had a look and "webkitdirectory" is still only supported in Chrome, so this looks good to me.
