### ISSUE TITLE
HED sidecar validation prints "undefined" instead of sidecar file name

### ISSUE THREAD

**Issue by happy5214** [bids-standard/legacy-validator#1151]
When HED sidecar validation finds an error, it prints out `undefined` instead of the sidecar file name. This is due to the code passing the file name string instead of a file object to the `Issue` constructor. This will be fixed in an upcoming pull request that will implement dataset-level validation. I wanted to post this here so people knew this was a known issue.

**Comment by happy5214** [comment]
Please assign this issue to me.

**Comment by effigies** [comment]
I'm going to assume this is resolved.
