### ISSUE TITLE
scans.tsv filename does not match dataset code: 129

### ISSUE THREAD

**Issue by hrswearingen** [bids-standard/legacy-validator#1152]
Hi,

After running the bids-validator (version 1.5.9), I receive this error: "The filename is scans.tsv file does not match what is present in BIDS dataset. (code: 129 - SCANS_FILE_NOT_MATCH_DATASET).

I believe this is happening due to my .bidsignore file. The scans that are written into my .bidsignore file are the ones listed under the error that do not match the scans.tsv.

If I do not use a .bidsignore file, this error goes away. 

Is there a work-around for this issue? Or is the best way to use the validator with this error to create a configuration file. 

Thanks!

**Comment by sappelhoff** [comment]
@hrswearingen do you mean you are listing data recordings in `scans.tsv` that are in your `.bidsignore` file?

May I ask why you are `.bidsignoring` these files in the first place? Perhaps there is a way not to ignore them?

If they MUST be ignored, then indeed the only solutions I currently see are:

1. remove them from the scans.tsv as well
2. add scans.tsv to bidsignore
3. create a configuration file to catch this error
4. (there may be more solution that I cant think of right now)

**Comment by hrswearingen** [comment]
@sappelhoff Yes - there are data recordings listed in my scans.tsv file that are also in my .bidsignore file.

I am using the .bidsignore for certain files that are not supported by BIDS specification, such as localizers or diffusion derivates. I am using heudiconv to convert my dicoms into BIDS.

I think I can use some of your solutions as a work around, and I appreciate your help! Thank you.

**Comment by sappelhoff** [comment]
Alright good to hear - please feel free to re-open this issue if you want to come back to discuss it.
