### ISSUE TITLE
Add validator for BEP001 qMRI filenames

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#1159]
related bids-examples issue for qMRI: https://github.com/bids-standard/bids-examples/issues/227

cc @agahkarakuzu @gilles86

**Comment by tsalo** [comment]
Per today's call, we're going to split this task into two components: (1) filename validation and (2) metadata validation. The filename validation will be pushed through before the 1.5 release, while the metadata validation may take longer.
