### ISSUE TITLE
Code 38: Each session should contain the same number of files with the same naming scheme.

### ISSUE THREAD

**Issue by jpellman** [bids-standard/legacy-validator#116]
When I run the BIDS validator on some data with multiple visits I get the following error:

> 3: Not all sessions contain the same corresponding files. Each session should contain the same number of > files with the same naming scheme. (code: 38)

This is then followed by many, many lines stating that a number of files should exist according to the validator, but don't. The problem I'm having is that in our study, for some visits/sessions some acquisitions are acquired that aren't acquired for other visits/sessions, so pretty much all of these hypothetical missing files are for acquisitions that wouldn't be taken in a given visit.  Is this something that BIDS mandates or is this more meant as a warning for studies where multiple sessions should have the same number/type of acquisitions?

**Comment by chrisgorgo** [comment]
It is true that most longitudinal studies have similar or the same set of scans for each session, but this test/warning was originally supposed to look at each session separately and find missing files across subjects (see #56). This was implemented in this PR #97, but maybe something got lost in translation. @rwblair could you have a look?

**Comment by rwblair** [comment]
@jpellman Can you post some of the output that you're get so I can get an idea of the naming scheme?

I'll go over the session validator code this weekend to make sure it matches up with the original issue.

**Comment by jpellman** [comment]
I think it actually does function as expected- sorry for the noise.

What threw me off is that files in the derivatives folder are displayed as though they were in the main folder, which caused me to think that other acquisitions that didn't belong in the non-derivatives session folder were being displayed as well.

For instance:

> Not all sessions contain the same corresponding files. Each session should contain the same number of files with the same naming scheme.
>                        Evidence: Subject: sub-M10957251; Missing file: /ses-DSA/func/sub-M10957251_ses-DSA_task-rest_acq-CAP_recording-despiked_physio.tsv.gz

Would actually be missing in _/derivatives/sub-M10957251/ses-DSA/func/sub-M10957251_ses-DSA_task-rest_acq-CAP_recording-despiked_physio.tsv.gz_ rather than _sub-M10957251/ses-DSA/func/sub-M10957251_ses-DSA_task-rest_acq-CAP_recording-despiked_physio.tsv.gz_.

**Comment by chrisgorgo** [comment]
This does not look like desired behavior. Derivatives should be ignored.

**Comment by tjhendrickson** [comment]
I know that this thread is already closed, but I am also running into this issue. I am not surprised that there are slight differences between participants within my BIDS data set as some participants were unable to complete particular scans, some had to have scans re-run etc. When I get the error: **Not all subjects contain the same files. Each subject should contain the same number of files with the same naming unless some files are known to be missing.**, I'm wondering whether the BIDS validator sees this as a BIDS incompatible data set? If not, is there a way I can provide conditionals, in a file for example, to indicate that a participant not having a particular scan is expected?

-Tim

**Comment by chrisgorgo** [comment]
Are you sure this is an error not a warning?

You can ignore warnings (actually consistency of files is not stricly part of the standard). Alternatively you can instruct the validator to supress this check via a [config](https://github.com/INCF/bids-validator#configuration) file.

**Comment by tjhendrickson** [comment]
Ahh yes I spoke incorrectly, I meant to say "warning" not "error" in my message above. That is good to know that warnings can be ignored. This was not immediately clear to me whether this was the case. It might be helpful for other users that text is included on the BIDS validator GUI indicating that warnings can be ignored and that the data set given passed BIDS validation.

Thanks for your help @chrisfilo !
