### ISSUE TITLE
test bids-examples as part of bids-validator CI

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#1164]
the bids-examples CI should probably be run also as part of the bids-validator CI to see early when validator changes break examples. 

https://github.com/bids-standard/bids-examples/blob/a3135a66987841c42023c20d28b0e676855c3cce/.github/workflows/validate_datasets.yml#L1

The bids-examples are already included as a git submodule, but not testet:

https://github.com/bids-standard/bids-validator/tree/master/bids-validator/tests/data

**Comment by nellh** [comment]
bids-examples are tested in bids-validator/tests/bids.spec.js - a list of the example datasets is generated from the datasets present in the submodule and that is used to create tests for each example.

**Comment by sappelhoff** [comment]
> bids-examples are tested in bids-validator/tests/bids.spec.js - a list of the example datasets is generated from the datasets present in the submodule and that is used to create tests for each example.

Thanks :) ... should we then update the submodule more often? I am just wondering why bids-validator was passing for the last few months, while the CI on bids-examples was failing all this time (it's fixed now, since a few days)


EDIT: I see now that bids.spec.js does not test all bids-examples, but only a selection with several targeted tests. I was talking about adding a full test of all examples, which I think will be helpful for development of bids examples, validator, and spec.

https://github.com/bids-standard/bids-validator/blob/fa5c35ff86b71fe9177aff67821f0cee6e2f2563/bids-validator/tests/bids.spec.js#L1-L286
