### ISSUE TITLE
Add a checkbox for empty file option to web interface

### ISSUE THREAD

**Issue by VisLab** [bids-standard/legacy-validator#1180]
Could a checkbox be added to add the option to ignore issue 99 which is the empty raw file ignore.  This would allow users to try validating the examples using the web-interface.

**Comment by sappelhoff** [comment]
I think it would be more sustainable to add a second "upload" button, where users can upload a `bids-validator-config.json` file.

If you want to ignore issue 99, you would then format that file as such:

```
{
	"ignore": [99]
}
```

EDIT: However, users can also just add a `.bids-validator-config.json` to their dataset before upload, and that will be used :thinking:  so perhaps some documentation about that will be enough.
