### ISSUE TITLE
Add check for validity of the participants.tsv participant_id column

### ISSUE THREAD

**Issue by adam2392** [bids-standard/legacy-validator#1194]
Raised in: https://github.com/bids-standard/bids-specification/issues/737

This would check that if a participants.tsv file is present, then the `participant_id` MUST be of a certain form: `sub-<label>`.

**Comment by sappelhoff** [comment]
I think that'd be a good thing to validate. Can you take a stab at this @adam2392?

**Comment by adam2392** [comment]
Is the correct place for unit test: `tests/tsv.spec.js`?

Then where would be the correct place for implementation of validation?

Sorry I am 1) worse at js compared to Python and 2) have trouble parsing the validator repo when doing dev :p

**Comment by sappelhoff** [comment]
> Is the correct place for unit test: tests/tsv.spec.js?

Yes, I think so

I think the validation should be implemented here: https://github.com/bids-standard/bids-validator/blob/b542235df3579ed1328058ad41777c5dd96d2d73/bids-validator/validators/tsv/tsv.js#L189-L220


> Sorry I am 1) worse at js compared to Python and 2) have trouble parsing the validator repo when doing dev :p

same :-)

**Comment by adam2392** [comment]
Actually, isn't this partially being tested here already? Does this capture our use-case?

https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/bids/subjects.js

**Comment by sappelhoff** [comment]
> Actually, isn't this partially being tested here already? Does this capture our use-case?

it seems to me like this is one step later, after 1) the sub-xxx folders have been parsed and 2) the participants.tsv has been parsed ... and then both are being compared:

https://github.com/bids-standard/bids-validator/blob/b542235df3579ed1328058ad41777c5dd96d2d73/bids-validator/validators/bids/subjects.js#L1-L62

and an issue 49 is being raised if they don't match:

https://github.com/bids-standard/bids-validator/blob/b542235df3579ed1328058ad41777c5dd96d2d73/bids-validator/utils/issues/list.js#L273-L277

this part of the code thus seems more relevant for https://github.com/bids-standard/bids-validator/issues/937
