### ISSUE TITLE
BIDS-Validator is producing error when validating ASL dataset (v 1.6.2)

### ISSUE THREAD

**Issue by marcocastellaro** [bids-standard/legacy-validator#1199]
I just run into this error while validating an ASL dataset after merging the validator bep005 branch up to v1.6.2:

`hed_validator__WEBPACK_IMPORTED_MODULE_1___default.a.validator` is undefined

Evidence:

`checkHedStrings@webpack-internal:///../node_modules/bids-validator/validators/events/hed.js:39:3 __webpack_exports__.default@webpack-internal:///../node_modules/bids-validator/validators/events/events.js:21:62 fullTest/<@webpack-internal:///../node_modules/bids-validator/validators/bids/fullTest.js:146:60 `

I believe this could potentially be an error occurred when trying to validate the aslcontext.tsv file as an HED, however I am not sure about this since HED has recently been introduced. 

@rwblair you might know how to solve this?

**Comment by rwblair** [comment]
Might try running `yarn install` again, dependencies might have updated since you last merged. Let me know if that helps.

**Comment by marcocastellaro** [comment]
@rwblair solved. Thank you.
