### ISSUE TITLE
RF to use bids-specification/src/schema/ (via https://github.com/bids-standard/bids-schema?) as much as possible

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#1202]
https://github.com/bids-standard/bids-specification/tree/master/src/schema now (thanks to @tsalo for leading the effort) is now providing a machine readable specification sufficient to validate file paths and basic structure.  We should start working on formalizing that specification possible serialization(s) so they would be exported across all versions of BIDS in https://github.com/bids-standard/bids-schema and also possibly in a form most useful to be used by the tools such as bids-validator (see e.g. https://github.com/bids-standard/bids-schema/issues/2).  Having formalized serializations across different versions of BIDS could elevate many needs for hardcoding in bids-validator, and also make its reports bids version specific (with hints on what would change whenever validating against current released version etc)

**Comment by tsalo** [comment]
@rwblair started on this in #1126, but I think it's still early days.

EDIT: I'm also happy to help with this, but I can't take point because I don't know Javascript.
