### ISSUE TITLE
Should iEEG space entity allow 'individual' for subject-specific reconstructions from T1w

### ISSUE THREAD

**Issue by adam2392** [bids-standard/legacy-validator#1207]
Related in bids-spec: https://github.com/bids-standard/bids-specification/issues/747

If that `space` entity is allowed, there is still some confusion as to what needs to be checked.
- IntendedFor
- SpatialReference
- CoordinateSystemDescription

**Comment by effigies** [comment]
Is this still an issue? @adam2392 @dorahermes?

**Comment by dorahermes** [comment]
I believe it was mostly resolved with issue 747 above. 

If electrodes in different spaces are present, the IntendedFor should also change, but I don't think that there always has to be a certain file if space has a certain label.

**Comment by effigies** [comment]
Okay. Let's close and if there's something new to do, we can open a new issue.
