### ISSUE TITLE
PET: Add checks that custom columns exist in tsv file

### ISSUE THREAD

**Issue by ckrountree** [bids-standard/legacy-validator#1230]
Add checks that custom columns, defined in a JSON sidecar, exist in the associated tsv file. 

- [ ] Include any/all supporting tests
- [ ] Make it an 'ERROR' for _blood and _pet data
- [ ] Make it a 'WARNING' for other modalities

**Comment by sappelhoff** [comment]
closed in https://github.com/bids-standard/bids-validator/pull/1229, but somehow GitHub didn't close automatically.
