### ISSUE TITLE
PET: Validate TSV columns in 'non_custom' by related JSON sidecar properties

### ISSUE THREAD

**Issue by ckrountree** [bids-standard/legacy-validator#1231]
### IMPLEMENTATION
Implement the conditional logic, noted in Martin's comment, in the schema. 

### Relevant COMMENT(S)
Martin's [comment](https://github.com/bids-standard/bids-validator/pull/1229#discussion_r594633162) about catching specific fields:
> _Should we include an additional test where e.g. "PlasmaAvail": true, but then "plasma_radioactivity" is not included in the corresponding *.tsv file? This is what we would like to catch, as mentioned in our previous discussions on validating the tsv file._

### FILES
- [bids_validator/tsv/non_custom_columns.json](https://github.com/bids-standard/bids-validator/pull/1204/files#diff-1cc6901fd472ed23b5a355454426f43a87adf53144f15372ff4e13ec3dd5e2a5)
- bids-validator/validators/json/schemas/blood_pet.json

### DEFINED in the SPEC
> "_As with all tabular files, additional columns MAY be defined in `_blood.json`. For clarity, it is RECOMMENDED to include the (listed) column definitions in `_blood.json`..._"

[The spec](https://bids-specification.readthedocs.io/en/bep-009/04-modality-specific-files/09-positron-emission-tomography.html#blood-recording-data) describes the following 5 fields:
- “time”
- “plasma_radioactivity”
- “whole_blood_radioactivity”
- “metabolite_parent_fraction”
- “hplc_recovery_fractions”

**Comment by sappelhoff** [comment]
closed in https://github.com/bids-standard/bids-validator/pull/1229, but somehow GitHub didn't close automatically.
