### ISSUE TITLE
PET: invalid naming scheme

### ISSUE THREAD

**Issue by antotorov** [bids-standard/legacy-validator#1236]
Hello,

I have a dataset with pet images. I use the following naming scheme (as per [BIDS documentation on PET datasets](https://bids-specification.readthedocs.io/en/bep-009/04-modality-specific-files/09-positron-emission-tomography.html#positron-emission-tomography)):
```
sub-001/pet/sub-001_trc-18FFDG_rec-acstat_pet.nii.gz
sub-001/pet/sub-001_trc-18FFDG_rec-acstat_pet.json
```
When I run `bids-validator` (version `1.6.2`, install with `npm`), I get the following error:
```
1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
```
I have also tried without the optional fields `trc` and `rec` (i.e. using `sub-001_pet` instead of `sub-001_trc-18FFDG_rec-acstat_pet`), but I get the same error.

Has support for PET dataset been already implemented in `v1.6.2`? If yes, what am I doing wrong?

Thanks for your valuable help!

PS: I have nodejs `v10.19.0` and I am on Ubuntu `20.04.2`.

**Comment by effigies** [comment]
PET support is a work in progress.

**Comment by sappelhoff** [comment]
@antotorov do you still have the issue with v1.7.2? PET validation should be much better now compared to when you ran into the error with v 1.6.2.
