### ISSUE TITLE
Including QC-failed images

### ISSUE THREAD

**Issue by ins0mniac2** [bids-standard/legacy-validator#1242]
We are including QC-failed images in a BIDS dataset naming them as *_BADdwi.nii.gz etc. and putting these files under "ignoredFiles" in the validator config file. However, in case someone actually wants to process these, we are including the IntendedFor definitions for these files in the appropriate fieldmap files. 

The problem is that validator ignores the BADdwi files but the Intent definition trips it up because it can't find those (ignored) files.
[ERR] 'IntendedFor' field needs to point to an existing file. (code: 37 - INTENDED_FOR)

What is the best way to handle this situation ?

**Comment by sappelhoff** [comment]
Hey @ins0mniac2 I think you may have more success (in terms of people answering you) on https://neurostars.org/tag/bids (using the bids tag). Your question sounds more like a user question than a bug/issue with the bids-validator.

**Comment by ins0mniac2** [comment]
Thank you @sappelhoff . You are right -- I'll post there.
