### ISSUE TITLE
MATLAB output encoding issues (when applied to BIDS EEGLAB outputs)

### ISSUE THREAD

**Issue by CorentinWicht** [bids-standard/legacy-validator#1262]
Dear developers,

I am using the `pop_validatebids.m` function for the first time in order to validate the outputs generated by the [EEGLAB BIDS plugin](https://github.com/sccn/bids-matlab-tools) in MATLAB and the output in the command window looks weird:
![image](https://user-images.githubusercontent.com/52161904/114174398-d8d52e00-9938-11eb-961a-64c60d3fd24f.png)

There seems to be enconding issues and I am having a hard time understanding the overall message.

Also, the link regarding existing topics on the utf-8 issue is deprecated (and shouldn't certainly contain space characters):
(https://neurostars.org/search?q=INVALID JSON ENCODING

Has this issue already been raised ?

Best regards,

Corentin Wicht

**Comment by sappelhoff** [comment]
Hi Corentin,

do you have NaN values in your participants.tsv file that are not coded as `n/a`? From the output it looks like there are some `NaN` values that should be recoded to `n/a`.

Regarding the format of the output in general, this seems to be a Matlab issue to me --> for that you are more likely to receive help at https://github.com/sccn/bids-matlab-tools (at least I don't have another advice right now)

**Comment by nellh** [comment]
The issue here is the caller is running a shell of some kind that says it supports color output. Then that output is getting read in with the color escape sequences even though they aren't used in MATLAB.

**Comment by dungscout96** [comment]
Hi Corentin, I created an issue at the bids-matlab-tools repo: https://github.com/sccn/bids-matlab-tools/issues/72. We will work on the formatting.

**Comment by sappelhoff** [comment]
Thanks @dungscout96, I'll close this one.

**Comment by CorentinWicht** [comment]
Many thanks for your replies, could you keep me updated as soon as you release a new build with the fix? 

Best wishes,

Corentin
