### ISSUE TITLE
Add configuration flag to disable terminal escape sequences (color) in output

### ISSUE THREAD

**Issue by nellh** [bids-standard/legacy-validator#1263]
To help with pseudo-terminal setups like MATLAB that advertise color support but don't actually understand the escape sequences. See #1262 and https://github.com/sccn/bids-matlab-tools/issues/72

The colors library we're using for this causes some issues for browser support as well, so maybe the right fix here is to drop the library and just implement the terminal feature detection in a way that works better for the MATLAB use case and has a flag to control it.

**Comment by effigies** [comment]
Additionally worth respecting the [`NO_COLOR`](https://no-color.org/) environment variable while we're at it.

**Comment by rwblair** [comment]
`--no-color` is respected by the colors library when passed to the validator. Tested calling `colors.disable()` in bids-validator/cli.js and that seemed to work, I can add a check for NO_COLOR there unless anyone can think of a more appropriate place to add it.

#1270

**Comment by nellh** [comment]
> `--no-color` is respected by the colors library when passed to the validator. Tested calling `colors.disable()` in bids-validator/cli.js and that seemed to work, I can add a check for NO_COLOR there unless anyone can think of a more appropriate place to add it.
> 
> #1270

Looks good for now, we don't have to drop the library, we can just put it outside of the browser entrypoint.
