### ISSUE TITLE
Does bids-validator support all the versions of the BIDS standard

### ISSUE THREAD

**Issue by civier** [bids-standard/legacy-validator#1269]
Hello,

Just wonder if the validator supports all versions of the BIDS standard? or rather only the latest version or up to a certain version? If it doesn't support all versions, can you please mention in the README the newest version which is supported.

Thanks ahead,
Oren

**Comment by sappelhoff** [comment]
Hi @civier the bids-validator tracks the latest *stable* version of the BIDS specification. In several cases, the bids-validator will be behind the specification, in that it does not actually check something that is prescribed by the spec. -> That's mostly an issue of too few contributors to extend the validator fast enough to keep up with the development of the specification. (We are looking for contributors to help us with that).

> can you please mention in the README the newest version which is supported.

If you want, you could make a Pull Request to this repo and add a short Markdown section under the "Support" section in the README. there you could mention what I just answered.

**Comment by erdalkaraca** [comment]
In this context, I just wondered if you considered to use the BIDS Schema to validate/check a BIDS dataset (whether it conforms to the BIDS spec). At least, it seems the BIDS schema is "closer" to the spec.

**Comment by effigies** [comment]
Yes, the goal is to move toward using the schema for validation. This is going to be a pretty significant effort, and we don't yet have a time frame.

**Comment by erdalkaraca** [comment]
I have not yet encountered a "working" json/yaml schema validator (tried on BEP-02 schema).
I am not sure if the BIDS schema itself has a formal meta-schema like XSD for XML. That would be a first step to ensure, I think.

> Yes, the goal is to move toward using the schema for validation. This is going to be a pretty significant effort, and we don't yet have a time frame.

**Comment by sappelhoff** [comment]
@erdalkaraca please see https://github.com/bids-standard/bids-specification/tree/master/src/schema and the related https://github.com/bids-standard/bids-specification/projects/4

It's all work in progress. If you want to join the efforts, I recommend you chime in on open issues about the schema-fication of BIDS!

@civier I am closing this now as your original inquiry has been answered.
