### ISSUE TITLE
Eye Tracking:  errors with top-level metadata files

### ISSUE THREAD

**Issue by loj** [bids-standard/legacy-validator#1275]
I'm working with a [dataset](https://github.com/psychoinformatics-de/studyforrest-data-phase2) that contains eyetracking data. Currently, there is an eyetracking `tsv.gz` file at the subject level:

`sub-<int>/ses-<id>/func/sub-<id>_ses-<id>_task-<id>_run-<int>_recording-eyegaze_physio.tsv.gz`

and then a top-level JSON metadata file:

`recording-eyegaze_physio.json`

<details><summary>file content</summary>
<p>

```
{
  "SamplingFrequency": 1000.0, 
  "StartTime": 0.0, 
  "Columns": ["x", "y", "pupil_dil", "movieframe_idx"], 
  "ContentDescription": "The x/y coordinates are normalized to (0,0) at the top-left corner of the movie stimulus (already excluding the gray horizontal bars)."
}
```
</p>
</details>

There are also top-level metadata files to describe each task:

  `task-*_physio.json`
<details><summary>example file content</summary>
<p>

```
{
  "TaskName": "movielocalizer",
  "TaskDescription": "Participants had to fixate the center of the screen, while a flickering stimulus was displayed, alternating every 12s between 'inside-movie' and 'outside-movie' areas, starting with 'inside-movie' for a total of four cycles. The 'inside-movie' area represented the same FoV used for displaying the movie in the 'movie' task.",
  "CogAtlasID": "http://www.cognitiveatlas.org/task/id/trm_4c898f72228f3"
}
```
</p>
</details>

When I run the dataset through the `bids-validator` (v1.7.1). The validator seems to mistake the `task-*_physio.json` files as the side car files for the subject-level `*_recording-eyegaze_physio.tsv.gz` files instead of seeing the  `recording-eyegaze_physio.json` file.
```
File Path: Invalid JSON file. The file is not formatted according the schema.

Type:  Error
File:  task-movie_physio.json
Location:  studyforrest-data-phase2/task-movie_physio.json
Reason: Invalid JSON file. The file is not formatted according the schema.
Evidence:  should have required property 'SamplingFrequency'
```

Is there a more correct way to structure/name these files? Or is this a mistake by the validator?

Ping https://github.com/psychoinformatics-de/studyforrest-data-phase2/issues/17

**Comment by effigies** [comment]
Pretty sure there's a rule that only one json file can apply at a level, as otherwise any overlaps are ambiguous. It's unclear why you need to describe the task in the physio file, though...

**Comment by effigies** [comment]
> ### [The Inheritance Principle](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#the-inheritance-principle)
> Any metadata file (such as .json, .bvec or .tsv) may be defined at any directory level, but ***no more than one applicable file may be defined at a given level*** (Example 1).

Emphasis added.

**Comment by loj** [comment]
Aha, that makes sense! Thanks for your response and the added emphasis. :-)
