### ISSUE TITLE
How to check/"stat" text file within BIDS validator?

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#1279]
I want to add a feature to the bids-validator: 

- if the recommended README file is present:
- check how "large" it is (either how many lines, or how much content?)
- raise a warning if it's only very little (threshold to be determined)

I think it could go well after this line as an `else`:

https://github.com/bids-standard/bids-validator/blob/b40aa16a4250bb4aaacd2c063dad108084f6b83f/bids-validator/validators/bids/checkReadme.js#L10-L12

How would I read the file contents? ... or maybe even a simply `stat README` (like in bash) and extracting the size would be sufficient for me to either say: "yup, that seems large enough", versus "that's a suspiciously small README. I'll raise a warning to make the user aware that the README is crucial and that they please spend more effort on it"

Related to 
- https://github.com/bids-standard/bids-specification/issues/662
- https://github.com/bids-standard/bids-specification/pull/793

**Comment by nellh** [comment]
Post #1244 / #1245 the idea is to consolidate this to [FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList) and [File](https://developer.mozilla.org/en-US/docs/Web/API/File) objects. file.size would be the only way to access the size.

Currently it requires the check to handle file.size for browsers (the above API) and file.stats.size for Node. Example: https://github.com/bids-standard/bids-validator/blob/571767eb23b4b8cae133166d0fcb62a629c8f191/bids-validator/utils/files/validateMisc.js#L5

File contents should also follow the web APIs going forward.

**Comment by sappelhoff** [comment]
> Post #1244 / #1245 the idea is to consolidate this to FileList and File objects. file.size would be the only way to access the size.

that sounds like it would be a great improvement 👍 

Thanks for the hint, that allows me to proceed with what we have right now.
