### ISSUE TITLE
Header Fields check doesn't account for missing units

### ISSUE THREAD

**Issue by constellates** [bids-standard/legacy-validator#128]
The headerFields.js validator relies on xyzt_units and breaks the validation if they're not defined.

https://github.com/INCF/bids-validator/blob/master/validators/headerFields.js#L48

Here's how we handle a similar issue in the main nifti validator.

https://github.com/INCF/bids-validator/blob/master/validators/nii.js#L74

We could use a similar ternary, but I don't know enough about the headerFields.js to know what else may be affected by setting units to null or an empty array.

@rwblair can you take a look or give me a breakdown of how this check is using the units. 

You can see the issue by testing ds108.

**Comment by rwblair** [comment]
I'll update headerFields.js to check to make sure the header values are there, and to skip dimensionality and resolution checks depending on what header values aren't present.
