### ISSUE TITLE
VolumeTiming be array of number (which is correct) not passing BIDS Validator

### ISSUE THREAD

**Issue by ycAbout** [bids-standard/legacy-validator#1289]
BIDS Validator v1.7.3-dev.0
https://bids-standard.github.io/bids-validator/

For bold scan, when VolumeTiming is array of number 
```
    "VolumeTiming": [
        0.0,
        1.5,
        3.0,
        4.5,
        6.0,
        7.5,
        9.0,
        10.5,
        12.0,
        13.5
    ],
```
bids validator report error:
```
Location:
project/func/sub-abc_task-resting_bold.json
Reason:
Invalid JSON file. The file is not formatted according the schema.

Evidence:
.VolumeTiming should be number

```
However, bids standard reads "array of numbers"
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#required-fields

**Comment by sappelhoff** [comment]
thanks for the report, I think that'd need to be fixed here: https://github.com/bids-standard/bids-validator/blob/1e92dc1da31046e741c80081cfb67e54ac11a763/bids-validator/validators/json/schemas/bold.json#L41-L44

Do you want to make  a PR for that?

**Comment by sappelhoff** [comment]
side note: it's odd that https://bids-standard.github.io/bids-validator/ shows `1.7.3-dev.0`, it should be `1.7.2` :thinking: but making a tag for a "development version" unfortunately also triggered a web-validator release. cc @nellh @rwblair 

I think that could be solved in CircleCI by skipping deployment if the current version contains `dev`:

https://github.com/bids-standard/bids-validator/blob/a3dccf93df338880b9c996dfb93b147419dc7df1/.circleci/config.yml#L153

**Comment by ycAbout** [comment]
Sure, @sappelhoff , I can make a PR for that.
