### ISSUE TITLE
Reducing HED's foot print in the BIDS validator

### ISSUE THREAD

**Issue by VisLab** [bids-standard/legacy-validator#1300]
We have been discussing how to reduce the foot print of HED in the BIDS validator for easier maintenance and would like some feedback as we proceed.  We see 3 changes that would improve the overall structure and usability.

1. Only load the HED schema if the data set explicitly has HED fields.  This is the subject of PR #1298.
2. Store the latest version of the HED schema in the HED JavaScript validator as a fall back so things can proceed in the case of a recalcitrant firewall. (We intended to do this in a couple of weeks when HED 3 is officially released. This change should be invisible with respect to BIDS.)
3. **Restructure the errors**.  The idea is that HED would only use two error codes (104 renamed as HED_ERROR and 105 renamed as HED_WARNING).  All of the details about the error would be provided in the evidence.

The restructuring would allow us to align the errors to the HED specification without impacting BIDS.  We would release the rest of the BIDS error codes used by HED.  @happy5214  and I have been looking at the current code base, and we think this restructuring would be feasible and would not involve too many changes on the BIDS side.  We would appreciate comments and or suggestions on this before we proceed with the restructuring. @sappelhoff @rwblair @effigies

**Comment by effigies** [comment]
This plan sounds good to me. I appreciate the effort you're putting into this, as fMRIPrep relies on being able to run the validator without hitting the internet in some very common use cases.

**Comment by sappelhoff** [comment]
Those are three good suggestions that'll make maintenance of the HED and BIDS validators easier :+1: 

I am not sure whether we ever "released" existing issue codes before, but I don't see a problem with it --> especially not until we think about giving an issue code that was previously some specific HED issue code a new, different meaning.

**Comment by VisLab** [comment]
As part of thinking about this, we made a spreadsheet of all of the existing BIDS codes and there are quite a few intermediate values that are now listed as unused.  We thought we could just contribute a bunch of these to a "pool" of free codes.
