### ISSUE TITLE
eeg, meg json schema include `InstitutionalDepartmentName` but the spec does not

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/legacy-validator#1310]
see here:
- https://github.com/bids-standard/bids-validator/blob/39922c4159688fcc67ba6b723d391991c75211e3/bids-validator/validators/json/schemas/eeg.json#L10
- https://github.com/bids-standard/bids-validator/blob/39922c4159688fcc67ba6b723d391991c75211e3/bids-validator/validators/json/schemas/meg.json#L10

I think this is only used for MRI data in the spec:

https://github.com/bids-standard/bids-specification/blob/master/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md#institution-information

and this seems to keep in line with a dicom tag

https://github.com/bids-standard/bids-specification/blob/master/src/schema/metadata/InstitutionalDepartmentName.yaml

My gut feeling is to remove it from the json schema in the validator rather than modify the spec to align with the validator. But I may be missing something.

**Comment by sappelhoff** [comment]
+1 to remove from the validator if it's not in the spec.
