### ISSUE TITLE
package-lock.json in root still uses old hed-validator version 

### ISSUE THREAD

**Issue by happy5214** [bids-standard/legacy-validator#1317]
The `package-lock.json` file in the root directory still contains instructions for installing version 3.0.5 of hed-validator. While it may be poor semver compliance on our part, the current code in bids-validator is no longer compatible with that version of hed-validator, so the web BIDS validator is effectively unusable with HED data. This is a must-fix, and I simply cannot figure out why the package manager will not put 3.4.0 (or any recent version for that matter) in the lock file.

**Comment by nellh** [comment]
The lockfile defines the root of the package tree and it won't consider anything above the lockfile (or adjacent in another package). It looks like there's accidentally an extra one in the bids-validator package, it just needs to be removed and the root level one updated. We should .gitignore package-lock.json except at the repository root.

**Comment by happy5214** [comment]
#1318 did not at all fix the original issue I raised, as the root `package-lock.json` still loads hed-validator version 3.0.5 due to a dependency clash (see line 1206). Please reopen.
