### ISSUE TITLE
Newest Docker image in DockerHub?

### ISSUE THREAD

**Issue by pvelasco** [bids-standard/legacy-validator#1322]
Hi,
Are there any plans on pushing the latest official Docker image to DockerHub?
The latest version [there](https://hub.docker.com/r/bids/validator/tags?page=1&ordering=last_updated) seems to be v1.8.0
Thanks!

**Comment by sappelhoff** [comment]
true, that's weird because the images should be automatically pushed upon a release. cc @rwblair

**Comment by pvelasco** [comment]
I think Docker now requires a subscription for [automated builds](https://docs.docker.com/docker-hub/builds/).

**Comment by sappelhoff** [comment]
True 🤔 thanks! Perhaps we need to extend our circleci script to make a deployment. Something like here: https://github.com/BIDS-Apps/HCPPipelines/blob/4923bb3bb29543a0b74b9b5940b694fb1595d101/circle.yml#L29-L37

**Comment by sappelhoff** [comment]
Seems to work now (thanks @pvelasco for starting and @rwblair for finishing up): https://hub.docker.com/r/bids/validator/tags?page=1&ordering=last_updated

@rwblair what kinds of images will be pushed now? For each PR on each commit? For each commit to master as "master" (not "latest"?)? For tags?

**Comment by sappelhoff** [comment]
also, the docker action fails in #1351 :thinking:

**Comment by sappelhoff** [comment]
okay, it seems to be working now

- https://hub.docker.com/r/bids/validator/tags
- and also on the GitHub container registry: https://github.com/bids-standard/bids-validator/pkgs/container/bids-validator

Thanks @rwblair
