### ISSUE TITLE
Valid SI units

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [bids-standard/legacy-validator#1354]
What's the status of valid SI units in BIDS? Since https://github.com/bids-standard/bids-specification/pull/411 was merged in June 2020, is it time to uncomment the following code?
https://github.com/bids-standard/bids-validator/blob/abb700c79b6d79683598a394aea5e0573b33412b/bids-validator/validators/tsv/tsv.js#L309-L336

**Comment by sappelhoff** [comment]
see bids-standard/bids-validator#71, please chime in over there! :-)
