### ISSUE TITLE
MP2RAGE [BEP001] - validator expects `flip` instead of `fa`

### ISSUE THREAD

**Issue by octomike** [bids-standard/legacy-validator#1356]
We're currently trying to validate a dataset that uses MP2RAGE anatomy imaging data defined through [BEP001](https://github.com/bids-standard/bep001/blob/master/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md).

[According to the extension](https://github.com/bids-standard/bep001/blob/master/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md#suffix) the flip angle value is supposed to be labeled `fa-<index>`, but the validator [seems to expect](https://github.com/bids-standard/bids-validator/blob/master/bids-validator/bids_validator/rules/file_level_rules.json#L122) `flip-<index>` instead. We verified it by trying to validate with version 1.8.0 on both file names, `flip` works fine, `fa` doesn't.

Are we missing something or is this just a simple typo?

**Comment by effigies** [comment]
BEP001 has been merged into the BIDS standard, which supersedes its provisional recommendations: https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomy-imaging-data

The `fa-` entity was deemed to potentially conflict with the `_FA` (fractional anisotropy) suffix, so it was replaced with `flip-`.

**Comment by octomike** [comment]
well that certainly makes sense.. sorry to bother you :)
