### ISSUE TITLE
Way to specify BIDS version?

### ISSUE THREAD

**Issue by jpellman** [bids-standard/legacy-validator#136]
Does the validator have any mechanism for specifying which version of the BIDS spec the dataset is organized in?

**Comment by chrisgorgo** [comment]
The validator does not do it right now, but it could, in theory, read the BIDSVersion field from dataset_description.json see https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit#heading=h.ie43v2mfgaeq.
