### ISSUE TITLE
MEG CTF format with filenames not matching the `.ds` folder name

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/legacy-validator#1360]
@guiomar and I are working on a talk where we plan to convert some data by hand (see this [repo](https://github.com/Remi-Gau/bids_cookbook/)).

She taught that it might not be a good idea to rename CTF MEG file manually by **simply** changing the `.ds` folder name if only because some of the files in this folder have names that is usually matched to that folder name.

My original script created something like this that the validator is happy with.

```
├── sub-01
│   ├── ses-eeg
│   │   └── eeg
│   ├── ses-meg
│   │   └── meg
│   │       ├── sub-01_ses-meg_task-FaceSymmetry_run-1_meg.ds
│   │       │   ├── BadChannels
│   │       │   ├── bad.segments
│   │       │   ├── ClassFile.cls
│   │       │   ├── MarkerFile.mrk
│   │       │   ├── params.dsc
│   │       │   ├── processing.cfg
│   │       │   ├── SPM_CTF_MEG_example_faces1_3D.acq              < -- Those filenames do not match the folder name
│   │       │   ├── SPM_CTF_MEG_example_faces1_3D.hc
│   │       │   ├── SPM_CTF_MEG_example_faces1_3D.infods
│   │       │   ├── SPM_CTF_MEG_example_faces1_3D.meg4
│   │       │   ├── SPM_CTF_MEG_example_faces1_3D.newds
│   │       │   └── SPM_CTF_MEG_example_faces1_3D.res4
│   │       └── sub-01_ses-meg_task-FaceSymmetry_run-2_meg.ds
│   └── ses-mri
│       ├── anat
│       └── func
├── T1w.json
└── task-FaceSymmetry_bold.json
```

Would it make sense for the validator to also check for the names inside `.ds` folders?

**Comment by sappelhoff** [comment]
See #692 :-)

CTF has another problem, see #651 

Regarding your demo, see this snippet from the BIDS spec:

> The renaming of CTF datasets SHOULD be done with a specialized software such as the CTF newDs command-line application or MNE-BIDS.

(souce: https://bids-specification.readthedocs.io/en/stable/99-appendices/06-meg-file-formats.html#ctf, and [code in mne-bids](https://github.com/mne-tools/mne-bids/blob/2f3d24fcefb6a5c3ff16ea9d752a8269e50b4b55/mne_bids/copyfiles.py#L135-L164))

**Comment by Remi-Gau** [comment]
ok closing this as it is a duplicate

thanks @sappelhoff

**Comment by guiomar** [comment]
Yes, we indeed included a note on meg specs at the time, so no good idea to do manual MEG-BIDS conversions, specially with ctf data
