### ISSUE TITLE
No error when channels.tsv files are not placed in the `meg` folder

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/legacy-validator#1369]
See issue in the bids example: https://github.com/bids-standard/bids-examples/issues/296

This is probably a bug.

Suggested course of action.

- open a PR to fix validator to throw an error on that dataset
- open a PR to fix dataset in the examples
- merge everything
- and they lived happily everafter

**Comment by effigies** [comment]
Not an issue. Might be weird, but the inheritance principle doesn't say you have to be normal.
