### ISSUE TITLE
bids-validator crashes when dataset_description.Authors is an array of arrays of strings

### ISSUE THREAD

**Issue by dmalt** [bids-standard/legacy-validator#1389]
Location:
[Empty]
Reason:
r.split is not a function; please help the BIDS team and community by opening an issue at (https://github.com/bids-standard/bids-validator/issues) with the evidence here.

Evidence:
TypeError: r.split is not a function at Oi (https://bids-standard.github.io/bids-validator/_next/static/chunks/pages/index-0f2773bd3f43be25560d.js:1:573440) at xi (https://bids-standard.github.io/bids-validator/_next/static/chunks/pages/index-0f2773bd3f43be25560d.js:1:573767) at https://bids-standard.github.io/bids-validator/_next/static/chunks/pages/index-0f2773bd3f43be25560d.js:1:577733

**Comment by sappelhoff** [comment]
Thanks for the report @dmalt:

- have you been able to solve this issue in the meantime?
- Did this problemonly occur with a specific dataset?
- It looks like you used the [web-validator](https://bids-standard.github.io/bids-validator/), did you try the command line validator as well and ran into the same issue?

**Comment by dmalt** [comment]
Hello @sappelhoff!
Nope, the issue persists, and yes I get this for a specific dataset. For others everything is fine. I've tried the CLI version and it shows the same error with a more sane traceback:

```
$ bids-validator ~/asus_home/Data/metacognition/MEG1/rawdata                                                                                              
bids-validator@1.8.5
bids-specification@disable
	1: [ERR] Internal error. SOME VALIDATION STEPS MAY NOT HAVE OCCURRED (code: 0 - INTERNAL ERROR)
		.undefined
			Evidence: TypeError: author.split is not a function
    at checkAuthorField (/usr/lib/node_modules/bids-validator/dist/commonjs/cli.js:140818:18)
    at checkDatasetDescription (/usr/lib/node_modules/bids-validator/dist/commonjs/cli.js:140801:30)
    at /usr/lib/node_modules/bids-validator/dist/commonjs/cli.js:140995:38

	Please visit https://neurostars.org/search?q=INTERNAL ERROR for existing conversations about this issue.

        Summary:                   Available Tasks:        Available Modalities:
        779 Files, 106.98GB                                MEG
        31 - Subjects                                      MRI
        1 - Session


	If you have any questions, please post on https://neurostars.org/tags/bids.
```

**Comment by sappelhoff** [comment]
Could you please upload you `dataset_description.json` file? Maybe that can help us to debug :-)

**Comment by dmalt** [comment]
Sure! Here you go: [dataset_description.json](https://drive.google.com/file/d/1NasZAtaztT_PMUD0BcqUUTqBr5CI8zGq/view?usp=sharing)

**Comment by sappelhoff** [comment]
Ah, you should be able to solve your problem by removing a duplicate pair of square brackets from the "Authors" field:

```yaml
{
    "Name": "meg1",
    "BIDSVersion": "1.6.0",
    "DatasetType": "raw",
    "Authors": [
        [ <-- This one needs to go !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            "Beatriz Martin Luengo",
            "Maria Alekseeva",
            "Dmitrii Altukhov",
            "Yuri Shtyrov"
        ] <-- This one needs to go !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    ]
}
```

**Comment by sappelhoff** [comment]
Having that said, bids-validator should not crash here, but give you a more meaningful error message. something like 

> You passed an array of arrays ... please use an array of strings.

cc @rwblair

**Comment by dmalt** [comment]
Thanks a lot! This was indeed the issue.

> Having that said, bids-validator should not crash here, but give you a more meaningful error message. something like

Yes, ideally it should also say which file caused the problem \ was the last to be checked.
