### ISSUE TITLE
Warning when gzip headers contain non-BIDS filenames

### ISSUE THREAD

**Issue by nellh** [bids-standard/legacy-validator#1400]
The original filename might contain identifiable information if NIfTI files are compressed prior to being renamed. We should detect this and raise a warning if the header doesn't match the current filename.

**Comment by effigies** [comment]
Note https://github.com/bids-standard/bids-specification/pull/1349 proposes making an error (I'm pushing for warning) for any value in the original filename. Also a non-zero timestamp.

**Comment by kousu** [comment]
Yes, isn't it simpler if the headers simply aren't there? BIDS already specifies a fairly strict format of filenames, there's no need for that data to be duplicated in the gzip header.

Particularly I have the rationales in https://reproducible-builds.org/docs/build-path/ and https://reproducible-builds.org/docs/timestamps/ in mind.

**Comment by Remi-Gau** [comment]
From a quick read, would this relate to this VERY old issue I opened ?

https://github.com/bids-standard/bids-specification/issues/136

**Comment by effigies** [comment]
Yeah, looks like it.
