### ISSUE TITLE
Validate numeric values in TSV files use periods for decimal separators, rather than thousands

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/legacy-validator#1401]
I ended up with an `events.tsv` with this "shape" for numerical value (Excel tried to be too smart once again!!!) and the validator did not pick up on this.

Am I right that this should probably be flagged?

```
onset	duration	trial_type
42.000.000	42.000.000	listening
126.000.000	42.000.000	listening
210.000.000	42.000.000	listening
294.000.000	42.000.000	listening
378.000.000	42.000.000	listening
462.000.000	42.000.000	listening
546.000.000	42.000.000	listening
```

**Comment by VisLab** [comment]
I think so.....   I seem to remember a section somewhere about European
format for fixed point numbers.  I didn't think it was allowed.

**Comment by effigies** [comment]
> ### [Tabular files](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#tabular-files)
> [...] Numerical values MUST employ the dot (.) as decimal separator and MAY be specified in scientific notation, using e or E to separate the significand from the exponent.

Checking all values will be prohibitive, but we can probably do a check of the first N lines for some smallish N.

One question is what's the appropriate format? We could require them to be C-style floating point literals, matched by the regex `[+-]?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?`. Or should we permit comma-separated triplets?

Further, is the string value "1.000.000" invalid? How does one distinguish that from an incorrectly formatted number? I'm not sure we can do more than warn here without invalidating strings. Ultimately, I think the logic would need to go:

```Python
likely_number = r"^[\d., eE+-]+$"
valid_number = r"^[+-]?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?$"
if re.match(likely_number, value) and not re.match(valid_number, value):
    warn
```

I did have a comment about potentially breaking existing datasets with Excel-generated TSVs, but in light of the string/number ambiguity, I think we can only warn anyway.

---

Edit: Combined three comments.

**Comment by effigies** [comment]
Checking all values will be prohibitive, but we can probably do a check of the first N lines for some smallish N.

I guess the question is what's the appropriate format? We could require them to be C-style floating point literals, matched by the regex `[+-]?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?`. Or should we permit comma-separated triplets?

Any choice made here feels like it has the potential to break a lot of datasets where TSV files were generated with tools like Excel.

**Comment by effigies** [comment]
Is the string value "1.000.000" invalid? How does one distinguish that from an incorrectly formatted number? I'm not sure we can do more than warn here without invalidating strings. I think the logic would need to go:

```Python
likely_number = r"^[\d., eE+-]+$"
valid_number = r"^[+-]?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?$"
if re.match(likely_number, value) and not re.match(valid_number, value):
    warn
```

**Comment by sappelhoff** [comment]
> I'm not sure we can do more than warn here without invalidating strings.

At least for `onset` and `duration` we can perform a "strong" validation (with errors). For other columns, I agree with your "warning logic"

**Comment by Remi-Gau** [comment]
seems to be fixed on the deno validator
