### ISSUE TITLE
Warn when BIDSVersion exceeds latest version at time of release

### ISSUE THREAD

**Issue by effigies** [bids-standard/legacy-validator#1403]
If a dataset declares itself to have `BIDSVersion` of 1.9.0, it likely is doing so because there are things specified in 1.9.0 that were not present in 1.7.0 or 1.8.0. Or, perhaps, they might have made a mistake (such as using the validator version instead of the spec version).

It probably makes sense for the validator to have a concept of what versions it knows about and can at least warn that the user might need to upgrade to properly validate their dataset.

**Comment by Remi-Gau** [comment]
Given this:
https://github.com/bids-standard/bids-specification/issues/1469

I am tempted to say that the message should make it clear which BIDSversion values are accepted.

I would also be tempted to make this an error and not a warning: given BIDSVersion is required, it makes sense from my point of view to only accept recognized version of BIDS: this will in any case be necessary if we want one day for the validator to validate specific BIDS versions and not "just" the latest.

**Comment by effigies** [comment]
Opened bids-standard/bids-specification#1472 to solve this problem in the schema validator. This could also be done independently in the legacy validator.
