### ISSUE TITLE
BUG (?) - scans.tsv backslash path

### ISSUE THREAD

**Issue by richardkoehler** [bids-standard/legacy-validator#1408]
Dear all,

I write my BIDS datasets with FieldTrip's [data2bids](https://www.fieldtriptoolbox.org/reference/data2bids/) function.
This function writes out filenames in scans.tsv with a backslash, e.g.:

> ieeg\sub-009_ses-EcogLfpMedOff01_task-SelfpacedRotationR_acq-StimOff01_run-01_ieeg.vhdr

The bids validator gives the following error:

> [ERR] The filename in scans.tsv file does not match what is present in the BIDS dataset. (code: 129 - SCANS_FILENAME_NOT_MATCH_DATASET)

I don't know enough about path styles and back and forward slashes, but my feeling is that file path separators are system-dependent, bids-validator should work in both cases and optimally convert the slash to the system-specific separator when checking if the file actually exists.
I am not sure if this makes sense or is even possible, but I am happy to hear your opinions and I am happy to contribute to the code if necessary :)

Thanks in advance!

**Comment by sappelhoff** [comment]
related: https://github.com/bids-standard/bids-specification/pull/867 which was brought up here: https://github.com/bids-standard/bids-specification/pull/820#discussion_r685768236

If I understood it correctly, Windows can actually deal with both `/` and `\` as path separators, whereas unix systems only accept `/` (maybe https://stackoverflow.com/q/1589930/5201771 ?) --> therefore, all BIDS path separators should be (MUST, actually) forward slashes `/`.

It's relatively straight forward for tools to make this easy for users, so we just need to make this clearer everywhere (and find consensus, if this is actually controversial)

**Comment by richardkoehler** [comment]
Okay, that's actually great news, and pretty much answers my question.
I hope your PR will make it to the next bids-specification then and I will make a PR to fieldtrip to handle this issue.
Thanks again!

**Comment by sappelhoff** [comment]
Buuut, I am not entirely sure about this comment of mine:

> If I understood it correctly, Windows can actually deal with both / and \ as path separators, whereas unix systems only accept /

Maybe some Windows users can chime in? @VisLab for example? Or you can test it on your machine?

**Comment by richardkoehler** [comment]
So, since I am pretty inexperienced with this kind of stuff, I am not sure if I need to test this in a specific piece of code, but the following cases work:
- Using both back and forward slashes works in my windows command prompt or terminal
- Replacing the back slash by a forward slash in the scans.tsv resolves the problem with the bids-validator, so forward slash seems to work fine on windows here
