### ISSUE TITLE
Channel columns: split cases "MISSING" and "WRONG_ORDER" 

### ISSUE THREAD

**Issue by richardkoehler** [bids-standard/legacy-validator#1411]
As discussed in #1410 
Currently, bids-validator checks the first columns in channels.tsv and throws a **[CODE72] MISSING_TSV_COLUMNS_IEEG_CHANNELS** error if the first columns are not all required columns, i.e. if the order of the columns is wrong.

![grafik](https://user-images.githubusercontent.com/70506259/151953688-1e5cbb81-bff5-459c-b6ef-e78f988a4414.png)

Ideally ,the error message should in this be more precise. When all required columns are present, but not in the right order, it should throw an error that is something like: **WRONG_ORDER_TSV_COLUMN_IEEG_CHANNELS**

The corresponding source code I think can be found [here](https://github.com/bids-standard/bids-validator/blob/4feb91b8aa9506c123d38327485dd5d4cd69e80b/bids-validator/validators/tsv/tsv.js#L406), where each single column name is checked to be at the correct position, e.g.
`checkheader('name', 0, file, 72)`
A solution might be to add a new method before the positional checks that checks simply if all required columns are present. If not, then we get the MISSING error. We would then also change the error code in the `checkheader` method to a different error code which would give us information about the wrong order.

Would this be the preferred way to go?

I am happy to contribute to this, but I have no prior experience in JS so it might be a bit bumpy

**Comment by sappelhoff** [comment]
I think you are on the right track, and improving the error message in this way would be a help to dataset curators :+1: Maybe @rwblair can lend you a hand with the details.
