### ISSUE TITLE
[SCHEMA] physio and stim not included for EEG, MEG, iEEG and PET

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/legacy-validator#1412]
`physio` and `stim` suffixes are currently included for [func](https://github.com/bids-standard/bids-specification/blob/master/src/schema/datatypes/func.yaml) and [beh](https://github.com/bids-standard/bids-specification/blob/master/src/schema/datatypes/beh.yaml).

But they are not included for the following data types:

- [x] EEG: https://github.com/bids-standard/bids-specification/blob/master/src/schema/datatypes/eeg.yaml
- [x] iEEG: https://github.com/bids-standard/bids-specification/blob/master/src/schema/datatypes/ieeg.yaml
- [x] MEG: https://github.com/bids-standard/bids-specification/blob/master/src/schema/datatypes/meg.yaml
- [x] PET: https://github.com/bids-standard/bids-specification/blob/master/src/schema/datatypes/pet.yaml
- [x] ASL
- [x] DWI

Implement validation for validator:
- [ ] EEG
- [ ] iEEG
- [ ] MEG
- [ ] PET
- [ ] ASL
- [ ] DWI
- [ ] mri anat

I can't think of a reason for why that's the case, should we add those to the schema ?

**Comment by effigies** [comment]
I think this is done. If it's not, please open a new issue with a clearer requirement.
