### ISSUE TITLE
Allow file extensions for README

### ISSUE THREAD

**Issue by mateuszpawlik** [bids-standard/legacy-validator#1431]
The discussion started in https://github.com/bids-standard/bids-specification/issues/972. We'd like to allow file extensions for the README file: `.md`, `.rst`, and `.txt`.

I've looked at the code but it's difficult for me to make a list of tasks.

**Comment by mateuszpawlik** [comment]
I've just testes the version v1.9.4 which I thought would have the README file extensions implemented. However, I figured that the changes from #1432 may not be enough. The validator reports `[WARN] The recommended file /README is missing. See Section 03 (Modality agnostic files) of the BIDS specification. (code: 101 - README_FILE_MISSING)`

The [check for `README` file](https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/bids/checkReadme.js) has the filename hard-coded.

I can't reopen this issue and I'm not sure what's the process.

**Comment by sappelhoff** [comment]
Thanks for the report, please open a new issue for this problem and then we can prepare a PR to close it :-)
