### ISSUE TITLE
mismatch tsv actually number of file seem ok

### ISSUE THREAD

**Issue by CPernet** [bids-standard/legacy-validator#1454]
@Jorge Bosch-Bayard reported the following

'I created a BIDS dataset with 200 subjects in the participants.tsv file but in fact, only 10 subjects are in the dataset. The web BIDS validator accepts it as a valid BIDS dataset. I think the same happens with the _scans.tsv files in the sessions, which are not obliged to have the same contents as the files inside the directories. My understanding is that these are not valid BIDS datasets.'

is that the case one doesn't not open the tsv to check N?

**Comment by Remi-Gau** [comment]
I think this relates to this long discussion: https://github.com/bids-standard/bids-specification/issues/914

TL;DR: we know about this issue but have not yet found a way to fix this

**Comment by CPernet** [comment]
I see - at first I was like option B is logical, but then I can see why it is more complicated (as always) ..

**Comment by oldgandalf** [comment]
Also, a similar thing happens with the _scan.tsv file in a subject's session: the validator does not match the number of files (studies) numbered in the _scan.tsv file and the real studies stored in the session. There may be two image types (T1 and T2) in the "anat" modality, for example, and only one of them is reported in the _scan.tsv file corresponding to that session.

**Comment by Remi-Gau** [comment]
> Also, a similar thing happens with the _scan.tsv file in a subject's session: the validator does not match the number of files (studies) numbered in the _scan.tsv file and the real studies stored in the session. There may be two image types (T1 and T2) in the "anat" modality, for example, and only one of them is reported in the _scan.tsv file corresponding to that session.

yeah I don't think that the spec says:

> Each neural recording file SHOULD be described by exactly one row. 

So I suspect we could expect the validator to throw a warning for missing files.

Bur I think that it DOES throw an error for files listed in scans.tsv but that do not exist in the dataset.

**Comment by oldgandalf** [comment]
I think this should be an error: suppose that I have a T1 image in "anat" that is not reported in the _scans, and I am storing the acquisition date in _scans.tsv. Then I read the T1 nii file from the "anat" but I cannot load the acquisition date from the _scans. In that case, the acquisition date for this file is missing data or just forgotten? In the case of missing, the row still should exist in the _scans file with the indication of the missing value. If we omit the row in the _scans file, it is not clear the condition of this variable for this subject. In this case, the BIDS definition is allowing an unnecessary inconsistency. Am I wrong?
I will check the contrary case that you mention.

**Comment by oldgandalf** [comment]
Yes, Remi, I checked the contrary case that the _scans.tsv mentions a file that is not in the BIDS structure and it produces an error.
