### ISSUE TITLE
npm package doesn't work in react app

### ISSUE THREAD

**Issue by calebtuttle** [bids-standard/legacy-validator#1461]
Hi,

I'm trying to use the bids-validator npm package in a web app, but for every dataset I upload, I get the following QUICK_VALIDATION_FAILED error: "Quick validation failed - the general folder structure does not resemble a BIDS dataset. Have you chosen the right folder (with "sub-*/" subfolders)? Check for structural/naming issues and presence of at least one subject."

The datasets pass validation on https://bids-standard.github.io/bids-validator/. 

Is this a configuration issue on my end? Is bids-validator-web using a different version?

I'm using node v16.14.0 and bids-validator 1.9.3.

**Comment by nellh** [comment]
Do you have some example code you could share? 

One guess, the file input used to select files requires the webkitdirectory property or the File objects will lack [webkitRelativePath property](https://developer.mozilla.org/en-US/docs/Web/API/File/webkitRelativePath) and it will always fail at quick validation.

Here's how OpenNeuro selects the files: https://github.com/OpenNeuroOrg/openneuro/blob/deb8546f3b0008bbca2fe3e2d6b29fd2e5d9c39a/packages/openneuro-app/src/scripts/uploader/file-select.tsx#L32-L41
Here's how the validator is called with the FileList returned by that onChange event: https://github.com/OpenNeuroOrg/openneuro/blob/deb8546f3b0008bbca2fe3e2d6b29fd2e5d9c39a/packages/openneuro-app/src/scripts/workers/validate.worker.ts#L7-L9

**Comment by calebtuttle** [comment]
@nellh Thanks for the quick response! Your guess was accurate.

I wasn't using webkitdirectory and directory. Also, I'm using react-dropzone, which probably modifies the file list somehow because validation didn't work even after adding webkitdirectory and directory.
