### ISSUE TITLE
TSV validation: Error when column header is blank, duplicated, or `"n/a"`

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#1465]
related to https://github.com/bids-standard/bids-specification/issues/1105

~~We still need to add a note to the spec about this as well.~~ done in bids-standard/bids-specification#1116

**Comment by sappelhoff** [comment]
@rwblair would you have some time in the next weeks to take this one on?

**Comment by rwblair** [comment]
For sure. Looks like we have code to look for blank values, so I'll include the headers in that check. For duplicates I'll add new issue and check close to where we check for blank values.
