### ISSUE TITLE
Automatically adding a brief summary to the output

### ISSUE THREAD

**Issue by adam2392** [bids-standard/legacy-validator#1477]
I'm currently going through the process of summarizing many datasets on Openneuro that I've uploaded, or collaborators uploaded in the past. However, in order to run "reports" through e.g. pybids or mne-bids, I have to download the actual datasets, which is going to take a long time.

It would be nice to have the bids-validator that runs on openneuro output a string summary of the metadata.

Is this possible? Is it possible to integrate then onto openneuro?

**Comment by nellh** [comment]
There is some summary metadata reported by the validator that OpenNeuro makes available via the GraphQL API. It could be expanded depending on what information you're looking for. Here's an example query and that you can run at the [OpenNeuro API playground](https://openneuro.org/crn/graphql). Summary has a few other fields (see docs for the Snapshot -> Summary type in the playground).

```graphql
query {
  dataset(id: "ds000001") {
    latestSnapshot {
      summary {
        tasks
        modalities
        subjects
      }
    }
  }
}
```

For something like pybids reports, that probably makes more sense as an OpenNeuro feature than the validator.

**Comment by effigies** [comment]
I don't think this will be a validator feature. Perhaps we can improve pybids behavior with sparse datalad datasets.
