### ISSUE TITLE
Improve _events validation

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#148]
- Raise a warning if the last (latest) event has onset before the halfway mark of the duration of the corresponding scan (number of volumes \* TR). The design is suspiciously short.
- Raise a warning if the last (latest) event has onset after the end of the duration of the corresponding scan. The design is suspiciously long.

**Comment by olgn** [comment]
@chrisfilo do you have example datasets that are passing / violating these requirements handy?

**Comment by chrisgorgo** [comment]
https://openneuro.org/datasets/ds000114/versions/1.0.0/file-display/task-fingerfootlips_events.tsv

- breaking modification 1: remove bottom 70% of rows
- breaking modification 2: add an event with onset time of 2000
