### ISSUE TITLE
Validator not checking pet blood data

### ISSUE THREAD

**Issue by mnoergaard** [bids-standard/legacy-validator#1499]
We just uploaded https://openneuro.org/datasets/ds004230 that includes blood data, but for some reason the validator did not complain about the blood data not having the recording entity, which it should have? Looking at the code for the validator this is indeed present in the schema for the pet datatype, but why is it not complaining? 

@rwblair @bendhouseart

**Comment by nellh** [comment]
Looks like recording is just incorrectly defined as optional here: https://github.com/bids-standard/bids-validator/blob/571767eb23b4b8cae133166d0fcb62a629c8f191/bids-validator/bids_validator/rules/file_level_rules.json#L519

**Comment by mnoergaard** [comment]
Thanks @nellh! I will open a PR to fix this.

**Comment by mnoergaard** [comment]
Hm. I failed to spot this while reviewing https://github.com/bids-standard/bids-specification/pull/1005, but seems a new version of the spec has not been released since then, so it is still the old information that is present.
