### ISSUE TITLE
update_submodules workflow fails

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#1524]
For some reason, this line fails: https://github.com/bids-standard/bids-validator/blob/195536f64a64b457e7eb88322e2061735ae1ac35/.github/workflows/update_submodules.yml#L83

see failed workflow:  https://github.com/bids-standard/bids-validator/runs/8088470302?check_suite_focus=true

Unfortunately the provided error message is not helpful:

![image](https://user-images.githubusercontent.com/9084751/187404810-0268a888-a4c6-4ceb-8125-3450d2a864a9.png)

I can also reproduce this locally. @Remi-Gau can you also reproduce this problem? The only thing that was recently changed was to bump the "pull request" GH action, but that seems entirely unrelated.

**Comment by Remi-Gau** [comment]
Also... Do we need this old thing of mine if dependabot does the trick?

**Comment by sappelhoff** [comment]
yes -- valid point. I think what's cool about your thing is, that it doesn't bother each fork individually when there's an update. But we could remove your old thing and only bring it back in favor of the new thing, when it turns out that the "fork-alerts" are too annoying?

**Comment by Remi-Gau** [comment]
Yeah I would say let's nuke this workflow and see how we all deal with the noise of useless dependatbot PRs.
