### ISSUE TITLE
BIDS- validator internal error (code: 0 - INTERNAL ERROR)

### ISSUE THREAD

**Issue by lizannea** [bids-standard/legacy-validator#1531]
Hi experts, 

I tried to validate my dataset through the bids validator which is included  in MRtrix3_connectome pipeline (bids-validator@1.5.3) and faced with the following problem. Below the error output of the bids-validator:

1. [ERR] Internal error. SOME VALIDATION STEPS MAY NOT HAVE OCCURRED (code: 0 - INTERNAL ERROR)[39m
		.undefined
			Cannot read property 'HED' of null; please help the BIDS team and community by opening an issue at (https://github.com/bids-standard/bids-validator/issues) with the evidence here.
			Evidence: TypeError: Cannot read property 'HED' of null
    at /usr/lib/node_modules/bids-validator/validators/events/hed.js:31:24
    at Array.forEach (<anonymous>)
    at checkHedStrings (/usr/lib/node_modules/bids-validator/validators/events/hed.js:16:15)
    at default (/usr/lib/node_modules/bids-validator/validators/events/events.js:16:10)
    at Object.validate [as validateEvents] (/usr/lib/node_modules/bids-validator/validators/events/validate.js:4:10)
    at /usr/lib/node_modules/bids-validator/validators/bids/fullTest.js:179:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

2. The second error that was shown (code: 84 - ACQTIME_FMT):
[ERR] Entries in the "acq_time" column of _scans.tsv should be expressed in the following format YYYY-MM-DDTHH:mm:ss (year, month, day, hour (24h), minute, second; this is equivalent to the RFC3339 “date-time” format.  (code: 84 - ACQTIME_FMT)[39m
		./sub-091/ses-1/sub-091_ses-1_scans.tsv
			acq_time is not in the format yyyy-MM-ddTHH:mm:ss 
			@ line: 2
			Evidence: 1925-01-01T09:22:29.280000

You can find the output log file attached: [bids_validator_connectom.txt](https://github.com/bids-standard/bids-validator/files/9543774/bids_validator_connectom.txt). 

Can the second error only be solved by updating the bids validator included in the container, or are there ways around this? As I do not think this is actually an error. The timestamp has the right format.
 
Do you have any ideas how to solve the first error? 

Thank you!

@civier

**Comment by sappelhoff** [comment]
I think both issues will be solved by using an up to date bids validator. Have you tried the browser version on your dataset? That should constitute an easy test.

**Comment by happy5214** [comment]
The HED issue was fixed in #963 and has since been offloaded into the supporting `hed-validator` package.

**Comment by effigies** [comment]
This seems like an issue for https://github.com/bids-apps/MRtrix3_connectome/ to update the validator in their Dockerfile. It does appear they provide a `--skip-bids-validation` flag, so if your dataset validates on the web validator, you could use that safely.

**Comment by ZhyGao** [comment]
> 

Hello， effigies'
Do you know how I can use --skip-bids-validation with the docker run bids/mrtrix3_connectome command? I try to add it directly. But that's an unrecognized argument.

**Comment by effigies** [comment]
What is your command?

**Comment by ZhyGao** [comment]
> What is your command?

Now I am using the command as the guidance 
$ docker run -i --rm \
      -v /Users/yourname/data:/bids_dataset \
      -v /Users/yourname/output:/output \
      bids/mrtrix3_connectome \
      /bids_dataset /output preproc --participant_label 01.

**Comment by effigies** [comment]
So it would be:

```
docker run -i --rm -v /Users/yourname/data:/bids_dataset -v /Users/yourname/output:/output \
    bids/mrtrix3_connectome /bids_dataset /output preproc --participant_label 01 --skip-bids-validator
```
