### ISSUE TITLE
paths for symbolic links

### ISSUE THREAD

**Issue by CPernet** [bids-standard/legacy-validator#1532]
ok I have a weird one ... 

Take two BIDS datasets with some subjects in common. Because I want to have a single source file, I use symbolic link for my anats folders
study1/sub01/anat/sub-01_T1w.nii
study2/sub01/symbolic_link_to_study1_anat_folder/   (note the sub name is the same)

now run the validator on study2, it follows the symbolic link and tries to validate study1/sub01/anat/sub-01_T1w.ii and of course because the root is study2 it doesn't pass -- anypone to comment on this? experience something similar 

@yarikoptic  @mih

**Comment by Remi-Gau** [comment]
if using datalad, maybe you could turn sub-01 into a subdataset to facilitate its reuse in other datasets.

but going down that route means having a lot of datalad dataset to manage...

**Comment by CPernet** [comment]
well it's not a datalad issue, the issue is that the **validator returns an error** if one follows the path it's study2/sub01/symbolic_link_to_study1/sub01/anat/sub-01_T1w.ii 

I don't know if that's something we want to fix per see, more thinking of some optional flag for symbolic links to show up as warning rather than error @rwblair @effigies what do you think?

**Comment by CPernet** [comment]
little add on ... if instead you symbolic link to files directly, the validator is happy :-) but our analysis tools don't see the files when querying 👎🏻
