### ISSUE TITLE
Non-existent Value Should be a Number

### ISSUE THREAD

**Issue by bendhouseart** [bids-standard/legacy-validator#1533]
Noticed that during conversion of some PET phantoms that when `ReconMethodParameterValues` are an array of `["none", "none"]` validator throws an error.

```bash
1: [ERR] Invalid JSON file. The file is not formatted according the schema. (code: 55 - JSON_SCHEMA_VALIDATION_ERROR)
                ./sub-GeneralElectricAdvanceNIMH/pet/sub-GeneralElectricAdvanceNIMH_pet.json
                        Evidence: .ReconMethodParameterValues[0] should be number
                ./sub-GeneralElectricAdvanceNIMH/pet/sub-GeneralElectricAdvanceNIMH_pet.json
                        Evidence: .ReconMethodParameterValues[1] should be number
```

This should be valid:
```json
"ReconMethodName": "2DFilteredBackprojection",
"ReconMethodParameterUnits": [
        "none",
        "none"
 ],
"ReconMethodParameterLabels": [
        "subsets",
        "iterations"
],
"ReconMethodParameterValues": [
        "none",
        "none"
]
```

First noticed by @CPernet

**Comment by CPernet** [comment]
to provide context: pet schema
```
  "ReconMethodParameterLabels": ["none"],
  "ReconMethodParameterUnits": ["none" ],
  "ReconMethodParameterValues": ["null"],
```

because some method don't have Parameters but the field is mandatory

**Comment by effigies** [comment]
This needs to be addressed in the spec before the validator. In [1.6.0](https://bids-specification.readthedocs.io/en/v1.6.0/04-modality-specific-files/09-positron-emission-tomography.html#reconstruction) and [stable](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/09-positron-emission-tomography.html#reconstruction):

Key name | Requirement level | Data type | Description
-- | -- | -- | --
ReconMethodParameterValues | REQUIRED | array of numbers | Values of reconstruction parameters (for example, [21, 3])

**Comment by effigies** [comment]
Also, given that `"none"` is permitted for the units and labels, why not just set these to 0 or -1?

```JSON
"ReconMethodParameterValues": [0, 0]
```

**Comment by CPernet** [comment]
@mnoergaard @melanieganz should advise here -- although [null is a valid json value](https://stackoverflow.com/questions/8526995/is-null-valid-json-4-bytes-nothing-else#:~:text=Thus%2C%20%22null%22%20is%20now%20a%20valid%20JSON%20document.)

I'm fine making my life easier with 0 btw

**Comment by bendhouseart** [comment]
> Also, given that "none" is permitted for the units and labels, why not just set these to 0 or -1?


> I'm fine making my life easier with 0 btw

Ditto. Seems like a much easier thing to have null representations of datatypes be the same type.
