### ISSUE TITLE
BIDS Validation Error 1: Internal error. SOME VALIDATION STEPS MAY NOT HAVE OCCURRED

### ISSUE THREAD

**Issue by wilmabainbridge** [bids-standard/legacy-validator#1544]
I'm new to the BIDS format and OpenNeuro -- but this is the only error I'm getting at the moment on my dataset and have no clue how to fix it. Hoping to make this data available ASAP so would be great to figure this out -- thanks! I saw a similar post in January that used \ instead of /, but I don't believe I have the same problem after looking through my files.

**REASON:**
can't convert null to object; please help the BIDS team and community by opening an issue at (https://github.com/bids-standard/bids-validator/issues) with the evidence here.

**EVIDENCE:**
filterHedStrings@https://openneuro.org/assets/index.ce2ebc4f.js:23051:35809 pt@https://openneuro.org/assets/index.ce2ebc4f.js:23051:35727 constructSidecarData/<@https://openneuro.org/assets/index.ce2ebc4f.js:23051:118088 constructSidecarData@https://openneuro.org/assets/index.ce2ebc4f.js:23051:118080 checkHedStrings@https://openneuro.org/assets/index.ce2ebc4f.js:23051:117109 events_default@https://openneuro.org/assets/index.ce2ebc4f.js:23051:118918 fullTest/<@https://openneuro.org/assets/index.ce2ebc4f.js:23052:15782

**Comment by effigies** [comment]
Does the dataset pass on https://bids-standard.github.io/bids-validator/?

**Comment by wilmabainbridge** [comment]
Hmm - nope! It also returns the same one error with info at the end of this message.

With this validator, I also see it has detected the wrong number of tasks (only detects "FOSS") - could that be related? I have 2 different functional MRI tasks (one with a single run, one with 10 runs) and the file structure is like:

sub-06/ses-01/func/
  sub-06_ses-01_task-foss_bold.json
  sub-06_ses-01_task-foss_bold.nii.gz
  sub-06_ses-01_task-foss_events.json
  sub-06_ses-01_task-foss_events.tsv
  sub-06_ses-01_task-onesecondmemory_run-01_bold.json
  sub-06_ses-01_task-onesecondmemory_run-01_bold.nii.gz
  sub-06_ses-01_task-onesecondmemory_run-01_events.json
  sub-06_ses-01_task-onesecondmemory_run-01_events.tsv
  sub-06_ses-01_task-onesecondmemory_run-02_bold.json .... etc

TaskName is specified in each _bold.json. Below is the error info from the BIDS validator you linked:

Evidence:
filterHedStrings@https://bids-standard.github.io/bids-validator/_next/static/chunks/175a9e79.a3b0d5e6681f0f3e827e.js:1:1400957 l@https://bids-standard.github.io/bids-validator/_next/static/chunks/175a9e79.a3b0d5e6681f0f3e827e.js:1:1400876 RNiq/fi/o<@https://bids-standard.github.io/bids-validator/_next/static/chunks/pages/index-51079599a79814cf1aaf.js:1:895544 RNiq/fi/o<@https://bids-standard.github.io/bids-validator/_next/static/chunks/pages/index-51079599a79814cf1aaf.js:1:895520 fi@https://bids-standard.github.io/bids-validator/_next/static/chunks/pages/index-51079599a79814cf1aaf.js:1:895594 vi@https://bids-standard.github.io/bids-validator/_next/static/chunks/pages/index-51079599a79814cf1aaf.js:1:897591 RNiq/So/<@https://bids-standard.github.io/bids-validator/_next/static/chunks/pages/index-51079599a79814cf1aaf.js:1:913511

**Comment by wilmabainbridge** [comment]
Ok I managed to track it down by uploading small chunks of my dataset bit by bit. Was indeed a slashes issue! Seems like some of the fields in the functional __bold.json_ files did use backslashes (e.g., ScanOptions, SoftwareVersions, ScanningSequence). I automatically generated these using dcm2niix_afni on a Mac and the data were originally acquired on a GE scanner, so probably a quirk of how one of those represents those parameters. Replacing all backslashes with forward slashes fixed it.
