### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#155]
and please don't forget to use annotated or signed tags for that.

Cheers!

**Comment by chrisgorgo** [comment]
Is this required for NeuroDebian packaging? So far we have been consistent about versions (kept here: https://github.com/INCF/bids-validator/blob/master/package.json). The package gets updated on NPM only when the version is bumped. Same goes with gh-pages (web version)

**Comment by yarikoptic** [comment]
not really for packaging... more for development and troubleshooting.  Without tags it is hard to figure out what is the current state of development, how far it is from the last release etc... so questions to which 'git describe' could give an answer right away if there is a tag.

Now I see that you have tagged 0.21.2... unfortunately it is neither annotated nor signed (so by default git describe doesn't use it).  For the next one please use '-a' option and provide some description (I usually place corresponding changelog entries for the release)

**Comment by chrisgorgo** [comment]
next time I'll add a changelog
