### ISSUE TITLE
Closing directory handle on garbage collection

### ISSUE THREAD

**Issue by ins0mniac2** [bids-standard/legacy-validator#1561]
We are getting this warning in bids-validator 1.9.4  followed by a bunch of errors saying "We were unable to read this file. Make sure it contains data (file size > 0 kB) and is not corrupted, incorrectly named, or incorrectly symlinked." for files that look fine. Any pointer would be appreciated.

**Comment by ins0mniac2** [comment]
This turned out to be the same issue as [#675](https://github.com/bids-standard/bids-validator/issues/675). Once ulimit was increased, the error went away. This means the issue isn't fixed.

**Comment by sappelhoff** [comment]
Thanks for the report, let's keep discussing this in #675 then (has been re-opened already).
