### ISSUE TITLE
Modalities reported by bids-validator

### ISSUE THREAD

**Issue by ins0mniac2** [bids-standard/legacy-validator#1562]
It seems the "Available Modalities" reported are no longer broken down by specific types of MRI contrast (T1w, BOLD, DWI etc.) but it only says MRI as in the screenshot. Or is there something else going on here ? If indeed this was a change made, what was the rationale ?

<img width="829" alt="image" src="https://user-images.githubusercontent.com/1168408/202542615-a3cf3293-1796-4a0c-b79d-6824453c72b3.png">

**Comment by effigies** [comment]
Modality was never a well-defined concept. The BIDS term for T1w/BOLD/DWI is suffix, while `anat/` `func/`, `dwi/` is datatype. So modality became instead closer to "recording instrument". It may not be fully settled: https://github.com/bids-standard/bids-specification/issues/1141

**Comment by sappelhoff** [comment]
I agree with Chris, but it would still be interesting to know which change lead to this and whether that was intended

**Comment by effigies** [comment]
The change was part of the OpenNeuro redesign as it is used by OpenNeuro to determine which landing page a dataset should fall under.

This concept is now specified in the schema, for better or worse.
