### ISSUE TITLE
Add conda recipe

### ISSUE THREAD

**Issue by sarthakpati** [bids-standard/legacy-validator#1565]
Please add a conda recipe, which would make daisy-chaining complex recipes much easier to manage and deploy.

**Comment by sarthakpati** [comment]
Added a solution to this already: https://github.com/conda-forge/staged-recipes/pull/21421

**Comment by effigies** [comment]
Thanks. Please add @effigies @rwblair and @sappelhoff as authorized admins on the recipe.

**Comment by sarthakpati** [comment]
Done. Please ensure all maintainers leave a comment in the PR so that they agreement is noted.
