### ISSUE TITLE
Number of subjects in "Summary" section can be inaccurate

### ISSUE THREAD

**Issue by wtriplett** [bids-standard/legacy-validator#158]
Using: 343c446 HEAD@{0}: clone: from https://github.com/INCF/bids-validator

Basically, if there are any files in the `derivatives` folder that contain the characteristic BIDS participant id token, they get picked up and added in with the subject count in the Summary.

Example: Start with this BIDS structure:

```
CHANGES
README
dataset_description.json
sub-01
sub-02
sub-03
sub-04
sub-05
sub-06
sub-07
sub-08
sub-09
sub-10
sub-12
sub-13
sub-14
task-reversalweatherprediction_bold.json
task-weatherprediction_bold.json
```

which produces the summary:

```
        Summary:                Available Tasks:                   Available Modalities:
        147 Files, 1.2GB        Reversal weather prediction        inplaneT2
        13 - Subjects           Weather prediction                 T1w
        1 - Session                                                bold
```

Then create `derivatives`, add a file `derived_data_for_sub-01.txt`

```
CHANGES
README
dataset_description.json
derivatives
   |- derivatives/derived_data_for_sub-01.txt
sub-01
sub-02
sub-03
sub-04
sub-05
sub-06
sub-07
sub-08
sub-09
sub-10
sub-12
sub-13
sub-14
task-reversalweatherprediction_bold.json
task-weatherprediction_bold.json
```

which yields the erroneous Summary:

```
        Summary:                Available Tasks:                   Available Modalities:
        148 Files, 1.2GB        Reversal weather prediction        inplaneT2
        14 - Subjects           Weather prediction                 T1w
        1 - Session                                                bold
```

**Comment by constellates** [comment]
Thanks for catching this. I actually started a branch last night to ignore /sourcedata that should also fix this. So far we have been calling any file in /sourcedata, /code or /derivatives a valid BIDS file path but have still been passing them through the rest of the checks. So any data in those could currently throw any of the issues.
