### ISSUE TITLE
empty dataset name and authors

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/legacy-validator#1581]
Just tested it and validation passes without warning if leave an empty string (`""`) or just spaces (`" "`) for the dataset_descrtiption name .

Same for `Authors`.

This probably deserves a warning.

**Comment by sappelhoff** [comment]
that's our old issue with generating warnings for JSON schema based validation. In that workflow we currently only have:

1. fail with an often cryptic error message because the schema is violated
2. succeed because the schema is adhered to

perhaps it'd be easier to explicitly forbid "whitespace-only" strings in the JSON schema, for example via a "pattern".

**Comment by effigies** [comment]
Name: #1572 will be in the next release.

Authors is supposed to be a list. There should be a warning if the list is empty or the field is missing `NO_AUTHORS`:

https://github.com/bids-standard/bids-validator/blob/40206be37d9db2114ed16e8891625f65a1aab449/bids-validator/utils/issues/list.js#L613-L618

Implementation is here:

https://github.com/bids-standard/bids-validator/blob/40206be37d9db2114ed16e8891625f65a1aab449/bids-validator/validators/bids/checkDatasetDescription.js#L49-L78

Tests are here:

https://github.com/bids-standard/bids-validator/blob/40206be37d9db2114ed16e8891625f65a1aab449/bids-validator/validators/bids/__tests__/checkDatasetDescription.spec.js#L78-L99

We could add an `EMPTY_AUTHOR` issue, just like the 2+ commas issue, and warn if `author.strip().length == 0`.

**Comment by Remi-Gau** [comment]
> We could add an `EMPTY_AUTHOR` issue, just like the 2+ commas issue, and warn if `author.strip().length == 0`.

that would be nice

**Comment by mateuszpawlik** [comment]
FYI I just got `code: 113 - NO_AUTHORS` although I have authors in CITATION.cff file, [as recommended](https://bids-specification.readthedocs.io/en/stable/modality-agnostic-files.html#citationcff).

**Comment by Remi-Gau** [comment]
> FYI I just got `code: 113 - NO_AUTHORS` although I have authors in CITATION.cff file, [as recommended](https://bids-specification.readthedocs.io/en/stable/modality-agnostic-files.html#citationcff).

- Could reproduce in this PR to the bids example: https://github.com/bids-standard/bids-examples/pull/426

https://github.com/bids-standard/bids-examples/actions/runs/7928356588/job/21646448322?pr=426#step:8:373
