### ISSUE TITLE
`chunk` entity not covered by validator?

### ISSUE THREAD

**Issue by jcohenadad** [bids-standard/legacy-validator#1582]
Hello! I have a dataset that contains the `chunk` entity, which is valid in v1.8.0 (see [here](https://bids-specification.readthedocs.io/en/stable/appendices/entities.html#chunk)). However, I am getting a bids-validator error: [test_bids_errors.txt](https://github.com/bids-standard/bids-validator/files/10397495/test_bids_errors.txt)

Dummy dataset for testing: [test_bids.zip](https://github.com/bids-standard/bids-validator/files/10397493/test_bids.zip)

Is it because the BIDS validator is not (yet) covering this entity? Or did I do something stupid with my naming?

Thanks!

**Comment by Remi-Gau** [comment]
It is just not an anat entity:

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomy-imaging-data

**Comment by jcohenadad** [comment]
Thank you for the insights @Remi-Gau ! 

How do people refer to various FOV chunks, which is pretty common in MRI

**Comment by Remi-Gau** [comment]
The acquisition label ?
Really not sure. But this would be my first response from the top of my head.

**Comment by jcohenadad** [comment]
Hum, that’s too bad because the definition of chunk is much closer to that of `acq` for describing different FOVs acquired on the same subject in the same imaging session:

> Definition: The chunk-<index> key/value pair is used to distinguish between different regions, 2D images or 3D volumes files, of the same physical sample with different fields of view acquired in the same imaging experiment.

Maybe there is already a BEP that plans to make a wiser use of chunk? @mariehbourget  @SylvainTakerkart do you know by any chance?

**Comment by Remi-Gau** [comment]
In theory we could add an entity from one datatype to an another existing datatype without needing a whole bep. Maybe open an issue in the specification describing your use case and motivations.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jcohenadad** [comment]
> In theory we could add an entity from one datatype to an another existing datatype without needing a whole bep. Maybe open an issue in the specification describing your use case and motivations.

👍 https://github.com/bids-standard/bids-specification/issues/1382

**Comment by SylvainTakerkart** [comment]
this would make sense to me, this indeed would be consistent with the BIDS microscopy chunking...
