### ISSUE TITLE
EstimatedTotalReadoutTime for Philips data instead of TotalReadoutTime

### ISSUE THREAD

**Issue by cmadjar** [bids-standard/legacy-validator#1588]
# Description

For Philips datasets converted to a BIDS dataset via dcm2niix, there are no "TotalReadoutTime" but an "EstimatedTotalReadoutTime" since it can be approximately estimated by dcm2nixx by making some assumptions (see https://github.com/rordenlab/dcm2niix/tree/master/Philips#missing-information for more details).

When running Philips datasets through the BIDS validator, we systematically get the following error:
```
2: [ERR] You have to define 'TotalReadoutTime' for this file. (code: 19 - TOTAL_READOUT_TIME_MUST_DEFINE)
		./sub-215102/ses-V02/fmap/sub-215102_ses-V02_dir-AP_run-1_epi.nii.gz
		./sub-215102/ses-V02/fmap/sub-215102_ses-V02_dir-AP_run-2_epi.nii.gz
		./sub-215102/ses-V02/fmap/sub-215102_ses-V02_dir-AP_run-3_epi.nii.gz
		./sub-215102/ses-V02/fmap/sub-215102_ses-V02_dir-PA_run-1_epi.nii.gz
		./sub-215102/ses-V02/fmap/sub-215102_ses-V02_dir-PA_run-2_epi.nii.gz
		./sub-215102/ses-V02/fmap/sub-215102_ses-V02_dir-PA_run-3_epi.nii.gz
```

Is there a way this could be turned into a warning when "EstimatedTotalReadoutTime" is available instead of the usual "TotalReadoutTime"?

**Comment by effigies** [comment]
In the schema validator, you can pass a configuration with `--config config.json`:

```json
{
  "ignore": [{ "code": "SIDECAR_KEY_REQUIRED", "subCode": "TotalReadoutTime" }]
}
```
