### ISSUE TITLE
Files listed twice in EchoTime{1,2} error for phasediff images

### ISSUE THREAD

**Issue by wtriplett** [bids-standard/legacy-validator#160]
See below - each file is listed twice.

```
    2: You have to define 'EchoTime1' and/or 'EchoTime2' for this file. (code: 15)
        /sub-100003/fmap/sub-100003_phasediff.nii.gz
        /sub-100003/fmap/sub-100003_phasediff.nii.gz
        /sub-100042/fmap/sub-100042_phasediff.nii.gz
        /sub-100042/fmap/sub-100042_phasediff.nii.gz
        /sub-100057/fmap/sub-100057_phasediff.nii.gz
        /sub-100057/fmap/sub-100057_phasediff.nii.gz
        /sub-100059/fmap/sub-100059_phasediff.nii.gz
        /sub-100059/fmap/sub-100059_phasediff.nii.gz
        /sub-100063/fmap/sub-100063_phasediff.nii.gz
        /sub-100063/fmap/sub-100063_phasediff.nii.gz
        /sub-100068/fmap/sub-100068_phasediff.nii.gz
        ... and 101 more files having this issue (Use --verbose to see them all).
```

**Comment by constellates** [comment]
Looks like the issue is here.

https://github.com/INCF/bids-validator/blob/master/validators/nii.js#L150-L164

There are two separate checks for "EchoTime1" and "EchoTime2" that are sharing an issue code. So if a file is missing both it gets added twice.

I should be able to create a fix/PR later today.

**Comment by constellates** [comment]
@chrisfilo I'll make sure we're not adding these files twice, but there's also some discrepancy between the error message and what we're actually checking?

The error message says you have to define "EchoTime1 **and/or** EchoTime2", but the current logic works as if you must define "EchoTime1 **and** EchoTime2" for a phasediff.

Which is currently correct, the message or the logic?

**Comment by chrisgorgo** [comment]
The logic is correct - the message needs to be corrected. Thanks for
catching this!
