### ISSUE TITLE
Test for collision of validator only errors and schema errors.yaml entries.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#1603]
For validator parity there's an issue with respect to this list of "non-schema" issues in the validator and the the errors list in the schema:
https://github.com/bids-standard/bids-validator/blob/master/bids-validator/src/issues/list.ts
https://github.com/bids-standard/bids-specification/blob/master/src/schema/rules/errors.yaml

Need a test that cross references them so that if it exists in both the test fails. Validator should remove its copy and use issue information from schema.

Some of the rules in either of them may be possible as checks now, empty file one for instance.

**Comment by effigies** [comment]
@rwblair Any update on your thinking here?

**Comment by rwblair** [comment]
I'll start writing the test now.
