### ISSUE TITLE
Validator fails with "Evidence:  should have required property 'GeneratedBy'"

### ISSUE THREAD

**Issue by mangstad** [bids-standard/legacy-validator#1628]
The validator fails a dataset_description.json for the reason:
"Evidence:  should have required property 'GeneratedBy'"
But according to the most recent BIDS spec, GeneratedBy is only a recommended entry, not required.

**Comment by effigies** [comment]
Could you provide the `dataset_description.json` contents?

**Comment by mangstad** [comment]
https://openneuro.org/datasets/ds003059/versions/1.0.0/file-display/dataset_description.json

**Comment by effigies** [comment]
Derivative datasets require `GeneratedBy`.

```
"DatasetType": "derivative",
```

See https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#derived-dataset-and-pipeline-description

**Comment by mangstad** [comment]
Sorry about that. My fault for not reading farther. Just checked the main table and saw only recommended so figured something was off. I'm used to the tables in some other sections of the spec where it says things like:
"RECOMMENDED, but REQUIRED for Arterial Spin Labeling" and similar so assumed that if GeneratedBy was ever required, it would be mentioned in that section of the table up front.
