### ISSUE TITLE
microscopy metadata not supported when in root folder

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/legacy-validator#1630]
Just tested on the bids-examples by putting some SEM.json or SPIM.json in the root folder the validator complained that those are not valid files.

This would prevent using the inheritance principle for microscopy.

I would not be surprised that this is also the case for all microscopy suffixes.

@mariehbourget @jcohenadad 

I may do what I did with qmri: 
- update the validator
- update the bids-example to have at least some metadata in the root folder of the microscopy examples

**Comment by jcohenadad** [comment]
Thank you for raising this issue @Remi-Gau , and your suggestion makes sense 💯 !

**Comment by Remi-Gau** [comment]
This seems fixed with the deno validator
