### ISSUE TITLE
[SCHEMA] Integrate HED validator

### ISSUE THREAD

**Issue by nellh** [bids-standard/legacy-validator#1639]
Taking a look at how the [HED JavaScript validator is called](https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/events/hed.js), we should find a way to provide the events and sidecar data required following schema validation, then call the HED validator. The returned events issues will need to be adapted to the new Issue type to be included in the results.

**Comment by effigies** [comment]
Done in #1648.
