### ISSUE TITLE
Exit code of command-line tool

### ISSUE THREAD

**Issue by glatard** [bids-standard/legacy-validator#166]
It would be nice if the command-line tool returned a non-zero exit code when the dataset is not valid.

**Comment by constellates** [comment]
This makes sense to me. I added a quick PR to add basic exit codes for errors. @glatard let me know if this looks like it will work for you.

**Comment by chrisgorgo** [comment]
Thanks for reporting Tristan!

**Comment by glatard** [comment]
Looks great, thanks @constellates.
