### ISSUE TITLE
bvec and bval use special context keys

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#1687]
https://github.com/bids-standard/bids-specification/blob/6af953770c0f4e1c3536571220c2872acb8296e9/src/schema/rules/checks/dwi.yaml#L30

Need to parse and count rows and add `data` to context just for these two rules. Or do we...

Also they are using old style `in` operators for membership that should be updated in specification.

**Comment by rwblair** [comment]
ds000117
ds114
eeg_rest_fmri
genetics_ukbb

Won't validate without the these.

**Comment by effigies** [comment]
I think fixed in #1797? Do the `in` operators need fixing, or is that style?
