### ISSUE TITLE
Change strings passed to bids ignore test?

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#1688]
.bidsignore entries not working for this dataset:
https://github.com/bids-standard/bids-examples/blob/master/fnirs_automaticity/.bidsignore

Neither of these will work:
`phenotype/practicelogbook.json`
`/phenotype/practicelogbook.json`

`**/phenotype/practicelogbook.json` Does, but requiring star star for things addressed from the root seems silly. The string being passed to the ignore test function is the `file.path` which is  `/phenotype/practicelogbook.json`

The leading slash in the ignore file puts the slash before the start of line carot:
```
    IgnoreRule {
      origin: "/phenotype/practicelogbook.json",
      pattern: "/phenotype/practicelogbook.json",
      negative: false,
      regex: /^phenotype\/practicelogbook\.json(?=$|\/$)/i
    },
```

Maybe we chomp leading slashes in the test function?

**Comment by effigies** [comment]
I think the regex should start with `(^|/)`, not `^`. Is that possible?

**Comment by effigies** [comment]
I believe this is done.
