### ISSUE TITLE
Chromium compatibility

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#171]
Currently Chromium users are blocked from using the validator, but it should work flawlessly without requiring any changes.

**Comment by constellates** [comment]
Do you know what version of chromium/operating system this is happening on? I just downloaded the nightly OSX build and I'm not having any issues. I'm building an ubuntu vm currently to test there.

**Comment by constellates** [comment]
Ok. I'm seeing this on ubuntu.
