### ISSUE TITLE
Explain that the web version is not uploading data

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#173]
Currently the web version of the validator has to use "Upload" label on the dialog box even though no data leaves the client computer and the validation is done completely offline. Let's add a one sentence disclaimer explaining that no data is being uploaded.

**Comment by constellates** [comment]
How does this look?

<img width="649" alt="screen shot 2016-06-21 at 9 56 36 am" src="https://cloud.githubusercontent.com/assets/4325905/16238891/302d0ad2-3797-11e6-9c5c-3f13768ed06c.png">

**Comment by chrisgorgo** [comment]
LGTM
