### ISSUE TITLE
Raise an error if a wrong .bvec/.bval separator is being used

### ISSUE THREAD

**Issue by arokem** [bids-standard/legacy-validator#175]
This is for hand-crafted single-subject data-set from HCP. I have verified independently that the bvals/bvecs do have the right number of entries, but I might be missing something. How is correspondence (file-to-file) determined? In this case, the bval/bvec files are in the `dwi` folder.

**Comment by chrisgorgo** [comment]
Could you share the bvec/back files? What separator do they use?

**Comment by arokem** [comment]
Here are the bvals/bvecs. Let me know if you need the DWI, and I can share in a less public fashion

https://drive.google.com/open?id=0BxmU4IuCMsYYVjVYNWtkX25SVGc

**Comment by arokem** [comment]
To answer your question: they use two spaces as the separator.

**Comment by chrisgorgo** [comment]
Double spaces are the problem - if you use single spaces (as described in the standard) instead everything should be fine. The error messages should reflect that.

We should test if:
1. multiple spaces are used as delimiters
2. tabs are used as delimiterd

and throw an error that the wrong separator is used.

**Comment by arokem** [comment]
Gotcha. I guess the HCP data that comes down from S3 is just non-compliant.
Oh well.

**Comment by constellates** [comment]
Determining the delimiter can be somewhat tricky, especially when bval files only contain a single row. Would it suffice to assume a single space delimiter and throw an error if any of the values are not numbers. Using this strategy a double spaced file would show a bunch of empty values that would be caught and we could also catch other delimiters like tabs or commas.

Then the error message would then indicate the delimiter and value requirments.

> Error
> .bvec files must be single space delimited and contain only floating point values.
>    /dwi.bvec
