### ISSUE TITLE
Reconcile schema objects that can be multiple types being passed into stricter expression language functions.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#1779]
ReconFilterSize can be a string or an array. pet sidecar passes it to intersects directly:
`'!intersects(sidecar.ReconFilterType, ["none"])'`

Intersects only takes two arrays as arguments. This causes errors if RecondFilterType is a string.

**Comment by effigies** [comment]
We could add a `listify` function to the expression language?

**Comment by effigies** [comment]
An idiom that wouldn't require a new function would be:

```
- '(intersects([sidecar.ReconFilterType], ["none"]) || intersects(sidecar.ReconFilterType, ["none"])) != true'
```

The first is guaranteed to be an array. If the second returns `null`, then with short-circuiting we should get:

| `ReconFilterType` | `intersects([ReconFilterType], ["none"])` | `intersects(ReconFilterType, ["none"])` | `X  \|\| Y != true` |
|--|--|--|--|
| `"none"` | `true` | n/a | `false` |
| `["none"]` | `false` | `true` | `false` |
| `"a"` | `false` | `null` | `true` |
| `["a"]` | `false` | `false` | `true` |

**Comment by rwblair** [comment]
For exists we can call `Array.isArray` on args and wrap in `[ ]` 

Not to self be sure to comment in expressionLanguage.ts
