### ISSUE TITLE
Update exists check in expression language.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#1780]
ieeg_filtered_speech is failing  schema.rules.checks.events.StimulusFileMissing when it shouldn't

**Comment by rwblair** [comment]
The following also generate the error:
eeg_ds003645s_hed
eeg_ds003645s_hed_inheritance
eeg_ds003645s_hed_library
eeg_ds003645s_hed_longform

**Comment by rwblair** [comment]
There are multiple 'n/a' in the events columns throwing off the counts in 
`exists(columns.stim_file, "stimuli") == length(columns.stim_file) - count(columns.stim_file, 'n/a')`

**Comment by effigies** [comment]
Fixed in bids-standard/bids-specification#1608.
