### ISSUE TITLE
Cast parsed column values as their expression language type?

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#1781]
https://github.com/bids-standard/bids-specification/blob/e1f853873036e2079d39a4fcb1357a04c8afbb80/src/schema/rules/checks/nirs.yaml#L41

This check counts occurrence of true as a boolean in a column. TSV columns are parsed as strings. 

We could change the rule to test for `"true"` or we could change the tsv parse to cast values accordingly.

**Comment by effigies** [comment]
I think in general we need to parse. [`short_channel`](https://github.com/bids-standard/bids-specification/blob/a98160aed1256f1b2ffe4b20a82e26b01f57d90c/src/schema/objects/columns.yaml#L468-L475) is defined as `bool`.

We also need to be able to do numeric computations with [`onset`](https://github.com/bids-standard/bids-specification/blob/a98160aed1256f1b2ffe4b20a82e26b01f57d90c/src/schema/objects/columns.yaml#L309-L327) here:

https://github.com/bids-standard/bids-specification/blob/a98160a/src/schema/rules/checks/hints.yaml#L24-L51

It would be convenient to use their string values when all we need to check is equality, though. We could add `parse_value()` to explicitly request that values be parsed to their declared types.

**Comment by rwblair** [comment]
Easiest fix is to wrap true in quotes in schema, let it match all the other calls to count.

**Comment by rwblair** [comment]
https://github.com/bids-standard/bids-specification/pull/1598
