### ISSUE TITLE
Fix bidsignore check for fnirs_automaticity

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#1782]
https://github.com/bids-standard/bids-examples/blob/master/fnirs_automaticity/.bidsignore

Is `phenotype/practicelogbook.tsv` in fnirs_automaticity/.bidsignore a valid bidsignore line to ignore fnirs_automaticity/phenotype/practicelogbook.tsv

**Comment by rwblair** [comment]
~~Exists in specification associations meta, need to start interpreting that in validator.~~

**Comment by effigies** [comment]
Fixed in #1841.
