### ISSUE TITLE
Add cordsystem to associations for optodes.tsv.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#1783]
https://github.com/bids-standard/bids-specification/blob/02d97b0c75b57e5f1a528253d4348fa236b115b1/src/schema/rules/checks/nirs.yaml#L91

failing for https://github.com/bids-standard/bids-examples/blob/master/fnirs_tapping/sub-02/nirs/sub-02_optodes.tsv

**Comment by effigies** [comment]
Validator implementation side. Defined in meta.context and meta.associations.

**Comment by effigies** [comment]
Fixed in #1797
