### ISSUE TITLE
Add dataset level hint to schema that there should be at least one subject.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#1788]
And that subject should have a modality.

**Comment by rwblair** [comment]
Or generate error if fewer than 2 valid files

**Comment by effigies** [comment]
Or at least one that isn't a core file (`dataset_description.json`, `CITATION.cff`, `README.*`, `CHANGES`, `LICENSE`, `genetic_info.json`, `participants.tsv`, `samples.tsv`).

**Comment by effigies** [comment]
We have:

```
	[ERROR] There are no subject directories (labeled "sub-*") in the root of this dataset.
 (SUBJECT_FOLDERS)

		./dataset_description.json
			Evidence: schema.rules.rules.checks.dataset.SubjectFolders
```
