### ISSUE TITLE
ds000001-fmriprep hitting schema.rules.sidecars.entity_rules.EntitiesResMetadata Rule

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#1790]
Rule in spec:
https://github.com/bids-standard/bids-specification/blob/master/src/schema/rules/sidecars/entity_rules.yaml#L66

This should be optional in derivatives right?

**Comment by effigies** [comment]
This is an open issue in fMRIPrep: https://github.com/nipreps/fmriprep/issues/3070

The spec is clear that this is required, so we should just patch the example.

**Comment by Remi-Gau** [comment]
will patch the example
