### ISSUE TITLE
Specific check for session name not present in filename.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#183]
Person converted a dataset from one without sessions to one with sessions. They added the session directory but not the session portion of the filenames. A check that looked for this mismatch would be more informative than the current "this file is not part of the bids standard"

**Comment by chrisgorgo** [comment]
@suyashdb was this covered by one of your recent PRs?

**Comment by suyashdb** [comment]
This will be covered in this PR https://github.com/INCF/bids-validator/pull/313.
PR #313 will check in filename and path to match session name and subject name.

**Comment by chrisgorgo** [comment]
Solved by #313.
