### ISSUE TITLE
MEG empty files tests not covered by specificaiton.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#1862]
Test from the old validator:
https://github.com/bids-standard/bids-validator/blob/master/bids-validator/tests/utils/files.spec.js#L104

This was ported to the new validator:
https://github.com/bids-standard/bids-validator/blob/master/bids-validator/src/tests/local/empty_files.test.ts#L25

New validator flat out ignores all the contents of *.ds/ directories. We should figure out a way to encode this rule in the schema, or how to check these files without building full contexts for them. Until then this check may be expected to fail in the new validator.

**Comment by effigies** [comment]
Fixed in https://github.com/bids-standard/bids-validator/pull/2064.
