### ISSUE TITLE
hed-validator version 3.13.0

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#1868]
hed-validator version 3.13.0 has been released on npm.  This release supports the new curly brace notation, improves tests, and fixes a few bugs.  Please update the npm dependencies for it.  Thx.   @sappelhoff

_Originally posted by @VisLab in https://github.com/bids-standard/bids-validator/issues/1866#issuecomment-1860740596_

**Comment by sappelhoff** [comment]
potentially fixed in https://github.com/bids-standard/bids-validator/pull/1867

**Comment by happy5214** [comment]
Co-opting this issue to say that hed-validator needs to be bumped to 3.13.2 now to fix the issue in https://github.com/bids-standard/bids-validator/pull/1869#issuecomment-1865993337. Also, all instances of `BidsEventFile` and `BidsTabularFile` (which are now deprecated) should be replaced with `BidsTsvFile`. This version provides full support for HED validation in all BIDS TSV files with column headers (i.e. those that aren't timeseries) and associated sidecars. I ran into issues bumping the `package-lock.json` myself without changing your hard-coded version dependencies.

**Comment by happy5214** [comment]
@rwblair This now needs to be bumped to 3.13.3 to fix a minor issue with generating plural forms for non-SI, non-symbol units.

**Comment by sappelhoff** [comment]
@happy5214 if you tell me the commands I need to run to do this, OR if you make a PR yourself, we can get this done between the two of us.

**Comment by happy5214** [comment]
~~This was fixed by #1879. Please close.~~

Edit. Not true. The assignment to `TsvFileClass` starting at https://github.com/bids-standard/bids-validator/blob/f50efda00818e50256586caa712aec74a90301c4/bids-validator/validators/hed.js#L55 needs to be replaced with `hedValidator.bids.BidsTsvFile` (and inlined).
