### ISSUE TITLE
HED column in tsv file should not give a warning

### ISSUE THREAD

**Issue by VisLab** [bids-standard/legacy-validator#1875]
bids-validator 1.14.0 gives a warning if a HED column appears in a `.tsv` file other than an `events.tsv` file:

>**Example:**    3: [WARN] Tabular file contains custom columns not described in a data dictionary (code: 82 - CUSTOM_COLUMN_WITHOUT_DESCRIPTION)
                ./participants.tsv
                        Evidence: Columns: HED not defined, please define in: /participants.json

HED can be usefully included in any `.tsv` file, but particularly `participants.tsv` and `scans.tsv`, and it is our understanding that the BIDS specification allows this.  However, HED cannot syntactically appear as a top-level key in the JSON file without triggering an error.

**Would it be possible to exclude HED from the listing of missing custom column definitions?**

P.S.  HED currently in the bids-validator appears to validate the `participants.tsv` and `scans.tsv` files okay. We are still working on `motion`, `phenotype` and `samples` related `.tsv` files. 

Our demo example is available at: [eeg_ds003645s_hed_demo](https://github.com/hed-standard/hed-examples/tree/develop/datasets/eeg_ds003645s_hed_demo). Once everything is working, we'll be able to replace a number of HED examples on `bids-examples` with a single demo that shows a lot of different uses.

  @sappelhoff @effigies @rwblair @happy5214

**Comment by sappelhoff** [comment]
> However, HED cannot syntactically appear as a top-level key in the JSON file without triggering an error.

I don't understand this point. If you would include an `HED` column in a `participants.tsv` file, why would you not be able to place a `HED` key inside a `participants.json` file?

I opened https://github.com/bids-standard/bids-validator/pull/1876 anyhow, to show how the request here could be fulfilled.

**Comment by VisLab** [comment]
The warning refers to HED as a column name.  This would require a json file:

{
    "HED": "Blah blah"
}

but the syntax for HED in BIDS requires that HED be at the same level as
"Levels" under a column name:

{
     "Column_name1":  {
           "Levels":  { .....}
           "HED": { .....}
     }
     "Column_name2": {
          "HED":  "Label/#"
      }
}

If the first example is used and "HED" appears at the first level, the HED
validator will rightfully detect it as an error.

**Comment by sappelhoff** [comment]
Thanks for the explanation @VisLab! may you please review #1876 then?
