### ISSUE TITLE
PEPOLAR fieldmaps throwing code 90 (SIDECAR_WITHOUT_DATAFILE) when `part-<value>` is present

### ISSUE THREAD

**Issue by oesteban** [bids-standard/legacy-validator#1882]
I assume that, as a result of bids-standard/bids-specification#1684, the validator throws:

```
[ERR] A json sidecar file was found without a corresponding data file (code: 90 - SIDECAR_WITHOUT_DATAFILE)
```

Sidecar: `./sub-001/ses-001/fmap/sub-001_ses-001_acq-bold_dir-AP_epi.json`

When the corresponding two NIfTI files exist:

```
./sub-001/ses-001/fmap/sub-001_ses-001_acq-bold_dir-AP_part-mag_epi.nii.gz
./sub-001/ses-001/fmap/sub-001_ses-001_acq-bold_dir-AP_part-phase_epi.nii.gz
```

Please let me know if I'm wrong on this expectation.

**Comment by oesteban** [comment]
Since bids-standard/bids-specification#1684 is now merged, propagating the changes here implies just updating the rules at top, session and file levels?

**Comment by effigies** [comment]
It's always possible that there's a corner case in constructing a sidecar/data file mapping, so it's worth testing.

**Comment by oesteban** [comment]
do you mean that some test should be added? If that is the case, is there anything you can point me at to get started without bugging you?

**Comment by effigies** [comment]
Probably, but I would have to dig to figure out what to suggest. I was thinking at the least you could use your dataset that's currently failing to test your patch. There's a `Dockerfile` in case a local node setup is a pain.
