### ISSUE TITLE
PET recon parameter error - need to implement a conditional statement

### ISSUE THREAD

**Issue by CPernet** [bids-standard/legacy-validator#1897]
Behaviour
- ReconMethodParameterLabels: "none"
(ReconMethodParameterUnits, ReconMethodParameterValues not present)

expected
- pass

current 
- error: should have properties ReconMethodParameterUnits, ReconMethodParameterValues when property ReconMethodParameterLabels is present

the spec says: RECOMMENDED, but ReconMethodParameterUnits & ReconMethodParameterValues not in the metadata as REQUIRED if ReconMethodParameterLabels does not contain "none"

**Comment by CPernet** [comment]
behaviour

- meta.ReconFilterType: "none"
(ReconFilterSize not present)

expected

- pass

current
 
- error: should have required property 'ReconFilterSize'

the spec says: RECOMMENDED, but REQUIRED if ReconFilterType is not "none"

For instance https://github.com/bids-standard/bids-examples/blob/master/pet001/sub-01/ses-01/pet/sub-01_ses-01_trc-CIMBI36_pet.json#L36 could be removed and be valid (but isn't)

**Comment by CPernet** [comment]
@rwblair @mnoergaard I'mguessing it's an update in the schema to do?   
@tsalo how do we encode a conditional statement? I think that's all we need

**Comment by bendhouseart** [comment]
I'm going to add a new entry to bids-examples to reflect this case @rwblair as that feels like a good first step.

**Comment by tsalo** [comment]
The schema seems to match the described rules. Is this maybe a bug in the old, non-schema validator?

**Comment by CPernet** [comment]
i used the online validator ??

**Comment by bendhouseart** [comment]
Added example to bids-examples in this PR -> https://github.com/bids-standard/bids-examples/pull/427
