### ISSUE TITLE
Make -s|--schema take path or add new --schema-file option to point to schema.json file

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#1930]
ATM the option seems to take only some hardcoded set of versions

```
  -s, --schema                    BIDS specification schema version to use for
                                  validation, e.g. "v1.6.0" (beta)
         [choices: "disable", "v1.6.0", "v1.7.0", "master"] [default: "disable"]
```

(note: current release is 1.9.0!).

That precludes to point to a specific `schema.org` e.g. produced while working on a BEP. Ref:

- bids-standard/bids-validator#24 

Quick resolution would be appreciated to proceed with

- https://github.com/bids-standard/bids-specification/pull/1775

**Comment by effigies** [comment]
The schema validator shows:

```
❯ deno run --allow-read --allow-env https://deno.land/x/bids_validator/bids-validator.ts --help

  Usage:   bids-validator <dataset_directory>
  Version: alpha                             

[...]

    -s, --schema          <type>  - Specify a schema version to use for validation                          (Default: "latest")   
```

This appears to be an experimental addition to the legacy validator. Probably best just to remove it.

**Comment by yarikoptic** [comment]
But how to specify not by "version" but by the path to the schema???

**Comment by effigies** [comment]
`deno run --allow-read --allow-env --allow-net https://deno.land/x/bids_validator/bids-validator.ts -s https://bids-specification.readthedocs.io/en/v1.9.0/schema.json /path/to/dataset`

**Comment by yarikoptic** [comment]
oh, will it work with `file://` URLs? (happen you could check quickly... if not -- I will try later).  Just need to wrap it all up into
https://github.com/bids-standard/bids-specification/pull/1775/files#diff-340dd8fa4a5cba6b30520d676d1831fd82628971874ea46396e3ace6c6ef0f03R111 but also then also into bep032 etc ... I feel like we need a github action to reuse here... Filed

- https://github.com/bids-standard/bids-validator/issues/1931

WDYT @effigies ?

**Comment by nellh** [comment]
> oh, will it work with `file://` URLs? (happen you could check quickly... if not -- I will try later).

File URLs or a path to a local file should work.

**Comment by yarikoptic** [comment]
just for clarity -- https://github.com/bids-standard/bids-examples/blob/master/.github/workflows/validate_datasets.yml aren't using new validator yet?

**Comment by effigies** [comment]
Correct.

**Comment by effigies** [comment]
Resolved in bids-standard/legacy-validator#1932.

**Comment by rwblair** [comment]
I wasn't able to get -s to work with `file://` Is this a me problem/has anyone else had luck with it?

**Comment by effigies** [comment]
I have `BIDS_SCHEMA=file://$HOME/Projects/bids/specification/src/schema.json bids-validator micr_SPIM ` in my history. I'm not sure if I've tried with `-s` or if things have stopped working since I last did that.
