### ISSUE TITLE
Validator requires echo entity to be immediately before "_bold.nii.gz"

### ISSUE THREAD

**Issue by erikglee** [bids-standard/legacy-validator#1933]
Hello,

I have looked at the BIDS standard's description of the "echo" entity, and based on my reading it seems like the BIDS standard doesn't denote where the "echo" entity should occur in the name of multi-echo fMRI files. So with that in mind the following two files should be equally compliant:

sub-9997_ses-1_task-GNG_echo-2_rec-NORDICNoNoiseVols_run-01_bold.nii.gz
sub-9997_ses-1_task-GNG_rec-NORDICNoNoiseVols_run-01_echo-2_bold.nii.gz

However, the BIDS validator only recognizes the second file as valid. Maybe I am misreading the BIDS standard here. But if I am reading it correctly it would be nice if either the validator or standard could be adjusted to make the preferred formatting clearer.

Thanks!
Erik

**Comment by effigies** [comment]
The order of entities is set by the specification.

**Comment by Remi-Gau** [comment]
@erikglee 

As @effigies please check the filename template of the functional MRI section of the specification to cross-check how to name this file.

https://bids-specification.readthedocs.io/en/latest/modality-specific-files/magnetic-resonance-imaging-data.html#task-including-resting-state-imaging-data

Also entities ALWAYS appear in the same order, this order is the one you can find in this page
https://bids-specification.readthedocs.io/en/latest/appendices/entities.html

**Comment by Remi-Gau** [comment]
So in your case

- sub
- task
- rec
- run
- echo

**Comment by erikglee** [comment]
Thanks for the quick replies! Looks like I had missed the entity table earlier.
