### ISSUE TITLE
deno 101: how to ship/run the "build"?

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#1934]
I thought to follow it and build myself a copy of deno bids-validator, running `./build.ts` just resulted in

```
runner@fv-az1269-285:~/bids-validator/bids-validator$ ls -l dist/validator/
total 4748
-rw-r--r-- 1 runner docker 2416374 Apr 18 01:54 bids-validator.js
-rw-r--r-- 1 runner docker 2445308 Apr 18 01:54 main.js
```

what I quickly googled is to use `deno bundle` but

```
runner@fv-az1269-285:~/bids-validator/bids-validator$ deno bundle dist/validator/
⚠️ Warning: `deno bundle` is deprecated and will be removed in Deno 2.0.
Use an alternative bundler like "deno_emit", "esbuild" or "rollup" instead.

runner@fv-az1269-285:~/bids-validator/bids-validator$ deno bundle dist/validator/bids-validator.js 
⚠️ Warning: `deno bundle` is deprecated and will be removed in Deno 2.0.
Use an alternative bundler like "deno_emit", "esbuild" or "rollup" instead.
error: Relative import path "ignore" not prefixed with / or ./ or ../
    at file:///home/runner/bids-validator/bids-validator/dist/validator/bids-validator.js:5338:35

```

so what is the recommended way to build/ship this validator for use?

**Comment by yarikoptic** [comment]
note: those builds are also pushed to https://github.com/bids-standard/bids-validator/tree/deno-build branch -- so could be ran from there! (might be worth adding answer to my question in that branch README.md?)

**Comment by yarikoptic** [comment]
even to run directly from deno-build branch seems to be getting to the same error:

```shell
runner@fv-az1114-215:~/bids-validator$ deno run bids-validator.js  --help
error: Relative import path "ignore" not prefixed with / or ./ or ../
    at file:///home/runner/bids-validator/bids-validator.js:5338:35
runner@fv-az1114-215:~/bids-validator$ deno run main.js  --help
error: Relative import path "ignore" not prefixed with / or ./ or ../
    at file:///home/runner/bids-validator/main.js:5527:35
runner@fv-az1114-215:~/bids-validator$ git branch
* deno-build
  master
```

**Comment by effigies** [comment]
Here's the script:

https://github.com/bids-standard/bids-validator/blob/master/bids-validator/bids-validator-deno

I'm not really sure what the "build" process is doing/supposed to do for you. You can just run `deno run $VALIDATOR_REPO/bids-validator/src/bids-validator.ts`

**Comment by nellh** [comment]
The build step isn't necessary but it is broken. This should make a single file you can run without network access but I get the same error @yarikoptic is reporting here running it because of our esbuild configuration.

The two builds are different entrypoints, `main.js` is an API meant to be used by applications embedding the validator (OpenNeuro or similar). `bids-validator.js` is the command line tool. At least the CLI tool should run with `deno run -A ./dist/validator/bids-validator.js` so that it can be run somewhere that doesn't have access to cache all the ESM modules from the network.

**Comment by yarikoptic** [comment]
Thank you @effigies for the pointer and @nellh for all the details!

JS-naive me, for the `build` I meant to establish some bundle which would not require entire independent `deno` installation, but I guess it is not an option.



> At least the CLI tool should run with `deno run -A ./dist/validator/bids-validator.js` so that it can be run somewhere that doesn't have access to cache all the ESM modules from the network.

it was not clear to me if `-A` somehow would address that error you confirmed getting to, so I have tried and received the same result

```
runner@fv-az1486-773:~$ git clone --depth 1 --branch deno-build https://github.com/bids-standard/bids-validator                                       
Cloning into 'bids-validator'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 1), reused 2 (delta 0), pack-reused 0
Receiving objects: 100% (4/4), 681.05 KiB | 6.68 MiB/s, done.
Resolving deltas: 100% (1/1), done.
runner@fv-az1486-773:~$ deno run  bids-validator/bids-validator.js --help
error: Relative import path "ignore" not prefixed with / or ./ or ../
    at file:///home/runner/bids-validator/bids-validator.js:5338:35
runner@fv-az1486-773:~$ deno run -A  bids-validator/bids-validator.js --help
error: Relative import path "ignore" not prefixed with / or ./ or ../
    at file:///home/runner/bids-validator/bids-validator.js:5338:35
runner@fv-az1486-773:~$ deno run -A $PWD/bids-validator/bids-validator.js --help
error: Relative import path "ignore" not prefixed with / or ./ or ../
    at file:///home/runner/bids-validator/bids-validator.js:5338:35
```

so is that something I should wait for to have overcome?

meanwhile tried without build using @effigies pointed and it seems to work

```shell
runner@fv-az1486-773:~$ git clone --depth 1 https://github.com/bids-standard/bids-validator                                                           
Cloning into 'bids-validator'...
remote: Enumerating objects: 715, done.
remote: Counting objects: 100% (715/715), done.
remote: Compressing objects: 100% (598/598), done.
remote: Total 715 (delta 71), reused 415 (delta 56), pack-reused 0
Receiving objects: 100% (715/715), 3.25 MiB | 13.59 MiB/s, done.
Resolving deltas: 100% (71/71), done.
runner@fv-az1486-773:~$ cd bids-validator/
runner@fv-az1486-773:~/bids-validator$ bids-validator/bids-validator-deno

Usage:   bids-validator <dataset_directory>
Version: alpha                             

```

so I will adopt that one for now

**Comment by nellh** [comment]
> error: Relative import path "ignore" not prefixed with / or ./ or ../
>    at file:///home/runner/bids-validator/bids-validator.js:5338:35

I made #1936 to fix the build error here. I'd generally recommend running either the HTTPS file (if you just want to use the validator) or the `bids-validator-deno` script (if you want to develop changes for the validator).

**Comment by yarikoptic** [comment]
I think I found peace now on this regard, thanks!
