### ISSUE TITLE
deno testing 101: deno_tests.yml is chronically red, "on purpose"?

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#1935]
seems like just 2 tests are failing... why then to not just xfail/skip them since otherwise sounds like no point of having that CI since it would mask new fails ...

**Comment by effigies** [comment]
Yeah, we should probably mark xfails at this point. The goal was for it not to go on so  long.

**Comment by effigies** [comment]
Nearly resolved for Ubuntu tests: https://github.com/bids-standard/bids-validator/pull/1958

Need to figure out the Mac and Windows tests.

**Comment by yarikoptic** [comment]
thanks -- that is great!

are those the tests on bids-examples and thus may be would allow to remove this skips I added to https://github.com/bids-standard/bids-examples/pull/435/files#diff-786f1d799afd8d7a2bd595ebff633b3683d87a556ec6abfa78bd537855ebe1a0R106 ?

**Comment by effigies** [comment]
Yes, it covers all tests, including examples. Some issues on Mac and Windows.
