### ISSUE TITLE
Exit status of the command line interface

### ISSUE THREAD

**Issue by gllmflndn** [bids-standard/legacy-validator#194]
Would it be possible to add options --version and --help to the command line interface of bids-validator, that would return an exit status of 0?
At the moment, a call without argument displays the help text but returns an exit status of 1.

**Comment by constellates** [comment]
Yea this sounds reasonable and should be a simple change. I'll take a look.

**Comment by chrisgorgo** [comment]
Out of curiosity - what do you need it for?

**Comment by gllmflndn** [comment]
The main reason is to come up with an easy test that checks whether the validator is installed and runs fine.

**Comment by chrisgorgo** [comment]
Makes sense!
