### ISSUE TITLE
Bundle schema validator and legacy validator into Docker container

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#1963]
it could be not the default entry point, but if installed as `bids-validator-deno` - I could run it by altering entry point. That would allow to use available docker containers for running new validator alongside with original node one.

**Comment by yarikoptic** [comment]
WDYT @effigies @rwblair @nellh -- doable/desired? or better be a separate container or ... ?

**Comment by effigies** [comment]
I don't see any reason that it wouldn't be doable. We would need to basically run `bids-validator/build.ts` and then either `deno install` or `deno compile -A bids-validator/dist/validator/bids-validator.js`.

Compiling locally, I get a 100MB binary. I'm not really sure who uses the docker image in what ways, so it's not clear if this is an acceptable increase in image size.

**Comment by yarikoptic** [comment]
in the light of

```
❯ du -Lscm ~/proj/repronim/containers/images/bids/bids-validator--1.14.5.sing
320	/home/yoh/proj/repronim/containers/images/bids/bids-validator--1.14.5.sing
320	total
❯ docker images| grep bids
bids/validator                                       latest                         574aeef5002c   5 months ago    1.06GB
```

I think extra 100MB would go unnoticed ;-)

**Comment by effigies** [comment]
We've split the repository because keeping the two things running from a single code base was becoming too difficult. Creating a single Dockerfile makes more sense as a standalone repository.
