### ISSUE TITLE
Add support for proton density maps

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#200]
nifti files in /anat folder with _PD suffix

**Comment by constellates** [comment]
It looks like PD is already an accepted suffix in anat directories. I tested naming a file accordingly and found this reference in the code.

https://github.com/INCF/bids-validator/blob/master/utils/type.js#L8

Do we need additional support?

**Comment by chrisgorgo** [comment]
nope - my bad!
