### ISSUE TITLE
Add support for phenotypic data split into multiple files (together with metadata

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#201]
See https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit#heading=h.pi5iigxxt8vy

**Comment by constellates** [comment]
Hey @chrisfilo I don't have a clear grasp of what needs to be done here. So here are a few questions for you.

From the spec:

> If the dataset includes multiple sets of participant level measurements (for example responses from multiple questionnaires) they can be split into individual files separate from participants.tsv. Those measurements should be kept in phenotype/ folder and end with the .tsv extension.

Are there limitations on where the phenotype folder can be placed in the dataset? Or can it be placed anywhere and lower level directories will inherit this data?

Are there any limitations about how these phenotype files are named (aside from the fact they have to have .tsv extensions and can optionally have a .json version for metadata)?

It looks like the tsv phenotype files must contain participant_id column. Aside from that is there more validation you would like to do on them at this time?

**Comment by chrisgorgo** [comment]
On Tue, Oct 11, 2016 at 1:22 PM, constellates notifications@github.com
wrote:

> Hey @chrisfilo https://github.com/chrisfilo I don't have a clear grasp
> of what needs to be done here. So here are a few questions for you.
> 
> From the spec:
> 
> If the dataset includes multiple sets of participant level measurements
> (for example responses from multiple questionnaires) they can be split into
> individual files separate from participants.tsv. Those measurements should
> be kept in phenotype/ folder and end with the .tsv extension.
> 
> Are there limitations on where the phenotype folder can be place in the
> dataset? Or can it be placed anywhere and lower level directories will
> inherit this data?
> 
> yes it's only in the root
> 
> Are there any limitations about how these phenotype files are named (aside
> from the fact they have to have .tsv extensions and can optionally have a
> .json version for metadata)?
> 
> no there are not limitations
> 
> It looks like the tsv phenotype files must contain participant_id column.
> Aside from that is there more validation you would like to do on them at
> this time?
> 
> nope - this should be sufficient

BTW here's an example dataset https://openfmri.org/dataset/ds000030/

**Comment by constellates** [comment]
Update merged.
