### ISSUE TITLE
incorrect statement about dataset json file

### ISSUE THREAD

**Issue by coaxlab0** [bids-standard/legacy-validator#204]
Keeps saying that the json file should have {} instead of / or ' ' yet the json file does not have / or ' ' 
Tells me that there are errors on specific lines that do not exist.

**Comment by chrisgorgo** [comment]
Thanks for reporting. Could you attach the log of the validator and the
JSON file that is causing problems?

**Comment by coaxlab0** [comment]
[image: Inline image 1]

**Comment by chrisgorgo** [comment]
I'm afraid your last comment did not come through correctly. You can email chrisgor@stanford.edu if this is easier.

**Comment by chrisgorgo** [comment]
This problem arose from using [txtedit](http://txtedit.en.softonic.com/) to generate the files which was outputting RTF instead of plain text.
