### ISSUE TITLE
.bidsignore format

### ISSUE THREAD

**Issue by tamjidimtiaz** [bids-standard/legacy-validator#2146]
Hi, my bids directory contains some files that are not compatible with the current bids format which are following:
<img width="872" alt="image" src="https://github.com/user-attachments/assets/f45aedf9-9c82-4179-b242-40815814ba17">

I want to include thase files in the .bidsignore. I created the .bidsignore file and include the following:

<img width="695" alt="image" src="https://github.com/user-attachments/assets/ce323575-0d7b-4f16-b468-ce15ea708711">

However it didn't work while I was validating again through bids-validator. Can someone give me some guidelines?

**Comment by effigies** [comment]
I'd get rid of the `**/`. That's not needed to match, and might not be implemented by the matching library.

**Comment by tamjidimtiaz** [comment]
I did that as well. But did not work. Do you have any other suggestions?

**Comment by effigies** [comment]
Could you show a full (text, not screenshot) listing of your dataset, the `.bidsignore` and the validator output (this could be screenshot, if there's no good way to format the text)?

**Comment by tamjidimtiaz** [comment]
Is it okay if I share the screenshot of the tree output of the listing of the dataset?

**Comment by tamjidimtiaz** [comment]
[bidstext.txt](https://github.com/user-attachments/files/17247091/bidstext.txt)

**Comment by effigies** [comment]
Okay, looking at that, you have derivatives directories inside your subject directories, which is likely to be a significant problem. You also use `space-<label>` in your anatomical filenames, which is not permitted.

What are the validator outputs?

**Comment by tamjidimtiaz** [comment]
The validator output:

![Image](https://github.com/user-attachments/assets/1a59e8e1-23b3-4629-bc11-779c212c90c5)

**Comment by tamjidimtiaz** [comment]
The validator output:

![Image](https://github.com/user-attachments/assets/49ff3533-d4aa-4680-a022-71ed9b58abe4)

**Comment by tamjidimtiaz** [comment]
Validator output:

![Image](https://github.com/user-attachments/assets/98a346dd-93ef-4b18-bedc-82506a47e241)

**Comment by tamjidimtiaz** [comment]
Validator output:

![Image](https://github.com/user-attachments/assets/5fb01123-b0cb-4ad1-a050-08eab2e42a7f)

**Comment by CPernet** [comment]
I have the same issue -- the old validator works but the new one does not like the .bidsignore

**Comment by effigies** [comment]
Hmm. Could you print out the bytes?

```console
python -c "with open('.bidsignore', 'rb') as fobj: print(fobj.read(50))"
```

I wonder if you have `\r` characters that are not being stripped.

**Comment by effigies** [comment]
Also, can you verify that this occurs with the CLI validator?

```console
deno run --reload -A jsr:@bids/validator $DATASET
```

**Comment by effigies** [comment]
Nevermind. Found the bug: #2151

**Comment by CPernet** [comment]
You guys are too fast ...  Thx 🙏
