### ISSUE TITLE
Incorrect warnings: TaskName key in channels.tsv, and events.tsv missing for noise

### ISSUE THREAD

**Issue by Moo-Marc** [bids-standard/legacy-validator#2154]
I get this error for MEG *_channels.tsv files:
warning: SIDECAR_KEY_RECOMMENDED (TaskName)
But that's clearly wrong for channel lists, and it's not in the specification.

There's another warning that could be improved.  Currently, it warns of missing events.tsv file, but recognizes "rest" tasks as not needing it.  Another task that doesn't need events is an [empty room noise recording](https://bids-specification.readthedocs.io/en/stable/modality-specific-files/magnetoencephalography.html#empty-room-meg-recordings), "noise".  The validator should check that word too and prevent this warning.

Cheers

**Comment by effigies** [comment]
The emptyroom problem was also noted in https://github.com/bids-standard/bids-validator/issues/2137 and should be resolved by the latest development version.

Added a fix for this to bids-standard/bids-specification#1941

**Comment by Moo-Marc** [comment]
@effigies @rwblair As I commented in bids-standard/bids-validator#12 (but I forgot to tag anyone so it was probably missed), noise recordings may be inside "normal" subject folders instead of `sub-emptyroom`, so that fix doesn't work in general.  I believe checking `task-noise` is the way to go.

**Comment by effigies** [comment]
Actually, reopening bids-standard/bids-validator#12 instead of this one, since it's more focused on this one problem.
