### ISSUE TITLE
Big dataset memory problem

### ISSUE THREAD

**Issue by jokedurnez** [bids-standard/legacy-validator#219]
I have a large dataset (120 subjects, 2.5GB per subject) and the bids-validator runs into a memory problem (with 64GB ram).
With only one of these subjects in the bids-folder, there seems to be no problem.  Is there a way to run the bids-validator for only one subject?

Specific error trace:

```
<--- Last few GCs --->

   21629 ms: Scavenge 1397.3 (1456.9) -> 1397.3 (1456.9) MB, 0.1 / 0 ms (+ 1.4 ms in 1 steps since last GC) [allocation failure] [incremental marking del
aying mark-sweep].

   22079 ms: Mark-sweep 1397.3 (1456.9) -> 1395.5 (1456.9) MB, 450.3 / 0 ms (+ 2.3 ms in 2 steps since start of marking, biggest step 1.4 ms) [last resor
t gc].
   22697 ms: Mark-sweep 1395.5 (1456.9) -> 1395.5 (1456.9) MB, 618.0 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xb055da37399 <JS Object>
    1: parse [native json.js:41] [pc=0x10c2fa78d4b2] (this=0xb055da381b1 <a JSON with map 0x2e4420210969>,r=0x2bfe3f804101 <Very long string[4019713]>,l=
0xb055da04131 <undefined>)
    2: arguments adaptor frame: 1->2
    3: /* anonymous */(aka /* anonymous */) [/XXX/node-v4.2.2-linux-x64/lib/node_modules/bids-validator/validators/json.js:21] [pc
=0x10c2fa875f3f] (this=0xb05...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted
```

**Comment by chrisgorgo** [comment]
Does this happen with or without the --verbose flag?

**Comment by jokedurnez** [comment]
With and without, The exact same error message.

**Comment by chrisgorgo** [comment]
@constellates let us know what kind of debug info we can provide to help resolving this issue

**Comment by constellates** [comment]
It would be awesome if I could at least get the full directory structure and metadata files for the dataset that's causing this issue. If the whole dataset is available somewhere online that would be great, but given the size it may be faster for me to mock the dataset with the metadata/structure than to download it anyways. 

I haven't debugged this issue at all yet, but my first guess is that one or more of our checks that require storing references and data to be referenced later in the process are just growing until the node memory limit above is hit.

**Comment by chrisgorgo** [comment]
@jokedurnez could you provide a version of this dataset with all .nii.gz files replaced by empty files?

**Comment by constellates** [comment]
Also I just searched memory limits in node and it looks like by default node will only allow a little over 1.7gb of memory usage. It also looks possible to increase this limit with a --max-old-space-size= flag, but we should definitely try to address memory usage in the validator.

**Comment by constellates** [comment]
So with this dataset the issue is we're collecting all of the json file contents to later be compared against the scan headers and that collection is hitting the memory limit. As mentioned above the default memory limit in node is about 1.7gb and my rough estimate of the total JSON file size in this dataset is about 4gb.

As a temporary fix I was able to run the validator with the memory limit flag.

```
node --max_old_space_size=6000 bin/bids-validator ~/Desktop/99_bids_mockup
```

With the full scans included this size may need to be further increased. The size is size in megabytes.

I don't have a real solution to the issue yet. Buffers are a potential strategy to persist data outside of the memory limit but they have 1gb limit per buffer. I think ultimately we need to find strategies to not store things like a full dictionary of all json contents. We might try storing only references to each JSON file and reading them on the fly when we need to make comparisons.

I'll start testing some alternative solutions and let you know how it goes.

**Comment by chrisgorgo** [comment]
We should try to address this - maybe by evaluating one nifti file at a
time.

As for this particular case the dataset can be greatly simplified by
pulling all of the common metadata from individual JSON files and putting
them in the single json file on top level. Also it might worth considering
to remove all of the extra non-standard (non-BIDS) json fields added by
heudiconv via dcmstack). It really should not be the case that JSONS alone
will be 4GB.

**Comment by chrisgorgo** [comment]
See https://github.com/nipy/heudiconv/issues/33

**Comment by mgxd** [comment]
this is still happening with large datasets (600GB of subject data, 5+TB `derivatives`) - most recent error

```
$ bids-validator /data

<--- Last few GCs --->

 1520047 ms: Mark-sweep 1389.4 (1437.5) -> 1389.4 (1437.5) MB, 1469.6 / 0.0 ms [allocation failure] [GC in old space requested].
 1521480 ms: Mark-sweep 1389.4 (1437.5) -> 1389.4 (1437.5) MB, 1432.9 / 0.0 ms [allocation failure] [GC in old space requested].
 1523000 ms: Mark-sweep 1389.4 (1437.5) -> 1402.8 (1421.5) MB, 1520.6 / 0.0 ms [last resort gc].
 1524499 ms: Mark-sweep 1402.8 (1421.5) -> 1416.1 (1421.5) MB, 1498.1 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x38dd0c8cf781 <JS Object>
    1: exec [native regexp.js:~116] [pc=0x1fc047374747] (this=0xcb8147fa851 <JS RegExp>,D=0xcb8147fa731 <String[109]: /derivatives/archive/hcp_pipeline/sub-BANDA028/task-rest_run-02_bold/OneStepResampling/prevols/vol0350.nii.gz>)
    2: test [native regexp.js:~260] [pc=0x1fc047370381] (this=0xcb8147fa851 <JS RegExp>,D=0xcb8147fa731 <String[109]: /derivatives/archive/hcp_pipeline/sub-BANDA028/ta...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [bids-validator]
 2: 0x7cff7c [bids-validator]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [bids-validator]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [bids-validator]
 5: v8::internal::Factory::NewByteArray(int, v8::internal::PretenureFlag) [bids-validator]
 6: v8::internal::Factory::NewCode(v8::internal::CodeDesc const&, unsigned int, v8::internal::Handle<v8::internal::Object>, bool, bool, int, bool) [bids-validator]
 7: v8::internal::RegExpMacroAssemblerX64::GetCode(v8::internal::Handle<v8::internal::String>) [bids-validator]
 8: v8::internal::RegExpCompiler::Assemble(v8::internal::RegExpMacroAssembler*, v8::internal::RegExpNode*, int, v8::internal::Handle<v8::internal::String>) [bids-validator]
 9: v8::internal::RegExpEngine::Compile(v8::internal::Isolate*, v8::internal::Zone*, v8::internal::RegExpCompileData*, v8::base::Flags<v8::internal::JSRegExp::Flag, int>, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>, bool) [bids-validator]
10: v8::internal::RegExpImpl::CompileIrregexp(v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, bool) [bids-validator]
11: v8::internal::RegExpImpl::IrregexpPrepare(v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>) [bids-validator]
12: v8::internal::RegExpImpl::Exec(v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, int, v8::internal::Handle<v8::internal::JSArray>) [bids-validator]
13: v8::internal::Runtime_RegExpExec(int, v8::internal::Object**, v8::internal::Isolate*) [bids-validator]
14: 0x1fc0471092a7
Aborted (core dumped)
```

**Comment by chrisgorgo** [comment]
Does your dataset include extensive DICOM header dump (from dcmstack) in each sidecar JSON file? Which node version do you use?

**Comment by chrisgorgo** [comment]
BTW Derivatives should not contribute to this - I expect the same result happens without the presence of the /derivatives folder (although it might be worth verifying).

**Comment by mgxd** [comment]
I'm using `node v6.14.2` - the sidecar JSON files are only 3KB

I'm encountering this while running the HCP_Pipelines bids app, perhaps the Dockerfile needs to be updated?

```
RUN apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
    apt-get remove -y curl && \
    apt-get install -y nodejs

RUN npm install -g bids-validator@0.19.2
```

**Comment by chrisgorgo** [comment]
Could you try latest version of the validator and if that does not help
node 10?

**Comment by mgxd** [comment]
looks like this has been solved with the latest versions of validator/node, sorry for the congestion!
