### ISSUE TITLE
Please add continuous integration testing

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#22]
1. Go to circleCI.com
2. Log in with a github account with admin rights to Squishymedia/bids-validator
3. Add (plus sign on the left hand side menu) the Squishymedia/bids-validator repo
4. You are done! circleCI will automatically recognise this as node.js project with mocha testing, install all of the dependencies and run tests. This is how the end result will look like: https://circleci.com/gh/chrisfilo/bids-validator/1

This way test will be run for each commit and each PR making sure nothing is getting broken. I would've done this myself, but I don't have admin rights to this repo.

**Comment by constellates** [comment]
Thanks Chris. It should be all setup. I also added the passing/failing badge to the readme.
