### ISSUE TITLE
cannot read property length

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#230]
From a user:

> The BIDS dataset is within ~/Documents/DE_420_01/, in ./anat, ./dwi, etc. 
> However, when I check the files using the bids-validator web interface, all the files check out as BIDS format. I installed bids-validator and ran bids-validator ~/Documents/DE_420_01/ as well as ~/Documents/DE_420_01/anat, but I get this error:
> 
> /usr/lib/node_modules/bids-validator/cli.js:25
>             } else if (errors.length >= 1 || warnings.length >= 1) {
>                              ^
> 
> TypeError: Cannot read property 'length' of undefined
>     at /usr/lib/node_modules/bids-validator/cli.js:25:30
>     at /usr/lib/node_modules/bids-validator/validators/bids.js:43:29
>     at Object.BIDS.quickTest (/usr/lib/node_modules/bids-validator/validators/bids.js:87:9)
>     at /usr/lib/node_modules/bids-validator/validators/bids.js:39:26
>     at Object.readDir (/usr/lib/node_modules/bids-validator/utils/files.js:89:9)
>     at /usr/lib/node_modules/bids-validator/validators/bids.js:38:29
>     at /usr/lib/node_modules/bids-validator/utils/options.js:20:17
>     at /usr/lib/node_modules/bids-validator/utils/options.js:63:25
>     at Object.module.exports.parse (/usr/lib/node_modules/bids-validator/utils/json.js:29:17)
>     at /usr/lib/node_modules/bids-validator/utils/options.js:53:22

**Comment by yeunkim** [comment]
version information:

$ bids-validator -v
0.19.1
$ node -v
v4.6.1

I downloaded/installed node.js via:
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs

then bids-validator:
npm install -g bids-validator

Thanks!

**Comment by chrisgorgo** [comment]
The dataset causing this error is not BIDS compatible. Nonetheless the previous version of the validator (before the config feature was merged) worked correctly giving: "This does not appear to be a BIDS dataset. For more info go to http://bids.neuroimaging.io/"

**Comment by constellates** [comment]
Thanks for the extra details I was having a hard time reproducing this error until I saw the "This does not appear to be a BIDS dataset" error.

PR #231  should address this issue.

**Comment by chrisgorgo** [comment]
This has been fixed in 0.19.2 - thanks for reporting @yeunkim
