### ISSUE TITLE
[_recording­<label>]_physio.json is shown as Non BIDS compatible file

### ISSUE THREAD

**Issue by suyashdb** [bids-standard/legacy-validator#236]
A top level [_recording­<label>]_physio.json creates warning as "This file is not Bids compatible".
```
/recording-cardresp_physio.json
			This file is not part of the BIDS specification, make sure it isn't included in the dataset by accident. Data derivatives (processed data) should be placed in /derivatives folder.
			Evidence: recording-cardresp_physio.json
		/recording-eyegaze_physio.json
			This file is not part of the BIDS specification, make sure it isn't included in the dataset by accident. Data derivatives (processed data) should be placed in /derivatives folder.
			Evidence: recording-eyegaze_physio.json
```

**Comment by suyashdb** [comment]
ds217 - 

1: This file is not part of the BIDS specification, make sure it isn't included in the dataset by accident. Data derivatives (processed data) should be placed in /derivatives folder. (code: 1 - NOT_INCLUDED)
		/task-picturetest_beh.json
			Evidence: task-picturetest_beh.json

**Comment by constellates** [comment]
To resolve, I believe a change would need to made to the regular expressions in this function defining accepted top level file patterns. 

https://github.com/INCF/bids-validator/blob/master/utils/type.js#L38

I believe the file in the first comment tripped the issue because "recording-" is not listed as an accepted prefix. And the file in the second comment created an issue because "_beh.json" is not listed as a top level suffix.

I haven't been following the spec closely enough lately to know if these should be allowed, but I would update one of the regex patterns in the above function if they are supported.

**Comment by suyashdb** [comment]
I will add the suggested edits and create a PR. I just updated the issue for records.

**Comment by suyashdb** [comment]
@constellates i added _beh.json to the valid list. Tried adding recording prefix under valid prefix list, but it didn't work. 

var funcTopRe = new RegExp('^\\/(?:ses-[a-zA-Z0-9]+_)?(?:recording-[a-zA-Z0-9]+_)?task-[a-zA-Z0-9]+(?:_acq-[a-zA-Z0-9]+)?(?:_rec-[a-zA-Z0-9]+)?(?:_run-[0-9]+)?'
            + '(_bold.json|_sbref.json|_events.json|_events.tsv|_physio.json|_stim.json|_beh.json)$');

Looking into it if made any mistakes in regex.

**Comment by constellates** [comment]
@suyashdb

I think the regex is ok. I can copy and paste from your comment above and then run the following in a small script and it returns true.

    funcTopRe.test('/task-picturetest_beh.json')

So something else must be going on. If you're still having issues I can try actually modifying the validator and running it against that dataset tomorrow to see if there's another issue.

**Comment by constellates** [comment]
I also just realized I'm not seeing ds217 on openfmri or in the bids example repo. Is there a way to access it?

**Comment by suyashdb** [comment]
@constellates  
ds217 is still unpublished. Should be published by tomorrow. 

i just created a 'recording-cardresp_physio.json' file in another dataset and was using it for tests. 

Just had a chat with chris about this error. As per current regex, we haven't taken into account a recording file without task label. hence the problem. i just need to add another regex expression to include files such as `recording-cardresp_physio.json`.

```
var funcTopRe = new RegExp('^\\/(?:ses-[a-zA-Z0-9]+_)?(?:recording-[a-zA-Z0-9]+_)?task-[a-zA-Z0-9]+(?:_acq-[a-zA-Z0-9]+)?(?:_rec-[a-zA-Z0-9]+)?(?:_run-[0-9]+)?'
            + '(_bold.json|_sbref.json|_events.json|_events.tsv|_physio.json|_stim.json|_beh.json)$');
```
