### ISSUE TITLE
Limit accuracy when validating header consistency

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#241]
I'm gettign this error when validating ds133
<img width="689" alt="screen shot 2016-11-07 at 4 14 27 pm" src="https://cloud.githubusercontent.com/assets/238759/20081601/786ec87c-a505-11e6-9693-df1f4668da67.png">

Let's round the numbers to three decimal places before doing the comparison to avoid such issues.

When fixed please update prod server.

**Comment by constellates** [comment]
This is up on prod.
