### ISSUE TITLE
why PARTICIPANT_ID_MISMATCH  ?

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#250]
getting
```
2: Subjects found in this dataset did not match the participant_ids found in the participants.tsv file. (code: 49 - PARTICIPANT_ID_MISMATCH)
	/participants.tsv
```
although I believe they are all kosher:

```shell

$ awk '/sub-/{print $1;}' participants.tsv | while read f; do ls -ld $f; done
drwxr-xr-x 1 mvdoc dbic 30 Nov  6 17:22 sub-sid000050                            
drwxr-xr-x 1 mvdoc dbic 24 Nov  6 18:19 sub-sid000056                            
drwxr-xr-x 1 mvdoc dbic 30 Nov  6 19:14 sub-sid000057                            
drwxr-xr-x 1 mvdoc dbic 24 Nov  6 20:07 sub-sid000059                            
drwxr-xr-x 1 mvdoc dbic 30 Nov  6 20:50 sub-sid000060                            
drwxr-xr-x 1 mvdoc dbic 24 Nov  6 21:50 sub-sid000061                            
drwxr-xr-x 1 mvdoc dbic 24 Nov  6 22:48 sub-sid000062                            
drwxr-xr-x 1 mvdoc dbic 24 Nov  6 23:36 sub-sid000063                            
drwxr-xr-x 1 mvdoc dbic 30 Nov  7 00:33 sub-sid000064                            
drwxr-xr-x 1 mvdoc dbic 24 Nov  7 01:35 sub-sid000065                            
drwxr-xr-x 1 mvdoc dbic 24 Nov  7 02:26 sub-sid000066                            
drwxr-xr-x 1 mvdoc dbic 24 Nov  7 03:18 sub-sid000067                            
drwxr-xr-x 1 mvdoc dbic 30 Nov  7 04:15 sub-sid000068                            
drwxr-xr-x 1 mvdoc dbic 30 Nov  7 05:18 sub-sid000069                            
drwxr-xr-x 1 mvdoc dbic 24 Nov  7 06:19 sub-sid000074                            
drwxr-xr-x 1 mvdoc dbic 24 Nov  7 07:09 sub-sid000075                       
drwxr-xr-x 1 mvdoc mvdoc 24 Nov 23 12:24 sub-sid000078                      
drwxr-xr-x 1 mvdoc mvdoc 24 Nov 23 13:24 sub-sid000079                      
drwxr-xr-x 1 mvdoc mvdoc 30 Nov 23 14:16 sub-sid000076                      
drwxr-xr-x 1 mvdoc mvdoc 30 Nov 23 15:19 sub-sid000077                     
drwxr-xr-x 1 mvdoc mvdoc 24 Nov 23 16:00  sub-sid000080

$ for d in sub-sid0000*; do grep -q $d participants.tsv|| echo $d;  done
```

```shell
$> cat participants.tsv 
participant_id	age	sex	group
sub-sid000050	25	F	control
sub-sid000056	19	M	control
sub-sid000057	18	F	control
sub-sid000059	20	F	control
sub-sid000060	20	F	control
sub-sid000061	18	F	control
sub-sid000062	20	M	control
sub-sid000063	18	M	control
sub-sid000064	18	M	control
sub-sid000065	19	M	control
sub-sid000066	19	M	control
sub-sid000067	18	F	control
sub-sid000068	18	F	control
sub-sid000069	17	M	control
sub-sid000074	19	M	control
sub-sid000075	19	M	control
sub-sid000078	18	F	control
sub-sid000079	19	F	control
sub-sid000076	18	F	control
sub-sid000077	19	F	control
sub-sid000080	19	F	control
```

so we do have all participants and for each sub- directory we have a record in the participants.tsv...  any idea?

**Comment by chrisgorgo** [comment]
We made error messages for this issue more verbose to help with those situations. Could you try it with the latest version?

**Comment by yarikoptic** [comment]
```shell
	2: Participant labels found in this dataset did not match the values in participant_id column found in the participants.tsv file. (code: 49 - PARTICIPANT_ID_MISMATCH)
		/participants.tsv
			Participant labels found in this dataset did not match the values in participant_id column found in the participants.tsv file.
			Evidence: participants.tsv: sid000050,sid000056,sid000057,sid000059,sid000060,sid000061,sid000062,sid000063,sid000064,sid000065,sid000066,sid000067,sid000068,sid000069,sid000074,sid000075,sid000078,sid000079,sid000076,sid000077,sid000080 folder structure: sid000050.jso,sid000056.jso,sid000050,sid000056,sid000050..anat..sub-sid000050,sid000056..anat..sub-sid000056,sid000050..func..sub-sid000050,sid000056..func..sub-sid000056,sid000057,sid000059,sid000060,sid000061,sid000062,sid000063,sid000064,sid000065,sid000066,sid000067,sid000068,sid000069,sid000074,sid000075,sid000076,sid000077,sid000078,sid000079,sid000080
```
could you help decypher it please? ;)  since I have no clue in what .jso are and where they come from

**Comment by yarikoptic** [comment]
may be a reason is some inconsistencies underneath (some subjects' scans were interrupted etc)

**Comment by chrisgorgo** [comment]
For some reason validator thinks that:

sid000050.jso

sid000056.jso

sid000050..anat..sub-sid000050

sid000056..anat..sub-sid000056

sid000050..func..sub-sid000050

sid000056..func..sub-sid000056

are participants labels (detected in the folder structure). Do you
have folders with those names? Coudl you attach `tree` of your
dataset?

**Comment by yarikoptic** [comment]
ha -- so the story is that I had `derivatives/mriqc` and `scratch/{out,work}` from me trying mriqc (via docker bids-app again)... I have removed them and now bids-validator doesn't complain like it was before... So  I guess validator looks also beyond `sub-*` files list in current directory??

**Comment by chrisgorgo** [comment]
The culprit is probably code found here:
https://github.com/INCF/bids-validator/blob/4f908facb8010f449bf0e82e69591762029e220f/validators/bids.js#L258  It's
too broad when looking for subjects and sessions.

**Comment by constellates** [comment]
Ok. I just opened a PR for a potential fix. My understanding of what is happening is that chunk of code you linked collects subject IDs by checking each file name for a "sub-" prefix and collecting the corresponding value. To get that value it's assuming the value is always between a "sub-" prefix and an underscore. So this issue would arise anytime a sub-<value> section is the last part of a file path before the extension.

This fix tries to prevent that and other potential issues by using the BIDS type check before checking for the sub- value. Are there any cases where a valid bids file name could have the subject section as the end of the file name (sub-01.json)? If so I'll need to add another small update to account for that.

**Comment by chrisgorgo** [comment]
@yarikoptic a fix has been merged and a new release minted. Could you give it a try? The web interface was also updated.
