### ISSUE TITLE
Sanity check: EffectiveEchoTime should be always smaller than TotalReadoutTime

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#254]

**Comment by SetCodesToFire** [comment]
Is the EffectiveEchoTime is the same header name as EchoTime in the sidecar files? @chrisfilo

**Comment by olgn** [comment]
@chrisfilo I'm a bit confused about this, too. There is no documentation of a variable called 'EffectiveEchoTime' mentioned in the bids spec. Is it possible you meant EffectiveEchoSpacing < TotalReadoutTime or EchoTime < TotalReadoutTime? Or both?

**Comment by chrisgorgo** [comment]
My bad. It should be `EffectiveEchoSpacing < TotalReadoutTime`

**Comment by olgn** [comment]
@chrisfilo should severity be error or warning?

**Comment by chrisgorgo** [comment]
Let's make it an error.
