### ISSUE TITLE
participant ID and 'invalid json'

### ISSUE THREAD

**Issue by coaxlab0** [bids-standard/legacy-validator#255]
I keep getting an error that my participant.tsv file doesn't have a participant id column which is does. I also am getting a constant error for my json file, I'm not sure the appropriate formatting for json files and I'm having issues finding examples of what one looks like.

**Comment by chrisgorgo** [comment]
Could you share:
1) the exact text of the errors you getting
2) the JSON and TSV files that are producing them

This will help us help you.

**Comment by chrisgorgo** [comment]
Here is an example of a JSON file: https://github.com/INCF/BIDS-examples/blob/master/ds001/task-balloonanalogrisktask_bold.json

Here is an example of a participants.tsv file: https://github.com/INCF/BIDS-examples/blob/master/ds001/participants.tsv

More example datasets: https://github.com/INCF/BIDS-examples

**Comment by coaxlab0** [comment]
[image: Inline image 2][image: Inline image 1]

**Comment by chrisgorgo** [comment]
I think something went wrong with your last comment.

**Comment by coaxlab0** [comment]
in json or the participants folder? Is it because it ends on a number
sequence? I wasn't sure if numbers need to be in quotation marks or not.

**Comment by chrisgorgo** [comment]
Please go to https://github.com/INCF/bids-validator/issues/255.

Numbers in JSON files should not be in quotes.

**Comment by coaxlab0** [comment]
so I've gotten rid of the numbers on the funding, after looking at examples
it seems like most people put quotations around their numbers, now its
giving me an error for curly brackets. I also don't understand why I'm
getting the error for my participants.tsv when I have a participant_id
column [image: Inline image 1]

**Comment by chrisgorgo** [comment]
Unfortunately, I don't see any images you are posting. Please post them directly on GitHub: https://github.com/INCF/bids-validator/issues/255 

Ideally, it would be best to get the participants.tsv and the JSON file that is giving you troubles.

**Comment by coaxlab0** [comment]
![screen shot 2016-12-13 at 2 25 03 pm](https://cloud.githubusercontent.com/assets/2701453/21159393/15f30328-c14f-11e6-9b29-71a4685bcdbf.png)
![screen shot 2016-12-13 at 1 29 26 pm](https://cloud.githubusercontent.com/assets/2701453/21159458/4a66e020-c14f-11e6-9b28-a7fdba359008.png)

**Comment by coaxlab0** [comment]
![screen shot 2016-12-13 at 4 16 32 pm](https://cloud.githubusercontent.com/assets/2701453/21159523/8bb0954e-c14f-11e6-9ce3-78be4a2dbaf5.png)
![screen shot 2016-12-13 at 4 17 09 pm](https://cloud.githubusercontent.com/assets/2701453/21159537/9ed177e2-c14f-11e6-87aa-91ad4a6c82e9.png)

**Comment by coaxlab0** [comment]
I'm having issues uploading the tsv and json so here are pictures of what they look like when you open them.

**Comment by chrisgorgo** [comment]
The .tsv file does not seem to be tab separated. Try using an editor such as notepad++ or Atom to fix it.

The JSON file is missing square brackets around the list of the two funding agencies. You can use http://jsonlint.com/ to validate your file interactively.
