### ISSUE TITLE
please provide git tags for the releases

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#259]
Dockefile of the bids-app installs bids-validator@0.19.9 which suggests nice versioning but I see no tags in the clone of this repository.
I was interested to try https://github.com/INCF/bids-validator/pull/210 which was merged in 7b31778c7e9398e51f883ee9de772bfe16560f30  but it is hard now to figure out which release should I try since 

```shell
$> git describe --contains --tags 7b31778           
fatal: cannot describe '7b31778c7e9398e51f883ee9de772bfe16560f30'
```

**Comment by chrisgorgo** [comment]
The versions are managed here: https://github.com/INCF/bids-validator/blob/master/package.json#L3

The feature you are interested in is in all versions since 0.19.0.

Tag based versioning will come when this is finished: https://github.com/INCF/bids-validator/pull/225
