### ISSUE TITLE
SliceTiming Field needs a n/a flag

### ISSUE THREAD

**Issue by alexlicohen** [bids-standard/legacy-validator#260]
In some datasets (typically post-hoc collections/distributions), the Slice Timing information is not available (e.g., some of the ABIDE datasets). Currently, having a task-rest_bold.json in the study directory with the line:
`  "SliceTiming": "n/a",`
 throws an error code that this needs to be an array.

If not available, and you want to explicitly say so, using "n/a" and de-escalating this from an error to a warning would be ideal.

**Comment by chrisgorgo** [comment]
Why not skipping the key completely? Isn't this equivalent to missing value?
