### ISSUE TITLE
PRs from forks don't trigger builds.

### ISSUE THREAD

**Issue by constellates** [bids-standard/legacy-validator#267]
As discovered in PR #266, PRs from forks are not triggering CI test builds and there are security issues to figure out to solve this issue.  

Here's documentation on enabled forked PR builds from circle-ci https://circleci.com/docs/1.0/fork-pr-builds/ 

The gist of the issue though is we have to store credentials for publishing to NPM and allowing forked builds means anyone could create a fork and PR and change the circle.yml commands to use those credentials. 

CircleCI offers more secure methods of storing credentials for specific things like ssh keys, aws credentials etc, but nothing I see that would support the NPM credentials.

I think a good option would be to change the build flow so only new tags trigger deployments that publish to npm. This would at least give us the option of reverting PRs from master before they get published.

**Comment by chrisgorgo** [comment]
What's wrong with building forks without passing secrets?

![image](https://cloud.githubusercontent.com/assets/238759/23809431/8b106d9a-0582-11e7-8c09-19b0f9b0581d.png)

**Comment by constellates** [comment]
Oh. That looks perfect. I misread the documentation thinking UI defined environment variables were not protected from forked builds as secrets. I'll try enabling this now.

**Comment by constellates** [comment]
Ok. This is working, but won't trigger tests on the pre-existing forked PR.
