### ISSUE TITLE
IntendedFor missing file error not specific to number of missing files

### ISSUE THREAD

**Issue by jbwexler** [bids-standard/legacy-validator#269]
If one of the files listed in the IntendedFor field does not exist, the error raised states that all of the files listed don't exist. Example:

/sub-010029/ses-02/fmap/sub-010029_ses-02_acq-GEfmap_run-02_phasediff.nii.gz
			'IntendedFor' property of this fieldmap ('ses-02/func/sub-010029_ses-02_task-rest_acq-AP_run-02_bold.nii.gz,ses-02/func/sub-010029_ses-02_task-rest_acq-PA_run-02_bold.nii.gz') does not point to an existing file. Please mind that this value should not include subject level directory ('/sub-010029/').

In this example, 'ses-02/func/sub-010029_ses-02_task-rest_acq-AP_run-02_bold.nii.gz' actually does exists and 'ses-02/func/sub-010029_ses-02_task-rest_acq-PA_run-02_bold.nii.gz' does not. However, the error states that both don't exist.

**Comment by suyashdb** [comment]
@jbwexler I tried recreating the error with latest version on bids but failed.. however was able to generate error using bids-validator installed on TACC.
Can you install latest version and check if missing IntendedFor file error is generated..?   
Looks like newer version is not generating the error wheee intended for files are missing.
