### ISSUE TITLE
please make possible with ignoredFiles to ignore entire subdirectory structure

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#293]
ATM, after not giving up initially I already breeded all kinds of possible globs for previous layouts:

```shell
$ cat ~/heudiconv/heuristics/dbic_bids_validator.cfg
{
    "ignore": [
       "TOTAL_READOUT_TIME_NOT_DEFINED"
    ],
    "warn": [],
    "error": [],
    "ignoredFiles": [
          "/.heudiconv/*", "/.heudiconv/*/*", "/.heudiconv/*/*/*", "/.heudiconv/*/*/*/*",  
          "/.heudiconv/.git*", "/.heudiconv/.git/*",
          "/.git*", 
          "/.datalad/*", "/.datalad/.*", 
          "/.*/.datalad/*", "/.*/.datalad/.*", 
          "/sub*/ses*/*/*__dup*", "/sub*/*/*__dup*"
    ]

$ /usr/bin/bids-validator -c ~/heudiconv/heuristics/dbic_bids_validator.cfg  $PWD
        1: This file is not part of the BIDS specification, make sure it isn't included in the dataset by accident. Data derivatives (processed data) should be placed in /derivatives folder. (code: 1 - NOT_INCLUDED)
                /.heudiconv/.git/annex/index
                        Evidence: index
                /.heudiconv/.git/annex/index.lck
                        Evidence: index.lck
                /.heudiconv/.git/annex/journal.lck
                        Evidence: journal.lck
                /.heudiconv/.git/annex/mergedrefs
                        Evidence: mergedrefs
                /.heudiconv/.git/annex/objects/09/5W/MD5E-s33197--56896ef4c721ba81607438c44877d6d2.py/MD5E-s33197--56896ef4c721ba81607438c44877d6d2.py
                        Evidence: MD5E-s33197--56896ef4c721ba81607438c44877d6d2.py

```
but pretty much I now need to define some quite obnoxiously deep globs to ignore any file under .git .datalad subdirectories. Also making directories starting with `.` even so special.  I am not sure what would be the easiest in JS/nodejs , but if it could be some kind of a regex, or smarter glob (e.g. with `**` to signal any depth), or just have trailing `/` in the path to signal to ignore anything under that directory (and below) would be super handy ;)

FWIW -- my version is 0.21.3

**Comment by chrisgorgo** [comment]
The '**' syntax is implemented. See #349.

**Comment by yarikoptic** [comment]
Is that the power of JS to pick up changes for mere documentation description (which is what #349 about)? ;)  I just wanted to see how it is done in JS but can't seems to find any relevant recent commit.. but even with 0.23.2 it seems to do the `**` matching, so I guess it was always working and just not documented?

The only gotcha is that it doesn't include directories starting with `.`.  So, to e.g. ignore `.heudiconv` git submodule I need to have 3 lines:
```
          "/.heudiconv/**",  # all regular subdirs
          "/.heudiconv/.git*",  # all the .gitignore etc files
          "/.heudiconv/.git/**",  # everything under .git which hopefully would never have . files
```
