### ISSUE TITLE
[begging] please strip leading '/' from the paths reported

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#294]
I think I have whined before but because it is a constant annoyance I guess I might keep coming.

Most frequent pattern for use of the validator is to run it, quickly cut paste the path into clipboard and paste into the command to view or edit a file. Linux terminals are super good at selecting contiguous portions of text, such as paths, so usually it is a quick double click on a path to select it all.  BUT with bids-validator it would not work since it uses leading `/` in the paths as they are from some kind of root.

Could
`/sub-sid000021/ses-actions1/sub-sid000021_ses-actions1_scans.tsv`
become a 
`sub-sid000021/ses-actions1/sub-sid000021_ses-actions1_scans.tsv`
or
`./sub-sid000021/ses-actions1/sub-sid000021_ses-actions1_scans.tsv`
the world would become such a better place!

validator 0.21.3

**Comment by suyashdb** [comment]
@yarikoptic  even i thought of adding it at some point as it helps me in curation. :)

Well i am gonna submit a PR for review to share my efforts in making "world a better place".
