### ISSUE TITLE
RF: Check file integrity for Nifti gzipped files

### ISSUE THREAD

**Issue by oesteban** [bids-standard/legacy-validator#297]
I wonder if it would be feasible to check the CRC to detect corrupted files when they are using compressed formats.

**Comment by chrisgorgo** [comment]
This would be a computationally expensive check since it would require reading contents of all files.

**Comment by chrisgorgo** [comment]
Options:
- make it optional and turn it off by default
- add progress bar

**Comment by oesteban** [comment]
Yep, I was to suggest making it optional.

In any case, I think it is still relevant, since the cost of fixing a corrupt file in a database outweighs the computational cost.

Besides, has the validator stopped opening all files to check some headers?

**Comment by chrisgorgo** [comment]
It only checks the headers without actually reading the data which makes it much faster.

**Comment by oesteban** [comment]
I see, thanks

**Comment by effigies** [comment]
Out of scope for validator. Data integrity checks are worth a separate tool like https://github.com/OpenNeuroOrg/miniqc
