### ISSUE TITLE
files with sub/ses keyvalue in filename at higher level should raise error 

### ISSUE THREAD

**Issue by suyashdb** [bids-standard/legacy-validator#298]
Case 1: Legal
`sub-03_task-dis_bold.json` at subject level eg: `ds500/sub-03/func/sub-03_task-dis_bold.json`  

case 2: Illegal
 json file(`sub-03_task-dis_bold.json`) is placed on top level directory  @`ds500/sub-03_task-dis_bold.json`

In case 2 validator should raise error but the current version does not.

**Comment by rwblair** [comment]
These rules are now enforced in the top_level_rules.json regex.
