### ISSUE TITLE
Multiecho files should have one corresponding physio and tsv files

### ISSUE THREAD

**Issue by suyashdb** [bids-standard/legacy-validator#303]
For eg: 
```
sub-01_task-cuedSGT_run-01_events.tsv
sub-01_task-cuedSGT_run-01_physio.tsv
sub-01_task-cuedSGT_run-01_echo-1_bold.nii.gz
sub-01_task-cuedSGT_run-01_echo-2_bold.nii.gz
sub-01_task-cuedSGT_run-01_echo-3_bold.nii.gz

```

I am not sure if this should be applicable to json files as well?

**Comment by chrisgorgo** [comment]
JSON should be set for individual echos since each echo will have different "EchoTime" value.

**Comment by rwblair** [comment]
Currently events files with 'echo-' matches will still validate when they shouldn't. To fix this events.tsv and physio.tsv will need to be moved from the 'func' regex in bids-validator/bids_validator/rules/file_level_rules.json into their own new dictionary with the same regex except without the echo rules.

**Comment by effigies** [comment]
This seems to have gotten done at some point.
