### ISSUE TITLE
Missing onset/duration column in beh events files produces error rather than warning

### ISSUE THREAD

**Issue by jbwexler** [bids-standard/legacy-validator#305]
Currently, if a 'beh' events file does not contain an onset and/or duration column, an error is produced. However, given that 'beh' events did not take place within a scanner (by definition), it is fairly common for researchers not to record onsets and durations for them. Thus, I think 'beh' events files without onsets and/or durations should be BIDS-compatible and leaving them out should produce a warning rather than an error.

**Comment by chrisgorgo** [comment]
I think this would need to be clarified in the spec first. Could you bring
this up on the mailing list?

**Comment by jbwexler** [comment]
True, I'll do that

**Comment by SetCodesToFire** [comment]
Is this issue still open to work on?

**Comment by jbwexler** [comment]
I brought up the issue on the mailing list and the solution we decided on was to add this line to the Behavioral Experiments section: 
"Additionally, events files that do not include the mandatory ‘onset’ and ‘duration’ columns can still be included, but should be labelled _beh.tsv rather than _events.tsv."

This is still only in the draft, but it will be included in the next version of BIDS. At that point, the BIDS-validator will need to be updated to recognize a sub-\*/beh/\*_beh.tsv file. This file should have the same requirements as an *_events.tsv file, with the exception that it does not require onset and duration columns. In fact, maybe it should produce an error or warning if it does include onsets and/or duration columns? I'm not really sure.

Feel free to help with this!

**Comment by rwblair** [comment]
sub-*/beh/*_beh.tsv are now recognized and onset and duration checks don't occur for them. There are still issues with beh.tsv validation. Opened new ticket about that here bids-standard/bids-validator#62
