### ISSUE TITLE
validator cmd tool generating error but http://incf.github.io/bids-validator/ genrates warning 

### ISSUE THREAD

**Issue by suyashdb** [bids-standard/legacy-validator#327]
In a following case when task label is missing, an error is generated in command line tool but when same dataset is validated using validator io tool, warning is generated for the same error. 

```
1: Sub label contain an Illegal Character hyphen or underscore. Please edit the filename as per BIDS spec. (code: 62 - SUBJECT_VALUE_CONTAINS_ILLEGAL_CHARECTER)
       		./sub-01/func/sub-01_rest_bold.nii.gz
       			Evidence: sub name contains illegal character:/sub-01/func/sub-01_rest_bold.nii.gz
```

<img width="1249" alt="screen shot 2017-10-09 at 3 15 33 pm" src="https://user-images.githubusercontent.com/11152799/31360769-c127faae-ad04-11e7-8f07-6ceb9fdd6740.png">

**Comment by chrisgorgo** [comment]
This looks like a screenshot of openneuro which uses an older version than
http://incf.github.io/bids-validator/

**Comment by suyashdb** [comment]
@chrisfilo 
Sorry my bad. shared incorrect screen shot. Even in case of INCF validator.io, i am getting warning instead of error. Not sure if i am doing anything incorrect. 

<img width="1250" alt="screen shot 2017-10-09 at 3 27 26 pm" src="https://user-images.githubusercontent.com/11152799/31361168-d4e02dc6-ad06-11e7-87b1-103ee4acf742.png">

**Comment by chrisgorgo** [comment]
I just made a new release - could you try now?

**Comment by suyashdb** [comment]
@chrisfilo: oddly enough, http://incf.github.io/bids-validator/  is taking long long time to validate.. Even after 18 mins now its has not run with validating wheel stills revolving.

**Comment by chrisgorgo** [comment]
Check the JS console in developer tools for error.

Do you get any errors on this dataset using latest master branch?

**Comment by chrisgorgo** [comment]
I fixed the problem with the web version of the validator. The problem was due to two things:

1) using .relativePath instead of utils.files.relativePath()
2) using for loop instead of eachOfAsync

You should try the web version of the validator again.

**Comment by suyashdb** [comment]
Thanks!
I am not getting any error now. Will keep in mind about using utils.files.relativePath() and eachOfAsync. 
Do you know any way of checking if my new code/PR is working on browser or not before merging with `INCF:master.`?

**Comment by chrisgorgo** [comment]
This is ow you can test the browser version locally https://github.com/INCF/bids-validator#running-locally-in-a-browser.

Regarding this issue - shouldn't you be getting an error regarding subject label in both web and command line version of the validator. So if we are not getting it in both there still might be a problem?
