### ISSUE TITLE
Check if there is a corresponding _events.tsv file for each _bold.nii.gz file

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#33]
One needs to account for hierarchies (done events file for the whole dataset, one events file for each subject, one events file for each session, one events file for each run). If file does not exist a warning should be thrown - unless word "rest" (any caps) is present in the task name.

**Comment by constellates** [comment]
With the exception of the "rest" keyword does the hierarchy logic work the same with these events files as it does with the JSON sidecars. I'm planning on reusing the logic that determines if those exist. And can you give me an example of how the word "rest" might appear in a taskname.

**Comment by chrisgorgo** [comment]
1) yes the hierarchy logic is the same as for json sidecars files
2) you should look for "rest" in the label part of "_task-<label>_"

Let me know if this helps.
