### ISSUE TITLE
validator doesn't recognize certain top-level json files as bids-compatible

### ISSUE THREAD

**Issue by jbwexler** [bids-standard/legacy-validator#333]
I haven't tested to see exactly which types of filenames generate this bug, but here is an example:
	
1: Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you can ignore this warning. Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
		./acq-epi_T1w.json
			Evidence: acq-epi_T1w.json
		./acq-mprage_T1w.json
			Evidence: acq-mprage_T1w.json

As far as I can tell, these are BIDS-compatible filenames but aren't being recognized as such.

**Comment by chrisgorgo** [comment]
I could replicate this. This should be easy to fix - the problem lies in this regualr expression: https://github.com/INCF/bids-validator/blob/master/utils/type.js#L45

It's a perfect introductory contribution - @jbwexler could you take this on and submit a PR (in a timely fashion?).

**Comment by suyashdb** [comment]
@jbwexler To start with i have already started playing with it.
https://regex101.com/r/QO13uM/1
You can use above regex.

**Comment by jbwexler** [comment]
Thanks, yes I will start working on this soon
