### ISSUE TITLE
bids-validator doesn't check for presence of dataset_description.json

### ISSUE THREAD

**Issue by jbwexler** [bids-standard/legacy-validator#338]
This PR looks like it was intended to add this feature: https://github.com/INCF/bids-validator/pull/289
But as far as I can tell, the current version does not raise an error or warning if dataset_description.json is missing.

**Comment by chrisgorgo** [comment]
It was accidentally removed by @suyashdb with this commit https://github.com/INCF/bids-validator/commit/7e79abfcdaeb6dca88a33cdaa36a4026ba001362#diff-11d6e4dee74f8b1811237b320d139186

@suyashdb could you send a quick PR reintroducing this check?
