### ISSUE TITLE
Distinguish ERRORS and WARNINGS with text in addition to color(command line version only)

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#347]
Right now if a dataset only generates warnings users can get the impression that they are errors since nothing other than yellow color on the console indicates that they are only errors. We should explicitly write if something is a warning or an error.

**Comment by SetCodesToFire** [comment]
Hi @chrisfilo , 
PR added for this issue. Added ERR for printing errors and WARN for Warnings

-R

**Comment by SetCodesToFire** [comment]
@chrisfilo  can you tell me what label does config issues should be attached with. I did them with the ERR only

**Comment by chrisgorgo** [comment]
See #421
