### ISSUE TITLE
Ignore files and folders starting with '.' in 

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#348]
It will reduce the noise in the NOT_INCLUDED warning.

@yarikoptic and @satra - what do you think?

Related to #293 and https://github.com/nipy/heudiconv/issues/106

**Comment by satra** [comment]
@chrisfilo - isn't @mgxd suggestion of generating a bids config file sufficient to handle this?

**Comment by chrisgorgo** [comment]
Yes it would, but it requires directing heudiconv users to perform a custom step which is not ideal. I would like the whole process to be as straightforward as possible for users. 

There are also other '.' files such as .DS_store on mac.

Do you see a substantial downside of ignoring '.' files in the validator?

**Comment by satra** [comment]
@chrisfilo - it wouldn't require heudiconv users to do a custom step. whenever they use `-b`, a bids config file will be created with the hidden files ignored. i'm assuming this gets used automatically by the validator.

regarding hidden files, perhaps bids will use hidden files in the future, who knows !?!

to generalize this a bit more, one can consider that we use a `.bidsignore` file, but i see the config option as being sufficient for now.

**Comment by chrisgorgo** [comment]
The config file is provided as command line option - it is not read automatically from the validated dataset (the config files were meant to be reused across datasets - for example by a repository that has specific, more strict metadata requirements). This means users will have to provide this command line option and point to the config file generated by heudiconv. It is also not possible to provide config files for the online version of the validator.

If BIDS will start using '.' files in the future we can modify the validator.

The concept of a `.bidsignore` file is definitely appealing and worth implementing at some point. However, changing the defaults might improve the user experience (especially for people with less expertise).

**Comment by chrisgorgo** [comment]
Actually in theory this test should already ignore '.git' subdirectories.
https://github.com/INCF/bids-validator/blob/c82f0064ad95c8fee5a3f42776d590444acbcf48/utils/type.js#L63

called in:

https://github.com/INCF/bids-validator/blob/c82f0064ad95c8fee5a3f42776d590444acbcf48/validators/bids.js#L219

**Comment by yarikoptic** [comment]
that one seems to be ignoring `.git` only on the top level. (what about any subdirectory being a git submodule?)
`.bidsignore` indeed sounds handy... what syntax would it be? ;)

**Comment by chrisgorgo** [comment]
It ignores `/.git` and all of its subdirectories. We would have to add some thing for submodules (again I think ignoring all `.` and their subdirectories at any level would be most user friendly)

`.bidsignore` should probably follow the same syntax as `.gitignore`. It would be cool, but I doubt it will get much use outside power users.

**Comment by chrisgorgo** [comment]
hidden ('.') files are now ignored reducing the noise #368
