### ISSUE TITLE
Warnings of type "Files with such naming scheme are not part of BIDS specification." do not list full path

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#357]
It's impossible to find the file in question
![image](https://user-images.githubusercontent.com/238759/32295970-166e2532-bf08-11e7-92a0-7fab392b9d5e.png)

**Comment by SetCodesToFire** [comment]
Hi @chrisfilo , can you elaborate on this?

**Comment by chrisgorgo** [comment]
location should be listed for those issues, like here
![image](https://user-images.githubusercontent.com/238759/36574163-2646fa34-17f9-11e8-87e6-82056c0dc746.png)

**Comment by SetCodesToFire** [comment]
So, for every method from validator/bids.js that is returning an issue to the cli.js should we just carefully detect which method to return the file-path and debug this issue.

Is my understanding right?

**Comment by chrisgorgo** [comment]
No - this seems to be only specific to issue class NOT_INCLUDED. It's also
been observed in the web version of the validator so cli.js might have
little to do with it.

Best,
Chris

**Comment by SetCodesToFire** [comment]
Okay. 😄 Thanks

**Comment by SetCodesToFire** [comment]
Hi @chrisfilo , 
I have fixed this issue.. Please check by replicating what caused this issue. 
Thanks

**Comment by parulsethi** [comment]
Hi @chrisfilo, [.DS_Store](https://en.wikipedia.org/wiki/.DS_Store) file type is a hidden file in macOS containing the folder's meta data. You can make the hidden files visible in macOS by running following command in terminal:
```
defaults write com.apple.finder AppleShowAllFiles -bool true
killall Finder
```
Then open the data folder in Mac's Finder app and you will see all hidden files including .DS_Store in it.

To hide them back, run:
```
defaults write com.apple.finder AppleShowAllFiles -bool false
killall Finder
```

**Comment by parulsethi** [comment]
Sorry for misinterpreting the issue, I just saw that https://github.com/INCF/bids-validator/pull/368 already resolves this and the actual issue is being addressed in https://github.com/INCF/bids-validator/pull/416
