### ISSUE TITLE
Raise an error if a JSON sidecar is found with no corresponding data file

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#358]
For example:
![image](https://user-images.githubusercontent.com/238759/32298383-6ec1aad6-bf0f-11e7-84b4-43e2cbc32b86.png)
https://openneuro.org/datasets/ds001110/versions/00001

**Comment by chrisgorgo** [comment]
Another example:
![image](https://user-images.githubusercontent.com/238759/40216661-a9a88b2e-5a2d-11e8-921d-b073eb5d2d05.png)

**Comment by bGrass** [comment]
This has been merged but has been superseded by #530
