### ISSUE TITLE
Inconsistent scanning parameter warning includes "undefined" string

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#360]
![image](https://user-images.githubusercontent.com/238759/32299010-3f41d34c-bf11-11e7-9fa2-047023171434.png)

**Comment by chrisgorgo** [comment]
https://openneuro.org/datasets/ds001128/versions/00002

**Comment by SetCodesToFire** [comment]
Can this be ellaborated more please. What is the error code?

**Comment by rwblair** [comment]
Tested in latest web validator and was unable to see 'undefined'.
