### ISSUE TITLE
fmap related json fields are checked when fmap files dont exist 

### ISSUE THREAD

**Issue by suyashdb** [bids-standard/legacy-validator#362]
Currently,  the implementation of the nii.js is such that, error codes 6,7,8, 9 are generated for all niftis. Latter these issues are filtered out when `fmap/` doesnt exist for that subject. 

However, when we raise these warnings to errors using config file, these errors doesn't get filtered in case the dataset does not contain fmap.

To solve this issue, may be it's a better option [not to generate](https://github.com/INCF/bids-validator/blob/master/validators/nii.js#L98) those warnings/error in cases where fmap doesn't exist.

**Comment by chrisgorgo** [comment]
Try (instead) modyfying this check https://github.com/INCF/bids-validator/blob/300c6437bf1a19d505b7ce15eb9f1e5c820e2b69/utils/issues/index.js#L32 too look for errors in addition to warnings.
