### ISSUE TITLE
inconsistent naming for top-level dwi json

### ISSUE THREAD

**Issue by jokedurnez** [bids-standard/legacy-validator#364]
There is an inconsistency on the naming of the jsons for dwi. 
1st warning: unknown filename `./acq-dir90LR_dwi.json`
2nd warning: suggested filename: `/acq-dir90LR_dwi.json`

I used version `0.23.11`

       1: Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you can ignore this warning. Please note that derive d (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
                ./acq-dir90LR_dwi.json
  
        2: You should define 'EchoTime' for this file. If you don't provide this information field map correction will not be possible. (code: 6 - ECHO_TIME_NOT_DEFINED)
                ./sub-S0509PIJ/dwi/sub-S0509PIJ_acq-dir90LR_run-1_dwi.nii.gz
                        You should define 'EchoTime' for this file. If you don't provide this information field map correction will not be possible. 
    It can be included one of the following locations: /acq-dir90LR_dwi.json, /sub-S0509PIJ/sub-S0509PIJ_acq-dir90LR_dwi.json, /sub-S0509PIJ/dwi/sub-S0509PIJ_acq-dir90LR_run-1_dwi.json

**Comment by jokedurnez** [comment]
Probably related to https://github.com/INCF/bids-validator/issues/333

**Comment by chrisgorgo** [comment]
Thanks for reporting it's a duplicate of #333.
