### ISSUE TITLE
[idea] error and warning codes

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#37]
Right now a dataset that is very close to being BIDS compatible can generate a lot of errors and warnings (imaging RepetitionTime was missing - it takes one line on the top level to fix it but validator will show as many errors as there are bold files). This can be ver off-putting and overwhelming from the user perspective. One solution would be to group errors and warnings of the same type in the UI. To allow that we can add error/warning codes (as one more field in the error class). 

Let me know what do you think.

**Comment by constellates** [comment]
The idea makes sense and should be very quick to implement on the validator side. I could also see how the codes could function in more automated situations like http status codes. I'm not yet fully picturing how we would design the semantics of the codes and how we would change the UI based on the codes. Do you have any ideas at this point about what codes might refer to?

Another way we can tackle the same problem is by making some of the errors more dynamic. In the same example you pointed out we could change this

```
REASON:
You should should define 'EchoTime' for this file. If you don't provide this information field map correction will not be possible. It can be included one of the following locations: /sub-04/func/sub-04_task-balloonanalogrisktask_run-01_bold.json, /sub-04/sub-04_task-balloonanalogrisktask_bold.json, /task-balloonanalogrisktask_bold.json

REASON:
You should should define 'PhaseEncodingDirection' for this file. If you don't provide this information field map correction will not be possible. It can be included one of the following locations: /sub-04/func/sub-04_task-balloonanalogrisktask_run-01_bold.json, /sub-04/sub-04_task-balloonanalogrisktask_bold.json, /task-balloonanalogrisktask_bold.json

REASON:
You should should define 'EffectiveEchoSpacing' for this file. If you don't provide this information field map correction will not be possible. It can be included one of the following locations: /sub-04/func/sub-04_task-balloonanalogrisktask_run-01_bold.json, /sub-04/sub-04_task-balloonanalogrisktask_bold.json, /task-balloonanalogrisktask_bold.json

REASON:
You should should define 'SliceTiming' for this file. If you don't provide this information slice time correction will not be possible. It can be included one of the following locations: /sub-04/func/sub-04_task-balloonanalogrisktask_run-01_bold.json, /sub-04/sub-04_task-balloonanalogrisktask_bold.json, /task-balloonanalogrisktask_bold.json

REASON:
You should should define 'SliceEncodingDirection' for this file. If you don't provide this information slice time correction will not be possible. It can be included one of the following locations: /sub-04/func/sub-04_task-balloonanalogrisktask_run-01_bold.json, /sub-04/sub-04_task-balloonanalogrisktask_bold.json, /task-balloonanalogrisktask_bold.json
```

to

```
REASON:
You should should define 'EchoTime', 'PhaseEncodingDirection', 'EffectiveEchoSpacing', 'SliceTiming' and 'SliceEncodingDirection' for this file. If you don't provide this information slice time correction will not be possible. It can be included one of the following locations: /sub-04/func/sub-04_task-balloonanalogrisktask_run-01_bold.json, /sub-04/sub-04_task-balloonanalogrisktask_bold.json, /task-balloonanalogrisktask_bold.json
```

And populate that first sentence based on which values are missing. There are likely other areas where we could make similar changes.

**Comment by chrisgorgo** [comment]
Yes that would also be useful. Let's consider a situation when a dataset has 20 subjects each has 2 bold files (total 40 bold files). Let's say 'SliceTiming' and 'SliceEncodingDirection' are missing for all files. Without grouping we produce 80 warnings. With error code grouping we produce 2 groups of warnings. With "potential future analysis limitation" grouping we get 40 groups of warnings. If we combine the two strategies we get only one group of warnings.

Things might get a bit more complicated when doing "potential future analysis limitation" grouping. Cases when only some subjects have missing parts of parameters (for example "SliceTiming" but not "SliceEncodingDirection"). For this reason I would start with error codes first. We can define grouping of error codes later.

In terms of what the codes might look like - they can be arbitrary numbers or (preferably) strings (for example ERR_REPETITION_TIME_MISSING). Let me know what do you think.

**Comment by constellates** [comment]
Yea that makes sense. I'm beginning to wonder if we want to make the error type the first level object of the validator results if that's going to be the most useful way to read the results in general. So where we currently have a return that looks something like this

```
{
    errors: [
        {
            filename: 'ds001/sub-01/ses-04/func/sub-01_T1w.nii.gz',
            issues: [
                {
                    reason: "this file isn't allowed"
                }
            ]
        },
        {
            filename: 'ds001/sub-01/ses-04/func/sub-02_T1w.nii.gz',
            issues: [
                {
                    reason: "this file isn't allowed"
                }
            ]
        }
    ],
    warnings: [
        {
            filename: 'ds001/sub-01/ses-04/func/sub-04_T1w.nii.gz',
            issues: [
                {
                    reason: 'repetition time is invalid'
                }
            ]
        },
        {
            filename: 'ds001/sub-01/ses-04/func/sub-05_T1w.nii.gz',
            issues: [
                {
                    reason: 'repetition time is invalid'
                }
            ]
        }
    ]
}
```

We could switch to a format more like this.

```
{
    errors: [
        {
            reason: "this file isn't allowed",
            files: [
                'ds001/sub-01/ses-04/func/sub-01_T1w.nii.gz',
                'ds001/sub-01/ses-04/func/sub-02_T1w.nii.gz'
            ]
        }
    ],
    issues: [
        {
            reason: 'repetition time is invalid',
            files: [
                'ds001/sub-01/ses-04/func/sub-04_T1w.nii.gz',
                'ds001/sub-01/ses-04/func/sub-05_T1w.nii.gz'
            ]
        }
    ]
}
```

This would save us re-mapping the results in both the CLI and web app. We could accomplish this without codes but codes could be helpful for keeping things organized and we could have a master index of possible errors and warnings. I would vote for number based codes. Strings can be difficult to keep standardized and numbers would give us the ability to create some semantics in the future for classes of errors and warnings (like how each hundred value in http codes carries meaning).

I think I have enough info to start working through this. Let me know if you have more thoughts or concerns.
