### ISSUE TITLE
unable to read sample data

### ISSUE THREAD

**Issue by takua624** [bids-standard/legacy-validator#377]
Hi, I tried to apply the validator on the reduced-size sample dataset to understand how it works. But the validator can't work with 0-size data and yields "We were unable to read this file" error. Is it possible for you to provide a sample dataset with small, but non-zero data, so that the validator can read?

Thanks!

**Comment by chrisgorgo** [comment]
Try --ignoreNiftiHeaders flag on the command line or use full datasets.

**Comment by chrisgorgo** [comment]
You can also use any dataset from http://OpenfMRI.org as an example.
