### ISSUE TITLE
Deploy web version of the validator in github gh-pages

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#38]
If we deploy (in an automated way through circleCI) the web version of the BIDS validator be able to quickly test it outside of other projects (for example CRN). This way we will be also able to provide validation service to people who do not (yet!) intend to share their data.

The user interface can be very basic since the main goal is to expose/test the underlying JS library.

**Comment by constellates** [comment]
Here's the start of this web demo of the validator. Greg hasn't had a chance to do any styling cleanup so there are a handful of visual issues. Once we get those fixed and the repository ownership stuff figured out we can design an auto deployment strategy to keep it up to date with the validator.
https://github.com/Squishymedia/bids-demo

**Comment by chrisgorgo** [comment]
Is this finished? I see some CircleCI authored updates in gh-pages, but I could not find any deployment code triggered when master branch is updated.

**Comment by constellates** [comment]
This isn't quite finished. I started testing the deployment scripting on the gh-pages branch. Just a few more things to wrap up.

**Comment by chrisgorgo** [comment]
Cool! thanks for the update!

**Comment by constellates** [comment]
Auto deployment is up and running. This will run on any change to master but changes will only get incorporated into the gh-pages if npm is updated first. So you will only see changes on there if you bump the version number on a commit/pull-request.

**Comment by chrisgorgo** [comment]
Excellent! Thanks!
