### ISSUE TITLE
Handle non-existent directiories

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#383]
```
> const validator = require('./index.js')
undefined
> validator.BIDS('./does-not-exist', {}, () => {})
Error: ENOENT: no such file or directory, scandir './does-not-exist'
    at Error (native)
    at Object.fs.readdirSync (fs.js:953:18)
    at getFiles (/home/nell/Git/crn/bids-validator/utils/files.js:191:20)
    at preprocessNode (/home/nell/Git/crn/bids-validator/utils/files.js:183:12)
    at callbackWrapper (/home/nell/Git/crn/bids-validator/utils/files.js:141:25)
    at getBIDSIgnore (/home/nell/Git/crn/bids-validator/utils/files.js:120:9)
    at Object.readDir (/home/nell/Git/crn/bids-validator/utils/files.js:151:5)
    at /home/nell/Git/crn/bids-validator/validators/bids.js:42:29
    at /home/nell/Git/crn/bids-validator/utils/options.js:20:17
    at /home/nell/Git/crn/bids-validator/utils/options.js:63:25
```

https://github.com/OpenNeuroOrg/openneuro/issues/99#issuecomment-355627085

**Comment by SetCodesToFire** [comment]
I solved this issue, added a new issue in the list.js and done some fs check in the validator/bids.js


![correct](https://user-images.githubusercontent.com/25459509/36394328-c04f1958-15d9-11e8-8b80-044c9082c9ab.PNG)

**Comment by SetCodesToFire** [comment]
Hi I solved this issue


![correct](https://user-images.githubusercontent.com/25459509/36395138-844bd938-15dd-11e8-91e5-8e8d7d38b618.PNG)

**Comment by SetCodesToFire** [comment]
Hi @chrisfilo ,
Thank you so much for merging the PR, you can close this issue now 😄

**Comment by chrisgorgo** [comment]
See #407

**Comment by SetCodesToFire** [comment]
@chrisfilo Should we re-merge the functionality 😄 as the #406 has problem with the dataset and not the validator.

**Comment by chrisgorgo** [comment]
No - see https://github.com/INCF/bids-validator/issues/406#issuecomment-367896867

**Comment by SetCodesToFire** [comment]
There is only one way that could help adding this functionality. To have asynchronous calls to a function that should check if the directory exists. But that would too throw the error stack before checking all the directories completely.
How to solve this issue? There is a big trade-off between increased time and adding this feature.

**Comment by effigies** [comment]
This got done at some point:

```
❯ /usr/bin/bids-validator /does-not-exist
/does-not-exist does not exist or is inaccessible
bids-validator@1.14.6
```
