### ISSUE TITLE
Add warning when metadata required by BIDS2NDA are missing

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#386]
Pinging @yarikoptic, @mgxd, and @mtnhuck for comments.

**Comment by yarikoptic** [comment]
sure, especially if a field is required.  If optional - not sure if worth a warning, just INFO would be enough.  OR could be ERROR for required, WARNING for optional

**Comment by SetCodesToFire** [comment]
Metadata required by the BIDS2NDA converter : 



![metadata](https://user-images.githubusercontent.com/25459509/36625443-873c8c9e-1945-11e8-85a9-a84b6c59b102.PNG)

**Comment by yarikoptic** [comment]
I wonder what other "popular" schemas besides image03 are used... May be abcd study used by other studies? Might be worth checking with NDA folks to get a better sense what fields might be needed, or may be bids validator could even get an option to validate for specific NDA schema (would require "integration" of that information with bids2nda)

**Comment by effigies** [comment]
All required fields in that screenshot are required.
