### ISSUE TITLE
T2star missing in anatSuffixes

### ISSUE THREAD

**Issue by naveau** [bids-standard/legacy-validator#388]
In the BIDS spec 1.0.2 the `T2star` modality is defined to label high resolution T2* images.
This suffix is not in the `anatSuffixes` list.

https://github.com/INCF/bids-validator/blob/2849aa65885da5994b122852dfde5efd46803a92/utils/type.js#L8

I didn't find any related discussion in the past issues, is there something I missed ?

**Comment by naveau** [comment]
~~Same question about `angio`.~~

Sorry for the noise

**Comment by chrisgorgo** [comment]
Thanks for reporting.

Seems like `angio` is listed, but `T2star` is not. Would you like to take a stab at fixing this (it should be very easy)?
