### ISSUE TITLE
Error when _events.tsv files have only two columns

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#392]
Rare but valid `_events.tsv` files with only two columns
```
onset	duration
1	3
2	3
```
lead to an error

```
        1: Second column of the events file must be named 'duration' (code: 21 - EVENTS_COLUMN_DURATION)
                ./sub-CTS202/func/sub-CTS202_task-restbaseline_events.tsv
                        @ line: 1 character: 6
                        Evidence: onset,duration
```

**Comment by SetCodesToFire** [comment]
Hi @chrisfilo ,
I tried to replicate this issue and I am getting another error which is shown here 

![tsv](https://user-images.githubusercontent.com/25459509/36594073-ad036cf0-18c2-11e8-9b7b-602fab02b8ec.PNG)

I tried to debug this but found nothing. Can you identify the mistake?

**Comment by SetCodesToFire** [comment]
where as trying to do the same function call for BIDS, NIFTI, JSON are working
