### ISSUE TITLE
Bad minimal NIFTI size check

### ISSUE THREAD

**Issue by effigies** [bids-standard/legacy-validator#394]
For INCF/BIDS-examples#48, I've created some minimal NIFTI files, which are just the header (+ 4 pad bytes), and gzipped. I'm getting the following error when validating: `This file is too small to contain the minimal NIfTI header.`

I suspect it may be checking for a 352 byte minimum for the file itself, not the unzipped contents.

**Comment by chrisgorgo** [comment]
It's hard to figure out what should be the size of a compressed header
(since different compression levels could be used). This seems like an edge
case - would you mind using uncompressed files in your example?

Best,
Chris

**Comment by effigies** [comment]
Sure.
