### ISSUE TITLE
Issue a warning if tsv files do not feature data dictionaries

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#398]
Additionally issue a warning if data dictionaries are incomplete.

**Comment by SetCodesToFire** [comment]
@chrisfilo I want to help in this. Guide me in the right direction. 🚶

**Comment by chrisgorgo** [comment]
Great! Are you familiar with the BIDS standard?

Best,
Chris

**Comment by SetCodesToFire** [comment]
No @chrisfilo , but is it some contribution guide? If it isn't then please tell me about it. I will be happy to study.
The present title feels me highly motivating as it seems like there is a tsv file call, if it doesn't contain (return) a data dictionary then i'll have to add a warning. Am i going wrong?

**Comment by chrisgorgo** [comment]
Great - I recommend the following:
1. Read the BIDS website http://bids.neuroinformatics.io
2. Read the BIDS paper https://www.nature.com/articles/sdata201644
3. Read the BIDS spec https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit section 4.2 is especially relevant to this issue.

**Comment by SetCodesToFire** [comment]
Hi @chrisfilo 

Thanks for the reading material. I had an overview of most of the things and got a good grasp about the Brain Imaging Data Structure. ☕️ I had a great time reading about such a fascinating topic. Also how BIDS solved the traditional approaches as well as how the upcoming versions can touch every part of the scanned images. 👀 


I also looked at the code in the repository and found the very interesting well separated issue in the utils. Could I now know that how do you want to get the warning part done.

I saw the file validators/tsv.js where line 28 th of the code sterilized empty .tsv file but it then just took the control out from the function. Does this is to be implemented ? A issue call here and a new issue code. Which then is to be included in the utils.

Tell me , Am I right? 😄

**Comment by chrisgorgo** [comment]
I'm not sure I follow. Could you send a pull request?

Best,
Chris

**Comment by SetCodesToFire** [comment]
Hi @chrisfilo ,
I am kind of lost. Whatever I thought of implementing in the tsv validatior is already implemented. I thought of checking each values of the row and according to them add the issue in the issue tray. 
Now I want to know what else do this github issue here want to implement. How can I help you in adding warnings?

**Comment by chrisgorgo** [comment]
Whenever, there is a .tsv file in the input dataset that does not come with a corresponding sidecar .json file (data dictionary see section 4.2 of the spec) an issue with severity class 'warning' should be produced. Example:

```
/participants.tsv
/participants.json
```
no warning



```
/participants.tsv
```
warning - there is no data dictionary

**Comment by SetCodesToFire** [comment]
Okay @chrisfilo , I'll work on this.

**Comment by chrisgorgo** [comment]
Thanks! You can also consider doing https://github.com/INCF/bids-validator/issues/357 - it might be easier.

**Comment by olgn** [comment]
fixed with #503
