### ISSUE TITLE
Increasing javascript array sorting performance

### ISSUE THREAD

**Issue by SetCodesToFire** [bids-standard/legacy-validator#408]
faster sorting algorithm of array

**Comment by chrisgorgo** [comment]
I would argue that performance is not our biggest problem right now.
Besides which sorting operation you wanted to optimize?

**Comment by SetCodesToFire** [comment]
Hi, I was trying to debug the issue #406 and while checking the code in utils/array.js I found a slight code region where we can tweek performance , hence opened this issue,

Still working on the directory existence check. 😄

**Comment by chrisgorgo** [comment]
I am not a fan of premature optimizations. I am not even convinced that  your fix would yield any measurable improvements, but it adds additional dependencies...

Glad you are looking at the code more closely.

**Comment by SetCodesToFire** [comment]
Okay, Sure. No problem.
