### ISSUE TITLE
Abstract away regular expressions for path validation in a programming language agnostic way

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#429]
Replacing all of the regular expressions from https://github.com/INCF/bids-validator/blob/master/utils/type.js with an import of an external package that provides only the regular expressions. See https://github.com/INCF/pybids/issues/131#issuecomment-370916864 for context.

**Comment by SetCodesToFire** [comment]
Is this issue telling just to create a json file that looks like 
```
[
  {
    "name": "is_cont",
    "pattern": "^\\/(sub-[a-zA-Z0-9]+)",
    "description": "Verifies that the file is..."
  },
  ...
]
```
where all the regex from the entire bids-validator tool will be kept.
Then this file created will be imported at appropriate locations and the variables will be fed at appropriate locations. Am I right?

Also I want to ask that if the value for name here could be any variable name comfortable with the programmer's point of view.

**Comment by chrisgorgo** [comment]
This should go to https://github.com/INCF/bids-validator-common

**Comment by chrisgorgo** [comment]
The patterns are ready - we should switch to using them.

**Comment by chrisgorgo** [comment]
This will probably require https://github.com/INCF/bids-validator-common/issues/2 to be done first.
