### ISSUE TITLE
RepetitionTime reading in nifti header

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/legacy-validator#430]
I am validating a dataset and find that the error message is saying that the nifti RepetitionTime is different than what is present in the nifti header. I expect an error for the different times defined between the json and nifti file, but it is not capturing the RepetitionTime present in the nifti header. 

![validator message](https://user-images.githubusercontent.com/35307458/37231068-9bbe2ed0-239e-11e8-85ba-ac05a1d89fb0.png)

![fslinfo sub1 social](https://user-images.githubusercontent.com/35307458/37231027-6f7d076a-239e-11e8-948c-39dc847a4dce.png)

![json tr](https://user-images.githubusercontent.com/35307458/37231075-a68a0c4e-239e-11e8-8b79-ec2767304220.png)

Thank you!

**Comment by chrisgorgo** [comment]
This is peculiar. Could you share an example NIFTI file that raises such error?

**Comment by franklin-feingold** [comment]
Please find the zip file attached with the NIFTI file within. This file can be opened in a NIFTI viewer, but the actual header could be the problem. If I were to try and edit the header using FSL, it says the file failed to open. It may not be openable, which could lead to the validator seeing zero as pixdim4? 
[github_nifti.zip](https://github.com/INCF/bids-validator/files/1812305/github_nifti.zip)

**Comment by chrisgorgo** [comment]
Did you try nibabel?

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.

**Comment by chrisgorgo** [comment]
the file in the zip archive seems to be some sort of datalad placeholder

```
In [5]: !cat sub-01_task-socialcomparison_bold.nii.gz
../../.git/annex/objects/Kq/8K/MD5E-s57419661--c5d48ccf5bd96b332a60ec68a1864a09.
nii.gz/MD5E-s57419661--c5d48ccf5bd96b332a60ec68a1864a09.nii.gz
```

**Comment by franklin-feingold** [comment]
I think after further investigation it is something weird happening with datalad. When I downloaded the image and tried to edit the header (no error was given) and after running the validator it was able to read the header and see that both the header and json match. 

Thank you!
