### ISSUE TITLE
BIDS online validator works longer than usual

### ISSUE THREAD

**Issue by hamedk72** [bids-standard/legacy-validator#431]
The [online validator](http://incf.github.io/bids-validator/) seems to be working longer than usual after browsing my bids dataset for validation.
Before this happens, I got plenty of errors and after resolving them, it didn't give me any response.

**Comment by chrisgorgo** [comment]
Hi,

Thanks for reporting. Some followup questions:
1. When you say longer than usual you mean you used the validator on the same dataset in the past and it was faster?
2. Could you try the command line version of the validator and share the console output?

Alternatively could you share the dataset that is giving your trouble?

**Comment by hamedk72** [comment]
Thank you for your help. 
1. Yes! I used it for the same dataset and it gave me some errors (including name of the folder and some header names in JSON files) but after 7 or 8 time, and resolving all the errors, it is just showing the 'validating' message and does not give any particular response.
2. I tried it actually, but it gives some strange errors:

C:\Users\hamedk72\AppData\Roaming\npm\node_modules\bids-validator\validators\tsv.js:88
        if (headers[1].trim() !== "duration"){
                       ^

TypeError: Cannot read property 'trim' of undefined
    at Object.TSV (C:\Users\hamedk72\AppData\Roaming\npm\node_modules\bids-validator\validators\tsv.js:88:24)
    at C:\Users\hamedk72\AppData\Roaming\npm\node_modules\bids-validator\validators\bids.js:260:25
    at C:\Users\hamedk72\AppData\Roaming\npm\node_modules\bids-validator\utils\files.js:51:47
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by hamedk72** [comment]
The dataset is too large, unfortunately I can't upload it

**Comment by chrisgorgo** [comment]
Thanks for extra information. It's a bug in the validator. Could you try this version: https://1021-37161308-gh.circle-artifacts.com/0/home/ubuntu/web_version/index.html ?

**Comment by hamedk72** [comment]
It works properly! thank a lot! :)
