### ISSUE TITLE
The validator gives RepetitionTime definition error although it is defined

### ISSUE THREAD

**Issue by hamedk72** [bids-standard/legacy-validator#435]
The error is as follows: File Path: You have to define 'RepetitionTime' for this file.
Type:		Error
	File:		sub-01_task-visual_echo-10_bold.nii.gz
	Location:		BIDS/sub-01/func/sub-01_task-visual_echo-10_bold.nii.gz
	Reason:		You have to define 'RepetitionTime' for this file. It can be included one of the following locations: /bold.json, /task-visual_bold.json, /task-visual_echo-10_bold.json, /sub-01/sub-01_bold.json, /sub-01/sub-01_task-visual_bold.json, /sub-01/sub-01_task-visual_echo-10_bold.json, /sub-01/func/sub-01_task-visual_echo-10_bold.json

my json file is located in "/sub-01/func/sub-01_task-visual_echo-10_bold.json" and it looks like this:
{
	"RepetitionTime": 3.0,
	"TaskName": "task-01",
	"SliceTiming": [0.0, 0.06521739130434782, ..., 2.9347826086956506]
}

**Comment by chrisgorgo** [comment]
I will look into this, but out of curiosity - you have a multi echo EPI sequence with 10 different echo times? I never seen anything like this.

**Comment by hamedk72** [comment]
Thank a lot!
Oh, no! I just wanted my different trials to have different index (I should have used [_run-index])

**Comment by chrisgorgo** [comment]
Do you run into the same validator issue when you use run- instead of echo-?

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.

**Comment by hamedk72** [comment]
Actually the error has kind of, changed: 
Type:		Error
	File:		sub-01_task-visual_run-10_bold.nii.gz
	Location:		BIDS/sub-01/func/sub-01_task-visual_run-10_bold.nii.gz
	Reason:		Repetition time was not defined in seconds, milliseconds or microseconds in the 
        scan's header.
	Type:		Error

And the pixdim array in the header file of my images is this: 
pixdim          : [-1.  3.  3.  3.  1.  1.  1.  1.] and pixdim[4] is defined in seconds. what am I getting wrong?

**Comment by chrisgorgo** [comment]
This indicates issues with the `xyzt_units` nifti header field. See https://brainder.org/2012/09/23/the-nifti-file-format/ for details. Probably easily fixed with nibabel.

**Comment by hamedk72** [comment]
Thank you very much! It is solved.
