### ISSUE TITLE
TypeError: Cannot read property 'toFixed' of undefined

### ISSUE THREAD

**Issue by eort** [bids-standard/legacy-validator#442]
Running the bids-validator on data that was freshly converted with `heudiconv`, crashes with this error: 

~~~
/home/user/local/lib/node_modules/bids-validator/validators/nii.js:169
                    var niftiTR = Number((repetitionTime).toFixed(3));
                                                          ^
TypeError: Cannot read property 'toFixed' of undefined
    at NIFTI (/home/user/local/lib/node_modules/bids-validator/validators/nii.js:169:59)
    at /home/user/local/lib/node_modules/bids-validator/validators/bids.js:390:29
    at Gunzip.<anonymous> (/home/user/local/lib/node_modules/bids-validator/utils/files.js:242:21)
    at Gunzip.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Gunzip.Readable.push (_stream_readable.js:213:10)
    at Gunzip.Transform.push (_stream_transform.js:146:32)
    at Zlib.processCallback (zlib.js:556:10)
~~~

As I don't have su rights on the server on which I ran this, I needed to install node.js in my home directory. To do that I followed [these instructions](https://stackoverflow.com/questions/31538988/install-nodejs-without-sudo-for-user-without-having-home-directory-in-ubuntu).

**Comment by chrisgorgo** [comment]
What command line did you run exactly?

It seems that there is something seriously wrong with the nifti headers of your files - repetition time is not defined in them at all - maybe confused sequences when writing heudiconv heuristics?

Nonetheless the validator should handle this more gracefully.

**Comment by eort** [comment]
> What command line did you run exactly?
 
The bids-validator I call with `bids-validator <absolute path to directory>`

The conversion I do with this heuristic: 

~~~.python
import os

scaninfo_suffix = '.json'

def create_key(template, outtype=('nii.gz',), annotation_classes=None):
    if template is None or not template:
        raise ValueError('Template must be a valid format string')
    return (template, outtype, annotation_classes)

def infotodict(seqinfo):
    """Heuristic evaluator for determining which runs belong where
    allowed template fields - follow python string module: 

    item: index within category 
    subject: participant id 
    seqitem: run number during scanning
    subindex: sub index within group
    """

    info = {}
    for s in seqinfo:
        key = None
        print(s[2])
        if 'SmartBrain' in s[2]:
            continue
        elif 'SMARTPLAN_TYPE_BRAIN' in s[2]:
            continue
        elif 'field map_calibrate' in s[2]:
            continue  
        elif 'EPI_3mm' in s[2]:
            key = create_key('{subject}/func/{subject}_task-choice_run-{item:02d}_bold')
        elif 'field map_check' in s[2]:
            key = create_key('{subject}/fmap/{subject}_fmap')       
        elif 'T1W_' in s[2]:
            key = create_key('{subject}/anat/{subject}_T1w')
    	elif 'ScreenCapture' in s[2]:
    	    continue
        else:
            print(s[2])
            raise(RuntimeError, "YOU SHALL NOT PASS!")

        if not key in info:
            info[key] = []
        if key:
            info[key].append(s[2])
    return info
~~~

and this command: 

~~~.python
# for one subject
heudiconv -d /home/data/foraging/raw/dcm/{subject} -s ks38_0982.20170503.110243.18.tar.gz -f /home/data/foraging/code/heudiconv_heuristic.py -o /home/data/foraging/ --anon-cmd /home/data/foraging/code/anon_id.py -b --overwrite
~~~

And here the output of fslhd for one of the functional niftis: 
[header.txt](https://github.com/INCF/bids-validator/files/1832493/header.txt)

**Comment by chrisgorgo** [comment]
Could you share a minimal dataset I could reproduce this error with?

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.

**Comment by eort** [comment]
In the mean time, I added some fields to the epi json sidecar that were missing (and needed for fieldmap processing) and this appears to have fixed the issue. The validator runs now without throwing this error. 

Do you still want me to upload a minimal dataset, or is it not necessary anymore?

**Comment by chrisgorgo** [comment]
So the only thing you changed is content of `_epi.json`? This is very surprising because the error you reported should only happen for `_bold` files - https://github.com/INCF/bids-validator/blob/37924a136d9831256bd0eb47606a9b2031cc523e/validators/nii.js#L169

It might be good to get some test data to get to the bottom of this.

**Comment by eort** [comment]
Oh sorry, I meant bold files. I only added fields (incl. `RepetitionTime`) to the bold.json files (e.g. `sub-03/func/sub-03_task-choice_run-10_bold.json`) and the fieldmap.json files. 

I'll upload some raw data in a bit.

**Comment by chrisgorgo** [comment]
Was the "RepetitionTime" field missing in the original `_bold.json` or set to something like `""`?

**Comment by eort** [comment]
I think I found the problem. There was a bold run that was corrupted (the scan was aborted halfway through). This file cannot be opened with `fslhd`. When it is included in the directory that is checked with the validator, I get the error described above. When I remove it, everything finishes fine. 

> Was the "RepetitionTime" field missing in the original _bold.json or set to something like ""?

For completeness sake, the field `RepetitionTime` was present all along. 

Sorry for the confusion!

**Comment by chrisgorgo** [comment]
No worries - thanks for reporting!

Best,
Chris
