### ISSUE TITLE
MEG-BIDS validator

### ISSUE THREAD

**Issue by guiomar** [bids-standard/legacy-validator#443]
Hi @jasmainak,

I copy this here so we can keep track:

The fields that should be checked are:

**Sidecar JSON document (*_meg.json)**

Manufacturer | OPTIONAL. Manufacturer of the MEG system ("CTF", "Elekta/Neuromag", "4D/BTi", "KIT/Yokogawa", "ITAB", "KRISS", "Other")
-- | --

ManufacturersModelName | OPTIONAL. Manufacturer’s designation of the MEG scanner model (e.g. "CTF-275"). See Appendix VII with preferred names
-- | --

**Coordinate System JSON document (*_coordsystem.json)**

MEGCoordinateSystem | REQUIRED. Defines the coordinate system for the MEG sensors. See Appendix VIII: preferred names of Coordinate systems. If "Other", provide definition of the coordinate system in  [MEGCoordinateSystemDescription].
-- | --

HeadCoilCoordinateSystem | OPTIONAL. Defines the coordinate system for the coils. See Appendix VIII: preferred names of Coordinate systems. If "Other", provide definition of the coordinate system in  HeadCoilCoordinateSystemDescription.
-- | --

DigitizedHeadPointsCoordinateSystem | OPTIONAL. Defines the coordinate system for the digitized head points. See Appendix VIII: preferred names of Coordinate systems. If "Other", provide definition of the coordinate system in  DigitizedHeadPointsCoordinateSystemDescription.
-- | --

AnatomicalLandmarkCoordinateSystem | OPTIONAL. Defines the coordinate system for the anatomical landmarks. See Appendix VIII: preferred names of Coordinate systems. If "Other", provide definition of the coordinate system in  AnatomicalLandmarkCoordinateSystemDescription.
-- | --

**Channels description table (*_channels.tsv)**

Restricted keyword list for field type

- MEGMAG: 		MEG magnetometer
- MEGGRADAXIAL: 	MEG axial gradiometer
- MEGGRADPLANAR: 	MEG planar  gradiometer
- MEGREFMAG: 	MEG reference magnetometer 
- MEGREFGRADAXIAL:MEG reference axial  gradiometer
- MEGREFGRADPLANAR: MEG reference planar gradiometer 
- MEGOTHER: 	Any other type of MEG sensor
- EEG:  	Electrode channel : electroencephalogram)
- ECOG:  	Electrode channel : electrocorticogram (intracranial)
- SEEG:  	Electrode channel :  stereo-electroencephalogram (intracranial)
- DBS: 		Electrode channel : deep brain stimulation (intracranial)
- VEOG: 	Vertical EOG (electrooculogram)
- HEOG: 	Horizontal EOG
- EOG: 		Generic EOG channel, if HEOG or VEOG information not available 
- ECG: 		ElectroCardioGram (heart)
- EMG: 		ElectroMyoGram (muscle) 
- TRIG: 	System Triggers
- AUDIO: 	Audio signal
- PD: 		Photodiode
- EYEGAZE: 	Eye Tracker gaze
- PUPIL: 	Eye Tracker pupil diameter
- MISC: 	Miscellaneous
- SYSCLOCK: 	System time showing elapsed time since trial started 
- ADC: 		Analog to Digital input 
- DAC:   	Digital to Analog output 
- HLU:  	Measured position of head and head coils
- FITERR:    Fit error signal from each head localization coil
- OTHER:     Any other type of channel

**Comment by jasmainak** [comment]
Thanks @guiomar

**Comment by guiomar** [comment]
Hi!

I'm not sure the acq_date is being checked properly in the validator.
"Datetime should be expressed in the following format 2009-06-15T13:45:30"

Cheers,

**Comment by chrisgorgo** [comment]
Could you open a new issue with more details?

**Comment by guiomar** [comment]
Yes :)

**Comment by guiomar** [comment]
#461

**Comment by jasmainak** [comment]
hmm ... there were two things mentioned in this issue but one was moved to #461 and the other was not. Perhaps we should reopen this?

@chrisfilo if you label this as MEG, I could perhaps tackle this in the coming days as I have more time now

**Comment by chrisgorgo** [comment]
Done! Looking forward!

**Comment by sappelhoff** [comment]
@jasmainak can we close this?

**Comment by jasmainak** [comment]
sure feel free to close
