### ISSUE TITLE
Check if _T1w is 3D

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#445]

**Comment by suyashdb** [comment]
@chrisfilo does checking Nifti header for `dim[]` field would suffice?

**Comment by chrisgorgo** [comment]
yup!

**Comment by olgn** [comment]
@chrisfilo and is it _exactly_ three dimensions, or _no more than_ three dimensions?

**Comment by chrisgorgo** [comment]
correct - same as magnitude1 and magnitude2 (in fact you can use the same function)
