### ISSUE TITLE
Misleading warning: Not all subjects contain the same files

### ISSUE THREAD

**Issue by eort** [bids-standard/legacy-validator#446]
One subject of my dataset has one more run than all the other subjects, but when running bids-validator one that dataset in verbose mode. I get for all other subjects the warning: 

`2: Not all subjects contain the same files. Each subject should contain the same number of files with the same naming unless some files are known to be missing.`, accompanied by `This file is missing for subject sub-##, but is present for most other subjects.` for each relevant file. 

It isn't really a big deal, but it is a little weird to say `...but is present for most other subjects.`, if "most other" refers to a single subject.

**Comment by chrisgorgo** [comment]
Would you mind submitting a pull request with improved wording?
