### ISSUE TITLE
Online BIDS validator works on single subject but not for the whole group

### ISSUE THREAD

**Issue by bgagl** [bids-standard/legacy-validator#452]
Hi, 

I am starting to work with BIDS and was already successfully using the validator for a single subject. This I am currently using with some BIDS apps and so far it works out fine. Today I wanted to validate the BIDS format for my whole group of subjects. It did not produce any results just posted the following error msg in the developer tools. 
﻿
3
app.min.js? [sm]:14575 Uncaught TypeError: Cannot read property 'toFixed' of undefined
    at t.exports (app.min.js? [sm]:14575)
    at app.min.js? [sm]:13756
    at FileReader.a.onloadend (app.min.js? [sm]:12190)

Best wishes, 
Ben

**Comment by chrisgorgo** [comment]
I wonder if this is the same issue as in https://github.com/INCF/bids-validator/issues/442 (corrupted file header).

**Comment by bgagl** [comment]
Thanks for the suggestion. It lead to finding that a fmap file was stored as an anatomical file. Correcting this error lead to a correct validator run.

Thanks again and best wishes, 
Ben
