### ISSUE TITLE
Ignore `sub-emptyroom` when counting partisipants/sessions

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#453]
Related to MEG. See https://github.com/OpenNeuroOrg/openneuro/issues/549

**Comment by olgn** [comment]
@chrisfilo would we still like to see errors about inconsistent subjects that have to do with sub-emptyroom? or should those be suppressed as well?

**Comment by chrisgorgo** [comment]
let's suppress that - good initiative!
