### ISSUE TITLE
Raise a warning/error if EffectiveEchoSpacing values are outside of expected range

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#465]
https://neurostars.org/t/fmriprep-susceptibility-distortion-fieldmap-problems/1586/10

@oesteban could you suggest the range of expected values (in seconds)?

**Comment by oesteban** [comment]
Upper bound: if the `RepetitionTime` is available, EffectiveEchoSpacing times number of pixels in the PE direction can't be greater than the TR. 

If not, 0.001s would be a very generous threshold that may prevent setting it wrong by mistake.

For the lower bound it is harder, there are really fast EPIs out there now.
