### ISSUE TITLE
(node:23048) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#466]
Node 10

**Comment by rwblair** [comment]
All calls directly to Buffer() have been updated. Only call left through Buffer directly uses Buffer.alloc():
https://github.com/bids-standard/bids-validator/blob/master/bids-validator/utils/files/readNiftiHeader.js#L46
