### ISSUE TITLE
validator should return != 0 when failing validation

### ISSUE THREAD

**Issue by smaffiol** [bids-standard/legacy-validator#469]
bids-validator should have a non 0 return code in case of failed validation of the provided input folder.
would this make sense ?
it would help - fer example - intergrate bids-validator programmatically.

S.

**Comment by chrisgorgo** [comment]
Yes but only if there are errors (not just warnings). Is this what you
observed?

**Comment by smaffiol** [comment]
Hi Chris

it seems bids_validator is returning 0 as exitcode irrespective on whether
it succeed to validate or not:
$ bids-validator -v
0.19.8
ubuntu@master001:~$ bids-validator /tmp/
This does not appear to be a BIDS dataset. For more info go to
http://bids.neuroimaging.io/
ubuntu@master001:~$ echo $?
0

and

$ bids-validator /mnt/bids_testbench/
1: This file is not part of the BIDS specification, make sure it isn't
included in the dataset by accident. Data derivatives (processed data)
should be placed in /derivatives folder. (code: 1 - NOT_INCLUDED)
/sub-dianae063/gbids.log
Evidence: gbids.log
/sub-kjpd142/gbids.log
Evidence: gbids.log

2: Not all subjects contain the same files. Each subject should contain the
same number of files with the same naming unless some files are known to be
missing. (code: 38 - INCONSISTENT_SUBJECTS)
/sub-caipi/anat/sub-caipi_T1w.nii.gz
/sub-cross64d/anat/sub-cross64d_T1w.nii.gz
/sub-invivoIBT/anat/sub-invivoIBT_T1w.nii.gz
/sub-invivoPUK/anat/sub-invivoPUK_T1w.nii.gz
/sub-kjpd142/anat/sub-kjpd142_T1w.nii.gz
/sub-meditation5141/anat/sub-meditation5141_T1w.nii.gz

3: Not all subjects/sessions/runs have the same scanning parameters. (code:
39 - INCONSISTENT_PARAMETERS)
/sub-caipi/dwi/sub-caipi_dwi.nii.gz
/sub-dianae063/dwi/sub-dianae063_dwi.nii.gz
/sub-hcp100307/anat/sub-hcp100307_T1w.nii.gz
/sub-hcp100307/dwi/sub-hcp100307_dwi.nii.gz
/sub-invivoIBT/dwi/sub-invivoIBT_dwi.nii.gz
/sub-invivoPUK/dwi/sub-invivoPUK_dwi.nii.gz
/sub-kjpd142/dwi/sub-kjpd142_dwi.nii.gz
/sub-meditation5141/dwi/sub-meditation5141_dwi.nii.gz

4: Nifti file's header field for unit information for x, y, z, and t
dimensions empty or too short (code: 41 - NIFTI_UNIT)
/sub-meditation5141/dwi/sub-meditation5141_dwi.nii.gz

        Summary:               Available Tasks:        Available
Modalities:
        29 Files, 377MB                                dwi

        8 - Subjects                                   T1w

        1 - Session


ubuntu@master001:~$ echo $?
0

It would be great if at least in the first case - i.e. failed to validate -
the return code would be != 0
agree to return with return code 0 in case on warnings

Regards,
Sergio


2018-05-03 15:57 GMT+02:00 Chris Filo Gorgolewski <notifications@github.com>
:

**Comment by chrisgorgo** [comment]
It seems that you are using a very old version - could you try with the latest (0.26.6)?

**Comment by smaffiol** [comment]
Hi Chris

indeed with 0.26.6 the return code works as expected: 
* 0 if success (plus warning in case)
* 1 if failed

thanks,
S.
