### ISSUE TITLE
MEG file extensions are not correct

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/legacy-validator#473]
The line https://github.com/INCF/bids-validator/blob/ac2a221b579ec6ca0253f1c0700768a54ad2f972/utils/type.js#L203 contains the file name extensions that are considered valid for MEG files. Some of them are not correct (like _meg.ctf and _meg.itab), whereas others that are valid are not listed (like  .raw and .raw.mhd for ITAB). 

For 4D/BTi data it is even more problematic, as those don't use file extensions. I have these example datasets 

```
bti148:
total 69540
-rw-rw-r-- 1 roboos fieldtrip 70814400 Apr 11  2011 c,rfhp0.1Hz
-rw-rw-r-- 1 roboos fieldtrip    14445 Apr 11  2011 c,rfhp0.1Hz.m4d
-rw-rw-r-- 1 roboos fieldtrip     3911 Apr 11  2011 c,rfhp0.1Hz.xyz
-rw-rw-r-- 1 roboos fieldtrip    83344 Apr 11  2011 hs_file

bti248:
total 68704
-rw-rw-r-- 1 roboos fieldtrip   195256 Apr 11  2011 config
-rw-rw-r-- 1 roboos fieldtrip 67725824 Apr 11  2011 e,rfDC
-rw-rw-r-- 1 roboos fieldtrip  2135416 Apr 11  2011 e,rfDC,F,a
-rw-rw-r-- 1 roboos fieldtrip      136 Apr 11  2011 hs_file

bti248grad:
total 2220
-rw-rw-r-- 1 roboos fieldtrip  219608 Oct  5  2010 config
-rw-rw-r-- 1 roboos fieldtrip 1997600 Oct  5  2010 e,rfhp1.0Hz,COH
-rw-rw-r-- 1 roboos fieldtrip   32992 Oct  5  2010 hs_file

```

**Comment by jasmainak** [comment]
Thanks for the report. I will look into it in a few days if nobody else beats me to it

**Comment by robertoostenveld** [comment]
I would appreciate if you could provide some guidance for file-name and file-content handling, as we also need to improve this for bids-eeg, where we have BrainVision vhdr/vmrk/[eeg|seg|dat] triplets. I really I would want to check that the triplet is complete, and that the content is OK (at least, not totally wrong).

**Comment by jasmainak** [comment]
I guess the issue of checking the triplet is easy. However, checking the content might be harder if there are no javascript readers. This is an issue that @choldgraf has also been facing for iEEG part of the validator. I am able to help more concretely after 2nd June since I am traveling until then ...

**Comment by robertoostenveld** [comment]
a superficial check on the content might be implemented based on file header magic. The code in https://github.com/fieldtrip/fieldtrip/blob/master/fileio/ft_filetype.m <https://github.com/fieldtrip/fieldtrip/blob/master/fileio/ft_filetype.m> documents some of the header details for quite some files. This would not allow for a content-wise check, which requires more proper parsing.
