### ISSUE TITLE
Large raw data files problematic for validation

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/legacy-validator#482]
Dicoms or any other large raw image data file can be problematic for validation. Perhaps there can be a way for the validation to detect those type of raw image data files are present and stop the validation with an error?

**Comment by chrisgorgo** [comment]
DICOMs should be ignored if stored in `sourcedata/`. Large niftis should not pose a problem (only the header is being read). Could you describe the environment and dataset a bit more?

**Comment by franklin-feingold** [comment]
This was helping a user validate their dataset. The validation was being done on a windows 10 OS using Chrome. The issue ended up being that raw image data files and nifti images (with accompanying sidecar jsons) were all together. This was likely creating a memory error and crashing chrome. Once the raw image data files were moved, the validator worked very well and created the report.
