### ISSUE TITLE
no modalities for MEG (and EEG) in summary

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#489]
When running the BIDS-validator successfully, there is a nice summary output at the end such as:
```


        Summary:                 Available Tasks:        Available Modalities: 
        57 Files, 19.34kB        rhyme judgment          T1w                   
        13 - Subjects                                    inplaneT2             
        1 - Session                                      bold   
```
When testing data that contain MEG modalities (e.g., ds000117), that modality does not show up. Same thing for the EEG validator, which has not yet been merged but is even with master besides the few EEG-specific commits.

I was looking for why this might be the case and stumbled over these lines:

https://github.com/INCF/bids-validator/blob/88a30a31babf6d1f91d2a9d54efab8c150a7c3b8/validators/bids.js#L249-L258

Why is the modality part indented so as to only occur, if a nifti file was found? Is that perhaps a bug?

If not, what else could be the reson that MEG and EEG modalities are not shown in the summary?

**Comment by chrisgorgo** [comment]
This is indeed a bug. Thanks for reporting. Would you like to try fixing it?
