### ISSUE TITLE
logo proporsal for bids validator

### ISSUE THREAD

**Issue by anablog** [bids-standard/legacy-validator#492]
Hello a pleasure in greeting you, I wanted to introduce myself I am Ana Medina Graphic Web Designer, I am very interested in your new open source project for me it would be a pleasure to provide my services as a designer and collaborate without commitments, You require a new logo for your brand I can help him?

I well be pleased to collaborate with you.

**Comment by chrisgorgo** [comment]
To be clear we do not have funds to compensate you for such services - are you still interested in helping?

**Comment by anablog** [comment]
There would be no problem, it is a contribution, from me to you, the idea is to join effort, you talk to me about the project, give me your ideas and I design based on your reference.

**Comment by chrisgorgo** [comment]
HI Anabel,

Thank you for your generous offer. I think what it might be even better (in terms of the exposure we can provide for your work) to work on a logo for the whole Brain Imaging Data Structure (BIDS) project, not just for this validator. You can read more about the project at http://bids.neuroimaging.io/ and https://www.nature.com/articles/sdata201644.

The BIDS website is visited by ~2800 unique visitors every month. I would be more than happy to mention your name and a link to your website there.

If you would like to discuss details you can reach me at krzysztof.gorgolewski@gmail.com.

Best,
Chris
