### ISSUE TITLE
link to source code from web validator

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#493]
The [web validator](https://incf.github.io/bids-validator/#) does not contain a link to the source code, only to the main BIDS website. I think it would be good to have a small but visible badge or something where people can get here to the Github page. Other opinions?

**Comment by franklin-feingold** [comment]
Hi Stefan, 
Thank you for raising this. I have added a link to the github source code on the web-based validator upon an error to enable further troubleshooting. 
Thank you, 
Franklin
