### ISSUE TITLE
app.min.js:24606

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#50]
http://incf.github.io/bids-validator/ throws an exception when using https://github.com/INCF/BIDS-examples/tree/master/ds114 dataset.

```
r   @   app.min.js:24606
i.onloadend @   app.min.js:30412
```

The same dataset produces appropriate feedback when used on the command line.

**Comment by constellates** [comment]
I believe this is caused by trying to read the empty nifti files. I'm working on a fix to make sure we return an error so the app doesn't fail.
