### ISSUE TITLE
improperly accessed header dimensions

### ISSUE THREAD

**Issue by olgn** [bids-standard/legacy-validator#515]
the `axes` variable defined [here](https://github.com/INCF/bids-validator/blob/71ab31597b3df18fbe546fb4bc81f1fee880f165/validators/nii.js#L232) is used to access the dimension of the nifti header on [this line](https://github.com/INCF/bids-validator/blob/71ab31597b3df18fbe546fb4bc81f1fee880f165/validators/nii.js#L235). the nifti header spec indicates that the `dim` field of the header is an array like `dim = [num_dimensions, i, j, k, num_volumes, ...]`. (see section "Image Dimensions" [here](https://brainder.org/2012/09/23/the-nifti-file-format/)). In light of this, shouldn't the `axes` variable be changed to `axes = {i: 1, j: 2, k: 3}`?

**Comment by chrisgorgo** [comment]
I believe you are right. Good catch!
