### ISSUE TITLE
Overzealous warnings for missing data dictionaires

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#521]
Since recently there is a warning for `.tsv` files that do not have an accompanying `.json` dictionary:

https://github.com/INCF/bids-validator/blob/6349fdbbac18688df7c5f9232eced9a7525268f9/utils/issues/list.js#L448-L451

This warning now gets triggered a lot on the [BIDS examples](https://github.com/incf/BIDS-examples).

I propose that we only raise this warning if the `.tsv` file under scrutiny contains columns that are NOT pre-specified in the BIDS document.

### Example

In my `channels.tsv` file I can specify the `name`,	`type`,	`units`,	`status`,	and `status_description` of my EEG electrodes. If these are the only columns present in the `.tsv`, there is no need to ask for a data dictionary, because these columns are already described in the BIDS document.

However, as soon as I add a custom column to the `.tsv` such as a boolean `experimental_tryout` (or whatever), the warning should get triggered.

**Comment by chrisgorgo** [comment]
Agreed that there might be too much noise. The refinement you propose seems like the right way forward.

**Comment by chrisgorgo** [comment]
Replaced by https://github.com/INCF/bids-validator/issues/530
