### ISSUE TITLE
BEP006 and BEP010 corrections to camelCase

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#526]
In both the [BEP006](https://docs.google.com/document/d/1ArMZ9Y_quTKXC-jNXZksnedK2VHHoKP3HCeO5HPcgLE/edit#heading=h.4k1noo90gelw) and [BEP010](https://docs.google.com/document/d/1qMUkoaXzRMlJuOcfTYNr3fTsrl4SewWjffjMD5Ew6GY/edit?ts=5b7ddb80#heading=h.4k1noo90gelw) extensions we had defined some keys using under_score notation. These have been merged into master such as here:

https://github.com/INCF/bids-validator/blob/6349fdbbac18688df7c5f9232eced9a7525268f9/validators/tsv.js#L224-L235

To be consistent across the specification, these should be converted to camelCase. However, we should wait with changing the repo here, until the conversion has taken place in the google docs specifications of the BEPs.

**Comment by sappelhoff** [comment]
on second thoughts, does the camel case convention not hold true to column labels in `.tsv` files @chrisfilo ?

**Comment by chrisgorgo** [comment]
It only applies to JSON dictionaries, with the exception of primary keys of
data dictionaries such have to match column keys.

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.
