### ISSUE TITLE
TypeError: Cannot set property 'files' of undefined

### ISSUE THREAD

**Issue by ddwagner** [bids-standard/legacy-validator#544]
Hi all, ran the bids validator last week without issues. Today it appears to be failing across all two servers that have access to the datasets I'm working with. Interestingly, one of the newer builds (e.g. https://1456-37161308-gh.circle-artifacts.com/0/root/web_version/index.html) that I spotted in an unrelated question on neurostars works just fine (see: https://neurostars.org/t/surprising-error-with-bids-validator/2347/2). 

The developer console error is beyond my ken:

**Here's the one in Chrome:**

Uncaught TypeError: Cannot set property 'files' of undefined
    at Object.format (app.min.js:1)
    at app.min.js:1
    at app.min.js:1
    at u (app.min.js:1)
    at app.min.js:1
    at m.run (app.min.js:1)
    at h (app.min.js:1)

**And in firefox:**

TypeError: u[f.code] is undefined[Learn More] app.min.js:1:148734

**Comment by chrisgorgo** [comment]
@olgn could you look into this?

**Comment by olgn** [comment]
@chrisfilo sure thing

**Comment by olgn** [comment]
@ddwagner thanks for filing this. would you mind trying to validate your dataset at [this address](https://1514-37161308-gh.circle-artifacts.com/0/root/web_version/index.html) and let us know if the problem is resolved?

**Comment by ddwagner** [comment]
Hey @olgn, the validator at that address fixes the issue. And now it looks like it's been pushed to the main validator address as that works now as well. Cheers for the fix!

**Comment by chrisgorgo** [comment]
This has resurfaced (on both OpenNeuro and the current version of the standalone validator):
![image](https://user-images.githubusercontent.com/238759/45932049-9212ba80-bf2b-11e8-8c86-021cfc7ec490.png)
Trying to get a dataset that would allow replicating this issue from the user that reported it.
