### ISSUE TITLE
Overzealous code 64 check

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#547]
![image](https://user-images.githubusercontent.com/238759/45235248-1e1ab600-b28d-11e8-97ea-b43ff3980426.png)

Context: https://neurostars.org/t/inconsistent-errors-with-bids-validator/2419/3

File naming conventions inside stimuli do not need to be checked.

**Comment by chrisgorgo** [comment]
@olgn do you think this could be related to changes in https://github.com/INCF/bids-validator/pull/501?

**Comment by olgn** [comment]
@chrisfilo i don't believe so - the sub-id mismatch test happens a while before the events checking in #501, and throws a different error code

**Comment by chrisgorgo** [comment]
I see. Could you look or @bGrass look into it nonetheless?  Thanks in advance.

**Comment by olgn** [comment]
@chrisfilo would you test if https://1526-37161308-gh.circle-artifacts.com/0/root/web_version/index.html resolves this issue?

**Comment by chrisgorgo** [comment]
Yup! https://neurostars.org/t/inconsistent-errors-with-bids-validator/2419/5

**Comment by olgn** [comment]
splendid
