### ISSUE TITLE
Validation of .bvec/.bval files

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#55]
Each _dwi.nii[.gz] file need to have .bvec .bval defined (at any level of the hierarchy - similarly to _events.tsv). Those files need to meet the following specification https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit#heading=h.xfuiufnb319

Things to check:
- .bvec has as 3 rows
- .bval has one row
- number of columns in .bvec file, number of values (columns) in .bval file and number or volumes in the corresponding _dwi file all have to be the same

**Comment by constellates** [comment]
Looks like something is wrong with google doc URL. It broke lines and only part of it became a link. Copying the whole URL also produces an error that the document doesn't exist.

**Comment by chrisgorgo** [comment]
Sorry:

https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit#heading=h.xfuiufnb319

**Comment by constellates** [comment]
Thanks. Is the 6 values mentioned above the minimum or the total expected? I'm looking at the .bvec in ds114 and there are 71 values in each row.

**Comment by chrisgorgo** [comment]
Sorry - I was wrong. Here's the corrected text:

Things to check:
- .bvec has as 3 rows
- .bval has one row
- number of columns in .bvec file, number of values (columns) in .bval file and number or volumes in the corresponding _dwi file all have to be the same

**Comment by constellates** [comment]
Ok that makes sense. And is the "number of volumes" defined by the time dimension in _dwi scan header? In the one dataset I have with _dwi scans this value (dim[4) correctly corresponds with the number of bvec/bval values? But I don't have more datasets with _dwi's to check this with.

**Comment by chrisgorgo** [comment]
yes - this is it!
