### ISSUE TITLE
[BUG] issue 90 checks disregard BTi MEG data

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#553]
Recently, we added the issue 90 on the issue [list.js](https://github.com/INCF/bids-validator/blob/fbf6a5574ec2742e39f4ff70727133cd2e127964/utils/issues/list.js#L495-L499). With the code, we make sure that each data dictionary is also accompanied by a corresponding data file. MEG data is sometimes saved in directories where inside the directories, the manufacturer specific file names are kept, see Appendix 1 in the [MEG BIDS paper](https://www.biorxiv.org/content/biorxiv/suppl/2017/08/08/172684.DC1/172684-1.pdf)

This is the case for CNT data, which is saved in a directory that has a name ending with `.ds`. This case is covered:

https://github.com/INCF/bids-validator/blob/335695c494c5b5b751509b9754895c933dbec426/utils/bids_files.js#L70-L80

However, there is also BTi data, which is *also* saved in a directory but that directory does not have an extension. 

Currently, correctly saved BTi data will trigger an issue 90 "SIDECAR_WITHOUT_DATAFILE"

**Comment by jasmainak** [comment]
+1 thanks @sappelhoff for reporting this

**Comment by sappelhoff** [comment]
This was potentially fixed in https://github.com/bids-standard/bids-validator/pull/607/files 

I'll reopen if I encounter this issue again.
