### ISSUE TITLE
Change color of "further questions" link in validator output

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#554]
Currently we have a red

`If you have any questions please post on https://neurostars.org/tags/bids`

output with every print that the BIDS-validator does. I think that this comes at the expense of the user experience because we are used to associating red with errors ... 

IMO we should reserve:
- green if something is good (validation correct)
- yellow for warnings
- red for errors.

Let's change the red information `If you have any questions please post on https://neurostars.org/tags/bids` to white:
https://github.com/INCF/bids-validator/blob/6349fdbbac18688df7c5f9232eced9a7525268f9/cli.js#L154-L159

**Comment by chrisgorgo** [comment]
Agreed - could you send a PR?
