### ISSUE TITLE
not all iEEG sidecar files are recognized properly

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/legacy-validator#555]
A json sidecar file was found without a corresponding data file (code: 90 - SIDECAR_WITHOUT_DATAFILE)^[[39m
    ./sub-cm4/ieeg/sub-cm4_space-2DImage_coordsystem.json

**Comment by robertoostenveld** [comment]
I will try to follow this up by digging in the code why it fails. I suspect that it might be because of the "space-2DImage" section in the filename, because for MEG we have had similar sidecar files without the space that were working just fine.

**Comment by olgn** [comment]
@robertoostenveld I recently opened a pr that refactors the potentialLocations function. it would be useful to see if that refactor will solve this issue. can you test to see if you get this error on [this branch](https://github.com/INCF/bids-validator/pull/551)? the web validator associated with this pr is located [here](https://1544-37161308-gh.circle-artifacts.com/0/root/web_version/index.html).

**Comment by robertoostenveld** [comment]
The dataset is this one
https://github.com/robertoostenveld/BIDS-examples/tree/bep010_ieeg/ieeg_filtered_speech

it now fails at a more general level. 

File Path: Quick validation failed - the general folder structure does not resemble a BIDS dataset. Have you chosen the right folder (with "sub-*/" subfolders)? Check for structural/naming issues and presence of at least one subject.

	Type:		Error
	File:		ieeg_filtered_speech
	Reason:		Quick validation failed - the general folder structure does not resemble a BIDS dataset. Have you chosen the right folder (with "sub-*/" subfolders)? Check for structural/naming issues and presence of at least one subject.

======================================================

**Comment by robertoostenveld** [comment]
the previous comment pertained to the online version. I also tried it with a local copy, which I noticed is now merged in master.
```
mac011> /Volumes/128GB/bids-validator/bin/bids-validator --bep010 ieeg_filtered_speech
	1: [ERR] A json sidecar file was found without a corresponding data file (code: 90 - SIDECAR_WITHOUT_DATAFILE)
		./sub-cm4/ieeg/sub-cm4_space-2DImage_coordsystem.json
		./sub-cm8/ieeg/sub-cm8_space-2DImage_coordsystem.json
```

**Comment by robertoostenveld** [comment]
The issue was that "space-xxx" was in the coordsys.json file, where it is not allowed. It would be allowed in the datafile, but there it does not make sense. It is also not needed in the coordsys.json file, so I will update the example dataset.
