### ISSUE TITLE
XXX_FILE_WITH_TOO_MANY_DIMENSIONS

### ISSUE THREAD

**Issue by benoitberanger** [bids-standard/legacy-validator#565]
Hello,

A new error appeared since the last time I used _bids-validator_ 3 days ago (Friday 14-sept-2018) :

***

`Error 2: [Code 95] T1W_FILE_WITH_TOO_MANY_DIMENSIONS`
However : 
```
mrinfo bids/sub-20180626AGENT10060/ses-S1/anat/sub-20180626AGENT10060_ses-S1_run-1_T1w.nii.gz
************************************************
Image:               "bids/sub-20180626AGENT10060/ses-S1/anat/sub-20180626AGENT10060_ses-S1_run-1_T1w.nii.gz"
************************************************
  Dimensions:        176 x 232 x 256
  Voxel size:        1 x 1 x 1
  Data strides:      [ -1 2 3 ]
  Format:            NIfTI-1.1 (GZip compressed)
  Data type:         signed 16 bit integer (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:                    1           0           0       -87.5
                               -0           1           0      -98.04
                               -0           0           1      -147.8
```

***

Same thing for field map :
`Error 1: [Code 94] MAGNITUDE_FILE_WITH_TOO_MANY_DIMENSIONS`
```
mrinfo bids/sub-20180626AGENT10060/ses-S1/fmap/sub-20180626AGENT10060_ses-S1_run-1_magnitude1.nii.gz
************************************************
Image:               "bids/sub-20180626AGENT10060/ses-S1/fmap/sub-20180626AGENT10060_ses-S1_run-1_magnitude1.nii.gz"
************************************************
  Dimensions:        70 x 70 x 50
  Voxel size:        3 x 3 x 3
  Data strides:      [ -1 2 3 ]
  Format:            NIfTI-1.1 (GZip compressed)
  Data type:         signed 16 bit integer (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:                    1           0           0        -102
                               -0       0.986     -0.1668      -80.31
                               -0      0.1668       0.986      -79.82
```
I didn't change my data set not the script to make them BIDS compatible.
Could the problem come from _bids-validator_ itself ?

Thanks you for your help
Benoît

**Comment by benoitberanger** [comment]
Could it come from [_magnitudex.nii[.gz] should have exactly 3 dimensions #559](https://github.com/INCF/bids-validator/pull/559/commits/359245ec442a7250ed94e16a01d02e1cdfdaed42) ?

https://github.com/olgn/bids-validator/blob/359245ec442a7250ed94e16a01d02e1cdfdaed42/validators/headerFields.js#L96 : `header[field][0] !== 4`
I might be wrong with the syntax, but for 3D data, dimension should be 3, like `header[field][0] !== 3`

**Comment by chrisgorgo** [comment]
@olgn could you look into this? Testing on Saturday some OpenNeuro data might be a good idea.

**Comment by benoitberanger** [comment]
I just tried with a free dataset of 3DT1 : https://openneuro.org/datasets/ds001505/versions/2.0.1
=> Same error `Error 1: [Code 95] T1W_FILE_WITH_TOO_MANY_DIMENSIONS`

**Comment by olgn** [comment]
The current bids implementation of the nifti header dimension requirement is that `dim[0]` indicates the _length of the `dim` array_. since this field is always included, for an n-dimensional scan, the value of `dim[0]` would be `n + 1`. for example, a 3-d scan should have `dim[0] = 4` (one entry describing the length of the array, and three entries for each dimension). this is enforced [here](https://github.com/INCF/bids-validator/blob/db97e261a1048da824b01256f7c4fd7812c89d44/validators/headerFields.js#L76)

@benoitberanger your question, as well as [this summary of the nifti spec](https://brainder.org/2012/09/23/the-nifti-file-format/) makes me think that perhaps `dim[0]` indicates the _number of dimensions other than `dim[0]`_. as in your example, a scan with three spatial dimensions should have length 4, and `dim[0]` should be 3. 

@chrisfilo does this match your understanding?

**Comment by chrisgorgo** [comment]
How does the header look like in case of T1w files in https://openneuro.org/datasets/ds001505/versions/2.0.1 ?

**Comment by chrisgorgo** [comment]
In comparison to bold files?

**Comment by benoitberanger** [comment]
@olgn this is also what I understand from `dim` field in nifti header:

> **Image dimensions**
> The field short dim[8] contains the size of the image array. The first element (dim[0]) contains the number of dimensions (1-7). If dim[0] is not in this interval, the data is assumed to have opposite endianness and so, should be byte-swapped (the nifti standard does not specify a specific field for endianness, but encourages the use of dim[0] for this purpose). The dimensions 1, 2 and 3 are assumed to refer to space (x, y, z), the 4th dimension is assumed to refer to time, and the remaining dimensions, 5, 6 and 7, can be anything else. The value dim[i] is a positive integer representing the length of the i-th dimension.

For a 3DT1 here what I have from _SPM_ `dim: [3 256 180 256 1 1 1 1]` ) and in _mrinfo_ `Dimensions:        256 x 180 x 256`
For a BOLD I have from _SPM_ : `dim: [4 66 66 46 5 1 1 1]` and in _mrinfo_ `Dimensions:        66 x 66 x 46 x 5`

**Comment by olgn** [comment]
@benoitberanger poking around on openneuro it is pretty clear that nifti files conform to the idea that 

`dim[0] = header['dim'].length - 1`

@chrisfilo I have submitted [this pull request](https://github.com/INCF/bids-validator/pull/567) as a fix for the recently implemented checks.

**Comment by chrisgorgo** [comment]
Thanks @olgn.

@benoitberanger Could you test the fix by installing the version from the branch

`npm install git://github.com/olgn/bids-validator.git#incorrect-header-dim-indexing --save`

Please let us know what do you find.

**Comment by olgn** [comment]
no problem. @benoitberanger alternatively you could test on the web validator that runs on this branch [here](https://1597-37161308-gh.circle-artifacts.com/0/root/web_version/index.html)

**Comment by curtcorum** [comment]
See this as well on my own dataset using http://incf.github.io/bids-validator/

File Path: _T1w.nii[.gz] files must have exactly three dimensions. 

	Type:		Error
	File:		sub-01_ses-18081901_acq-axfspgr_T1w.nii.gz
	Location:		ngfnProject/sub-01/ses-18081901/anat/sub-01_ses-18081901_acq-axfspgr_T1w.nii.gz
	Reason:		_T1w.nii[.gz] files must have exactly three dimensions. 
	Evidence:	this T1w file does not have exactly three dimensions. 

	Type:		Error
	File:		sub-01_ses-18081901_acq-sagmprage_T1w.nii.gz
	Location:		ngfnProject/sub-01/ses-18081901/anat/sub-01_ses-18081901_acq-sagmprage_T1w.nii.gz
	Reason:		_T1w.nii[.gz] files must have exactly three dimensions. 
	Evidence:	this T1w file does not have exactly three dimensions. 


======================================================

and the one suggested @olgn 
https://1597-37161308-gh.circle-artifacts.com/0/root/web_version/index.html

gives no errors...
This is a valid BIDS dataset!

[sub-01_ses-18081901_acq-axfspgr_T1w.txt](https://github.com/INCF/bids-validator/files/2390680/sub-01_ses-18081901_acq-axfspgr_T1w.txt)
[sub-01_ses-18081901_acq-sagmprage_T1w.txt](https://github.com/INCF/bids-validator/files/2390684/sub-01_ses-18081901_acq-sagmprage_T1w.txt)
[Info for sub-01_ses-18081901_acq-axfspgr_T1w_nii.txt](https://github.com/INCF/bids-validator/files/2390686/Info.for.sub-01_ses-18081901_acq-axfspgr_T1w_nii.txt)
[Info for sub-01_ses-18081901_acq-sagmprage_T1w_nii.txt](https://github.com/INCF/bids-validator/files/2390687/Info.for.sub-01_ses-18081901_acq-sagmprage_T1w_nii.txt)

**Comment by benoitberanger** [comment]
Great thank you guys for your help !
