### ISSUE TITLE
refactor bids.js

### ISSUE THREAD

**Issue by olgn** [bids-standard/legacy-validator#570]
bids.js, most notably fullTest(), has become too big for its britches! the goal of this refactor is to make this code cleaner + more maintainable, and to get rid of the outdated `async` library and use promises instead. maybe codeclimate will stop yelling at us, too...

- [x] separate bids.js into a module, with the different tests (fullTest, quickTest, etc) as module exports.
- [x] refactor and further divide fullTest into more maintainable chunks 
- [x] remove the async library from the bids-validator and substitute promises

**Comment by nellh** [comment]
Maybe we can start moving some tests closer to the code under testing? Especially as things get more complex, it's helpful to find the tests near the code involved. This applies more to unit tests than integration tests which might not have an obviously related file. The usual convention for this is a __tests__ directory in the same directory as the source files being tested.

**Comment by olgn** [comment]
@nellh sure, added to the to-do list

**Comment by olgn** [comment]
as of #574 all this needs is the updates to the tests allowed by the refactor

**Comment by olgn** [comment]
closing this, as the remaining test refinement is ongoing and convenient to do over time as we develop, rather than a heavy lift to increase coverage.
