### ISSUE TITLE
Bogus "custom column without description" warning

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#577]
Context: https://neurostars.org/t/tabular-file-contains-custom-columns-not-described-in-a-data-dictionary/2513

**Comment by bGrass** [comment]
I'm not able to recreate this.  I was able to resolve the custom column warnings on a test dataset by adding a data dictionary in the same format this user posted.

**Comment by olgn** [comment]
should be fixed with #631
