### ISSUE TITLE
[MAINT] Add a coverage CI tool

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#587]
It would be a great help to have a coverage tool together with the other continuous integration services we are using with this repo.

@jasmainak has proposed https://istanbul.js.org/

**Comment by jasmainak** [comment]
I don't know what is the standard in javascript community :) That's what I found by google search ...

**Comment by nellh** [comment]
Istanbul is great, we're using it with Jest and Codecov on OpenNeuro. Since we're not using Jest here, it requires a little manual setup but not much.

Codecov is nice to easily see the output from Istanbul on pull requests.

**Comment by nellh** [comment]
@chrisfilo Can you add the Codecov GitHub app to the repo? Looks like I don't have access to add it. Everything else should be configured already.

https://github.com/marketplace/codecov/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4xNg==#pricing-and-setup

**Comment by chrisgorgo** [comment]
Should be done now.

Best,
Chris
