### ISSUE TITLE
Automate release notes via Chronicler

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#589]
https://github.com/NYTimes/Chronicler

**Comment by nellh** [comment]
Another interesting option here is [semantic-release](https://github.com/semantic-release/semantic-release#readme) which does this but also automates tagging the releases. The disadvantage of semantic-release vs chronicler is it requires commit messages to follow a [specific format](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) that may be hard for everyone to follow.
