### ISSUE TITLE
Only push build artifacts to GitHub pages

### ISSUE THREAD

**Issue by nellh** [bids-standard/legacy-validator#595]
Right now the validator is built with browserify and grunt on releases by combining the web version in the gh-pages branch and importing the package from the master branch. If we made a few changes, we could do this build on the master branch and only push the built artifacts to gh-pages. There's a few advantages of this approach.

1. It would remove the need to split the web validator development into patches across two branches.
1. The browser version would be easier to test for a given change (no "did I get the right version into my github-pages build?") since you wouldn't need to mess around with two branches.
1. New features like #593 would be easier to implement if the libraries were maintained in the main branch and tests could be written for the web components along with the main test suite.
1. It is more discoverable for new contributors if it is on the main branch.

What needs to happen for this:

- [ ] Need to move the existing app to the master branch.
- [ ] Update the web version to current dependencies should happen, many of the web validator dependencies are very out of date and would need to be consolidated with the main branch.
- [ ] Switch to a more modern bundler (Rollup or Webpack 4). Might be optional but could simplify this setup.

**Comment by chrisgorgo** [comment]
This make debugging the web validator easier.

**Comment by jasmainak** [comment]
yes I remember I struggled with this. It would be a great change!
