### ISSUE TITLE
[BUG] sidecar without datafile ... although there is one

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#600]
I encountered an error that looks like a bug:

#### 1. Defining a `.json` sidecar very close to the data can yield:
>	1: [ERR] A json sidecar file was found without a corresponding data file (code: 90 - SIDECAR_WITHOUT_DATAFILE)

example: for [ds001](https://github.com/bids-standard/bids-examples/tree/master/ds001), try to define a file: `ds001/sub-02/func/sub-02_task-balloonanalogrisktask_run-01_events.json` and run the validator.

--> This should not yield an error, because the corresponding data file exists (ds001/sub-02/func/sub-02_task-balloonanalogrisktask_run-01_events.tsv`)

**Comment by chrisgorgo** [comment]
I think those two issues are unrelated - would you mind splitting them?

**Comment by sappelhoff** [comment]
okay, no problem

**Comment by chrisgorgo** [comment]
got another report of this bug with `sub-01_ses-01_task-Stroop_acq-cf1PA_run-02_physio.json` and `sub-01_ses-01_task-Stroop_acq-cf1PA_run-02_physio.tsv.gz` files
