### ISSUE TITLE
 [BUG] sidecar not part of BIDS spec ... although it is

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#601]
I encountered an error that looks like a bug:

#### 1.  Defining a `.json` sidecar very close to the data can yield:
> 1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)

example: for [eeg_matchingpennies](https://github.com/bids-standard/bids-examples/tree/bep006_eeg/eeg_matchingpennies), try to define a file: `eeg_matchingpennies/sub-05/eeg/sub-05_task-matchingpennies_events.json` and run the validator with the `--bep006` flag.

--> This should not yield an error, because it is perfectly fine to have a .json sidecar for a .tsv datafile at any directory level.

**Comment by chrisgorgo** [comment]
Could this be an issue with bep006 regexps?

**Comment by sappelhoff** [comment]
I would appreciate some help with this ... asking some of the frequent committers in this repo:  @olgn @nellh @DaNish808 

reproduce:
```bash
# prepare
git clone https://github.com/bids-standard/bids-examples
cd bids-examples
git checkout bep006_eeg
cd eeg_matchingpennies

# test ... no issues
bids-validator --bep006 .

# create the issue ... we want to define a JSON file to
# accompany the events.tsv file (this is perfectly fine and
# sometimes even required, e.g., when having non-custom
# column names in events.tsv)
touch sub-05/eeg/sub-05_task-matchingpennies_events.json

# test ... get an Error `Files with such naming scheme are not part of BIDS specification`
bids-validator --bep006 .
```

**Comment by chrisgorgo** [comment]
This also looks like an issue with regular expressions. Did you check us
they cover EEG events on all folder hierarchies?
