### ISSUE TITLE
bleeding edge validator shows version 0.0.0

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#602]
When using the bids-validator in the master repo and the /bin directory, it yields 0.0.0 as its version.

`bids-validator/bin/bids-validator --version`

Shouldn't this be 1.0.1.dev (whatever the current version is) or similar?

**Comment by chrisgorgo** [comment]
Possibly - wouldn't say this is the most pressing issue though :)

**Comment by sappelhoff** [comment]
I agree ... but it might be easy to address:

I think this is something that is related to how the `package.json` is dealt with. Basically, whenever somebody makes a new release, they can call

`npm version minor` ... or `patch` or `major`, which will automatically create a commit that bumps up the version here:

https://github.com/bids-standard/bids-validator/blob/5bf12b4f24fe0fb9072e4aa3454e78ec02d40a50/package.json#L3

(major.minor.patch)

I don't know how releases are currently handled, but this is a small step that could be added to the pipeline :-)

**Comment by yarikoptic** [comment]
confirming:
```shell
$> docker pull bids/validator
Using default tag: latest
latest: Pulling from bids/validator
a073c86ecf9e: Pull complete 
becc6a89816a: Pull complete 
fa183c3e7c21: Pull complete 
4ae42d442676: Pull complete 
3069b9cb26a0: Pull complete 
Digest: sha256:cedebddf3ea2f014be3df1160ca72e5fdedb1cbc3a2825401f98fcd4ee5772dd
Status: Downloaded newer image for bids/validator:latest

$> docker run -it --rm bids/validator --version 
0.0.0
```

**Comment by yarikoptic** [comment]
that is what I would call the **stablest** version:
```shell
$> docker pull bids/validator:latest
latest: Pulling from bids/validator
Digest: sha256:cedebddf3ea2f014be3df1160ca72e5fdedb1cbc3a2825401f98fcd4ee5772dd
Status: Image is up to date for bids/validator:latest

$> docker run -it --rm bids/validator --version 
0.0.0
```

**Comment by sappelhoff** [comment]
> that is what I would call the stablest version:

What do you mean by that?

**Comment by yarikoptic** [comment]
> > that is what I would call the stablest version:
> 
> What do you mean by that?

The **stablest** was meant to mean The **most stable** version.
That was just yet another form of my whiny ping to hopefully see a resolution to this seemingly easy/trivial to fix issue.  Sure thing it is not a ground breaking issue, but quite annoying to not be able to know what version is used.

**Comment by sappelhoff** [comment]
@chrisfilo perhaps you could tell us a bit more about the steps that are being done for each release of the bids-validator.

Using that description of the workflow, we might come up with an easy fix to this issue.

**Comment by chrisgorgo** [comment]
A new release is triggered by creating a new Release on github, which is picked up by a) circle and pushed to npm (see https://github.com/bids-standard/bids-validator/blob/master/circle.yml#L45) as well as b) docker hub (which automatically builds any tagged release).

Please note that `--version` works correctly when bids-validator is installed using npm. 

```
filo@MSI MINGW64 ~
$ npm install -g bids-validator
C:\Users\filo\AppData\Roaming\npm\bids-validator -> C:\Users\filo\AppData\Roaming\npm\node_modules\bids-validator\bin\bids-validator

> date-fns@2.0.0-alpha.25 postinstall C:\Users\filo\AppData\Roaming\npm\node_modules\bids-validator\node_modules\date-fns
> node ./docs/printV2Notice.js


������������������������������������������������������������������
�����������
  Thank you for testing (⩗) date-fns v2!

  In v2 we've introduced a number of breaking changes
  that make date-fns even more consistent and reliable.
  Please read the changelog carefully: https://git.io/fxCWb

  Please support us at Open Collective: https://opencollective.com/date-fns

������������������������������������������������������������������
�����������
+ bids-validator@1.1.1
added 133 packages from 125 contributors in 32.762s

filo@MSI MINGW64 ~
$ bids-validator --version
1.1.1
```

**Comment by sappelhoff** [comment]
Thanks! Yes, if we install stable versions hosted on npm, we can get the proper version number. But for any bids-validator installed via github (e.g., the latest version, using ``), we do get `0.0.0`, which is because of this line (reiterating what I said before): https://github.com/bids-standard/bids-validator/blob/5bf12b4f24fe0fb9072e4aa3454e78ec02d40a50/package.json#L3

Perhaps we could sneak a line into the `circle.yml` file which updates that line to something like `*whatever the current version*.dev` upon each release (triggered via github). What do you think @yarikoptic ?

**Comment by yarikoptic** [comment]
well, I see that there is already such "sneak line" at https://github.com/bids-standard/bids-validator/blob/master/circle.yml#L59
```
     # Set the version number
      - run: sed -i -E "s/0.0.0/$CIRCLE_TAG/" package.json
```
but I wonder if order of lines isn't "reversed" (warning: I have no clue in node/npm ;-)) from what it should be and that line should come earlier -- I will send a PR so someone more knowledgeable could assess
