### ISSUE TITLE
"This does not appear to be BIDS dataset" for BIDS dataset with "derivatives" folder

### ISSUE THREAD

**Issue by jpellman** [bids-standard/legacy-validator#61]
When I run the BIDS validator on a BIDS dataset that contains a "derivatives" folder, it gives me the following error and then stops:

"This does not appear to be a BIDS dataset. For more info go to http://bids.neuroimaging.io/"

I tried temporarily removing the "derivatives" folder, and that allowed it to continue.

**Comment by constellates** [comment]
This sounds like our quick test to check if the structure looks generally BIDS-like needs to make an exception for the "derivatives" folder. I'll take a look.

**Comment by constellates** [comment]
Try that fix out when you have a chance and let us know if that worked for you. It should be on the master branch and up to date on NPM now if your using the command line version and want to update. Otherwise the github pages demo site is also up to date. http://incf.github.io/bids-validator/

**Comment by jpellman** [comment]
It works!  Thanks!
