### ISSUE TITLE
Erroneous CUSTOM_COLUMN_WITHOUT_DESCRIPTION raised on the web, but not CLI

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#619]
Tested with 1.0.3 CLI and http://bids-standard.github.io/bids-validator/

Dataset: https://wetransfer.com/downloads/cfaf88073166683ea5d30cee9a3742f720181010194153/131627
Context: https://neurostars.org/t/tabular-file-contains-custom-columns-not-described-in-a-data-dictionary/2513/5

**Comment by olgn** [comment]
the root of this issue is that (at least in the dataset linked above) is that the new line character for .tsv file is `/r/n`, instead of the `/n` that we expect to see throughout the validator

**Comment by olgn** [comment]
the validator currently only supports unix / mac osx new line charactes `/n`
