### ISSUE TITLE
Publish ES5 compatible library to npm

### ISSUE THREAD

**Issue by nellh** [bids-standard/legacy-validator#625]
We should publish some more compatible module formats with a prepublish hook. This would make it easier for downstream JavaScript packages to use the validator with differing build requirements (such as browser targets). [Rollup](https://rollupjs.org/guide/en) should work for this.

See https://github.com/OpenNeuroOrg/openneuro/pull/954 for some more context.

**Comment by rwblair** [comment]
Closing in favor of #869
