### ISSUE TITLE
Redirect incf.github.io/bids-validator to bids-standard.github.io/bids-validator

### ISSUE THREAD

**Issue by effigies** [bids-standard/legacy-validator#626]
Existing slide decks and references point people to the old URL. We should help people along. Should be easy to do in a repository at https://github.com/INCF/incf.github.io, adding a `bids-validator/index.html` file that redirects.

**Comment by rwblair** [comment]
Recreated https://github.com/INCF/bids-validator and set its github pages (https://incf.github.io/bids-validator/ ) to redirect to https://bids-standard.github.io/bids-validator/
