### ISSUE TITLE
Provide error/warning specific url to neurostars search for each error/warning

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#628]
E.g. 
https://neurostars.org/search?q=Repetition%20time%20did%20not%20match%20between%20the%20scan%E2%80%99s%20header%20and%20the%20associated%20JSON%20metadata%20file

if error talks about "Repetition time did not match between the scan’s header and the associated JSON metadata file"

**Comment by yarikoptic** [comment]
or just by the "error codename": https://neurostars.org/search?q=JSON_SCHEMA_VALIDATION_ERROR

**Comment by olgn** [comment]
@chrisfilo @yarikoptic do y'all think this link should be available in the console summary? or just in the browser?

**Comment by chrisgorgo** [comment]
many terminals automatically parse URLs and make them actionable so I think it might be worthwhile
