### ISSUE TITLE
Raise a warning if there is only one author and its name includes a comma

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#629]
We want to catch situations like this
```
"Authors": [
        "Name1, O., Name2, J., Name3, D., & Name4, K.A."
    ]
```

**Comment by nellh** [comment]
Maybe this could also raise an error for multiple commas? There's often authors with a useful comma but not more than one comma looking at the OpenNeuro datasets.

**Comment by chrisgorgo** [comment]
+1
