### ISSUE TITLE
Automatic Builds in Dockerhub

### ISSUE THREAD

**Issue by pvelasco** [bids-standard/legacy-validator#633]
Hi,

Since you moved the repository to bids-standard/bids-validator, the automatic Docker builds in Dockerhub don't work, so the latest one there is v.0.27.10

I suspect you will have to create a new "Automatic Build" linked to the new Github repository.

Thanks!

**Comment by olgn** [comment]
@chrisfilo we don't have access to do this, could you get this setup?

**Comment by chrisgorgo** [comment]
I fixed this on docker cloud. We'll see on the next release if it works.

**Comment by chrisgorgo** [comment]
It works: https://cloud.docker.com/u/bids/repository/docker/bids/validator/tags

**Comment by pvelasco** [comment]
Hi @chrisfilo.  Sorry to be a pain in the neck.  The automated build works for the new tags (1.0.5), but the `:latest` corresponds to an old build.  Maybe you can add a second "Automatic Build" for that repository, so that any new tag pushed to Github also triggers a build with label "latest"?

Thanks!

**Comment by chrisgorgo** [comment]
thanks for reporting. added a new rule - we should see if it works at the next release
