### ISSUE TITLE
Roadmap for supporting/checking BIDS Common Derivative(s) (BEP003 etc)?

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#637]
Living without validation by bids-validator now feels like venturing into the unknown... While we try to prepare **kosher** BIDS Derivative datasets, I wondered what is the plan for adding validation support for those within bids-validator?

Thank you in advance for the clarification!

**Comment by chrisgorgo** [comment]
I hope to have something covering [BIDS Derivatives RC1](https://docs.google.com/document/d/17ebopupQxuRwp7U7TFvS6BH03ALJOgGHufxK8ToAvyI/edit#heading=h.mqkmyp254xh6) by the beginning of next week

**Comment by yarikoptic** [comment]
Awesome, thank you @chrisfilo !

**Comment by sappelhoff** [comment]
Now that common derivatives are finally merged, we are planning to open discrete issues and corresponding PRs to implement validation checks.

This will be tracked in https://github.com/bids-standard/bids-validator/projects/1 ... so if you have ideas for issues, please open them and add them to the project.

**Comment by yarikoptic** [comment]
as that project is completely empty, I would say "there is no roadmap" I think this issue could as well be reopened

**Comment by sappelhoff** [comment]
I see 19 to do issues, and 1 done on that project board. What do you mean by empty?

**Comment by yarikoptic** [comment]
I have opened it again and they appeared.  I swear it was empty when I have tried! ha -- sorry for the noise, and I will just blame github!
