### ISSUE TITLE
Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1538084632897/phantomjs-2.1.1-macosx

### ISSUE THREAD

**Issue by ckrountree** [bids-standard/legacy-validator#642]
Links back to OpenNeuro:  https://github.com/OpenNeuroOrg/openneuro/issues/931

**Comment by sappelhoff** [comment]
closing based on @nellh's comment https://github.com/OpenNeuroOrg/openneuro/issues/931#issuecomment-429513441
