### ISSUE TITLE
Improve the developer documentation

### ISSUE THREAD

**Issue by choldgraf** [bids-standard/legacy-validator#646]
Right now the developer documentation is very sparse:

https://github.com/bids-standard/bids-validator#development

In particular, it assumes that:

1. The developer knows Javascript, and already has it installed
2. The developer understands `npm` and already has it installed
3. The developer understands the general structure of the repository

I think that we cannot assume that any of these is true for the typical "user" audience of the bids-validator. The developer docs could be improved to make this project a bit more welcoming to new contributors who may not be javascript devs.

**Comment by choldgraf** [comment]
cc @KirstieJane as maybe she has thoughts on this

**Comment by jasmainak** [comment]
I agree. I was initially quite confused about the "Running Locally on a Browser" part which you need only if you want to build the html. It would be better to squash this into a makefile or something like that. I had my own little script to push my fork of the built html which looked like this:

```py
sed -i -E "s#latest#../bids-validator/#" package.json
npm install
node_modules/.bin/gulp build
git commit dist/ --allow-empty -m "Validator demo update"
git push origin gh-pages
```

**Comment by marcocastellaro** [comment]
I am trying to develop the ASL module for BIDS and @sappelhoff suggested me to ask here for any issues, since it might help future users of the development documentation. 

I cloned the repository, installed npm, node, yarn, react and next packages and I can now run bids-validator in my local terminal, I have also tried the python version and it is working too.

However, I have some difficulties with this bit in the documentation:

> "To develop bids-validator and see how it will act in the browser, simply run `yarn web-develop` in the project root and navigate to localhost:3000"

I do understand that this is to build the html version of the bids validator on a local web-server but I got this error and still I do not understand why, could you please help me?

> yarn run v1.15.2
error Command "web-develop" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by choldgraf** [comment]
you may need to move one folder deeper (`bids-validator/bids-validator`)...that fixed some other issues for me, can you try that?

**Comment by marcocastellaro** [comment]
@choldgraf yes, sure: I tried more or less the all sub-tree of the project root `bids-validator`

```
bids-validator
bids-validator/bids-validator
bids-validator/bids-validator-web
```

but still I am encountering the same issue. Not sure I am missing some steps?

**Comment by sappelhoff** [comment]
perhaps @rwblair can help?

**Comment by marcocastellaro** [comment]
@sappelhoff I solved the issue in this way, a bit unintuitive for me but it worked. I had to go in the `bids-validator/bids-validator-web` folder and I had to install the dependency with the following commands:
```
npm install next
npm install react
npm install react-dom
```

and, always from the same folder, I had to run the build with next `next build`.
Afterwards, I started the application with 
`yarn start`

now I can access the server from my localhost:3000.

I still can't run  `yarn web-develop` anyway. Could it be that my yarn version or node have some trouble with the command?

Perhaps there is a better way to do this, it might be a good idea to suggest the user that want to develop a new BIDS validator branch and is not familiar with it (like me) that it could be necessary to do all the steps I listed.

**Comment by nellh** [comment]
@marcocastellaro You had it right but the documentation is wrong. It's `yarn web-dev` - I'll submit a PR with the documentation fix. You should only need to clone the repo, run `yarn` (this installs all dependencies for all packages) and then `yarn web-dev`.

You can see which scripts are defined for `yarn <script>` or `npm run <script>` in the scripts property of package.json for reference.

**Comment by marcocastellaro** [comment]
@nellh you are right!! just tried and it works like a charm!! TY

**Comment by jasmainak** [comment]
When I run `yarn` with the master of bids-validator, I get:

```sh
yarn install v1.17.3
warning package-lock.json found. 
Your project contains lock files generated by tools other than Yarn. 
It is advised not to mix package managers in order to avoid resolution 
inconsistencies caused by unsynchronized lock files. 
To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
error eslint@5.16.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0". Got "8.9.4"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I removed `package-lock.json` as they suggest but I still get the same error. Any clues what I should do @nellh ?
