### ISSUE TITLE
Improve error msg when `.bidsignore` is a directory

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#648]
https://openneuro.org/datasets/ds001583/versions/1.0.1

![image](https://user-images.githubusercontent.com/238759/48289640-0d212900-e425-11e8-8b03-aa7e3148bb6b.png)

**Comment by sappelhoff** [comment]
Passing `.bidsignore` as a directory does not seem to be possible anymore:

![image](https://user-images.githubusercontent.com/9084751/84421906-85148e00-ac1c-11ea-8798-c5a74662049e.png)

however, the error message could be improved.

**Comment by sappelhoff** [comment]
closing, we can deal with it in bids-standard/bids-validator#50. The original intent of this issue has been addressed (not accepting directories). In bids-standard/bids-validator#50 we can improve on it with a better failure.
