### ISSUE TITLE
Validation with events.json 

### ISSUE THREAD

**Issue by pbeukema** [bids-standard/legacy-validator#653]
Hi,
I am attempting to upload a new dataset to openNeuro and wish to include metadata associated with the events.tsv in an events.json, which following the online BIDS validation check, I am putting at the top level directory as it is identical across all subjects (I have also put it in sub directories). I receive an error stating the events.json is not a valid file and should be put it the .bidsignore, but at the same time get a warning for each of the corresponding events.tsv columns that the columns are not described by an events.json. I can avoid the Error by simply removing the json but would prefer to keep it in. I appreciate any advice. 
Cheers,
PB

**Comment by chrisgorgo** [comment]
Could you try this version: https://1914-37161308-gh.circle-artifacts.com/0/root/web_version/index.html? (from #654).

**Comment by pbeukema** [comment]
Hey Chris, 
Thank you for the help. I did try that version and the BIDS validator appears to get stuck on the BIDS validating animation (with or without including events.json). Also you had asked me earlier for the tree, the events.tsv and the json. Apologies for not including in the above message. Those are below. 
```json
{
    "onset":{
        "LongName":"Onset Time",
        "Units":"seconds"
    },
    "duration":{
        "LongName":"Duration of Stimulus"
    },
    "trial_type":{
        "LongName":"Trial type",
        "Description":"Movement type sequence (MS*) or Cue Type Sequences (CS*) ",
        "Levels":{
            "MS1":"index, middle, little, index",
            "MS2":"ring, little, middle, little",
            "MS3":"middle, index, ring, middle",
            "MS4":"little, ring, index, ring",
            "CS1":"A,B,D,A",
            "CS2":"C,D,B,D",
            "CS3":"B,A,C,B",
            "CS4":"D,C,A,C"
        }
    },
    "correct":{
        "LongName":"Correct Response",
        "Description":"Boolean, Correct (1) if all responses were correct, Incorrect (0) if any response was incorrect"
    }
}
```
[events.txt](https://github.com/bids-standard/bids-validator/files/2593510/events.txt)
[tree.txt](https://github.com/bids-standard/bids-validator/files/2593511/tree.txt)

**Comment by chrisgorgo** [comment]
Sorry about this. You must've run int https://github.com/bids-standard/bids-validator/issues/655

While that is being fixed. Could you try `/task-cuedMFM_events.json` instead of `/events.json`?

**Comment by pbeukema** [comment]
Yep - that did the trick.
