### ISSUE TITLE
Uncaught TypeError: i.existsSync is not a function

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#655]
On the web version on current master (https://1910-37161308-gh.circle-artifacts.com/0/root/web_version/index.html)

```
Uncaught TypeError: i.existsSync is not a function
    at Object.isGitAnnex (app.min.js:1)
    at app.min.js:1
    at app.min.js:1
    at app.min.js:1
    at Object.t.exports [as readDir] (app.min.js:1)
    at app.min.js:1
    at app.min.js:1
    at app.min.js:1
    at Object.parse (app.min.js:1)
    at app.min.js:1
```
Seems to be related to https://github.com/bids-standard/bids-validator/blob/aa58a07258f398673cea98c041cd028f2a18b3fd/utils/files/remoteFiles.js#L232. @olgn could you have a look?

**Comment by olgn** [comment]
@chrisfilo sure thing
