### ISSUE TITLE
release policy?

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#657]
Is there some information on when developers of other apps can expect a release of the new bids-validator version? Is there some temporal regularity ... or is it based on some features that make it possible to predict the imminence of a release?

asking for MNE-BIDS :-) 

cc @jasmainak @teonbrooks

**Comment by chrisgorgo** [comment]
`master` is currently broken - we can release after https://github.com/bids-standard/bids-validator/pull/656 is merged

**Comment by chrisgorgo** [comment]
I am a bit confused - I don't see any PRs merged into master concerning MEG or EEG since the last release. Am I missing something?

**Comment by sappelhoff** [comment]
We are also working with iEEG data, see #591 :-)

**Comment by chrisgorgo** [comment]
ah I see - done
