### ISSUE TITLE
debug validator for ieeg (bep010): typo in coordsystem.json?

### ISSUE THREAD

**Issue by irisgroen** [bids-standard/legacy-validator#665]
While checking an bids-example dataset (PR#138) for the ieeg (bep010) branch I came across this error which I think may be a bug:

1: [ERR] Invalid JSON file. The file is not formatted according the schema. (code: 55 - JSON_SCHEMA_VALIDATION_ERROR)
		./sub-som682/ses-nyuecog01/ieeg/sub-som682_ses-nyuecog01_coordsystem.json
			Evidence:  should NOT have additional properties

I think it caused by a typo in the validator in the  "iEEGCoordinateProcessingDescription": field of _coordsystem.json, because it passes the validator if the field is labeled iEEGCoordinateProcessingDescrip**ton**

@choldgraf

**Comment by sappelhoff** [comment]
good catch, that's indeed a typo in the validator:

https://github.com/bids-standard/bids-validator/blob/bdec39565eb13dab5e0dd6381975fac85020ec2a/validators/json/schemas/coordsystem_ieeg.json#L7

**Comment by sappelhoff** [comment]
this is fixed now, thanks for reporting @irisgroen !
