### ISSUE TITLE
SUGGESTED: place current version in the online README

### ISSUE THREAD

**Issue by dorianps** [bids-standard/legacy-validator#671]
It might be useful to have the current version of `bids_validator` on the front page. Also, a link to the version changes would be helpful.

We were getting weird errors of good files not being read with v.0.0.0 and just updated to v.1.1.1. Will see if the errors get resolved.

**Comment by chrisgorgo** [comment]
Thanks. When you say front page what do you mean specifically? How did you obtain the validator with version 0.0.0?

**Comment by dorianps** [comment]
`bids-validator --version`

I mean in the main README.md so that a quick peak at the GitHub page can
inform the user if there is any newer version.

**Comment by chrisgorgo** [comment]
I wasn't clear - I was asking how did you install bids-validator. Using npm but pointing to github?

You can find changelogs here https://github.com/bids-standard/bids-validator/releases

**Comment by dorianps** [comment]
Using the npm command shown in the instructions. Also tried to upgrade the
nodejs to v10 last night, not sure of that makes a difference.

Thanks for the changelogs.

**Comment by chrisgorgo** [comment]
Weird - I cannot replicate this issues:
```
(python2) me@christop ~ $ npm --version
6.5.0
(python2) me@christop ~ $ node --version
v11.0.0
(python2) me@christop ~ $ npm install -g bids-validator
C:\Users\me\AppData\Roaming\npm\bids-validator -> C:\Users\me\AppData\Roaming\npm\node_modules\bids-validator\bin\bids-validator

> date-fns@2.0.0-alpha.26 postinstall C:\Users\me\AppData\Roaming\npm\node_modules\bids-validator\node_modules\date-fns
> node ./docs/printV2Notice.js


🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

  Thank you for testing (⩗) date-fns v2!

  In v2 we've introduced a number of breaking changes
  that make date-fns even more consistent and reliable.
  Please read the changelog carefully: https://git.io/fxCWb

  Please support us at Open Collective: https://opencollective.com/date-fns

🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

+ bids-validator@1.1.1
added 133 packages from 125 contributors in 24.496s
(python2) me@christop ~ $ bids-validator --version
1.1.1
```

**Comment by dorianps** [comment]
Thanks.

There is no issue yet. We will check with the new version and open another issue if the problem presents. The error we got with v0.0.0 is number 44 [here](https://github.com/bids-standard/bids-validator/blob/9e57bfb5e9a95868b8acaf5b96610b73988c2458/utils/issues/list.js#L243-L248), and we verified that the file is there, headers are ok, and images look good in ITKsnap.
