### ISSUE TITLE
Assert that if `electrodes.tsv` present, `coordsystem.json` is present as well

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#672]
In `electrodes.tsv`, we specify the coordinates for the electrodes placed on the subjects scalp (EEG), or in/on their brain (iEEG). These coordinates should/must be accompanied by a `coordsystem.json` file.

I suggest that we implement a test that produces an error if `electrodes.tsv` is present, but `coordsystem.json` is not.

`electrodes.tsv` ist always subject specific, `coordsystem.json` could potentially be defined at an upper level and then inherited further downstream in the directory structure.

see the specification:
- [electrodes](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html#electrodes-description-_electrodestsv) rules
- [coordsystem](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html#coordinate-system-json-_coordsystemjson) rules

**Comment by sappelhoff** [comment]
I have prepared a short Python test script for this using the [`eeg_matchingpennies`](https://github.com/bids-standard/bids-examples/blob/master/eeg_matchingpennies) dataset from the bids-examples repository. Simply clone that repo, open an interactive python prompt, paste and run the code ... and use your bids-validator to check eeg_matchingpennies in the bids-examples clone.

# Minimal working example that should raise an error

```Python
import os.path as op

# Set this to point to your bids-examples/eeg_matchingpennies dataset
mp_path = '/home/stefanappelhoff/Desktop/bids/bids-examples/eeg_matchingpennies'

# write electrodes.tsv files
for sub in range(5,12):
    fpath = op.join(mp_path, 'sub-{:02}'.format(sub), 'eeg')
    fname = 'sub-{:02}_task-matchingpennies_electrodes.tsv'.format(sub)
    with open(op.join(fpath, fname), 'w') as fout:
        fout.write('name\tx\ty\tz')

# use BIDS-validator on eeg_matchingpennies ... it passes
# but it SHOULD not (coordsystem.json is missing)
```

# Minimal working example that should pass

```Python
import os.path as op
import json

mp_path = '/home/stefanappelhoff/Desktop/bids/bids-examples/eeg_matchingpennies'

# define a standard coordsystem.json for example reasons
coords = dict(EEGCoordinateUnits='mm', EEGCoordinateSystem='CapTrack')


for sub in range(5,12):
    fpath = op.join(mp_path, 'sub-{:02}'.format(sub), 'eeg')

    # write electrodes.tsv
    fname = 'sub-{:02}_task-matchingpennies_electrodes.tsv'.format(sub)
    with open(op.join(fpath, fname), 'w') as fout:
        fout.write('name\tx\ty\tz')

    # write coordsystem.json
    fname = 'sub-{:02}_task-matchingpennies_coordsystem.json'.format(sub)
    with open(op.join(fpath, fname), 'w') as fout:
        json.dump(coords, fout)

# use BIDS-validator on eeg_matchingpennies ... it passes - and that's good!
# Note however, that *strictly* speaking, we should still fail, because:
# the electrodes.tsv file has no rows beyond the header
```

**Comment by adam2392** [comment]
> In `electrodes.tsv`, we specify the coordinates for the electrodes placed on the subjects scalp (EEG), or in/on their brain (iEEG). These coordinates should/must be accompanied by a `coordsystem.json` file.

Any suggestion on where in the code this would go?

> `electrodes.tsv` ist always subject specific, `coordsystem.json` could potentially be defined at an upper level and then inherited further downstream in the directory structure.

According to the specification, I think they are always housed in the same directory no? or am I reading it wrong?

**Comment by sappelhoff** [comment]
> According to the specification, I think they are always housed in the same directory no? or am I reading it wrong?

@rwblair and me are discussing that right now within https://github.com/bids-standard/bids-specification/issues/528#issuecomment-669935358

what part of the spec makes you think coordsystem and electrodes.tsv are always in the same directory?

> Any suggestion on where in the code this would go?

I don't know :shrug:

**Comment by rwblair** [comment]
Right now there isn't a good way to assert that one file requires another. A file requiring a json file is also a different than most cases when inheritance applies since you need to compose json files at all levels to see if any apply. Here is a PR im working on that checks this for continuous recording files:

bids-standard/bids-validator#1040

The other place we see a file type checking for the existence of another is in the nifit validator:
https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/nifti/nii.js

Right now the sensible place would be somewhere in the tsv validator, like the physio one.

So these are a bunch of hard coded rules that each enforce a part of the spec. @sappelhoff has mentioned this before but it may be time to make a more generic way of specifying file dependence so that they can be encoded as a schema with one set of code to enforce that schema.

**Comment by effigies** [comment]
This is done in the schema validator.
