### ISSUE TITLE
Validator gets stuck when incorrectly passed a string when expecting a number.

### ISSUE THREAD

**Issue by axiezai** [bids-standard/legacy-validator#674]
Hello,

Found a small issue when a youngster in my lab tried to create our first BIDS dataset. 

When entering `RepetitionTime` into the .json files inside the `func` folder, the validator gets stuck on validating and becomes unresponsive when the number entered is mistakenly surrounded by quotation marks as a string, for example: `{"RepetitionTime: "2.0"}`. Took us a while to find this tiny mistake we made, and the validator worked fine after we removed the quotation marks.

Should the validator detect this incorrect syntax and spit out an error saying "RepetitionTime should not be a string"?

**Comment by chrisgorgo** [comment]
This should've been captured by this schema https://github.com/bids-standard/bids-validator/blob/master/validators/json/schemas/bold.json, but for some reason wasn't. Perhaps the order of checks is wrong. @DaNish808 any ideas?

**Comment by rwblair** [comment]
Fixed in master, will have to wait for a new version to be released for it to show up on web validator.
