### ISSUE TITLE
Add a flag to allow empty files

### ISSUE THREAD

**Issue by choldgraf** [bids-standard/legacy-validator#676]
A few times now we've run into issues w/ tests because we're running the validator on empty files:

https://travis-ci.org/bids-standard/bids-examples/builds/471063492#L2009

How do folks think about adding a flag to the validator like `--allow-empty` that would allow empty files to pass the validator, only for use with testing/dev.

**Comment by chrisgorgo** [comment]
The `--ignoreNiftiHeaders` flag was originally intended for testing purposes (https://github.com/bids-standard/bids-validator/blob/master/bin/bids-validator#L14). It might be worth replacing it with something more generic such as `--ignoreEptyFiles`.

Alternatively, you can pass a config file ignoring the `99` error.

**Comment by sappelhoff** [comment]
see also https://github.com/bids-standard/bids-validator/issues/651 and discussion therein

**Comment by choldgraf** [comment]
I'm equally +1 on:

1. Giving an `--ignoreEmptyFiles` flag and using this in the examples
2. Documenting (in the dev docs) the pattern that @sappelhoff described in the bids-examples PR

**Comment by jasmainak** [comment]
+1 also for me!

**Comment by chrisgorgo** [comment]
Are empty files allowed for some MEG datasets?
 https://neurostars.org/t/error-using-bids-validator/3218/9

**Comment by sappelhoff** [comment]
@chrisfilo see #651
