### ISSUE TITLE
Command line & browser validator getting stuck / running out of memory

### ISSUE THREAD

**Issue by mariannnne** [bids-standard/legacy-validator#677]
Hi-- I validated a data set with the in-browser tool. After I made the changes it called for, the validator stopped working for that dataset (works for other datasets).  Changes I made: (1) appended TR info to json files and (2) changed session folder names from ses-1(uniquenumbers) to just ses-1, (3) I renamed anat/my_T1_defaced.nii to subject appropriate names like 'sub-005_ses-18621_T1w.nii' & matched the sidecar.
When I try to validate the folder now it just gets stuck. The web runs for ~10 min then crashes my browser. I let the command line version run over an hour it gave a memory error (pasted below). My dataset is 24.23 GB. Any idea what I could have done that would be causing it to get stuck? It ran fine 4 other times on this folder. Thanks in advance!

I ran this with the actual path (also tried it without any flag options):
bids-validator --verbose --json /PATH/TO/Stanford_MASC/Nifti

Error:
```
<--- Last few GCs --->

[770:0x104800000]  3080259 ms: Mark-sweep 1318.5 (1325.0) -> 1318.5 (1324.5) MB, 8.3 / 0.0 ms  (average mu = 1.000, current mu = 0.002) last resort GC in old space requested
[770:0x104800000]  3080268 ms: Mark-sweep 1318.5 (1324.5) -> 1318.5 (1324.5) MB, 9.0 / 0.0 ms  (average mu = 0.999, current mu = 0.001) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xc27729dbe3d]
Security context: 0x31b061f88bc9 <JSObject>
    1: stringSlice(aka stringSlice) [0x31b0c1524621] [buffer.js:594] [bytecode=0x31b0c15587e1 offset=91](this=0x31b0738826f1 <undefined>,buf=0x31b061ff0cc9 <Uint8Array map = 0x31b074551eb1>,encoding=0x31b061f9e071 <String[4]: utf8>,start=0,end=48759136)
    2: toString [0x31b0b34f1cd1] [buffer.js:667] [bytecode=0x31b0c15582d1 offset=145](this=0x31b061ff0cc9 <...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x10003b125 node::Abort() [/usr/local/bin/node]
 2: 0x10003b32f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001a8e85 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x1005742a2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x10057d7a4 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 6: 0x10054f594 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: 0x10054f1d9 v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 8: 0x1001cb228 v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [/usr/local/bin/node]
 9: 0x1000ddc1a node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [/usr/local/bin/node]
10: 0x100053f9b void node::Buffer::(anonymous namespace)::StringSlice<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
11: 0x10023170f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
12: 0x100230c51 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
13: 0x1002302f0 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0xc27729dbe3d 
Abort trap: 6
```

**Comment by chrisgorgo** [comment]
This sounds similar to  https://neurostars.org/t/fmri-prep-and-slice-time-correction/2902/11

**Comment by mariannnne** [comment]
thanks! i got it working. i think what happened was when i renamed the session folder name, i didn't update the ses portion of the imaging file names, and it must have been spinning its wheels trying to match? not sure, but updating all the imaging file names got me back online. thanks!

**Comment by chrisgorgo** [comment]
The temporary solution might involve increasing node memory: https://stackoverflow.com/a/38560292/616300

**Comment by arnodelorme** [comment]
I get the same error. I have tried 

export NODE_OPTIONS=--max_old_space_size=4096

and it did not help. I have also checked my session files and they are OK. Before that the archive used to pass. **I have tried with 2 different BIDS folders that used to pass**. This is using the flag "--bep006" to check EEG data.

This happened after doing this update.

Updating 4fd11fb..63768cf
Fast-forward
 README.md                                       |  2 +-
 bids_validator/rules/file_level_rules.json      | 18 +++++-------------
 bids_validator/rules/fixed_top_level_names.json |  3 ++-
 bids_validator/rules/session_level_rules.json   |  2 +-
 package.json                                    |  4 ++++
 tests/json.spec.js                              | 49 ++++++++++++++++++++++++++++++++++++++++++++++---
 tests/type.spec.js                              | 14 +++++++-------
 utils/files/remoteFiles.js                      |  8 +++++---
 utils/files/validateMisc.js                     | 20 +++++---------------
 utils/issues/list.js                            |  2 +-
 utils/modalities.js                             |  2 +-
 utils/type.js                                   |  6 +++---
 validators/bids/groupFileTypes.js               |  5 ++---
 validators/json/json.js                         |  9 +++++++--
 validators/json/schemas/coordsystem_ieeg.json   | 24 +++++++++++-------------
 validators/json/schemas/eeg.json                |  6 ++----
 validators/json/schemas/ieeg.json               |  2 +-
 validators/tsv/checkAcqTimeFormat.js            |  5 ++---
 18 files changed, 106 insertions(+), 75 deletions(-)

I have checked out again 4fd11fb (detached head) and my BIDS folders pass no problem.

**Comment by chrisgorgo** [comment]
Another case of memory issue (this time in the browser) https://github.com/bids-standard/pybids/issues/339

**Comment by david-nishi** [comment]
Hi all, could someone give us access to a full not-working dataset (or at including the file tree and events.json/tsv files)? We're having trouble reproducing the error with stripped down datasets.
Thanks!

**Comment by chrisgorgo** [comment]
Another case: https://neurostars.org/t/error-using-bids-validator

**Comment by chrisgorgo** [comment]
Anyone experiencing this error - could you try https://2001-37161308-gh.circle-artifacts.com/0/root/web_version/index.html or

`npm install -g git+https://git@github.com/DaNish808/bids-validator.git#more-memory-#677`

**Comment by ericearl** [comment]
@chrisgorgo or @nellh I don't know that this is fixed...  At least, I just got the out of memory error.  Thanks, ABCD and my 14TB worth of BIDS input data (NIfTI's and JSON's).  :-)  Using the node CLI.  It ran a good while before it gave out.

```
$ bids-validator . --verbose --json > bids_validator.json
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8dc510 node::Abort() [bids-validator]
 2: 0x8dc55c  [bids-validator]
 3: 0xad9b5e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [bids-validator]
 4: 0xad9d94 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [bids-validator]
 5: 0xec7bf2  [bids-validator]
 6: 0xec7cf8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [bids-validator]
 7: 0xed3dd2 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [bids-validator]
 8: 0xed4704 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [bids-validator]
 9: 0xed5b3f v8::internal::Heap::HandleGCRequest() [bids-validator]
10: 0xe74eba v8::internal::StackGuard::HandleInterrupts() [bids-validator]
11: 0x11400c5 v8::internal::Runtime_StackGuard(int, v8::internal::Object**, v8::internal::Isolate*) [bids-validator]
12: 0x206e0d5be1d
Aborted (core dumped)
```
