### ISSUE TITLE
`bold.json` is not valid despite what issue description says

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#680]
![image](https://user-images.githubusercontent.com/238759/50998705-43972500-14f6-11e9-9e4b-762b7dfb76e5.png)
https://neurostars.org/t/bids-problem-naming-scheme-not-recognized/3174

`task` is a compulsory filename keyword for bold

**Comment by chrisgorgo** [comment]
Since `task` filename key is compulsory `/bold.json` is not valid and should not be listed as potential location.

**Comment by olgn** [comment]
@chrisfilo in the example above, `/sub-20/func/sub-20_bold.json`, `sub-20/sub-20_bold.json`, and `bold.json` should also be excluded, correct?

also, are there any other examples of special cases where there is a compulsory key associated with a filetype? if so, could your please point to any locations

**Comment by chrisgorgo** [comment]
> @chrisfilo in the example above, `/sub-20/func/sub-20_bold.json`, `sub-20/sub-20_bold.json`, and `bold.json` should also be excluded, correct?

Correct!
 
> also, are there any other examples of special cases where there is a compulsory key associated with a filetype? if so, could your please point to any locations

None that I am aware of at the moment.
