### ISSUE TITLE
Deploy to PyPI on release

### ISSUE THREAD

**Issue by tyarkoni** [bids-standard/legacy-validator#684]
We need to deploy to PyPI on release; this is currently keeping us from using this package in pybids (instead, we're currently using hard-copied versions of the rules from a few months ago). @effigies, any chance you could help us with this? It will probably take me a lot longer than it would take you...

**Comment by effigies** [comment]
This is JS, not Python. Do you mean to `npm`?

**Comment by jasmainak** [comment]
It is already on npm: https://www.npmjs.com/package/bids-validator

**Comment by effigies** [comment]
I mean, we could create a tiny Python package which is just:

```
bids-validator-config/
    __init__.py
    data/
        rules/
            *.json
```

And push that on release.

**Comment by tyarkoni** [comment]
I'd prefer for the `BIDSValidator` class to live here, since it doesn't depend on the `BIDSLayout` in any way... then it's trivial to import `BIDSValidator` into pybids. And I can see some people wanting to use the validator in Python without necessarily needing anything from pybids.

**Comment by tyarkoni** [comment]
And re: the language, everything in `bids_validator` is Python (including the `BIDSValidator` class).

**Comment by effigies** [comment]
Oh, I did not even notice that. That makes sense. Not today, I think though.
