### ISSUE TITLE
"Not a valid JSON file" error for structural MRI

### ISSUE THREAD

**Issue by ins0mniac2** [bids-standard/legacy-validator#688]
We came across an error where ONLY the command line version 1.1.1 complains about invalid json file. Docker version does not complain. An example json file (extension changed to .txt so it allows the attachment) is attached.
[sub-00000000_ses-01_run-01_T1w.txt](https://github.com/bids-standard/bids-validator/files/2754084/sub-00000000_ses-01_run-01_T1w.txt)

**Comment by chrisgorgo** [comment]
Thanks for sharing. I could not replicate this issue when injecting the provided JSON file into another dataset (using native installation outside of docker). I suspect there is something wrong with your local installation (especially considering other reports #675). I recommend upgrading node and reinstalling bids-validator.

**Comment by ins0mniac2** [comment]
OK we will get back to you after suggested upgrade/reinstall and retest. Thanks.

**Comment by rwblair** [comment]
@sandhitsu Feel free to reopen if issue persists.
