### ISSUE TITLE
Inheritance principle does not seem to apply for a single, real fieldmap image (case 3) JSON

### ISSUE THREAD

**Issue by jpellman** [bids-standard/legacy-validator#69]
I have a fieldmap JSON at the root of a BIDS directory.  This JSON contains a "Units" field to be inherited by nested NifTIs with the optional "IntendedFor" field omitted.  I've tried two file names for the fieldmap JSON, neither of which seem to work: ses-NFB3_fieldmap.json and fieldmap.json.

> ```
>    1: You have to define 'Units' for this file. (code: 17)
>            /sub-A00037112/ses-NFB3/fmap/sub-A00037112_ses-NFB3_fieldmap.nii.gz
>            /sub-A00038998/ses-NFB3/fmap/sub-A00038998_ses-NFB3_fieldmap.nii.gz
>            /sub-A00052181/ses-NFB3/fmap/sub-A00052181_ses-NFB3_fieldmap.nii.gz
>            /sub-A00052340/ses-NFB3/fmap/sub-A00052340_ses-NFB3_fieldmap.nii.gz
>            /sub-A00054504/ses-NFB3/fmap/sub-A00054504_ses-NFB3_fieldmap.nii.gz
>            /sub-A00054857/ses-NFB3/fmap/sub-A00054857_ses-NFB3_fieldmap.nii.gz
>            /sub-A00054914/ses-NFB3/fmap/sub-A00054914_ses-NFB3_fieldmap.nii.gz
>            /sub-A00055121/ses-NFB3/fmap/sub-A00055121_ses-NFB3_fieldmap.nii.gz
>            /sub-A00055373/ses-NFB3/fmap/sub-A00055373_ses-NFB3_fieldmap.nii.gz
>            /sub-A00055446/ses-NFB3/fmap/sub-A00055446_ses-NFB3_fieldmap.nii.gz
>            /sub-A00055447/ses-NFB3/fmap/sub-A00055447_ses-NFB3_fieldmap.nii.gz
>            /sub-A00055738/ses-NFB3/fmap/sub-A00055738_ses-NFB3_fieldmap.nii.gz
>            /sub-A00056452/ses-NFB3/fmap/sub-A00056452_ses-NFB3_fieldmap.nii.gz
>            /sub-A00057005/ses-NFB3/fmap/sub-A00057005_ses-NFB3_fieldmap.nii.gz
>            /sub-A00057035/ses-NFB3/fmap/sub-A00057035_ses-NFB3_fieldmap.nii.gz
>            /sub-A00057182/ses-NFB3/fmap/sub-A00057182_ses-NFB3_fieldmap.nii.gz
> 
>    1: This file is not part of the BIDS specification, make sure it isn't included in the dataset by accident. >Data derivatives (processed data) should be placed in /derivatives folder. (code: 1)
>            /ses-NFB3_fieldmap.json
>                    Evidence: ses-NFB3_fieldmap.json
> ```

**Comment by chrisgorgo** [comment]
This indeed looks like a bug. Thanks for reporting!

**Comment by chrisgorgo** [comment]
Could you try this branch and see if you still get this error? https://github.com/chrisfilo/bids-validator/tree/fix/topLevelFieldmaps
