### ISSUE TITLE
Files such as `/participants` are listed in summary as modalities

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#704]
![image](https://user-images.githubusercontent.com/238759/52449373-f48be200-2aeb-11e9-8224-d932d39896f9.png)

**Comment by sappelhoff** [comment]
+1, same error for me

**Comment by irisgroen** [comment]
+1, I get the same error running command line validator `using bids-validator --bep010 ./ieeg_visual_multimodal/`as part of testing for ieeg bids-examples https://github.com/bids-standard/bids-examples/pull/138
