### ISSUE TITLE
write a mock OpenNeuro (integration) test

### ISSUE THREAD

**Issue by ckrountree** [bids-standard/legacy-validator#705]

**Comment by nellh** [comment]
This should replicate both entrypoints into the validator from OpenNeuro with a variety of test datasets, similar to the existing tests. The uploader embeds the validator and makes a call to BIDS.validate expecting a callback. Datalad-service runs the command line validator with the `--json` flag and should always get a stable valid JSON object (at least showing error 0 in case of non-zero exits).
