### ISSUE TITLE
brainvision-validator breaks web validator 

### ISSUE THREAD

**Issue by olgn** [bids-standard/legacy-validator#718]
#710 improves browser testing and lead to the following discovery: the recently implemented #701 introduced a dependency (on brainvision-validator) that breaks the web validator. this package relies on the `fs` api, which is node specific and incompatible with the browser. see `bids-validator/utils/files/readFile.js` ('isNode' variable + conditional logic) for how this is discrepancy being handled in the current code-base.

**Comment by olgn** [comment]
@chrisfilo this issue is a breaking change on the web validator and as such we should not publish a new version until it is resolved

**Comment by olgn** [comment]
@sappelhoff let me know if you would like input / prs to `brainvision-validator` to make it browser-compatible.

**Comment by chrisgorgo** [comment]
Thanks for catching this @olgn!

**Comment by sappelhoff** [comment]
@olgn 

> prs to `brainvision-validator` to make it browser-compatible.

PRs of any kind are welcome! Thanks for offering

**Comment by sappelhoff** [comment]
Hi @olgn, I am planning to overhaul the brainvision-validator. Is there something other than the `fs` package that would be creating problems? 

When alternative to `fs` do you suggest I use?

EDIT: A better question would be: How can I check the packages and modules I potentially want to use for compatibility with our bids-validator?

**Comment by olgn** [comment]
@sappelhoff sadly, there is not a file-access api that is consistent with both node and the browser. We need to handle cases where the filesystem is accessed in node with `fs`, and those where accessed through the browser with the [File API](https://developer.mozilla.org/en-US/docs/Web/API/File)

one suggestion would be to create two separate entrypoints for the application via the `package.json` file -  one defined in `main` which handles node imports of the package and one in `browser` which handles imports of the package from the browser. these are defined [here](https://docs.npmjs.com/files/package.json#main). Then ensure that the entrypoint defined in `main` only uses the node file access api, and the entrypoint defined in `browser` only refers to the File API. 

to answer the 'EDIT' above - a simple way to check packages and modules for web imports is to import them in a simple web application. you can build such an app with any js framework you like - the underlying browser apis will remain the same.

**Comment by chrisgorgo** [comment]
@olgn do you think it would make sense (in the long term) to refactor our filesystem access module as a separate package that could be reused in other packages?

**Comment by olgn** [comment]
@chrisfilo that could be a good idea. Additionally, some attempts toward an environment agnostic file access package have been made - like [BrowserFS](https://github.com/jvilk/BrowserFS). Perhaps refactoring to use this would be helpful.
