### ISSUE TITLE
Deployment fails with `error: branch 'gh-pages' not found.`

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#721]
```
#!/bin/sh -eo pipefail
git branch -D gh-pages
error: branch 'gh-pages' not found.
Exited with code 1
```
More details: https://circleci.com/gh/bids-standard/bids-validator/2268

@olgn @DaNish808

**Comment by olgn** [comment]
@chrisfilo this is due to the recent changes in #710. I'll look into it today.
