### ISSUE TITLE
"Missing package name" error

### ISSUE THREAD

**Issue by choldgraf** [bids-standard/legacy-validator#723]
All of a sudden I cannot install the validator with `npm install -g`. When I do so, I get the following error:

```
Can't install ....../bids-validator: Missing package name
```

I'm running from the master branch. I've tried updating my node and re-running `yarn`. Can anybody point me in the right direction?

**Comment by chrisgorgo** [comment]
Perhaps @olgn can help

**Comment by nellh** [comment]
> All of a sudden I cannot install the validator with `npm install -g`. When I do so, I get the following error:
> 
> ```
> Can't install ....../bids-validator: Missing package name
> ```
> I'm running from the master branch. I've tried updating my node and re-running `yarn`. Can anybody point me in the right direction?

What version of npm are you using? I think we did break npm prior to 6 with the changes in #710 - and yarn is required to run tests at the moment (npm 7 will include the required fixes for cross package tests).

If you are using npm 6, make sure you don't have a rogue node_modules directory, npm will follow the directory tree upwards until it finds one which can result in conflicts.

**Comment by choldgraf** [comment]
Thanks for the ideas!  I'm on npm version 6.7.0.

I tried deleting everything in the bids-validator folder, then re-installing, but still no success. FWIW here is the log:

<details>
<pre>
0 info it worked if it ends with ok
1 verbose cli [ '/home/knight/holdgraf/anaconda/bin/node',
1 verbose cli   '/home/knight/holdgraf/anaconda/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g' ]
2 info using npm@6.7.0
3 info using node@v11.10.0
4 verbose npm-session 5299f31d64ede8a8
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 info lifecycle @~prepack: @
8 info lifecycle @~postpack: @
9 silly pacote directory manifest for undefined@file: fetched in 914ms
10 timing stage:loadCurrentTree Completed in 944ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
16 silly install loadAllDepsIntoIdealTree
17 timing stage:rollbackFailedOptional Completed in 1ms
18 timing stage:runTopLevelLifecycles Completed in 951ms
19 verbose stack Error: Can't install /home/knight/holdgraf/github/forks/python/neuro/bids-validator: Missing package name
19 verbose stack     at hasMinimumFields (/home/knight/holdgraf/anaconda/lib/node_modules/npm/lib/install/validate-args.js:26:15)
19 verbose stack     at Array.<anonymous> (/home/knight/holdgraf/anaconda/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/home/knight/holdgraf/anaconda/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19 verbose stack     at chain (/home/knight/holdgraf/anaconda/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
19 verbose stack     at /home/knight/holdgraf/anaconda/lib/node_modules/npm/lib/install/validate-args.js:16:5
19 verbose stack     at /home/knight/holdgraf/anaconda/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
19 verbose stack     at Array.forEach (<anonymous>)
19 verbose stack     at /home/knight/holdgraf/anaconda/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
19 verbose stack     at Array.forEach (<anonymous>)
19 verbose stack     at asyncMap (/home/knight/holdgraf/anaconda/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
19 verbose stack     at module.exports (/home/knight/holdgraf/anaconda/lib/node_modules/npm/lib/install/validate-args.js:15:3)
19 verbose stack     at Array.<anonymous> (/home/knight/holdgraf/anaconda/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/home/knight/holdgraf/anaconda/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19 verbose stack     at chain (/home/knight/holdgraf/anaconda/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
19 verbose stack     at Installer.loadAllDepsIntoIdealTree (/home/knight/holdgraf/anaconda/lib/node_modules/npm/lib/install.js:477:3)
19 verbose stack     at Array.<anonymous> (/home/knight/holdgraf/anaconda/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
20 verbose cwd /home/knight/holdgraf/github/forks/python/neuro/bids-validator
21 verbose Linux 2.6.32-754.el6.x86_64
22 verbose argv "/home/knight/holdgraf/anaconda/bin/node" "/home/knight/holdgraf/anaconda/bin/npm" "install" "-g"
23 verbose node v11.10.0
24 verbose npm  v6.7.0
25 error Can't install /home/knight/holdgraf/github/forks/python/neuro/bids-validator: Missing package name
26 verbose exit [ 1, true ]
</pre>
</details>

**Comment by nellh** [comment]
Is this to install your local checkout as a global binary? This should still work but it is the one case where you'll need to run `npm install -g` in the new bids-validator subdirectory, since that's the new root of the main package.

```shell
cd /home/knight/holdgraf/github/forks/python/neuro/bids-validator/bids-validator && npm install -g
```

**Comment by choldgraf** [comment]
ahhh that was the problem. thanks so much for the help :-)

FWIW, I was following the instructions here: https://github.com/bids-standard/bids-validator#development and didn't see anything about `cd`ing into a subdirectory. We should make sure that developer instructions stay up-to-date with changes in the repo so folks don't get frustrated

**Comment by nellh** [comment]
That was missed with all the documentation fixes in #710, I've submitted #727 to add the extra cd step.

**Comment by choldgraf** [comment]
no worries, and thanks for helping me :-) documentation is always the hardest thing to keep updated since it usually exists in many forms and places!

**Comment by sappelhoff** [comment]
This is relevant to the https://github.com/bids-standard/bids-examples repository, where `bids-validator` is not installed properly anymore in the Travis CI:

https://travis-ci.org/bids-standard/bids-examples/builds/498363631?utm_source=github_status&utm_medium=notification

Any idea how to solve this?

**Comment by nellh** [comment]
@sappelhoff I think it is generally better to use the registry version in cases where we don't want or need to test unreleased changes, I've opened a PR against bids-examples to switch the install over to the npm release.

**Comment by sappelhoff** [comment]
Okay, thanks @nellh !
