### ISSUE TITLE
Pickup config from a dataset at some standard location

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#741]
ATM config should be specified in the command line. Since config quite often dataset specific, such configuration would be stored within the dataset.  To not breed various user-specific paths, would be nice to standardize location of such a config (e.g. `.bids-validator.cfg`) and pick it up by default.  It would then require an option to avoid loading it though (e.g. an empty config path in `-c`?)

Might interact with bids-standard/bids-validator#294

**Comment by yarikoptic** [comment]
ha ha - was looking for something like that and found that me-in-the-past already expressed himself.  I wish I knew JS enough to not break things, then I would have submitted a PR ;-)

**Comment by yarikoptic** [comment]
I found myself again here! amazing!  So is there a perspective to have this issue addressed (or at least commented on), or I will just keep talking to the past myself here? ;)

**Comment by effigies** [comment]
This is definitely beyond my JS knowledge, so I don't even have a sense of how great an effort this would be.

@62442katieb Do you happen to have some time to prod at this?

@yarikoptic Do you know any JS developers?

**Comment by nellh** [comment]
I've added a quick version of this in bids-standard/legacy-validator#891 - documentation for how it works is [here](https://github.com/bids-standard/bids-validator/pull/891/files#diff-05937fda664c9b6cbf8c756271359982R103). This does introduce a breaking change since relative configuration paths are now interpreted as dataset relative.

**Comment by yarikoptic** [comment]
THANK YOU @nellh -- skimmed through the code (I have little to no JS knowledge, so it was very superficial) -- looks great to me ;)  FWIW, in the use case where I was providing config file, I was using absolute path.
