### ISSUE TITLE
Verify expected number of warnings in tests.

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#75]

**Comment by constellates** [comment]
So the above PR is fairly minor. Only the full BIDS tests return warnings. All the individual checks return issues before they're separated into warning and errors. So tests on individual checks are already testing both.

I added warning assertions to the two semi-static dataset tests, but I'm unsure how best to tackle setting warning assertions for the test that loops through the example datasets and validates each one. Many of them have different numbers of warnings.

I can think of two options so far. We can create some sort of map that lists each dataset by name and the number of expected warnings or if it's possible/reasonable we could assert that the example datasets should not have any warnings and update them to match.

Let me know if you have any preferences or thoughts on addressing this issue.

**Comment by constellates** [comment]
Update merged.
