### ISSUE TITLE
Minimal dependency list

### ISSUE THREAD

**Issue by TheChymera** [bids-standard/legacy-validator#759]
I am looking to figure out what the minimal dependencies of the package are, I came across this in your code:

```
bids-validator/package.json
22:  "dependencies": {
23-    "ajv": "^6.5.2",
24-    "aws-sdk": "^2.327.0",
25-    "bytes": "^3.0.0",
26-    "colors": "^1.3.1",
27-    "cross-fetch": "^2.2.2",
28-    "date-fns": "^2.0.0-alpha.22",
29-    "ignore": "^4.0.2",
30-    "jshint": "^2.9.6",
31-    "minimatch": "3.0.4",
32-    "nifti-js": "^1.0.1",
33-    "p-limit": "^2.1.0",
34-    "pako": "^1.0.6",
35-    "path": "^0.12.7",
36-    "pluralize": "^7.0.0",
37-    "table": "^5.2.3",
38-    "yargs": "^12.0.1"
39-  },
```

Are all of these really required? `aws-sdk` shouldn't be needed if one just wants to validate file names, right? And `colors` seems rather tangential as well, some of the others I haven't ever heard of. Is there any way to get a more stripped down version of the validator functionality?

**Comment by nellh** [comment]
aws-sdk is used for validating DataLad datasets where annexed files may only exist on an S3 remote. It is currently required to run the validator, though it would be relatively easy to make it optional.

The rest of these are needed for most use cases. Are you interested in making the bundle size smaller? Some of these can be removed or reduced in size via tree shaking with tools like [Webpack](https://webpack.js.org/).

**Comment by TheChymera** [comment]
We're not bundling this, but I am looking to make the dependency stack smaller, yes. The functionalities you mention sound rather specific and unrelated to actual BIDS parsing.

A use case I might be looking at is using `from bids_validator import BIDSValidator` to parse BIDS strings into dictionaries. This is a rather small functionality which I could just write up myself, but in the interest of not de-syncing with BIDS development, it makes sense to use a single package. This is, however, made significantly more difficult if that package ships and depends on all sorts of specific things like S3 support.

**Comment by TheChymera** [comment]
@tyarkoni in reference to https://github.com/bids-standard/pybids/issues/289#issuecomament-476954128a

I can just cd into https://github.com/bids-standard/bids-validator/tree/master/bids-validator and build with setup.py and forget about the deps?

**Comment by nellh** [comment]
The NPM dependencies don't affect the Python package, which only shares static files with the JavaScript validator.

**Comment by TheChymera** [comment]
Ok, turns out the Python package indeed has no dependencies, and can be used independently of the JS stuff. It's a bit confusing that it's bundled up, but it's clear to me now :)
