### ISSUE TITLE
fMRI BIDS Validator Issues

### ISSUE THREAD

**Issue by auy17** [bids-standard/legacy-validator#760]
We are trying to upload 50 participants' data, including the following: anat, resting-fMRI, task-fMRI, DTI, eye-tracking, as well as behavioral data. 

We have followed the BIDS data formatting for structure as well as file type, as far as we know. The validation process via Chrome used to work, however, after correcting for the last error message (which was about file name) it is no longer making progress, and it's not giving us any error message either--it just runs for days. 

We have tried uploading from the terminal, which gives us this message (we're not sure what to make of it): 
![ScreenOpenNeuro](https://user-images.githubusercontent.com/31372193/55257168-74edda00-5235-11e9-853d-2146abed7540.png)

We also downloaded a validator, and tried validating locally, however, the validator just does the same thing and run for days without giving any error message, so we end up terminating it. This is the case even with only one subject data. 

Has anyone else experienced this problem, or has an idea of what to do? We would greatly appreciate any feedback.

**Comment by nellh** [comment]
Thanks for the bug report! The validator should take at most a few minutes to run, if it runs longer than 10 minutes or so it has likely gotten stuck.

It looks like this is a bug in the check for the RepetitionTime field in a NIfTI sidecar. Do you have RepetitionTime defined as a string? It might be in quotes `"2.0"` when it should be a JSON number `2.0`.

If that is the issue we'll work on improving the validator so this check gives useful feedback in this case.

**Comment by sappelhoff** [comment]
Closing now. Please reopen if this issue persists @auy17.
