### ISSUE TITLE
validator cmd tool returns 0 even if there are errors

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/legacy-validator#761]
This issue was already reported in #166 and #299 as solved/closed, but still I have 0 when there are errors. Can you fix it, please?

```
> bids-validator --version
1.2.2
> bids-validator /Storage/beliy/COFITAGE/Public/BIDS
	1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible.
...
> echo $?
0
```

**Comment by rwblair** [comment]
@DaNish808 I had made a first pass at this issue in this PR #771. Feel free to use as much or as little of it in resolving this.

**Comment by effigies** [comment]
If it's useful, @rwblair ran a `git bisect`, and the issue was reintroduced in 3ae01a7b317db1758612abc26dfadb971d790691.
