### ISSUE TITLE
Array/String type mismatches in dataset_description.json schema

### ISSUE THREAD

**Issue by nellh** [bids-standard/legacy-validator#772]
These are currently defined ambiguously as strings or arrays. From the [text of the specification](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#dataset_descriptionjson): Funding should be an array. Acknowledgements and HowToAcknowledge should be strings.

https://github.com/bids-standard/bids-validator/blob/96326ecc97fc5c7f04085f37919e4ac46e990508/bids-validator/validators/json/schemas/dataset_description.json#L20-L37

**Comment by ckrountree** [comment]
This could make the validator more spec-compliant.  Do we want to do this in this specific case?

**Comment by rwblair** [comment]
I think it would be good. Bringing out of spec dataset descriptions up to date won't be too much work for any one who needs to do it.

**Comment by effigies** [comment]
Closed by #852.
