### ISSUE TITLE
bids-validator incorrectly interpreting repetition time as 0 from nifti header

### ISSUE THREAD

**Issue by jbwexler** [bids-standard/legacy-validator#776]
I've come across this issue twice now. Bids-validator produces a repetition mismatch error because it thinks the repetition time from the nifti header is zero. When I look at pixdim4, it's the same as the RepetitionTime field in the json. I was able to get around this by manually changing pixdim4 to some other value and then changing it back to the original value. 

A good example is https://openneuro.org/datasets/ds000237

**Comment by effigies** [comment]
Looking at `ds000237/sub-01/func/sub-01_task-MemorySpan_acq-multiband_run-01_bold.nii.gz` with `print(nibabel.load(fname).header)`, I see:

```
pixdim          : [-1.  3.  3.  3.  0.  0.  0.  0.]
```

Similarly, with `mri_info`:

```
TR: 0.00 msec
```

I assume you're looking with `fslhd`, which shows:

```
pixdim0        0.000000
pixdim1        3.000000
pixdim2        3.000000
pixdim3        3.000000
pixdim4        1.000000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
```

FSL does some interpolation of missing data sometimes.

**Comment by jbwexler** [comment]
Thanks! That makes perfect sense. Sorry forgot to reply until now. I'll close the issue
