### ISSUE TITLE
Validate units used in TSV files.

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#777]
Several `.tsv` files can have a column called `units`.

We have a list of permissible units in our [appendix V](https://bids-specification.readthedocs.io/en/stable/99-appendices/05-units.html).

# The validator should ...

- check each tsv file for a "units" column
- check each unit in all units columns
- throw an error if a unit is not part of our list in appendix II

# Basic example of what this feature would fix

The `channels.tsv` file in https://github.com/bids-standard/bids-examples/pull/155#discussion_r281095667 contained a unit `uV` to indicate micro Volts. The validator accepted this, although according to our Appendix II, we would only accept `µV` or `microV` (...or `µvolt` or `microvolt`)

The validator could catch this case and throw a message "please fix this unit in that file, that column, that row" ... and link to our appendix.

cc @ftadel

**Comment by sappelhoff** [comment]
What is the status on this issue @DaNish808 @ckrountree @rwblair ?

**Comment by ckrountree** [comment]
@sappelhoff It was put back into the backlog for the moment.  We had some ON issues arise that needed more immediate attention.  That being said, we recognize that this is a higher priority BIDS issue!  We will address it asap.

**Comment by ckrountree** [comment]
Released in v3.9
