### ISSUE TITLE
Zenodo entry for BIDS-Validator

### ISSUE THREAD

**Issue by oesteban** [bids-standard/legacy-validator#781]
Having a DOI for the validator would make referencing it a lot cleaner (and more amenable to scientific journals)

**Comment by sappelhoff** [comment]
I agree, this is related to https://github.com/bids-standard/bids-specification/issues/66

@rwblair wanted to look into this these days

**Comment by effigies** [comment]
@rwblair @sappelhoff This is pretty easy to enable, but ownership of the Zenodo entry goes to the person to enable it on the repo, making them the person everybody bugs if something needs to be fixed in an entry. Would either of you like to be that person?

**Comment by sappelhoff** [comment]
I am generally willing to be that person ... here are two questions however:

1. is the "ownership" of the Zenodo entry transferrable?
    1. else, we could make a "BIDSSTANDARD" GitHub user and have that user as the "owner" of the Zenodo entry
1. what regular changes to the entry do you expect @effigies ?

PS: We still need to resolve which authors to include and how to determine the order (see the issue I linked above)

**Comment by effigies** [comment]
1. Not trivially. It's possible that if the activating user deactivates the repo on Zenodo, and then another reactivates it, that would transfer, but I haven't experimented with it, and it doesn't show up in the documentation anywhere.
    1. I would be okay with that. Perhaps a `bids-maintenance` user?
1. No regular changes. Most metadata can be handled via the `.zenodo.json` file. Just occasionally we've needed to adjust something after deposition, such as a typo in the abstract.

**Comment by effigies** [comment]
Speaking of `bids-maintenance`, that might be a more sensible user than Franklin for automatic commits to the main repository.

**Comment by sappelhoff** [comment]
We now have @bids-maintenance so we can get back to getting a DOI for the validator and storing the software in a zenodo archive.

Unfortunately, we still need to resolve the authorship order before we can take action: bids-standard/bids-specification#66

**Comment by effigies** [comment]
As the validator is a code object, I would be inclined to follow the PyBIDS model:

```
maintainer
everyone else, ordered by commit count
```

**Comment by effigies** [comment]
I have turned on bids-validator Zenodo processing through the @bids-maintenance user. I will open a PR this week to add `.zenodo.json`.

The default Zenodo behavior should be pretty reasonable if we need a release before then, and we can edit the metadata as needed.

**Comment by effigies** [comment]
Worked as advertised: https://zenodo.org/record/3688707

Can improve from here.
