### ISSUE TITLE
Proper BIDS Setup for Clinical Study

### ISSUE THREAD

**Issue by dlevitas** [bids-standard/legacy-validator#783]
Hi,

I'm helping a clinical group organize their data into BIDS format, but have a question regarding how to best handle the two groups (control and clinical groups). Participant IDs in the control group begin with "C" (i.e. ```C1000```) and clinical group IDs begin with "A" (i.e. ```A1001```). My current approach has been to keep both both groups in the same study folder and keep the group identifier (C or A) in the subject ID. Would this be an acceptable BIDS format, or would I need to remove the letter from the subject ID (or even have groups in separate study directories)?

Thanks for the help,

Dan

**Comment by effigies** [comment]
> My current approach has been to keep both both groups in the same study folder and keep the group identifier (C or A) in the subject ID. Would this be an acceptable BIDS format

Yes, the subject ID can be any alphanumeric string. You may also want to put diagnosis in the `participants.tsv`.

**Comment by dlevitas** [comment]
Great, thanks!
