### ISSUE TITLE
DWI B0 file BIDS format

### ISSUE THREAD

**Issue by dlevitas** [bids-standard/legacy-validator#784]
Sorry for the barrage of questions lately. I've got a protocol that has two opposite phase encoding direction DWI sequences, one of which only contains B0 dicoms. Normally I would name dwi files as ```sub-000_run-01_dir-AP_dwi.nii.gz``` and ```sub-000_run-02_dir-PA_dwi.nii.gz```; however I saw from this [post](https://neurostars.org/t/bids-b0-correction-for-dwi/3802) that B0 dwi files should be organized in the fmap directory. If this is still the case, would the proper name for this file be something like ```sub-000_run-01_dwi.nii.gz``` and in the corresponding .json file have an "IntendedFor" field with the path to the other dwi?

Thanks again.

**Comment by rwblair** [comment]
Sorry for the delay in response, I think this is the naming scheme that should be used for the fieldmap files:
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-4-multiple-phase-encoded-directions-pepolar

So the fieldmaps will be saved as '_epi' instead of '_dwi' and their phase encoding stored in a json file accompanying the niftis.

**Comment by dlevitas** [comment]
Thanks @rwblair. I'm a little confused though since these files are opposite phase encoding direction DWI and not fieldmaps, unless I'm misunderstanding how the data is acquired. So you're saying that the b-zero file should be treated as a fieldmap and not have ```_dwi``` in the name? I use the ```_epi``` designation for spin echo fieldmaps, but didn't know if that should apply for this b-zero file?

**Comment by oesteban** [comment]
Hi @dlevitas, @rwblair is right. You are not acquiring DWI data (what model could you fit to a bunch of lowb images?, -even worse so if all of them are b=0).

Your files should be named with `_epi` designation and make sure you fill the `IntendedFor` metadata, pointing to the `_dwi` files this EPI applies to.

EDIT: a different issue would be if you acquired a repetition of your `_dwi` with opposite PE blips. That would, indeed, be another `_dwi`.

**Comment by dlevitas** [comment]
Ah I see, thanks for the clarification!
