### ISSUE TITLE
Validation of "status" column in channels.tsv

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#787]
The `channels.tsv` file is used for MEG, EEG, and iEEG and can optionally contain a column `status`, see `channels.tsv` definition for these modalities: [ieeg](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/04-intracranial-electroencephalography.html#channels-description-_channelstsv), [eeg](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#channels-description-_channelstsv), [meg](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#channels-description-_channelstsv)

This `status` column SHOULD have only one of two values `good` or `bad`.

This is something that the validator should check when making a pass through a dataset.

cc @robertoostenveld @jasmainak

**Comment by jasmainak** [comment]
agreed!

**Comment by robertoostenveld** [comment]
agreed.
