### ISSUE TITLE
Tutorial walking through contributing to BIDS validator

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/legacy-validator#788]
This point was raised during the BIDS community meeting - it could be useful to have a tutorial on how to contribute/extend the BIDS validator (a walkthrough) and tips/tricks that helped contribute. 

@sappelhoff: perhaps may you please write down your process and things that were useful that you learned through the process. This will be really useful to have as BEPs are getting closer to opening a PR and work in parallel with the validator to support the extension. I can help you with this too!

**Comment by sappelhoff** [comment]
yes, I'll give it a shot soon - this is related to #646
