### ISSUE TITLE
Have a CI for BIDS-validator on Windows

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#791]
Given my recent adventures to make BIDS-validator work in the development version on Windows (see #790 ), I think that it would be nice to set up a continuous integration service that would test for Windows based systems.

cc @jasmainak

**Comment by effigies** [comment]
Just a quick note that AppVeyor tends to run in serial, so if you have more than one job, the queue can build up quickly. It might be worth looking into Azure pipelines.

**Comment by nellh** [comment]
I just requested access to Windows environments for CircleCI. It would be nice to share the CI configuration across platforms if possible.

**Comment by effigies** [comment]
I didn't even know they had that...

**Comment by nellh** [comment]
FYI I'm talking to CircleCI about this tomorrow.

**Comment by nellh** [comment]
This is implemented but #821 limits how useful it is at the moment.

**Comment by nellh** [comment]
This is working and useful now. There is one test failure on Windows to resolve but the test suite is reporting Windows issues correctly now.

**Comment by sappelhoff** [comment]
Thanks @nellh :-)

Just for future reference, Windows testing is happening on this GitLab mirror: https://gitlab.com/bids-standard

using the GitLab CI runner https://github.com/bids-standard/bids-validator/blob/920d1957c1788c96f3df5b0be3eb7c2be594f8d3/.gitlab-ci.yml#L1-L14
