### ISSUE TITLE
bids-validator "master" should indicate this in --version

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#803]
We can now see the version of the "master" / "dev" version of bids validator, which is nice ... **however**, that version is equal to the version of the latest release.

This shows I am using the "master" version
> (base) stefanappelhoff@arc-lin-004309:~$ which bids-validator 
/home/stefanappelhoff/Desktop/bids/bids-validator/bids-validator/bin/bids-validator

However, the version string is the same as the latest **release**
> (base) stefanappelhoff@arc-lin-004309:~$ bids-validator --version
1.2.5

I would rather expect a version string like `1.2.dev0` or similar for the master/dev version. Else, we can run into issues when helping users to debug their code: We ask them what version they are using, and their answer is ambiguous to us.

**Comment by rwblair** [comment]
Right now versions numbers are only changed on publish. I'm looking into what it would take to change the post publish version to something along the lines of what you mentioned above and if there's any way it can be automated.

**Comment by sappelhoff** [comment]
closed with #1081
