### ISSUE TITLE
validator not case sensitive

### ISSUE THREAD

**Issue by jasmainak** [bids-standard/legacy-validator#804]
In the OpenNeuro dataset ds001512: https://openneuro.org/datasets/ds001512, the EEG folder is capitalized. However, according to the specification, [it should be lowercase](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#eeg-recording-data). The validator lets this go through which breaks many other programs.

**Comment by effigies** [comment]
The `.bidsignore` contains:

```
/sub-*/EEG/**
/additional_files/**
```

The validator does not validate files specified there.

**Comment by jasmainak** [comment]
I see, didn't realize that. Still seems a problem, no? Maybe the issue can be transferred to Openneuro?

If you can `.bidsignore` your way to ignoring all the rules, then it seems that the standard will not be a standard any more ...

**Comment by effigies** [comment]
I would make a comment on the dataset with suggested fixes. I don't know that there's any good way to avoid the ignore file.

**Comment by jasmainak** [comment]
umm ... you could probably do a check where you compute the size of all files in .bidsignore relative to the size of the full dataset. If it exceeds a certain fraction, raise an error.

**Comment by jasmainak** [comment]
ps: I left a comment as per @effigies suggestion also on the dataset page, but unfortunately due to unresponsiveness of my browser ended up leaving 10 copies of the same comment. @nellh how do I delete them? :)

**Comment by effigies** [comment]
> you could probably do a check where you compute the size of all files in .bidsignore relative to the size of the full dataset. If it exceeds a certain fraction, raise an error.

We're considering something on those lines, but haven't settled on an approach/threshold.

**Comment by jasmainak** [comment]
Is it an open discussion where I can pitch in? :)

**Comment by effigies** [comment]
I'm not sure that it's made it off slack, yet, but we can open an issue tomorrow.

**Comment by sappelhoff** [comment]
+1 for an open discussion, thanks for raising this issue @jasmainak ... the "fix" you suggested sounds sensible to me.

**Comment by ckrountree** [comment]
The validator is case sensitive.  This is an issue with what is in bidsignore...to be addressed in a separate ticket.
