### ISSUE TITLE
Not Included Error: .bval and .bvec fmap files

### ISSUE THREAD

**Issue by dlevitas** [bids-standard/legacy-validator#805]
Hello,

I've got some DWI data that includes B0 images. I was told that the proper BIDS specification for these files is in ```/fmap``` as ```epi``` files.  The naming convention is therefore:
```
sub-C01086_ses-01_run-05_epi.bval
sub-C01086_ses-01_run-05_epi.bvec
sub-C01086_ses-01_run-05_epi.json
```
I also have the following in my .bidsignore file:
```
"sub-C01086/ses-01/fmap/sub-C01086_ses-01_run-05_epi.bval"
"sub-C01086/ses-01/fmap/sub-C01086_ses-01_run-05_epi.bvec"
```

When I try to validate the data though, I get this error:
```
sub-C01086_ses-01_run-05_epi.bval
0.015 KB |
Location:

bids_validate_test/sub-C01086/ses-01/fmap/sub-C01086_ses-01_run-05_epi.bval
Reason:

Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.
```

I thought this would be taken care of with the .bidsignore; is there something else that I'm missing here that's causing the error?

Thanks

**Comment by effigies** [comment]
Hi @dlevitas I think [NeuroStars](https://neurostars.org/tags/bids) will generally have a wider audience for questions like this. I don't think most of the people involved in diffusion are watching the issues list for the validator.

**Comment by dlevitas** [comment]
Solution is [here](https://neurostars.org/t/not-included-error-bval-and-bvec-fmap-files/4678/2).
