### ISSUE TITLE
Yesterdays (2019-08-06) merged PRs break validation

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#812]
The PRs merged yesterday lead to issues with our pipeline in [mne-bids](https://github.com/mne-tools/mne-bids/pull/252).

merged yesterday: #809 #810 #811

prior to that, everything was running smoothly, now we get the following issue:

```shell
Unhandled rejection (reason: {}).

('', '')
```

For all our BIDS datasets.

We are using `master` of bids-validator, see our CI configs here:

[Appveyor](https://github.com/mne-tools/mne-bids/pull/252/files#diff-180360612c6b8c4ed830919bbb4dd459)
[Travis](https://github.com/mne-tools/mne-bids/pull/252/files#diff-354f30a63fb0907d4ad57269548329e3)

cc @jasmainak @nellh @DaNish808 @rwblair

**Comment by nellh** [comment]
Looks like Node 10.10.0 is not sufficient due to this change released in 10.11 https://github.com/nodejs/node/pull/22832, can you update to the latest LTS (10.16.1)?

I'll make a PR to raise the engine requirement to a version which passes the test suite

**Comment by sappelhoff** [comment]
That seems to work, thanks.

However, I get the following warning:

`(node:15492) ExperimentalWarning: The fs.promises API is experimental`

**Comment by nellh** [comment]
@sappelhoff That is expected on Node 10. fs.promises was marked stable in Node 11, you could use Node 12 (soon to be the LTS version) if you want to suppress the warning.

**Comment by sappelhoff** [comment]
Ah alright. :-)

@nellh if I may depend on your skill once more ... our Windows CLI is still giving issues: [log](https://ci.appveyor.com/project/mne-tools/mne-bids/builds/26506058?fullLog=true)

Every dataset now gives quick validation errors: 

```
1: [ERR] Quick validation failed - the general folder structure does not resemble a BIDS dataset. Have you chosen the right folder (with "sub-*/" subfolders)? Check for structural/naming issues and presence of at least one subject. (code: 61 - QUICK_VALIDATION_FAILED)
```

Although nodejs is properly installed (and runs fine on non-windows OS using the same data):

```
node --version
v10.16.1
npm --version
6.9.0
yarn --version
1.16.0
```

Could it be due to these error messages when cloning `bids-validator` from `master` and calling `yarn`? (see beginning of the log linked above)

```
warning "workspace-aggregator-64438cff-256a-4b62-80cd-079d0b54a139 > bids-validator > jest-environment-jsdom-global@1.2.0" has unmet peer dependency "jest-environment-jsdom@22.x || 23.x || 24.x".
warning "workspace-aggregator-64438cff-256a-4b62-80cd-079d0b54a139 > bids-validator-web > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning "workspace-aggregator-64438cff-256a-4b62-80cd-079d0b54a139 > bids-validator-web > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning "workspace-aggregator-64438cff-256a-4b62-80cd-079d0b54a139 > bids-validator-web > @zeit/next-css > css-loader@1.0.0" has unmet peer dependency "webpack@^4.0.0".
warning "workspace-aggregator-64438cff-256a-4b62-80cd-079d0b54a139 > bids-validator-web > @zeit/next-css > mini-css-extract-plugin@0.4.3" has unmet peer dependency "webpack@^4.4.0".
warning "workspace-aggregator-64438cff-256a-4b62-80cd-079d0b54a139 > bids-validator-web > @zeit/next-sass > sass-loader@6.0.6" has unmet peer dependency "webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0".
```

**Comment by nellh** [comment]
> Ah alright. :-)
> 
> @nellh if I may depend on your skill once more ... our Windows CLI is still giving issues: [log](https://ci.appveyor.com/project/mne-tools/mne-bids/builds/26506058?fullLog=true)
> 
> Every dataset now gives quick validation errors:
> 
> ```
> 1: [ERR] Quick validation failed - the general folder structure does not resemble a BIDS dataset. Have you chosen the right folder (with "sub-*/" subfolders)? Check for structural/naming issues and presence of at least one subject. (code: 61 - QUICK_VALIDATION_FAILED)
> ```

Quick validation is just after the new readDirs implementation - my guess is this is a platform bug with the changes. I filed #814 and I can check it out today.
