### ISSUE TITLE
Required JSON field 'TaskName' is not tested for presence

### ISSUE THREAD

**Issue by mih** [bids-standard/legacy-validator#82]
see title

**Comment by chrisgorgo** [comment]
There is one remaining issue after applying #192. Validator complains about lack of TaskName for sbref files where it is not required.

```
    1: You have to define 'TaskName' for this file. (code: 50)
            /sub-100307/func/sub-100307_task-EMOTION_acq-LR_sbref.nii.gz
```

**Comment by constellates** [comment]
Does the above PR cover this or are there any additional scans with "task-" keys that don't require a sidecar "TaskName" definition?
