### ISSUE TITLE
[wishlist] -o|--output option to specify file to store output in

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#829]
although it is trivial to implement and workaround on any POSIX system with directing output into a file (i.e. `>| validator.log`), my use case is to use [datalad-containers](https://github.com/datalad/datalad-container/) datalad extension. Since container has the entry point which runs  bids-validator already, it makes it impossible (without making default entry point to be just `bash`) to make invocation to `datalad containers-run` to specify output file.  If there was an `-o` option it would have looked like `datalad containers-run -n containers/bids-validator --input sourcedata --output sourcedata-validator.log '{inputs}' -o '{outputs}'` .

while storing into file there would be no ANSI coloring, it could stay consistent with having --verbose in a regular invocation.

**Comment by yarikoptic** [comment]
Do you think it would be feasible to get this issue addressed in some forseable future? may be at least in deno validator (if it suffers the same).  I keep running into this shortcoming :-/  ping @nellh @rwblair

**Comment by rwblair** [comment]
Would it be ok for the output saved to a file to be the json version of the output? or do you want what would have been printed to a console (unless --json was passed)?

**Comment by yarikoptic** [comment]
original intent was to have what is printed to output. With `--json` option in tandem - it would be json ;)
