### ISSUE TITLE
Support phase functional MRI data

### ISSUE THREAD

**Issue by tsalo** [bids-standard/legacy-validator#834]
Per https://github.com/bids-standard/bids-specification/pull/128 and https://github.com/bids-standard/bids-specification/pull/312, phase fMRI data are supported as a suffix (`_phase`) in the `func` datatype. It doesn't look like that change has been pushed to the BIDS validator (at least as of the current latest release on DockerHub last month).

**Comment by effigies** [comment]
Sure. Want to add it to:

https://github.com/bids-standard/bids-validator/blob/731b8aee3f615760044f3ec7962e52f43c87b3b7/bids-validator/bids_validator/rules/file_level_rules.json#L119-L141

**Comment by tsalo** [comment]
Absolutely! I didn't realize that was all there was to it.

**Comment by effigies** [comment]
I'm not positive it is, but it will at least get us started, and then a more experienced reviewer should be able to point you to any other changes needed.
