### ISSUE TITLE
validate correct data type (value) of some fields such as MagneticFieldStrength

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#851]
Although BIDS ATM does not explicitly state the data types for the fields in the sidecar files ( https://github.com/bids-standard/bids-specification/issues/350), data types for some fields (such as `MagneticFieldStrength`) are implicitly assumed.  Since I am encountering datasets which have incorrect values in the fields, e.g. `"3T"` literal in this example, I think it would be very valuable if bids-validator added checks for a set of known to be numeric fields.

**Comment by sappelhoff** [comment]
Thanks for raising this so long ago.

datatypes are meanwhile properly documented since https://github.com/bids-standard/bids-specification/pull/605

I am closing this, because of the more specific issue: #1074 that covers the requested enhancement here.
