### ISSUE TITLE
meg.json schema is missing a key for HardwareFilters field

### ISSUE THREAD

**Issue by riddlet** [bids-standard/legacy-validator#854]
https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/json/schemas/meg.json

Either that or the spec here is incorrect:

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html

**Comment by jasmainak** [comment]
Can you make a pull request to fix it? Thanks
