### ISSUE TITLE
[Question] How should processed MRI be named?

### ISSUE THREAD

**Issue by tashrifbillah** [bids-standard/legacy-validator#872]
# Save a brain mask

I want to save a T1w brain mask with description that it was created using bet. What is the specification?

`/parentDir/derivatives/sub-001/anat/sub-001_{???}_T1w.nii.gz`

`/parentDir/derivatives/sub-001/anat/sub-001_T1w_{???}.nii.gz`

# Documentation found so far
I have been looking at [this](https://bids.neuroimaging.io/bids_spec.pdf) and [this](https://docs.google.com/document/d/1Wwc4A6Mow4ZPPszDIWfCUCRNstn7d_zzaWPcfcHmgI4/edit#) for a while, but didn't get a definitive answer so far. FSL bet saves a mask with `_mask` suffix irrespective of whatever the file name is. I think BIDS says, there can't be more than one suffix in a file name (shouldn't be `_T1w_mask`, which is more natural to me). So, I have the confusion.

# Save an eddy corrected dwi

Related to the above, I want to save an eddy corrected dwi. How should I do it?

`/parentDir/derivatives/sub-001/anat/sub-001_{???}_dwi.nii.gz`

`/parentDir/derivatives/sub-001/anat/sub-001_dwi_{???}.nii.gz`

The `desc-` keywords seems most relevant to me. Yet, I appreciate any suggestion/redirection.

# Things tried so far

```python
[In]: validator.is_bids('/derivatives/pnlNipype/sub-003GNX007/anat/sub-003GNX007_T1w_mask.nii.gz')                                                         
Out: True

In: validator.is_bids('/derivatives/pnlNipype/sub-003GNX007/anat/sub-003GNX007_desc-bet_T1w.nii.gz')                                                       
Out: True

In: validator.is_bids('/derivatives/pnlNipype/sub-003GNX007/anat/sub-003GNX007_desc-bet_T1w_mask.nii.gz')                                                       
Out: True


```

**Comment by effigies** [comment]
https://bids-specification.readthedocs.io/en/common-derivatives/05-derivatives/03-imaging.html#masks

To be clear, that's the draft common derivatives spec. It's still subject to change, but it's been pretty stable for over a year.

**Comment by tashrifbillah** [comment]
Hi @effigies, your direction was helpful. In addition, I followed [this](https://bids-specification.readthedocs.io/en/common-derivatives/05-derivatives/01-introduction.html#file-naming-conventions). Nevertheless, can you comment on the compliance of the structure below?

```
bids_compliant/
├── derivatives
│   └── sub-001
│       ├── anat
│       │   ├── sub-001_desc-axisAligned_T1w.nii.gz
│       │   ├── sub-001_desc-axisAligned_T2w.nii.gz
│       │   ├── sub-001_desc-T1w_mask.nii.gz
│       │   └── sub-001_desc-T2w_mask.nii.gz
│       └── dwi
│           ├── sub-001_desc-axisAligned_dwi.nii.gz
│           ├── sub-001_desc-bet_mask.nii.gz
│           └── sub-001_desc-eddy_dwi.nii.gz
└── sub-001
    ├── anat
    │   ├── sub-001_T1w.nii.gz
    │   └── sub-001_T2w.nii.gz
    └── dwi
        └── sub-001_dwi.nii.gz

```

Still I have one more confusion. The mask was obtained from axis aligned T1w image, not the raw one. The above reference says:

> When the derivatives chain involves outputs derived from a single raw input, source_keywords MUST be the entire source filename, with the omission of the source suffix and extension. 

So, will the masks be named:

```
sub-001_desc-axisAligned_desc-T1w_mask.nii.gz
sub-001_desc-axisAligned_desc-T2w_mask.nii.gz
```

I guess the question is, if previous derived file name already had a keyword that I should use now, should I include that keyword twice?

**Comment by effigies** [comment]
> When the derivatives chain involves outputs derived from a single raw input, source_keywords MUST be the entire source filename, with the omission of the source suffix and extension.

This means that, if you have `sub-01_acq-hires_T1w.nii.gz` and `sub-01_acq-lores_T1w.nii.gz`, a derivative that depends *only* on `sub-01_acq-hires_T1w.nii.gz` must include `sub-01_acq-hires`, but if you use both to produce a derivative file, the `acq` entity could be dropped. And similarly for any other set of files.

> I guess the question is, if previous derived file name already had a keyword that I should use now, should I include that keyword twice?

No. The source file would be considered the one in the raw dataset. Desc is a free-form field that you can use however seems appropriate, but multiple entries are not permitted.

**Comment by tashrifbillah** [comment]
Thanks, but the following is not caught as an error though:

```python
In: validator.is_bids('/derivatives/sub-001/anat/sub-001_desc-axisAligned_desc-T2w_mask.nii.gz')                                                                       
Out: True
```

Neither is existence of multiple suffix:

```python
In: validator.is_bids('/derivatives/sub-001/anat/sub-001_desc-axisAligned_T2w_mask.nii.gz')                                                                            
Out: True
```

Is it a BUG or we just expect users to not challenge with such non-compliant names?

**Comment by effigies** [comment]
The Python package here is pretty limited. I'm fairly sure these would fail the actual validator.

**Comment by tashrifbillah** [comment]
Tried [this](http://bids-standard.github.io/bids-validator/) with the following three, but it didn't fail.


```
bids_compliant_1
├── dataset_description.json
├── derivatives
│   └── pnlNipype
│       └── sub-001
│           ├── anat
│           │   ├── sub-001_desc-bet_desc-T1w_mask.nii.gz
│           │   ├── sub-001_desc-bet_T1w_mask.nii.gz
│           │   └── sub-001_T1w_mask.nii.gz
│           └── dwi
├── README
└── sub-001
    ├── anat
    │   ├── sub-001_T1w.nii.gz
    │   └── sub-001_T2w.nii.gz
    └── dwi
        ├── sub-001_dwi.bval
        ├── sub-001_dwi.bvec
        └── sub-001_dwi.nii.gz

```

**Comment by effigies** [comment]
Oh, right. The current validator does not validate derivatives. Updating the validator to consider derivatives will be part of the final push to merge the derivatives specification.
