### ISSUE TITLE
Remove lerna?

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#882]
Currently only bids-validator is having a version set by lerna. @nell what would the consequences of removing lerna and having npm pushes done in circle deployment workflow be? Is lerna responsible for anything besides setting version number/tag and pushing to npm?

Right now we get tags from lerna and then again from github publish, which had caused some problems with versioneer, and each tagging gets CI run against it. The other two solutions I can see would be to use circle filters to only run tests against one format of tag, and the other would be to have the github tag match the lerna style of tag, with the version being prepended with "bids-validator@".

**Comment by nellh** [comment]
The other useful thing about Lerna was kind of supplanted by Yarn/NPM workspaces and NPM will support these soon, so it could be removed at that point if we don't want to use it to manage interdependencies between the web validator and core validator.

**Comment by rwblair** [comment]
With #883 fixed this isn't an issue at the moment.
