### ISSUE TITLE
Bug: Incorrect Error Reporting

### ISSUE THREAD

**Issue by hebbianloop** [bids-standard/legacy-validator#886]
Summary: 
bids-validator reports `code-10` (REPETITION_TIME_MUST_DEFINE) even when json file already contains repetition time information but ONLY when `code-50` (TASK_NAME_MUST_DEFINE) is triggered. Simply adding TaskName: "${TASKNAME}" to the json file suppresses both messages. bids-validator should only report `code-50` not `code-10`.

How to replicate:
Delete the TaskName line from a JSON file and run bids-validator. Incorrect codes are reported. Adding TaskName back suppresses both errors.

version 0.26.2
running on mac os 10.13.6

**Comment by sappelhoff** [comment]
Thanks for the report, I just tried to replicate the issue using your instructions and example dataset [`7t_trt`](https://github.com/bids-standard/bids-examples/tree/master/7t_trt).

1. validate `bids-validator 7t_trt/ --ignoreNiftiHeaders --ignoreWarnings` ... passes
1. remove `TaskName` from `task-rest_acq-fullbrain_bold.json`
1. validate again (see step 1) ... yields error code-50

no error code-10 was raised in my case, so I assume that either:

- this issue has been solved meanwhile (I tried all of this with the up to date version of bids-validator)
- there was some other (unrecognized) issue with your files

Either way, I am closing this now. Please feel free to re-open if your problem still persists after updating bids-validator.
