### ISSUE TITLE
Unit questions (probably rather BIDS specification related)

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#893]
related to: https://github.com/bids-standard/bids-validator/pull/885

specifically, comments by @jasmainak 
- https://github.com/bids-standard/bids-validator/commit/1590ab899f60244df2f5aa4c09669e803ed7d071#commitcomment-36606925
- https://github.com/bids-standard/bids-validator/commit/1590ab899f60244df2f5aa4c09669e803ed7d071#r36606928

apparently some values in MEG are specified in units that are combinations of the SI units ... e.g., `T/m`. 

I am not sure in how far this is accommodated by the specification. @jasmainak @robertoostenveld @effigies

**Comment by jasmainak** [comment]
`T/m` is still an SI unit, just a derived one :-)

**Comment by robertoostenveld** [comment]
agreed, see https://en.wikipedia.org/wiki/SI_derived_unit. 

Brain signals and behaviour can be quantified in SI and derived units. The MEG part of the specification specifies this more or less, see [here](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#channels-description-_channelstsv) and [appendix V](https://bids-specification.readthedocs.io/en/stable/99-appendices/05-units.html). But it would be good to be more explicit, e.g. perhaps change 

"Physical unit of the data values recorded by this channel in SI (...)" -> "Physical unit of the data values recorded by this channel in SI units or SI derived units (...)"  

It would also be good to update the MEG, EEG and iEEG together and make them consistent. The iEEG description is now the most elaborate and also mentions prefixes, which are also allowed (i.e. I believe that fT/cm should be allowed).

**Comment by sappelhoff** [comment]
seems like this will be fixed in #896 + #897  I'll take a look at the spec and what can be clarified there.
