### ISSUE TITLE
Concept of the validator - RFI

### ISSUE THREAD

**Issue by pvdemael** [bids-standard/legacy-validator#906]
Could someone explain me the algorithmic logic of the BIDS validator?
What steps are taken from reading the file tree to the report?
How is dealt with the several rules files?
Don't kneed detailed explanations (although very much appreciated ;-) ) but I would like to understand the concept behind it.
I have no JS experience but can probably read relevant code. Thx!

**Comment by sappelhoff** [comment]
The answer to this would be a great addition to the contributing guide! https://github.com/bids-standard/bids-validator/blob/master/CONTRIBUTING.md

**Comment by sappelhoff** [comment]
@rwblair would you know somebody (or yourself) who has a sufficiently broad overview of the bids-validator codebase to write such a paragraph?

**Comment by pvdemael** [comment]
I am involved in the BEP-005 on ASL and know that Marco Castellaro has written an extension for the validator. Apart from that, no, sorry
