### ISSUE TITLE
Unit validation issue in bids-examples ieeg_epilepsy

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#907]
>                 ./sub-01/ses-postimp/ieeg/sub-01_ses-postimp_task-seizure_run-01_channels.tsv
>                         @ line: 68
>                         Evidence: Subunit (uV) of unit uV is invalid.

**Comment by sappelhoff** [comment]
This would need to be fixed in the dataset itself: https://github.com/bids-standard/bids-examples
