### ISSUE TITLE
Jest test failure.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#909]
There's a point in the bids spec test on circle ci that is failing and I'm not sure why. Test failures for commits in #908 or other recent pull should have it.

Is #904  related?

**Comment by nellh** [comment]
I think there must be a race condition in our tests which is triggered under CPU pressure. It almost goes away by adding a 10 second delay before running tests, which gives other work on the server time to settle. I was able to reproduce this on GitLab's free workers but not our custom worker as well, and the main difference is available CPU time is higher on our custom worker. It does not seem to vary based on Node.js version in the range 12.0.0 -> 13.7.0 but I still need to test Node 10.

**Comment by exbotanical** [comment]
@rwblair #904 is around the time when the `nifti headers` test started failing. While debugging I found that the test was receiving two different values (hence the '8 equals 9' comment). IIRC, the test was being called twice, with stdin vals 8 and 9, respectively.
