### ISSUE TITLE
Web validator fails frequently

### ISSUE THREAD

**Issue by dungscout96** [bids-standard/legacy-validator#914]
We are experiencing issues with the web validator (http://bids-standard.github.io/bids-validator/) both on Chrome and on Firefox.
For the same dataset the validator hangs and the error we receive on Chrome is
<img width="1680" alt="Screen Shot 2020-02-06 at 11 14 59 AM" src="https://user-images.githubusercontent.com/10362238/73970566-3c497300-48d2-11ea-98d5-aa0a3ec53488.png">
and for Firefox it's
<img width="1680" alt="Screen Shot 2020-02-06 at 11 17 56 AM" src="https://user-images.githubusercontent.com/10362238/73970659-5daa5f00-48d2-11ea-9486-c421693bf101.png">

We tried different datasets whose sizes are:
- 54,380,137 bytes with 31 files
- 5,684,891,775 bytes with 458 files

We tried on different systems, including personal MacBook Pros and a Mac Pro. Attempted to retrieve browser memory quota as mentioned in #884 but the command 
`await navigator.storage.estimate().then(estimate => estimate.quota)` 
doesn't work on either browser

**Comment by sappelhoff** [comment]
Hey @dungscout96 sorry for the late reply. Do you still have the issue?

**Comment by sappelhoff** [comment]
Closing because it's uncertain whether the problem still persists and there is not enough information here to replicate the issue.
