### ISSUE TITLE
Intended for error on a file that is there but not yet part of the BIDS spec

### ISSUE THREAD

**Issue by cmadjar** [bids-standard/legacy-validator#915]
I am creating a BIDS dataset that contain ASL acquisitions. Since the ASL spec has not yet been merged with the BIDS spec, I have to add those acquisitions to the `.bidsignore` file so that I do not get an error for those sequences.

We also acquire fieldmap acquisition to be used with the ASL scans and I added to the JSON file of the fieldmap acquisitions an IntendedFor field which points to the ASL scan. However, because the ASL sequence is part of the list of files in `.bidsignore`, when I run the `bids-validator` on the dataset, I get an `INTENDED_FOR` error.

My question is, is there a way to tell the `bids-validation` to not check for `INTENDED_FOR`? I tried a few things but was not successful in getting it ignored.

Thank you!

**Comment by rwblair** [comment]
The validator has a separate configuration that can be used to ignore certain codes. If you put a file named `.bids-validator-config.json` in the dataset root directory with the following in it:
```
{
        "ignore": [37]
}
```

The validator should ignore the intended for errors.

**Comment by cmadjar** [comment]
Thank you for your reply.

I actually tried that but I still get the error when running the `bids-validator` on the dataset (see below):
```
bids-validator@1.3.6

(node:20907) ExperimentalWarning: The fs.promises API is experimental
	1: [ERR] 'IntendedFor' field needs to point to an existing file. (code: 37 - INTENDED_FOR)
		./sub-7550757/ses-PREBL00/fmap/sub-7550757_ses-PREBL00_run-001_phasediff.nii.gz
			Evidence: ses-PREBL00/asl/sub-7550757_ses-PREBL00_run-001_asl.nii.gz
		./sub-7550757/ses-PREFU12/fmap/sub-7550757_ses-PREFU12_run-001_phasediff.nii.gz
			Evidence: ses-PREFU12/asl/sub-7550757_ses-PREFU12_run-001_asl.nii.gz
		./sub-7550757/ses-PREFU24/fmap/sub-7550757_ses-PREFU24_run-001_phasediff.nii.gz
			Evidence: ses-PREFU24/asl/sub-7550757_ses-PREFU24_run-001_asl.nii.gz
		./sub-7550757/ses-PREFU36/fmap/sub-7550757_ses-PREFU36_run-001_phasediff.nii.gz
			Evidence: ses-PREFU36/asl/sub-7550757_ses-PREFU36_run-001_asl.nii.gz
		./sub-7550757/ses-PREFU48/fmap/sub-7550757_ses-PREFU48_run-001_phasediff.nii.gz
			Evidence: ses-PREFU48/asl/sub-7550757_ses-PREFU48_run-001_asl.nii.gz
		./sub-7863306/ses-PREBL00/fmap/sub-7863306_ses-PREBL00_run-001_phasediff.nii.gz
			Evidence: ses-PREBL00/asl/sub-7863306_ses-PREBL00_run-001_asl.nii.gz

```

Thank you!

**Comment by rwblair** [comment]
Can you try upgrading the validator to 1.4.2. I wasn't able to get the implicit configuration to work in 1.3.6, and when I explicitly specified one with -c I received an error.

If the upgrade doesn't work one final thing to try on 1.4.2 would be to specific the full path to the configuration file.

**Comment by cmadjar** [comment]
I just upgraded to 1.4.2 and adding the `.bids-validator-config.json` file to the dataset directory worked perfectly!

I'll let you close the comment as I don't know your Github policy when it comes to closing issues.

In any case, thank you very much for your help. Very appreciated!
