### ISSUE TITLE
bids-validator v1.4.2 throws a TypeError, doesn't run anymore

### ISSUE THREAD

**Issue by VisLab** [bids-standard/legacy-validator#916]
I recently did an npm update on bids-validator. It now doesn't run on things that it previously ran on.  Here is the error that it throws:

```
Unhandled rejection (
  reason: TypeError: Cannot read property 'length' of undefined
    at Object.formatIssues [as issues] (C:\Users\Kay Robbins\AppData\Roaming\npm\node_modules\bids-validator\utils\consoleFormat.js:21:21)
    at C:\Users\Kay Robbins\AppData\Roaming\npm\node_modules\bids-validator\cli.js:47:36
    at C:\Users\Kay Robbins\AppData\Roaming\npm\node_modules\bids-validator\validators\bids\start.js:26:7
    at C:\Users\Kay Robbins\AppData\Roaming\npm\node_modules\bids-validator\utils\options.js:25:9
    at C:\Users\Kay Robbins\AppData\Roaming\npm\node_modules\bids-validator\utils\options.js:63:9
    at C:\Users\Kay Robbins\AppData\Roaming\npm\node_modules\bids-validator\utils\options.js:50:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
).
```

**Comment by rwblair** [comment]
@VisLab From the traceback it looks this is being generated when the validator config is being parsed. Can you post your current validator config. Once I can recreate I'll make a fix and republish.

**Comment by VisLab** [comment]
I am running using command line as indicated in option 2 of the README.  I have not provided a configuration file.

Example:    bids-validator AdvancedGuard

where AdvancedGuard is the root directory of a BIDS study.  I am executing in the directory containing AdvancedGuard, but I have also tried with the full path. I am not sure what config file you need. Let me know where I should look.  The only likely candidate that I found was setup.cfg.  I have attached the setup.cfg (I renamed it .txt so it could be attached).
[setup.cfg.txt](https://github.com/bids-standard/bids-validator/files/4182900/setup.cfg.txt)

**Comment by rwblair** [comment]
The validator will look for a file called `.bids-validator-config.json` in the root  of the dataset directory and load it automatically. One option is to try  `bids-validator --no-config AdvancedGuard` to see if that gets further into validation.

Is the dataset available any where publicly? Would be helpful to attempt to recreate the issue. I haven't been able to trigger a similar issue on any datasets that I currently have available to me.

**Comment by VisLab** [comment]
I tried the --no-config and it worked! Note that the same study that worked with no problem two weeks ago has this issue.  (I updated bids-validator on January 31.)  This solves my problem, but the documentation should probably indicate that the flag is now required if a configuration file is not provided.  If you still need to see the study, I can put it somewhere, but it will take a couple of days.  (I'm in the process of putting a large collection up on openNeuro, but it has to be staged on a fast connection in order to work.).. Thanks

**Comment by sappelhoff** [comment]
> but the documentation should probably indicate that the flag is now required if a configuration file is not provided.

To my knowledge this is not the case. The `--no-config` is not required (and not documented as you say) ... rather, a user can optionally use `--config <path>` to apply a config file.

There must have been a different issue at work and given that neither Ross nor I could replicate it, I am closing this for now.

Please feel free to re open if this is still a concern. Then we can discuss how to replicate the issue. :-)
