### ISSUE TITLE
_defacemask for BOLD

### ISSUE THREAD

**Issue by mih** [bids-standard/legacy-validator#93]
Here is the file in question:

/sub-16/ses-r08/func/sub-16_ses-r08_task-orientation_rec-dico_run-05_recording-motion_physio.tsv

It contains motion estimates as part of a scanner-side distortion correction (corrected BOLD data is stored as "rec-dico"). AFAICS this should be valid. But the validator thinks otherwise.

**Comment by chrisgorgo** [comment]
It's not tsv.gz maybe this is the problem?

**Comment by mih** [comment]
Ah!

Thanks for the pointer. That must be it!

**Comment by mih** [comment]
Will reuse this issue for another filename issue. I think this should be valid:

```
/sub-04/ses-localizer/func/sub-04_ses-localizer_task-objectcategories_run-4_defacemask.nii.gz
         This file is not part of the BIDS specification, make sure it isn't included in the dataset by accident. Data derivatives (processed data) should be placed in /derivatives folder.
         Evidence: sub-04_ses-localizer_task-objectcategories_run-4_defacemask.nii.gz
```

**Comment by chrisgorgo** [comment]
According to the spec _defacemask is only valid for anatomical scans. We
could however extend it to functional scans.

**Comment by mih** [comment]
Ah, that explains it.

I routinely deface any image that covers the face, regardless of the image contrast. I'd prefer to be able to include such mask also for BOLD images.

**Comment by chrisgorgo** [comment]
Could you propose a solution at the [BIDS mailing list](https://groups.google.com/forum/#!forum/bids-discussion)? The only problem I see is how to distinguish deface mask for different modalities (BOLD vs ASL, T1 vs. T2) any suggestions?
