### ISSUE TITLE
Validity of JSON files should be tested before meta-data availability

### ISSUE THREAD

**Issue by mih** [bids-standard/legacy-validator#95]
At present, meta-data checks (e.g. RepetitionTime specification) run before JSON validity checks. In case of a typo in the JSON (it happended to me once!) this leads to countless "false-positives". If nothing speaks against it, switching the order of these checks could help people retain more hair ;-)

See #94 for an example of me being misguided.

**Comment by constellates** [comment]
This does indeed create confusing warnings.

I believe the checks do run in the appropriate order, but an invalid JSON file does not prevent the meta-data presence checks from running.

I can change this so if a JSON file is present and invalid, meta-data checks for info that could be in that file will not be tested. 

There are however, dataset configurations that could complicate this strategy. If for example you have a scan that has more than one JSON files that refer to it. If one of those JSON files is invalid it's impossible to know how metadata is split between the JSONs and what checks we should ignore. The simplest solution would be to still ignore the metadata checks in this scenario and they'll pop back up next time the user tests the dataset with the fixed JSON file.

@chrisfilo What do you think about ignoring meta-data presence checks when any possible location for them is an invalid file? Also if multiple JSONs can't refer to one scan then this is moot, but I believe that is allowed.

**Comment by chrisgorgo** [comment]
@constellates this sounds like a great solution. Sorry for a terribly slow responce.

**Comment by chrisgorgo** [comment]
@constellates is this resolved? can we close it?

**Comment by constellates** [comment]
I add a PR just now.
