### ISSUE TITLE
[Code 0] Internal Error: Cannot read property 'HED' of null

### ISSUE THREAD

**Issue by dvm-shlee** [bids-standard/legacy-validator#956]
Hi All, I have an issue during the validation as below. This issue is not showing when I check 'ignore 
NifTi Header'. Attacking screenshot and error message.

Thanks!
 
![Picture1](https://user-images.githubusercontent.com/7221078/81637803-46a16e80-93e5-11ea-8393-6bc73a089c2a.png)

Reason:
Cannot read property 'HED' of null; please help the BIDS team and community by opening an issue at (https://github.com/bids-standard/bids-validator/issues) with the evidence here.

Evidence:
TypeError: Cannot read property 'HED' of null at https://bids-standard.github.io/bids-validator/_next/static/xR2eAacfkH2A9NYaGkYfI/pages/index.js:1:1596570 at Array.forEach (<anonymous>) at xi (https://bids-standard.github.io/bids-validator/_next/static/xR2eAacfkH2A9NYaGkYfI/pages/index.js:1:1596350) at _i (https://bids-standard.github.io/bids-validator/_next/static/xR2eAacfkH2A9NYaGkYfI/pages/index.js:1:1598552) at Object.Bi [as validateEvents] (https://bids-standard.github.io/bids-validator/_next/static/xR2eAacfkH2A9NYaGkYfI/pages/index.js:1:1599843) at https://bids-standard.github.io/bids-validator/_next/static/xR2eAacfkH2A9NYaGkYfI/pages/index.js:1:1611186

**Comment by sappelhoff** [comment]
perhaps @happy5214 can help

**Comment by rwblair** [comment]
https://github.com/bids-standard/bids-validator/blob/0d21b0adc30ab00ba53df61cbbb4d931cbac36ee/bids-validator/validators/events/hed.js#L31

Might be coming from here. Will try and replicate error and add a check to ensure sideCarValue is defined.

**Comment by dvm-shlee** [comment]
@rwblair  I think I found where the issue comes from and posted in neurostars forum.
Thank you for hinting about the potential origin of the issue!
https://neurostars.org/t/code-0-internal-error-cannot-read-property-hed-of-null/6895/4?u=dvm-shlee

**Comment by happy5214** [comment]
The issue was that a `null` sidecar value violated the assumption that `sidecarValue` is a non-null object. I've fixed that and also added an actual object type check.
