### ISSUE TITLE
Allow fractional seconds in scans file datetimes

### ISSUE THREAD

**Issue by tsalo** [bids-standard/legacy-validator#957]
This stems from bids-standard/bids-specification#470, and is related to nipy/heudiconv#447 and nipy/heudiconv#451.

In bids-standard/bids-specification#470, I am proposing that fractional seconds be allowed in the accepted datetime format for the `acq_time` column in scans files. @sappelhoff pointed out that the validator will need to be updated in line with this change to the specification. The locations that need to be updated in the validator are below:

https://github.com/bids-standard/bids-validator/blob/ecacf0d30f9bc803393c1bb9833179d47a5d5451/bids-validator/validators/tsv/checkAcqTimeFormat.js#L4-L12

https://github.com/bids-standard/bids-validator/blob/920d1957c1788c96f3df5b0be3eb7c2be594f8d3/bids-validator/utils/issues/list.js#L465-L470

I can update `list.js` easily enough, but I don't know Javascript, so I'm not sure how to update `checkAcqTimeFormat.js`. Any help anyone can give would be appreciated.

**Comment by sappelhoff** [comment]
cc @rwblair

**Comment by rwblair** [comment]
Fortunately looks like the library we use supports fractional seconds:
https://date-fns.org/v2.9.0/docs/parse

I'll try updating the format string to use them and seeing how it plays with existing datasets.

**Comment by tsalo** [comment]
The associated `bids-specification` PR was merged, so I just wanted to ping this issue in case anyone was waiting for fractional seconds to be officially supported.
