### ISSUE TITLE
UTF-8 check on .tsv files

### ISSUE THREAD

**Issue by MaxvandenBoom** [bids-standard/legacy-validator#962]
Hi again :)

The bids-validator gives me an error when JSON files are not in UTF-8 ("JSON files must be valid utf-8."). But it does not give me a similar error for (ASCII) .tsv files

Could it be that such an UTF-8 check is not implemented for .tsv files?

**Comment by MaxvandenBoom** [comment]
I checked this issue and I am pretty sure only the encoding of JSON files is validated, not that of the .TSV files.

It should be fairly easy to fix and I would like to make a pull request, but that would require the addition of a new error code or broaden the scope of the JSON one `123` - `INVALID JSON ENCODING`. @sappelhoff What do you prefer? And is there a system to the error codes that I should follow?

**Comment by effigies** [comment]
ASCII is a valid subset of UTF-8, so that certainly shouldn't be an error. Can you put in an invalid byte sequence and see if that produces a reasonable error?

**Comment by MaxvandenBoom** [comment]
This issue derives from having the wrong or wrongly encoded micro sign µ in the _channels.tsv. It does produce a reasonable error saying the sign is incorrect. But should it not also check the encoding like what happens to the JSON files?

PS. Forget about the ASCII, I meant ANSI, my mistake. Main point is, should there be a check for UTF-8 on .tsv files, like there is one for JSON files.

**Comment by effigies** [comment]
Predates https://github.com/bids-standard/bids-validator/issues/43, but I've already transferred that to the schema validator repo.
