### ISSUE TITLE
Non-NIFTI event data not tested

### ISSUE THREAD

**Issue by happy5214** [bids-standard/legacy-validator#967]
The event validation does not appear to validate event data for EEG datasets, nor any non-NIFTI datasets for that matter. Lines 61 and 79 of `validators/events/events.js` in particular appear to assume NIFTI "bold" data. If NIFTI data is not in the dataset, it will not check event data associated with other filename templates.

This will need to be fixed in order to run EEG validation with the sidecar additions suggested in #942.

**Comment by VisLab** [comment]
To that end --- has issue #912 (also a bug) ever been addressed?

**Comment by effigies** [comment]
Yes, this should operate on any `events` file, whether EEG or [behavioral](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/07-behavioral-experiments.html).

**Comment by happy5214** [comment]
I think the actual issue is rooted even deeper. The event validation code loops through a filtered set of headers, and the original header list is only generated for NIFTI data. See line 45 of https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/events/events.js and line 148 of https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/bids/fullTest.js.

**Comment by happy5214** [comment]
The repetition time validation would not be affected, as those datasets have NIFTI, but EEG and other non-NIFTI data passed through to the HED validation will have an empty header list, causing the validation to not run at all.
