### ISSUE TITLE
 [Code 0] INTERNAL ERROR

### ISSUE THREAD

**Issue by acsouza** [bids-standard/legacy-validator#968]
Hi, 
I'm running BIDS validator on a small test dataset with only 2 subjects and only one modality (fMRI). Got this error e.split is not a function. Does anyone know what the problem is? 

Evidence:

Nn/<@https://bids-standard.github.io/bids-validator/_next/static/xR2eAacfkH2A9NYaGkYfI/pages/index.js:1:1607905 Nn@https://bids-standard.github.io/bids-validator/_next/static/xR2eAacfkH2A9NYaGkYfI/pages/index.js:1:1607883 Tn@https://bids-standard.github.io/bids-validator/_next/static/xR2eAacfkH2A9NYaGkYfI/pages/index.js:1:1608308 Ln/<@https://bids-standard.github.io/bids-validator/_next/static/xR2eAacfkH2A9NYaGkYfI/pages/index.js:1:1610763 a@https://bids-standard.github.io/bids-validator/_next/static/chunks/commons.856bab05f307cc99f5ad.js:1:169515 R/<@https://bids-standard.github.io/bids-validator/_next/static/chunks/commons.856bab05f307cc99f5ad.js:1:169660 c@https://bids-standard.github.io/bids-validator/_next/static/chunks/commons.856bab05f307cc99f5ad.js:1:173170 

Thanks.

**Comment by rwblair** [comment]
The split function is called in quite a few places in the validator. Shows up in bvec, bval, header fields, tsv, events, and hed validation among other places.

To confirm do all the nifti files contain headers? What json or tsv files have you added to the dataset so far? A list of the paths and files in the dataset would be helpful, can test similar setup to try and recreate the error.

**Comment by acsouza** [comment]
Thanks for your reply! 
I have .json files for anatomical and functional subfolders (creatted with dcm2nixx). Also have dataset_description.json and participants.tsv (only 4 fields) which I created manually as I'm just testing with a small dataset. 
I don't have any more errors besides the one mentioned. 

|-- dataset_description.json
|-- participants.tsv
|-- sub-01
|   |-- anat
|   |   |-- sub-01_T1w.json
|   |   `-- sub-01_T1w.nii
|   `-- func
|       |-- sub-01_task-rest_bold.json
|       `-- sub-01_task-rest_bold.nii
`-- sub-02
    |-- anat
    |   |-- sub-02_T1w.json
    |   `-- sub-02_T1w.nii
    `-- func
        |-- sub-02_task-rest_bold.json
        `-- sub-02_task-rest_bold.nii

**Comment by acsouza** [comment]
I've got some help and was actually an error with one of the fields in the dataset_description.json
