### ISSUE TITLE
Validator should throw an error if scans.tsv and scans list don't match?

### ISSUE THREAD

**Issue by adam2392** [bids-standard/legacy-validator#971]
Reference issue: https://github.com/mne-tools/mne-bids/pull/443

If one sets up a BIDs valid dataset, then the scans.tsv sidecar file should be a reference of truth, and reflect what is actually in the scans list, else an error should be thrown. 

Currently, the bids-validator will pass if one deletes scans from the dataset, but not from the scans.tsv file.

**Comment by sappelhoff** [comment]
Yes, I agree that it'd be sensible for the validator to check that each file referenced in `scans.tsv` is actually present in the dataset.

**Comment by jasmainak** [comment]
@adam2392 can you give this a shot with a PR?

**Comment by adam2392** [comment]
> @adam2392 can you give this a shot with a PR?

Can try sometime in the near future! Will add this to my sticky notes of laundry list TODO. 

Have not seen or worked w/ this codebase yet. Any advice on where  to start looking first, and/or best path forward?

**Comment by jasmainak** [comment]
Perhaps @nellh or @rwblair can help :)

**Comment by rwblair** [comment]
@adam2392  So it looks like the full 'fileList' is getting passed into the main tsv validation file bids-validator/validators/tsv/tsv.js. An example of this fileList being used in validating another type of tsv file can be found here:

https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/tsv/tsv.js#L140

The scans.tsv validation happens a bit futher in the function here:

https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/tsv/tsv.js#L298

Should be possible to use fileList to cross reference the filenames in scans and in the dataset there. A new issue and issue code may need to be made and added to bids-validator/utils/issues/list.js to cover a mismatch between the files and scans.tsv.

If you have any questions or need more details about anything please let me know
