### ISSUE TITLE
Use bids-specification files for filename patterns

### ISSUE THREAD

**Issue by tsalo** [bids-standard/legacy-validator#974]
This may be premature, but in https://github.com/bids-standard/bids-specification/pull/475 we are attempting to build a machine-readable version of the specification that can be versioned and pulled in for other packages, like `pybids` and `bids-validator`. While the PR is in early stages, I wanted to make sure that the `bids-validator` devs were aware of the effort, so they could provide input if they wanted. 

The goal would be to replace, at minimum, the validator's [filename rules](https://github.com/bids-standard/bids-validator/tree/8891c2978c41aeac28d89324baadc9b5be76365b/bids-validator/bids_validator/rules) with parsers that would rely on config files from the official specification.

**Comment by yarikoptic** [comment]
Might be worth creating a little tiny validator right here to start with may be?

**Comment by yarikoptic** [comment]
I believe that is WiP within https://github.com/bids-standard/bids-validator/tree/use_schema branch, which I do not think yet was proposed as a PR which then could close this issue.

**Comment by yarikoptic** [comment]
actually I was wrong -- that branch is some old initial attempt or smth.  @rwblair @nellh -- where is current work done on RFing bids-validator to use BIDS schema?

**Comment by effigies** [comment]
https://github.com/bids-standard/bids-validator/blob/master/bids-validator/src/README.md
