### ISSUE TITLE
Cannot read property 'Authors' of null

### ISSUE THREAD

**Issue by zits69** [bids-standard/legacy-validator#977]
Hi 
I tried to upload my dataset to OpenNeuro, and I got an error. When I try with the BIDS validator I get a similar problem:

TypeError: Cannot read property 'Authors' of null at Tn (https://bids-standard.github.io/bids-validator/_next/static/xR2eAacfkH2A9NYaGkYfI/pages/index.js:1:1608313) at https://bids-standard.github.io/bids-validator/_next/static/xR2eAacfkH2A9NYaGkYfI/pages/index.js:1:1610763

OR

TypeError: Cannot read property 'Authors' of null at Ar (https://openneuro.org/0-dd64aa8d.bundle.worker.js:69:129835) at https://openneuro.org/0-dd64aa8d.bundle.worker.js:69:131920

Thanks for your help,
z

**Comment by sappelhoff** [comment]
Hi @zits69 could you please post the contents of your `dataset_description.json` here?

You can format the contents using backticks: `

Do it like this:

````
```JSON
<paste your content here>
```
````

**Comment by zits69** [comment]
Hi @sappelhoff , thanks for your reply! Here it is:

```JSON
{
  "Name": "Human MEG recordings during sequential conflict task",
  "BIDSVersion": "1.0.1",
  "License": "CC0",
  "Authors": [
    "Rafal Bogacz",
    "Vladimir Litvak"
  ],
  "Acknowledgements": "We thank Dr. Ashwini Oswal, Dr. Simon Little, Dr. David Pedrosa, Dr. Damian Herz and Dr. 	Viswas Dayal for clinical support of patient recordings, as well as the patients and their families.",
  "HowToAcknowledge": "Please cite this paper: Patai, Z. E., Foltynie, T., Limousin, P., Hariz, M. I., Zrinzo, L., 	Bogacz, R., Litvak, V. (2020). Conflict detection in a sequential decision task is associated with increased 	cortico-subthalamic coherence and prolonged subthalamic oscillatory response in the beta band.",
  "Funding": [
    "MC_UU_12024/5",
    "MC_UU_00003/1",
    "BB/S006338/1",
    "203147/Z/16/Z",
    "MR/K005464/1"
  ],
  "EthicsApprovals": [
    "University College London Ethics Committee approval for minimum risk magnetoencephalography studies of healthy human cognition"
  ],
  "ReferencesAndLinks": [
    ""
   ],
  "DatasetDOI": ""
}

{
  "Name": "Human MEG recordings during sequential conflict task",
  "BIDSVersion": "1.0.1",
  "License": "CC0",
  "Authors": [
    "Rafal Bogacz",
    "Vladimir Litvak"
  ],
  "Acknowledgements": "We thank Dr. Ashwini Oswal, Dr. Simon Little, Dr. David Pedrosa, Dr. Damian Herz and Dr. Viswas Dayal for clinical support of patient recordings, as well as the patients and their families.",
  "HowToAcknowledge": "Please cite this paper: Patai, Z. E., Foltynie, T., Limousin, P., Hariz, M. I., Zrinzo, L., 	Bogacz, R., Litvak, V. (2020). Conflict detection in a sequential decision task is associated with increased 	cortico-subthalamic coherence and prolonged subthalamic oscillatory response in the beta band.",
  "Funding": [
    "MC_UU_12024/5",
    "MC_UU_00003/1",
    "BB/S006338/1",
    "203147/Z/16/Z",
    "MR/K005464/1"
  ],
  "EthicsApprovals": [
    "University College London Ethics Committee approval for minimum risk magnetoencephalography studies of healthy human cognition"
  ],
  "ReferencesAndLinks": [
    ""
   ],
  "DatasetDOI": ""
}
```

**Comment by sappelhoff** [comment]
Thanks @zits69 --> there are several issues with this file. paste the contents into https://jsonformatter.curiousconcept.com/ to see.

Some examples:
- you are using tab characters instead of space characters in some strings
- some JSON objects are not properly opened or closed (take a look at all your brackets

After fixing all your errors, and taking a really good look at that JSON, try to validate again and let me know if the issue is solved.

**Comment by zits69** [comment]
Thank you

**Comment by zits69** [comment]
Sorry i didn't mean to close it! Thank you and I'll check your suggestions now and get back to you
z

**Comment by zits69** [comment]
it worked thank you for your help!

**Comment by sappelhoff** [comment]
good to hear, happy to help. :-)
