### ISSUE TITLE
Gulp-sass version in gh-pages branch on Os X

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#98]
I was unable to complete a gulp build gh-pages locally on Os X due to the version of gulp-sass in package.json. the specific errors were coming from a version of node-sass that it had as a dependency. It would attempt to install node-sass 2.1.1 which no longer has a binary in the node-sass repository.

Following these instructions allowed gulp build to complete successfully:
https://github.com/dlmanning/gulp-sass/wiki/Update-to-the-latest-Gulp-Sass

**Comment by constellates** [comment]
Thanks for reporting this along with the instructions to fix it!

I've already updated gulp sass on gh-pages and tested it with the latest node (5.6.0) locally on osx. Let me know if you're still experiencing issues.

Additionally there's a PR to make sure our CI server will be running the latest stable node version.

**Comment by constellates** [comment]
gulp-sass and the node version on CI have been updated.
