### ISSUE TITLE
Check for file naming conflict between derivatives and raw dataset.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#980]
"Filenames that are permissible for a raw BIDS data type have a privileged status. Any modification of raw files must use a modified filename that does not conflict with the raw filename. Further, any files created as part of a derivative dataset must not match a permissible filename of a valid raw dataset. Stated equivalently, if any filename in a derivative dataset has a name permissible for a raw BIDS data, then that file must be an identical copy of that raw file."

**Comment by effigies** [comment]
> if any filename in a derivative dataset has a name permissible for a raw BIDS data, then that file must be an identical copy of that raw file.

**Comment by effigies** [comment]
I would suggest this be a warning, because verifying exact copies is going to require a complicated check of a separate dataset.
