### ISSUE TITLE
enforce source_entities filenaming

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#983]
When the derivatives chain involves outputs derived from a single raw input, source_entities MUST be the entire source filename, with the omission of the source suffix and extension. One exception to this rule is filename entities that are no longer relevant. Depending on the nature of the derivative file, the suffix can either be the same as the source file if that suffix is still appropriate, or a new appropriate value selected from the controlled list.

**Comment by effigies** [comment]
I don't think this can be validated, although perhaps you could say "No raw entities can be used that do not appear in the source file". But that feels like it's just asking for someone to come up with a good exception.

**Comment by effigies** [comment]
I continue to believe this can't be validated.
